### ISSUE TITLE
Internal and SEUS shaders make my whole game blink a lot.

### ISSUE THREAD

**Issue by Telokis** [sp614x/optifine#1036]
In the same context as #1031 I tried to activate shaders (without AA/AF).
I tried internal but when I start the game after changing it from the main menu, I can't play at all.
The game starts to blink between white and grey and I don't see the game at all.

The same happens with SEUS but I didn't try other.

**Comment by sp614x** [comment]
Testing Chisel + Shaders, no problems so far:

![image](https://user-images.githubusercontent.com/16635441/33433853-8c53fa2e-d5dd-11e7-90f0-f5d3b0ce771c.png)

this is with very latest preview C7 (some bugfixes added).

**Comment by Telokis** [comment]
This is with the pack minus Chisel and CTM as you mentioned in the other issue.
Maybe the update will fix it indeed.

**Comment by Telokis** [comment]
Here is a gif of what happens:

![mc](https://user-images.githubusercontent.com/6382729/33446557-bb957cfe-d600-11e7-992d-23e1761be2d1.gif)

It stays like this forever. I know that I am in game because I hear my character moving and hitting blocks but nothing show up.

**Comment by sp614x** [comment]
Can you post the error log or game output to pastebin.com?

**Comment by Telokis** [comment]
It's way too big for pastebin. I'll attach it here.

[latest.log](https://github.com/sp614x/optifine/files/1519619/latest.log)

**Comment by sp614x** [comment]
So many errors in the log file, it is hard to find the real problem.
You can try to disable shaders for a start.

Some posible causes:

```
[18:57:38] [main/ERROR]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:46) [forge-1.10.2-12.18.3.2511.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more

java.lang.NullPointerException
	at mezz.jei.util.StackHelper.getAllSubtypes(StackHelper.java:265) [StackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.expandSubtypes(ItemStackHelper.java:24) [ItemStackHelper.class:?]
	at mezz.jei.util.Ingredients.setInputLists(Ingredients.java:32) [Ingredients.class:?]

java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:250) ~[adz.class:?]
	at mezz.jei.util.StackHelper.toItemStackList(StackHelper.java:340) ~[StackHelper.class:?]
	at mezz.jei.util.StackHelper.toItemStackList(StackHelper.java:353) ~[StackHelper.class:?]
	at mezz.jei.util.StackHelper.toItemStackList(StackHelper.java:333) ~[StackHelper.class:?]
	at mezz.jei.util.StackHelper.toItemStackList(StackHelper.java:328) ~[StackHelper.class:?]

[18:58:29] [Client thread/WARN]: Invalid sounds.json
java.lang.NullPointerException
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SourceFile:82) [bzw.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
```

**Comment by Telokis** [comment]
Is there something I can do?

**Comment by sp614x** [comment]
To find the mod that has a conflict:

1. Start removing mods or groups of mods and test if MC works
2. When MC starts working, add the mods one by one until you find the one that makes MC crash again

You can start by removing the core mods:
```
WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.13.133-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.19.jar)
Contact their authors BEFORE contacting forge
```
