### ISSUE TITLE
Cannot open chests

### ISSUE THREAD

**Issue by Roxforbraynz** [sp614x/optifine#1071]
Forge 14.23.1.2577
OptiFine 1.12.2 HD U C7

Unable to open chests. No crash, but this error appears in the log:
```
[18:05:54] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.AbstractMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at net.minecraft.block.BlockChest.func_176456_n(BlockChest.java:541) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_176457_m(BlockChest.java:536) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_189418_a(BlockChest.java:460) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180676_d(BlockChest.java:444) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180639_a(BlockChest.java:421) ~[api.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

When Optifine is removed, chests open as normal.

**Comment by Kzitold** [comment]
Happened to me to.

**Comment by SteveKunG** [comment]
See also : https://github.com/sp614x/optifine/issues/1067

**Comment by realjackasterisk** [comment]
[Optifine 1.12.2 HD U C7 is compatible with Forge #2555.](https://optifine.net/changelog?f=OptiFine_1.12.2_HD_U_C7.jar)

**Comment by Roxforbraynz** [comment]
@SteveKunG The logs show different errors, so this _may_ be a separate issue stemming from the same vanilla class. I didn't crash, I just couldn't open chests.
@realjackasterisk That's good if you're using Optifine alone. I ran into this issue while updating all my mods though, some of which need the offending versions of Forge.

**Comment by liach** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4584/files#diff-a11c1bfb3a77552647e2eac0c84e2ef4R27
@sp614x Does optifine have custom block state containers? We can create a forge pull to default this out and restore compatibility.

**Comment by liach** [comment]
Hmm, on another look, this looks more like a patching failure

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2 with a bugfix., compatible with Forge #2577.
http://optifine.net/changelog?f=preview_OptiFine_1.12.2_HD_U_C8_pre.jar
