### ISSUE TITLE
Enabling Render Regions on OS X crashes Minecraft.

### ISSUE THREAD

**Issue by GreyAsteroid** [sp614x/optifine#1235]
```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2/20/18 6:31 PM
Description: Rendering chunk

java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL31.glCopyBufferSubData(GL31.java:217)
	at VboRegion.expandVbo(VboRegion.java:274)
	at VboRegion.checkVboSize(VboRegion.java:227)
	at VboRegion.bufferData(VboRegion.java:102)
	at cdz.a(VertexBuffer.java:36)
	at bvg.a(SourceFile:14)
	at bxm.a(ChunkRenderDispatcher.java:307)
	at bxm.a(ChunkRenderDispatcher.java:266)
	at bxm$3.run(ChunkRenderDispatcher.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at bxm.a(ChunkRenderDispatcher.java:116)
	at buy.a(RenderGlobal.java:2469)
	at buq.a(EntityRenderer.java:1730)
	at buq.b(EntityRenderer.java:1611)
	at buq.a(EntityRenderer.java:1382)
	at bib.az(SourceFile:1023)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 294871752 bytes (281 MB) / 503316480 bytes (480 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 5, allocated: 17, tallocated: 89
```

**Comment by sp614x** [comment]
Updated preview D1 with a bugfix
