### ISSUE TITLE
"java.lang.NoSuchFieldError: aM" Minecraft 1.8.8 with optifine crash after run

### ISSUE THREAD

**Issue by AcerAspire5738zSucks** [sp614x/optifine#1282]
hi, i have a problem trying to launch minecraft 1.8.8 with Optifine, the screen gone black and crash, this is the "crash report"

---- Minecraft Crash Report ----
// Don't do that.

Time: 12/03/18 06:51 PM
Description: Initializing game

java.lang.NoSuchFieldError: aM
	at ave.am(SourceFile:376)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.am(SourceFile:376)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 7 (amd64) version 6.1
	CPU: 2x Pentium(R) Dual-Core CPU T4300 @ 2.10GHz
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 334102120 bytes (318 MB) / 422051840 bytes (402 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.8-OptiFine_HD_U_I3
	LWJGL: 2.9.4
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.2202, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 2x Pentium(R) Dual-Core CPU T4300 @ 2.10GHz
	OptiFine Version: OptiFine_1.8.8_HD_U_I3
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2202
	OpenGlRenderer: Mobile Intel(R) 4 Series Express Chipset Family
	OpenGlVendor: Intel
	CpuCount: 2

pd: if i launch the game withou mods, runs perfect, but the framerate sucks
pd2: "why you still using that 10+ laptop?" test and nostalgic
pd3: "this is your principal computer" nope, i have a bunch of cats

**Comment by sp614x** [comment]
Is OptiFine installed standalone or with Forge?
Forge version?

**Comment by KaiAF** [comment]
No response from the OP
