### ISSUE TITLE
[1.12.2] Incompatible with BetterFps

### ISSUE THREAD

**Issue by SteveKunG** [sp614x/optifine#1283]
After update latest preview of OptiFine (1.12.2 HD U D1 pre / 13.03.2018). It crashes at startup of the game.

BetterFps v1.4.8

`[21:37:52] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class Reflector
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:138) ~[b.class:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) ~[b.class:?]
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:425) ~[b.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:381) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more`

**Comment by TheSnowyChickens** [comment]
Yes, I think I have the same bug. :)

**Comment by border999** [comment]
I will add to this that I had a very similar crash that seemed to mention some form of failure to find the Better Foliage mod.

**Comment by sp614x** [comment]
Looks like BetterFPS fails to patch the EntityRenderer class.

```
[11:54:13] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[11:54:13] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[11:54:13] [main/INFO] [BetterFps]: Patching net.minecraft.client.renderer.EntityRenderer... (buq)
[11:54:13] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class Reflector
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:138) ~[b.class:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) ~[b.class:?]
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:425) ~[b.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:381) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
```

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2 with a bugfix.
