### ISSUE TITLE
Conflict with Dynamic Surroundings 1.12.2 causes crash

### ISSUE THREAD

**Issue by Tsoccerguy3** [sp614x/optifine#1285]
Mod Version:
1.12.2

Forge Version:
forge-1.12.2-14.23.2.2625-installer.jar

Link to crash log (if applicable):
No Crash logs

Description:
https://github.com/OreCruncher/DynamicSurroundings/issues/282
Crash on start. This is new development as of today , Most likely Optifine pre problem . No Crash logs.
http://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_D1_pre.jar

**Comment by Tsoccerguy3** [comment]
This is a Optifine bug

Here is the Forge log . More details look on my Onedrive in the Ore directory
https://onedrive.live.com/?id=77B5E138E468EDE3%212070&cid=77B5E138E468EDE3

**Comment by sp614x** [comment]
OptiFine D1_pre works with DynamicSurroundings-1.12.2-3.4.7.2.
Crashes with any of the 3.4.9.x versions.

**Comment by sp614x** [comment]
Looks like the ASM patcher fails to load the class "bxy" (ICamera) from the right place when patching one of the ICamera implementations, probably the Frustum class.
The ICamera class was not changed in OptiFine C9, it is changed in D1_pre.
```
java.lang.RuntimeException: java.lang.SecurityException: class "bxy"'s signer information does not match signer information of other classes in the same package
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
	at org.blockartistry.lib.asm.MyTransformer.transform(MyTransformer.java:71)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Reflector.<clinit>(Reflector.java:157)
	at net.minecraft.client.settings.GameSettings.setForgeKeybindProperties(GameSettings.java:3404)
```

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2 with a bugfix.
