### ISSUE TITLE
Client crash - NPE - Tesselating block model - Preconditions.checkNotNull

### ISSUE THREAD

**Issue by ProsperCraft** [sp614x/optifine#1290]
https://gist.github.com/owen-pi/ed0ba82491d8d52e64b5122a03dd4051

When looking at an Immersive Engineering waterwheel.

This crash is repeatable and does not happen without Optifine.

**Comment by sp614x** [comment]
The crash is inside Immersive Engineering, the IESmartObjModel tries to create a list with NULL contents.

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/client/models/IESmartObjModel.java#L241

```
java.lang.NullPointerException: Tesselating block model
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
	at blusunrize.immersiveengineering.client.models.IESmartObjModel.getQuads(IESmartObjModel.java:241)
	at blusunrize.immersiveengineering.client.models.IESmartObjModel.func_188616_a(IESmartObjModel.java:206)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:106)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:89)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:76)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:55)
```
