### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Entiz** [sp614x/optifine#1328]
Hi, evertime when i start Minecraft with Ressoucepack on and Optifine in, i get a crash, if i start without Optifine the fellow error apears in. openEye

`

java.lang.IndexOutOfBoundsException: 

    at java.nio.Buffer.checkBounds(Buffer.java:567)
    at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
    at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:322)
    at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:194)
    at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:178)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:347)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:151)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:172)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Java

    Oracle Corporation 1.8.0_25

Minecraft

    Minecraft 1.12.2

FML

    8.0.99.99

MCP

    MCP 9.42

Forge

    14.23.2.2635

Branding

    Minecraft 1.12.2
    MCP 9.42
    Powered by Forge 14.23.2.2635
    Optifine OptiFine_1.12.2_HD_U_C9
    Optifine OptiFine_1.12.2_HD_U_D1
`
If i start with Optifine and without Pack and turn it on, it deactivat the Pack

**Comment by sp614x** [comment]
Do you have 2 version of OptiFine active at the same time?
```
Optifine OptiFine_1.12.2_HD_U_C9
Optifine OptiFine_1.12.2_HD_U_D1
```

**Comment by Entiz** [comment]
No i only have the Opifine D1 , i have tested with C9 but not together, i have no idea why there are two listed in Branding

**Comment by sp614x** [comment]
Make sure that there is only one copy of OptiFine in the mods folder.

**Comment by Entiz** [comment]
There is only one, in the crash log is only one listed just openeye says that there are more

**Comment by Entiz** [comment]
Crash report: https://pastebin.com/QM7Qtna3

**Comment by sp614x** [comment]
Have you tried with Shaders set to OFF?
