### ISSUE TITLE
[1.12.2] Imcompatibility with schematica (java.nio.BufferOverflowException)

### ISSUE THREAD

**Issue by Syl2010** [sp614x/optifine#1356]
Version forge : 14.32.0.2529
Version schematica : 1.8.0.168
Version optifine : optifine 1.12.2 HD_U_D1

Complete issue : https://github.com/Lunatrius/Schematica/issues/321

**Comment by sp614x** [comment]
Have you tried with Render Regions = OFF?
```
java.nio.BufferOverflowException
    at java.nio.Buffer.nextPutIndex(Buffer.java:521)
    at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
    at VboRegion.drawArrays(VboRegion.java:297)
```

**Comment by NovaLynxie** [comment]
Hi, I've encountered this crash glitch as well. I have turned Render Regions OFF and all schematics I have are able to load without crashing now.

**Comment by TheFinalDawn** [comment]
Was this fixed?
Latest everything for 1.12, Forge, Schematica, and Optifine.
Render Regions solves it, but that seems... Strange.
