### ISSUE TITLE
Crash with replay mod

### ISSUE THREAD

**Issue by TheCoder3156** [sp614x/optifine#1434]
Minecraft crashes when a replay is loaded from the replay menu. I feel this is a bug in optifine because it worked on a previous version (OptiFine 1.12.2 HD U C9) and does not work on anything past. See https://www.replaymod.com/forum/thread/2118 for other's problems too.

Here is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (replaymod-1.12.2-2.1.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 6/3/18 10:24 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.chunk.RenderChunk.updateRenderChunkNeighboursValid(RenderChunk.java:801)
	at net.minecraft.client.renderer.chunk.RenderChunk.getRenderChunkNeighbour(RenderChunk.java:777)
	at net.minecraft.client.renderer.RenderGlobal.getRenderChunkOffset(RenderGlobal.java:1510)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1399)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.chunk.RenderChunk.updateRenderChunkNeighboursValid(RenderChunk.java:801)
	at net.minecraft.client.renderer.chunk.RenderChunk.getRenderChunkNeighbour(RenderChunk.java:777)
	at net.minecraft.client.renderer.RenderGlobal.getRenderChunkOffset(RenderGlobal.java:1510)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1399)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [CameraEntity['Player'/-1789435, l='MpServer', x=127.11, y=68.94, z=327.40]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (116,64,256), Chunk: (at 4,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6275 game time, 6275 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 1 total; [CameraEntity['Player'/-1789435, l='MpServer', x=127.11, y=68.94, z=327.40]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-22-generic
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 377821248 bytes (360 MB) / 935890944 bytes (892 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_D3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version      | Source                        | Signature                                |
	|:------ |:----------------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft               | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJA | mcp                     | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJA | FML                     | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                   | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | replaymod-compat        | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod               | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod-editor        | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod-extras        | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod-online        | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod-recording     | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod-render        | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod-replay        | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |
	| UCHIJA | replaymod-simplepathing | 1.12.2-2.1.2 | replaymod-1.12.2-2.1.2.jar    | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (replaymod-1.12.2-2.1.2.jar)
  
	GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 18.0.0-rc5' Renderer: 'AMD Radeon (TM) RX 460 Graphics (POLARIS11 / DRM 3.23.0 / 4.15.0-22-generic, LLVM 6.0.0)'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) RX 460 Graphics (POLARIS11 / DRM 3.23.0 / 4.15.0-22-generic, LLVM 6.0.0) GL version 3.0 Mesa 18.0.0-rc5, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4300 Quad-Core Processor
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 18.0.0-rc5
	OpenGlRenderer: AMD Radeon (TM) RX 460 Graphics (POLARIS11 / DRM 3.23.0 / 4.15.0-22-generic, LLVM 6.0.0)
	OpenGlVendor: X.Org
	CpuCount: 4

Yes I use Gnu/linux but that is not  the problem as others also had the problem.

**Comment by Johni0702** [comment]
This [has been fixed](https://github.com/ReplayMod/ReplayMod/commit/62d2ce4b37aec7828ace1e1de0b1545d1b24abc3) in the ReplayMod and will be in version 2.1.3.

I don't think this needs any changes on the Optifine side. We were just re-instantiating `RenderChunk`s for no good reason. We've switched to calling their `setNeedsUpdate` method instead which does what we want without breaking other mods.
