### ISSUE TITLE
OptiFine for Minecraft 1.13 does not start

### ISSUE THREAD

**Issue by DendyCraftMen** [sp614x/optifine#1645]
In short, I installed the latest Optifine assembly for Minecraft 1.13 ...
but after installing Minecraft does not start!

What to do? DEVELOPER - fix it

**Comment by FirebornGD** [comment]
What OS do you use? JVM version? Is there any error or Minecraft just crashes silently? Maybe there are some logs? "Minecraft does not start" is not enough to understand what's wrong.

**Comment by DendyCraftMen** [comment]
OS: Win 8.1 JVM version 8 update 172

Well, in general: I pressed the "Launch" button in Tlauncher and after the Java process was created, disappears in a couple of seconds in the task manager.

Most likely - it's crash

**Comment by Chrishunk** [comment]
I also have this bug

**Comment by Nik-mmzd** [comment]
I found that all users got crashes are using windows and installer exports json with
```
{
  "id": "1.13-OptiFine_HD_U_E3_alpha8",
  "inheritsFrom": "1.13",
  "time": "2018-08-15T16:38:33+03:00",
  "releaseTime": "2018-08-15T16:38:33+03:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.13_HD_U_E3_alpha8"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minecraftArguments": "--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userType ${user_type} --versionType ${version_type}  --tweakClass optifine.OptiFineTweaker"
}
```
I tried this JSON and got same crash
But when I tried to install OptiFine I had other json:
```
{
  "id": "1.13-OptiFine_HD_U_E3_alpha8",
  "inheritsFrom": "1.13",
  "time": "2018-08-15T16:57:20+03:00",
  "releaseTime": "2018-08-15T16:57:20+03:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.13_HD_U_E3_alpha8"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "arguments": {
    "game": [
      {
        "value": [
          "--tweakClass"
        ]
      },
      {
        "value": [
          "optifine.OptiFineTweaker"
        ]
      }
    ]
  }
}
```
and no crashes at all
I sent second JSON to peoples had this
```
> Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
>   at java.lang.Class.getDeclaredConstructors0(Native Method)
>   at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
>   at java.lang.Class.getConstructor0(Unknown Source)
>   at java.lang.Class.newInstance(Unknown Source)
>   at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
>   at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
>   at java.net.URLClassLoader.findClass(Unknown Source)
>   at java.lang.ClassLoader.loadClass(Unknown Source)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>   at java.lang.ClassLoader.loadClass(Unknown Source)
>   ... 8 more
``` crash and it helped.

So, Optifine devs, please help me figure out why one installer exports not same profiles and please, check `minecraftArguments` in "broken" JSON

**Comment by DendyCraftMen** [comment]
@Nik-mmzd Many thanks! It's working :+1:

**Comment by Chrishunk** [comment]
@DendyCraftMen How did you make it work?

**Comment by skmedix** [comment]
Replace `1.13.json` content with: 
https://gist.githubusercontent.com/skmedix/220788300ac6b74ea144fdbd58418e5d/raw/8a6cd7ccd5dd1ef1fdd622891eda0f2d761a6a1e/1.13.json
And replace `1.13-OptiFine_HD_U_E3_alpha8.json` content with: https://gist.githubusercontent.com/skmedix/a2907114a54e8568e97a9db493691a54/raw/e3e084a31ed2e17ee3fad720b3fb59c35f17f2be/1.13-OptiFine_HD_U_E3_alpha8.json

**Comment by DendyCraftMen** [comment]
@Chrishunk I did as told to me @Nik-mmzd
