### ISSUE TITLE
Game crash on launch

### ISSUE THREAD

**Issue by CooperWallace** [sp614x/optifine#1665]
I'm attempting to use optifine pre release version 8. I don't seem to get any logs when I attempt to open the game, as the log window waits continuously. This is revealed in the launcher log however;
```
[0815/173926:INFO:ClientStarter.cpp(626)] ${user_type} == "mojang"
[0815/173926:INFO:ClientStarter.cpp(626)] ${version_type} == "release"
[0815/173926:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[0815/173926:INFO:GameCallbacks.cpp(199)] launcher/monitor (Process Monitor) fatal Process crashed with exit code 1
[0815/173926:INFO:GameCallbacks.cpp(31)] Destroying GameCallbacks!
[0815/173926:INFO:ClientHandler.cpp(176)] Launcher is already open!
```

I'm running Manjaro 17.1.11
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)

**Comment by skmedix** [comment]
Try to use OracleJDK 8

**Comment by CooperWallace** [comment]
That did the trick! I thought the problem was the other way around, using an outdated version of java.
