### ISSUE TITLE
Crashing everytime I try to play on Optifine 1.13 beta1.

### ISSUE THREAD

**Issue by chl0maki** [sp614x/optifine#1718]
I get this error:
 ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/27/18 9:07 PM
Description: Tesselating liquid in world

java.lang.IllegalArgumentException: Cannot get property bly{name=type, clazz=class bmg, values=[top, bottom, double]} as it does not exist in Block{minecraft:water}
	at bkr.c(SourceFile:95)
	at bhc.r(SourceFile:70)
	at cuk.a(BlockFluidRenderer.java:309)
	at cuj.a(SourceFile:78)
	at cwj.b(RenderChunk.java:309)
	at cwf.a(SourceFile:100)
	at cwf.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chl0maki** [comment]
Closed because didn't notice beta2 came out.
