### ISSUE TITLE
MD5 not matching

### ISSUE THREAD

**Issue by mickedplay** [sp614x/optifine#172]
```
java.lang.Exception: MD5 not matching, name: b$1.class, saved: c455f0109946088a442bf8588e26875d, patched: 681216b310e039d54efc3b5dce0d1993
  at optifine.Patcher.process(Patcher.java:98)
  at optifine.Installer.installOptiFineLibrary(Installer.java:308)
  at optifine.Installer.doInstall(Installer.java:96)
  at optifine.InstallerFrame.onInstall(InstallerFrame.java:422)
  at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:487)
  at optifine.InstallerFrame.access$7(InstallerFrame.java:481)
  at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
  at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
  at java.awt.Component.processMouseEvent(Unknown Source)
  at javax.swing.JComponent.processMouseEvent(Unknown Source)
  at java.awt.Component.processEvent(Unknown Source)
  at java.awt.Container.processEvent(Unknown Source)
  at java.awt.Component.dispatchEventImpl(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Window.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
  at java.awt.EventQueue.access$500(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue.dispatchEvent(Unknown Source)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.run(Unknown Source)

```

This happens if I double click the downloaded "OptiFine 1.8.9 HD U H6" and click on install without changing anything.

**Comment by HeartyYF** [comment]
This is because you installed for the second time.

**Comment by mickedplay** [comment]
Not really. It never installed that version before.

**Comment by sp614x** [comment]
Make sure that the Minecraft 1.9.6 jar is not changed or delete the "versions/1.8.9" folder so the launcher can redownload it. 
The OptiFine installer needs the original unchanged 1.8.9.jar in order to generate the patched class files.

**Comment by HeartyYF** [comment]
Minecraft 1.9.6 jar?!
I think you mean Minecraft 1.8.9 jar...

**Comment by sp614x** [comment]
Yep, 1.8.9 the version you are installing.

**Comment by mickedplay** [comment]
I never touched the 1.8.9.jar and it still exists as a vanilla version. Reinstall worked fine, thanks anyways.
