### ISSUE TITLE
crash when activating Jerms resource pack with latest Optifine

### ISSUE THREAD

**Issue by CaptainKyros** [sp614x/optifine#1726]
[crash-2018-08-29_16.55.04-client.txt](https://github.com/sp614x/optifine/files/2334153/crash-2018-08-29_16.55.04-client.txt)

**Comment by sp614x** [comment]
```
java.lang.ExceptionInInitializerError
	at net.optifine.CustomColors.readSpawnEggColors(CustomColors.java:1558)
	at net.optifine.CustomColors.readColorProperties(CustomColors.java:518)
	at net.optifine.CustomColors.update(CustomColors.java:336)
	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:320)
	at net.optifine.util.TextureUtils$1.a(TextureUtils.java:367)
```

**Comment by CaptainKyros** [comment]
if it helps find the cause of the crash, I had TIS-3D installed

**Comment by sp614x** [comment]
The game is already modded with Rift, this has never been tested.
```
Is Modded: Definitely; Client brand changed to 'rift'
```

**Comment by CaptainKyros** [comment]
a related crash:
[latest.log](https://github.com/sp614x/optifine/files/2362361/latest.log)

**Comment by sp614x** [comment]
Fixed in next beta9.
