### ISSUE TITLE
[1.13 beta4] Crashed

### ISSUE THREAD

**Issue by RealepiBars** [sp614x/optifine#1728]
Minecraft closed with exit code: 1 (0x1)
In Alpha8 - beta4

**Comment by sp614x** [comment]
Error log, crash report?

**Comment by RealepiBars** [comment]
[1.13-OptiFine_HD_U_E3_beta4 (2018-08-31).log](https://github.com/sp614x/optifine/files/2338843/1.13-OptiFine_HD_U_E3_beta4.2018-08-31.log)

**Comment by sp614x** [comment]
This is a custom launcher (TLauncher) which is not supported.
Looks like it is missing the ASM library:
```
[08:01:22] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
```
