### ISSUE TITLE
Client doesn't start

### ISSUE THREAD

**Issue by iLukeOff** [sp614x/optifine#1732]
Exception in thread "Client thread" java.lang.NoClassDefFoundError: Could not initialize class optifine.Reflector
    at net.minecraft.crash.CrashReport.populateEnvironment(CrashReport.java:145)
    at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
    at net.minecraft.crash.CrashReport.makeCrashReport(CrashReport.java:418)
    at net.minecraft.client.Minecraft.run(Minecraft.java:426)
    at net.minecraft.client.main.Main.main(Main.java:124)
  <log4j:Event logger="net.minecraft.server.MinecraftServer" timestamp="1535643411431" level="INFO" thread="Client Shutdown Thread">
    <log4j:Message><![CDATA[Stopping server]]></log4j:Message>
  </log4j:Event>

**Comment by iLukeOff** [comment]
```
-------------------------------------Log out of the Minecraft game output---------------------------------------------------------------

22:25:03	launcher	main	info	Starting!
22:25:04	launcher	main	info	Using default game log configuration client-1.7.xml (outputs XML)
22:25:37	com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication	main	info	Logging in with username & password
22:25:48	net.minecraft.client.Minecraft	Client thread	info	Setting user: Derviloper
22:25:48	net.minecraft.client.Minecraft	Client thread	info	(Session ID is token:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) //I replaced it
22:25:52	optifine.Config	Client thread	info	[OptiFine] *** Reflector Forge ***
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.Attributes
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.ChunkWatchEvent$UnWatch
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.relauncher.CoreModManager
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.common.DimensionManager
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Post
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$CameraSetup
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$FogColors
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.eventhandler.Event
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.eventhandler.EventBus
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.eventhandler.Event$Result
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.common.property.ExtendedBlockState
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.FMLClientHandler
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.FMLCommonHandler
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.world.biome.BiomeGenBase.getWaterColorMultiplier
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.addDestroyEffects
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.addHitEffects
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.canCreatureSpawn
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.canRenderInLayer
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.doesSideBlockRendering
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.getBedDirection
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.getExtendedState
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.hasTileEntity
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isAir
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isBed
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isBedFoot
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isSideSolid
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.entity.Entity.canRiderInteract
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Field not present: net.minecraft.entity.Entity.captureDrops
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Field not present: net.minecraft.entity.Entity.capturedDrops
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.entity.Entity.shouldRenderInPass
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Method not present: net.minecraft.entity.Entity.shouldRiderSit
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.event.ForgeEventFactory
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeHooks
22:25:52	optifine.Config	Client thread	info	[OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
00:25:52	game		error	Exception in thread "Client thread" java.lang.NoClassDefFoundError: Could not initialize class optifine.Reflector
	at net.minecraft.crash.CrashReport.populateEnvironment(CrashReport.java:145)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraft.crash.CrashReport.makeCrashReport(CrashReport.java:418)
	at net.minecraft.client.Minecraft.run(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(Main.java:149)
  <log4j:Event logger="net.minecraft.server.MinecraftServer" timestamp="1535660752909" level="INFO" thread="Client Shutdown Thread">
    <log4j:Message><![CDATA[Stopping server]]></log4j:Message>
  </log4j:Event>
00:25:52	monitor	Process Monitor	error	expected <
22:25:55	launcher	main	info	
00:25:55	monitor	Process Monitor	fatal	Process crashed with exit code 1
```

**Comment by iLukeOff** [comment]
i comment it this code `public static ReflectorMethod ForgeHooksClient_applyTransform = new ReflectorMethod(ForgeHooksClient, "applyTransform"/*, new Class[]{Matrix4f.class, Optional.class}*/);` out? is there any problem if i do so? because with this method it works for me

**Comment by sp614x** [comment]
Which Minecrat version (1.12.2, 1.13, 1.13.1)?
Which OptiFine version (E3, alpha, beta, etc)?
