### ISSUE TITLE
[1.13] Don't work in Linux

### ISSUE THREAD

**Issue by jedenastka** [sp614x/optifine#1742]
Hi. I just downloaded and installed Optifine (1.13 beta4) on my Debian 9 and... it isn't working. All other versions working fine.
Crash log:
```
[17:18:18] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[17:18:18] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[17:18:18] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```
Launcher log: https://pastebin.com/9AhLRP5W
Launcher: SKLauncher 2.8 (crack)
OS:
```
grzesiek11@pecet:~$ neofetch
       _,met$$$$$gg.          grzesiek11@pecet 
    ,g$$$$$$$$$$$$$$$P.       ---------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 9.5 (stretch) x86_64 
 ,$$P'              `$$$.     Model: OptiPlex 790 01 
',$$P       ,ggs.     `$$b:   Kernel: 4.9.0-7-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 7 hours, 31 minutes 
 $$P      d$'     ,    $$P    Packages: 1832 
 $$:      $$.   -    ,d$$'    Shell: bash 4.4.12 
 $$;      Y$b._   _,d$P'      Resolution: 1280x1024 
 Y$$.    `.`"Y$$$$P"'         DE: XFCE 
 `$$b      "-.__              WM: Xfwm4 
  `Y$$                        WM Theme: Arc 
   `Y$$.                      Theme: Arc [GTK2], Adwaita [GTK3] 
     `$$b.                    Icons: Papirus [GTK2], Adwaita [GTK3] 
       `Y$$b.                 Terminal: mate-terminal 
          `"Y$b._             CPU: Intel i5-2400 (4) @ 3.4GHz 
              `"""            GPU: NVIDIA GeForce GTX 660 
                              Memory: 2855MB / 3911MB 
                               
                              ████████████████████████ 
                               

grzesiek11@pecet:~$ 

```
Java:
```
grzesiek11@pecet:~$ command java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
grzesiek11@pecet:~$ 
```
JVM Arguments: ```-Xmx4G -Xmn128M```
If you need more info, tell me.

**Comment by sp614x** [comment]
External launchers (SKLauncher) are not supported.
Ask in the corresponding forum/issues.
https://github.com/skmedix/SKlauncher/issues

**Comment by jedenastka** [comment]
I don't know that it's launcher related... I'll try another launcher.
