### ISSUE TITLE
[1.13]Module conflict

### ISSUE THREAD

**Issue by ZL2333** [sp614x/optifine#1803]
```
[16:24:01] [Sound Library Loader/INFO]: Preloading sound minecraft:sounds/ambient/underwater/underwater_ambience.ogg

[16:24:01] [Sound Library Loader/INFO]: Sound engine started

[16:24:05] [main/INFO]: [OptiFine] Sprite size: 32

[16:24:05] [main/INFO]: [OptiFine] Mipmap levels: 5

[16:24:05] [main/INFO]: [OptiFine] Multitexture: false

[16:24:05] [main/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/kelp_plant, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dead_fire_coral_block, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dead_brain_coral_block, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/seagrass, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/stripped_jungle_log_core, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/stripped_dark_oak_log_core, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/tall_seagrass_bottom, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:item/dried_kelp, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/tall_seagrass_top, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/blue_ice, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/kelp, 16 -> 32

[16:24:05] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dead_tube_coral_block, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/horn_coral_block, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/tripwire, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/stripped_birch_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dead_bubble_coral_block, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/dark_oak_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/stripped_acacia_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/acacia_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dried_kelp_top, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/stripped_oak_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/spruce_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/tube_coral_block, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dead_horn_coral_block, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/tube_coral, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/jungle_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dried_kelp_bottom, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/birch_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/conduit, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/fire_coral_block, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/oak_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/sea_pickle, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/dried_kelp_side, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/bubble_coral_block, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: halflogs:block/stripped_spruce_log_core, 16 -> 32

[16:24:06] [main/INFO]: [OptiFine] Scaled too small texture: minecraft:block/brain_coral_block, 16 -> 32

[16:24:06] [main/INFO]: Created: 1024x1024 textures-atlas

[16:24:07] [main/INFO]: [OptiFine] Animated sprites: 27

---- Minecraft Crash Report ----

// Hi. I'm Minecraft, and I'm a crashaholic.



Time: 18-9-16 下午4:24

Description: Initializing game



java.lang.OutOfMemoryError: Java heap space

	at dhc.<init>(SourceFile:22)

	at cuu.rotateVertex(FaceBakery.java:283)

	at cuu.fillVertexData(FaceBakery.java:185)

	at cuu.makeQuadVertexData(FaceBakery.java:112)

	at cuu.makeBakedQuad(FaceBakery.java:76)

	at cuu.a(FaceBakery.java:58)

	at cur.a(SourceFile:240)

	at cur.a(SourceFile:231)

	at cur.a(SourceFile:208)

	at cva.a(SourceFile:74)

	at cvf.a(SourceFile:87)

	at des.a(SourceFile:346)

	at des$$Lambda$911/159053033.accept(Unknown Source)

	at java.util.HashMap.forEach(Unknown Source)

	at des.a(SourceFile:345)

	at det.a(SourceFile:23)

	at vg.a(SourceFile:117)

	at cfi.am(SourceFile:504)

	at cfi.a(SourceFile:377)

	at net.minecraft.client.main.Main.main(SourceFile:144)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)





A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------



-- Head --

Thread: Client thread

Stacktrace:

	at dhc.<init>(SourceFile:22)

	at cuu.rotateVertex(FaceBakery.java:283)

	at cuu.fillVertexData(FaceBakery.java:185)

	at cuu.makeQuadVertexData(FaceBakery.java:112)

	at cuu.makeBakedQuad(FaceBakery.java:76)

	at cuu.a(FaceBakery.java:58)

	at cur.a(SourceFile:240)

	at cur.a(SourceFile:231)

	at cur.a(SourceFile:208)

	at cva.a(SourceFile:74)

	at cvf.a(SourceFile:87)

	at des.a(SourceFile:346)

	at des$$Lambda$911/159053033.accept(Unknown Source)

	at java.util.HashMap.forEach(Unknown Source)

	at des.a(SourceFile:345)

	at det.a(SourceFile:23)

	at vg.a(SourceFile:117)

	at cfi.am(SourceFile:504)



-- Initialization --

Details:

Stacktrace:

	at cfi.a(SourceFile:377)

	at net.minecraft.client.main.Main.main(SourceFile:144)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)



-- System Details --

Details:

	Minecraft Version: 1.13

	Operating System: Windows 10 (amd64) version 10.0

	Java Version: 1.8.0_181, Oracle Corporation

	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

	Memory: 314665824 bytes (300 MB) / 452984832 bytes (432 MB) up to 536870912 bytes (512 MB)

	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx512m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump

	Launched Version: HMCL 3.1.94

	LWJGL: 3.1.6 build 14

	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.

	GL Caps: Using GL 1.3 multitexturing.

Using GL 1.3 texture combiners.

Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.

Shaders are available because OpenGL 2.1 is supported.

VBOs are available because OpenGL 1.5 is supported.



	Using VBOs: Yes

	Is Modded: Definitely; Client brand changed to 'rift'

	Type: Client (map_client.txt)

	Resource Packs: vanilla, file/Faithful+1.13-rv2.4.zip, file/Default+Improved+PBR+1.12_for_1.13_by_icrdr.zip, file/%5B1.13.x%5DBallad.zip, neat

	Current Language: 简体中文 (中国)

	Profiler Position: N/A (disabled)

	CPU: 4x Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz

	OptiFine Version: OptiFine_1.13_HD_U_E3_beta4

	OptiFine Build: 20180829-225136

	Render Distance Chunks: 11

	Mipmaps: 4

	Anisotropic Filtering: 1

	Antialiasing: 0

	Multitexture: false

	Shaders: null

	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008

	OpenGlRenderer: AMD Radeon HD 5450

	OpenGlVendor: ATI Technologies Inc.

	CpuCount: 4
```

**Comment by sp614x** [comment]
```
java.lang.OutOfMemoryError: Java heap space
...
Resource Packs: vanilla, file/Faithful+1.13-rv2.4.zip, file/Default+Improved+PBR+1.12_for_1.13_by_icrdr.zip, file/%5B1.13.x%5DBallad.zip, neat
...
Memory: 314665824 bytes (300 MB) / 452984832 bytes (432 MB) up to 536870912 bytes (512 MB)
```
Allocate more memory to Minecraft.
1GB should be enough.
