### ISSUE TITLE
Crash when launching Optifine HD U E3 pre1 for Minecraft 1.13.1

### ISSUE THREAD

**Issue by Polda18** [sp614x/optifine#1815]
Hi. I got this error:
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 19.9.18 22:17
Description: Initializing game

ddj: Unable to fit: minecraft:block/lava_flow, size: 32x32, atlas: 0x0, atlasMax: 0x0 - Maybe try a lower resolution resourcepack?
	at ddi.c(Stitcher.java:69)
	at ddk.b(TextureMap.java:288)
	at ddk.a(TextureMap.java:121)
	at dfb.a(ModelBakery.java:463)
	at dfc.a(SourceFile:24)
	at vh.a(SourceFile:118)
	at cfs.am(SourceFile:507)
	at cfs.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ddi.c(Stitcher.java:69)
	at ddk.b(TextureMap.java:288)
	at ddk.a(TextureMap.java:121)
	at dfb.a(ModelBakery.java:463)
	at dfc.a(SourceFile:24)
	at vh.a(SourceFile:118)
	at cfs.am(SourceFile:507)

-- Initialization --
Details:
Stacktrace:
	at cfs.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 422705304 bytes (403 MB) / 805306368 bytes (768 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	Launched Version: 1.13.1-OptiFine_HD_U_E3_pre1
	LWJGL: 3.1.6 build 14
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.5.13506 Compatibility Profile Context 23.20.15017.3010, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Čeština (Česko)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-6310 APU with AMD Radeon R4 Graphics 
	OptiFine Version: OptiFine_1.13.1_HD_U_E3_pre1
	OptiFine Build: 20180914-191348
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13506 Compatibility Profile Context 23.20.15017.3010
	OpenGlRenderer: AMD Radeon(TM) R4 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```
I started getting this error first today with `beta5` version, so I tried to restart launcher - didn't work. Tried to install to `pre1` version - didn't work. Tried clear cache with CCleaner from litter - didn't work. Tried reinstall Optifine - didn't work. What the hell is going on?

**Comment by sp614x** [comment]
Usually happens after a new graphics driver is installed. 
To fix it restart the computer.
