### ISSUE TITLE
Crash on 1.13.1-Pre2

### ISSUE THREAD

**Issue by Vitaliy100** [sp614x/optifine#1825]
[19:33:05] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[19:33:05] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[19:33:05] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
[L] Minecraft closed with exit code: 1 (0x1)
[L] Launcher stopped.

**Comment by ESTPlayer** [comment]
I have exactly the same crash.

**Comment by Vitaliy100** [comment]
[1.13.1-OptiFine_HD_U_E3_pre2 Fixed JSON.zip](https://github.com/sp614x/optifine/files/2412224/1.13.1-OptiFine_HD_U_E3_pre2.Fixed.JSON.zip)
Fixed JSON,it's took a hour for me to fix the problem

**Comment by Linkmontblac** [comment]
The fix Is not opening for some reason

**Comment by Vitaliy100** [comment]
But it's worked for me and my friends

**Comment by skmedix** [comment]
https://github.com/sp614x/optifine/issues/1728#issuecomment-418708929
`This is a custom launcher (TLauncher) which is not supported.`
