### ISSUE TITLE
Minecraft won't launch on Linux on 1.13.1

### ISSUE THREAD

**Issue by lelandliu** [sp614x/optifine#1909]
Tested on Arch Linux, found another person with the [same issue on Debian](https://www.reddit.com/r/Minecraft/comments/9ckrzx/113_optifine_not_working_on_linux/). Had the issue on all 1.13 versions of optifine.

I am unable to get a crash log on my computer for some reason (it's just stuck on "Waiting for log output..."), but here is the multimc5 crash log.

`MultiMC version: 0.6.2-custom

Minecraft folder is:
/home/aquamarine/.local/share/multimc/instances/1.13.1/.minecraft

Java path is:
/usr/lib/jvm/java-8-openjdk/jre/bin/java

Java is version 1.8.0_181, using 64-bit architecture.

AMD Ryzen 5 2600 Six-Core Processor
NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)

Subsystem: eVga.com. Corp. GP106 [GeForce GTX 1060 6GB]

Kernel driver in use: nvidia

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/aquamarine/.local/share/multimc/instances/1.13.1/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/aquamarine/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/aquamarine/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/aquamarine/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/aquamarine/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/aquamarine/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/aquamarine/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/aquamarine/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/aquamarine/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/aquamarine/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/aquamarine/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/aquamarine/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/aquamarine/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/aquamarine/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/aquamarine/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar
  /home/aquamarine/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/aquamarine/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/aquamarine/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/aquamarine/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/aquamarine/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/aquamarine/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /home/aquamarine/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/aquamarine/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/realms/1.13.8/realms-1.13.8.jar
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/aquamarine/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/aquamarine/.local/share/multimc/libraries/INVALID (missing)
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/minecraft/1.13.1/minecraft-1.13.1-client.jar

Native libraries:
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-linux.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-linux.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-linux.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-linux.jar
  /home/aquamarine/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-linux.jar
  /home/aquamarine/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/aquamarine/.local/share/multimc/instances/1.13.1/.minecraft --assetsDir /home/aquamarine/.local/share/multimc/assets --assetIndex 1.13.1 --uuid  --accessToken  --userType  --versionType release --tweakClass optifine.OptiFineTweaker

Window size: 1280 x 720

Java Arguments:
[-Xms409m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 9536

Using onesix launcher.

[19:37:14] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[19:37:14] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
`

**Comment by ozals** [comment]
I don't know much about Arch (I run Linux Mint myself), but this might fix your problem https://github.com/sp614x/optifine/issues/1818#issuecomment-427983171

**Comment by ozals** [comment]
Yep, multimc is known to have problems with optifine, I don't have a reddit account myself so if you have one it would be greatly appreciated to link them to [this](https://github.com/sp614x/optifine/issues/1818#issuecomment-427983171) (the [reddit thread](https://www.reddit.com/r/Minecraft/comments/9ckrzx/113_optifine_not_working_on_linux/) I'm talking about).

**Comment by lelandliu** [comment]
sure thing!
