### ISSUE TITLE
[1.13.1 E4 pre1] OpenGL error: 1281 (Invalid value), at: Expand VBO

### ISSUE THREAD

**Issue by SteveKunG** [sp614x/optifine#1950]
OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid offset and/or size.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39)
	at org.lwjgl.opengl.GL15.nglBufferSubData(Native Method)
	at org.lwjgl.opengl.GL15.glBufferSubData(GL15.java:480)
	at dhp.glBufferSubData(OpenGlHelper.java:1024)
	at net.optifine.render.VboRegion.bufferData(VboRegion.java:105)
	at ddu.a(VertexBuffer.java:36)
	at cun.a(SourceFile:14)
	at cwo.a(ChunkRenderDispatcher.java:308)
	at cwo.a(ChunkRenderDispatcher.java:270)
	at cwo.lambda$uploadChunk$2(ChunkRenderDispatcher.java:284)
	at cwo$$Lambda$1183/1668212785.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cwo.a(ChunkRenderDispatcher.java:126)
	at cud.a(RenderGlobal.java:2430)
	at ctx.b(EntityRenderer.java:1337)
	at ctx.a(EntityRenderer.java:1217)
	at ctx.a(EntityRenderer.java:979)
	at cfs.c(SourceFile:850)
	at cfs.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheRealDannyyy** [comment]
I'm experiencing similar issues with OpenGL. Maybe this helps towards what's causing it but I have a suspicion that certain particle effects could be the cause.

**Comment by sp614x** [comment]
@Zefferis can you post a minimal resource pack that triggers the problem?

**Comment by Zefferis** [comment]
@sp614x 

Here ya go

when flying through a world, ( places that can generate gravel for instance ) with an overlay for gravel; it causes this.

I believe a few other overlay blocks cause this but I lost my note on which ones :( 

quick way to cause it to happen, use seed: 6209738985621030524
coordinates: "/tp <player> -134 95 1626"

In this particular case, it only requires a gravel overlay to list stone as match block, other blocks are fine.

[OpenGL Error 1281.zip](https://github.com/sp614x/optifine/files/2640467/OpenGL.Error.1281.zip)

**Comment by sp614x** [comment]
Can't reproduce it so far.
Testing OF 1.13.2 E5_pre6 + RP "OpenGL Error 1281.zip" + VBOs + Render Regions:

![image](https://user-images.githubusercontent.com/16635441/49579916-ec79bf80-f94d-11e8-9b88-a55dedcc375b.png)

Also tested on a new world, seed 6209738985621030524 + "/tp -134 95 1626".
Terrain generation is a bit slow, but no OpenGL errors.

**Comment by Barteks2x** [comment]
As I said on discord, I can almost always reproduce it by using F3+A right after fast movement that causes loading new chunks. Depending on complexity of terrain, it may need very fast movement (max spectator speed), or creative flight is enough.

It doesn't need any special resource pack, no special coordinates are needed. I think the only reason it may be easier to reproduce in some world/coordinates/resourcepack is that it makes chunk updates slower. I was only able to reproduce it with high render distance values, but that may have been just a coincidence.

**Comment by sp614x** [comment]
Looks like a race condition between the chunk loading threads and the forced chunks reload.

**Comment by SteveKunG** [comment]
This also happened when entering to The Nether.

![2018-12-09_23 48 53](https://user-images.githubusercontent.com/6128413/49700114-0e549a00-fc0d-11e8-8a2c-c6d13bdb11de.png)

**Comment by Zefferis** [comment]
Another individual who had this problem had an nvidia graphics card; perhaps related?

**Comment by Lord-Vlad** [comment]
![2019-07-31_13 23 22](https://user-images.githubusercontent.com/44706659/62208320-c3071b80-b396-11e9-9052-907eb6d2aed8.png)

I got this in my log:

> OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL14C.nglMultiDrawArrays(Native Method)
	at org.lwjgl.opengl.GL14C.glMultiDrawArrays(GL14C.java:153)
	at org.lwjgl.opengl.GL14.glMultiDrawArrays(GL14.java:352)
	at com.mojang.blaze3d.platform.GlStateManager.glMultiDrawArrays(GlStateManager.java:1221)
	at net.optifine.render.VboRegion.finishDraw(VboRegion.java:325)
	at dnp.drawRegion(VboRenderList.java:110)
	at dnp.a(VboRenderList.java:40)
	at dng.a(WorldRenderer.java:1555)
	at dng.a(WorldRenderer.java:1531)
	at dnc.b(GameRenderer.java:1307)
	at dnc.a(GameRenderer.java:1032)
	at dnc.a(GameRenderer.java:792)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

**Comment by SteveKunG** [comment]
Since 1.13.2 I cannot reproduce this. Closing this?

**Comment by Newkdehenkeil** [comment]
I've the same error, but I don't have a GtForce or a Nvidia...I've a Intel HD 4000  and I play in 1.12.2 or 1.8
![2019-08-18_19 45 57](https://user-images.githubusercontent.com/48518299/63228804-f2bc7d00-c1f8-11e9-9fb8-e01f8372540b.png)

**Comment by flarefluffsune** [comment]
I was wondering what this was popping up in my minecraft lately, but I'm getting the same issue. Using 1.14.4 Minecraft, Latest Optifine and latest forge build 28.1.99, with the Clarity 1.14 texture pack.
![2019-12-03_13 26 55](https://user-images.githubusercontent.com/20187367/70055180-f2da6000-15d0-11ea-8998-b3000aae6110.png)

**Comment by jackjt8** [comment]
**GPU / Driver:** RTX 2070 Driver `445.87`
**Tested with OptiFine:** `1.13.2 HD_U_E7`, `1.13.2 HD_U_F5`, `1.14.4 HD_U_F5`
**Resource pack:** Excalibur v1.4

Something about having `VBOs` & `Render Regions` ON while using a resource pack with CTM is causing this for me. Disabling any of these three fixes the problem but of course that's not ideal.

Suppressing Open GL Errors is probably the better "solution" here given we can still benefit from VBOs, Region Regions, & CTMs... But then we won't be able to see any other OpenGL Errors if they occur.

[latest.log](https://github.com/sp614x/optifine/files/4668904/latest.log)
