### ISSUE TITLE
Optifine 1.13.1 U E3 crash at startup

### ISSUE THREAD

**Issue by Jericho2k18** [sp614x/optifine#1951]
When I try to play MC, it gives me this message:

[12:33:25] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[12:33:25] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[12:33:25] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

**Comment by ozals** [comment]
Are you on Linux, or using MultiMC?

**Comment by sp614x** [comment]
This is a problem with Team Extreme Launcher.
https://github.com/sp614x/optifine/issues/1825
