### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by andrew121410** [sp614x/optifine#1958]
Running Ubuntu Destop 18.10
Optifine Version: OptiFine 1.13.1 HD U E3

[1021/151306:WARNING:x11_util.cc(1404)] X error received: serial 1213, error_code 182 (GLXBadWindow), request_code 155, minor_code 32 (X_GLXDestroyWindow)
[1021/151306:WARNING:x11_util.cc(1404)] X error received: serial 1219, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
[1021/151306:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Strum355** [comment]
Please see issue #1818 as i posted the fix there

**Comment by andrew121410** [comment]
Thanks, don't know why ubuntu comes with open-jdk.

**Comment by andrew121410** [comment]
How do i close this issue.

**Comment by Strum355** [comment]
Oracle java requires you to accept T&C sorta thing, openjdk doesnt

**Comment by mrpickles3rd** [comment]
> How do i close this issue.

You can use `[key words](https://help.github.com/articles/closing-issues-using-keywords/)` to close the issue - like - "close #1818" or "closed"... check doc's for more... sorry I can't help more.
