### ISSUE TITLE
OptiFine can't launch with Minecraft Launcher 2.1.1462

### ISSUE THREAD

**Issue by SiuSum** [sp614x/optifine#1973]
> OptiFine Version: OptiFine_1.13_HD_U_E4
OptiFine Build: 20181025-102956

When I enter to singleplayer world or server, the game has crashed.

```
It looks like you are using an unsupported modified version of the game.

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```

I added `-Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true` to JVM Arguments, but it has no effect.

```
java.lang.NullPointerException: Unexpected error
	at cex.a(SourceFile:60)
	at cex.a(SourceFile:72)
	at ctm.a(FogRenderer.java:69)
	at ctn.b(EntityRenderer.java:1269)
	at ctn.a(EntityRenderer.java:1246)
	at ctn.a(EntityRenderer.java:979)
	at cfi.c(SourceFile:847)
	at cfi.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:157)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23)
```

**Comment by sp614x** [comment]
Can you post the error log or game output?
Is vanilla working correctly?

**Comment by SiuSum** [comment]
I found the cause of the problem, just delete the original OptiFine settings file.

**Comment by SiuSum** [comment]
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 27/10/2018 上午12:46
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cex.a(SourceFile:60)
	at cex.a(SourceFile:72)
	at ctm.a(FogRenderer.java:69)
	at ctn.b(EntityRenderer.java:1269)
	at ctn.a(EntityRenderer.java:1246)
	at ctn.a(EntityRenderer.java:979)
	at cfi.c(SourceFile:847)
	at cfi.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:157)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cex.a(SourceFile:60)
	at cex.a(SourceFile:72)
	at ctm.a(FogRenderer.java:69)
	at ctn.b(EntityRenderer.java:1269)
	at ctn.a(EntityRenderer.java:1246)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 416, 416
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 252 game time, 252 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at cqv.a(WorldClient.java:589)
	at cfi.b(SourceFile:1811)
	at cfi.a(SourceFile:405)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:157)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23)

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 12-ea, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 286746936 bytes (273 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13-OptiFine_HD_U_E4
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 745/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.16, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: 繁體中文 (台灣)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.13_HD_U_E4
	OptiFine Build: 20181025-102956
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.16
	OpenGlRenderer: GeForce GTX 745/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```
