### ISSUE TITLE
Ubuntu Java v10 Optifine won't launch

### ISSUE THREAD

**Issue by kylerchin** [sp614x/optifine#2044]
Got this error plz, save me:
```[1122/144129:INFO:LocalVersionProvider.cpp(81)] Looking for installed versions in /root/.minecraft/versions

[1122/144129:INFO:GameCallbacks.cpp(193)] launcher/launcher (main) info Process closed with exit code 0

[1122/144129:INFO:GameCallbacks.cpp(193)] launcher/launcher (main) info Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by SetantaLP** [comment]
It's a problem with the launchwrapper that optifine uses. But there are workarounds for this issue as mentioned in #1739

**Comment by ozals** [comment]
This should fix it https://github.com/sp614x/optifine/issues/1818#issuecomment-427983171
