### ISSUE TITLE
Optifine HD for 1.12.2 E2 crashing

### ISSUE THREAD

**Issue by gspalato** [sp614x/optifine#2048]
Log: `[13:02:30] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:02:30] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:02:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[13:02:30] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2784 for Minecraft 1.12.2 loading
[13:02:30] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_51
[13:02:31] [main/INFO] [FML]: Searching C:\Users\hinok\AppData\Roaming\.minecraft\mods for mods
[13:02:31] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E2.jar
[13:02:31] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:02:31] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[13:02:31] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:02:31] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:02:31] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:02:31] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[13:02:31] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[13:02:31] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[13:02:31] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[13:02:31] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\hinok\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_E2.jar
[13:02:31] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:02:33] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[13:02:33] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[13:02:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:02:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:02:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:02:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:02:34] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[13:02:34] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[13:02:36] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[13:02:36] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[13:02:36] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: java.lang.ExceptionInInitializerError
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.common.ForgeHooks.<clinit>(ForgeHooks.java:324)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName0(Native Method)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName(Class.java:264)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.getTargetClass(ReflectorClass.java:47)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:26)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:17)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:264)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.renderer.vertex.DefaultVertexFormats.<clinit>(DefaultVertexFormats.java:16)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.client.ForgeHooksClient$LightGatheringTransformer.<clinit>(ForgeHooksClient.java:599)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.client.ForgeHooksClient.<clinit>(ForgeHooksClient.java:642)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:335)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:02:39] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:02:39] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.RuntimeException: Accessed Items before Bootstrap!
[13:02:39] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.init.Items.<clinit>(SourceFile:9)
[13:02:39] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 18 more
[13:02:40] [main/WARN] [Config]: [OptiFine] (Reflector) More than one method found: net.minecraft.potion.Potion.renderHUDEffect
[13:02:40] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(net.minecraft.potion.PotionEffect,net.minecraft.client.gui.Gui,int,int,float,float)
[13:02:40] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(int,int,net.minecraft.potion.PotionEffect,net.minecraft.client.Minecraft,float)
[13:02:40] [main/INFO] [Config]: [OptiFine] *** Reflector Vanilla ***
[13:02:41] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: o_Hinoki
[13:02:44] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.init.Items
	at net.minecraft.potion.PotionHelper.func_185207_a(PotionHelper.java:154) ~[akh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:504) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[13:02:44] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:02:44] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[13:02:44] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[13:02:44] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[13:02:44] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[13:02:44] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[13:02:44] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by ProxyPlayerHD** [comment]
still getting the crash, removing optifine works.

Forge: 14.23.5.2808

OF: 1.12.2_HD_U_E2

**Comment by realjackasterisk** [comment]
E2 is incompatible with the latest versions of forge. you need E3.

**Comment by ProxyPlayerHD** [comment]
welp should've checked the versions. didn't excpet there to be a new one

**Comment by Xwicked-knightX** [comment]
I know this is closed but from what i can tell he had an item with no texture throwing optifine into an infinite loop looking for an none existing texture.. At least thats what i encountered with this issue
