### ISSUE TITLE
OptiFine_1.12.2_HD_U_E2 crashing with Forge >= 2794

### ISSUE THREAD

**Issue by QuImUfu** [sp614x/optifine#2068]
Issue originally reported here https://github.com/MultiMC/MultiMC5/issues/2480 , log included.
can reproduce with **only** Forge and  OptiFine.  
Log:  
```
MultiMC version: 0.6.2-1137


Minecraft folder is:
/home/koala/MultiMC/instances/Tst/.minecraft


Java path is:
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java


Java is version 1.8.0_181, using 64-bit architecture.


Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz
Advanced Micro Devices, Inc. [AMD/ATI] RV620 LE [Radeon HD 3450]

Subsystem: PC Partner Limited / Sapphire Technology RV620 LE [Radeon HD 3450]

Kernel driver in use: radeon

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/koala/MultiMC/instances/Tst/natives

Libraries:
  /home/koala/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/koala/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/koala/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/koala/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/koala/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/koala/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/koala/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/koala/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/koala/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/koala/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/koala/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/koala/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/koala/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/koala/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/koala/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/koala/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/koala/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/koala/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/koala/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/koala/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/koala/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/koala/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/koala/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/koala/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/koala/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/koala/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/koala/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/koala/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/koala/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/koala/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/koala/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/koala/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2794/forge-1.12.2-14.23.5.2794-universal.jar
  /home/koala/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/koala/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /home/koala/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /home/koala/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/koala/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/koala/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/koala/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/koala/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/koala/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/koala/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/koala/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/koala/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/koala/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/koala/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/koala/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/koala/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/koala/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/koala/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /home/koala/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/koala/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/koala/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/koala/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Mods:
  OptiFine_1.12.2_HD_U_E2(3)

Params:
  --username  --version MultiMC5 --gameDir /home/koala/MultiMC/instances/Tst/.minecraft --assetsDir /home/koala/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms1024m, -Xmx1536m, -Duser.language=en]


Minecraft process ID: 13985


Using onesix launcher.

[22:53:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:53:08] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:53:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[22:53:08] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2794 for Minecraft 1.12.2 loading
[22:53:08] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_181, running on Linux:amd64:4.19.4-041904-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[22:53:08] [main/INFO] [FML]: Searching /home/koala/MultiMC/instances/Tst/.minecraft/mods for mods
[22:53:08] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E2(3).jar
[22:53:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:53:08] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[22:53:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:53:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:53:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:53:08] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[22:53:08] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[22:53:08] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[22:53:08] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[22:53:08] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: /home/koala/MultiMC/instances/Tst/.minecraft/mods/OptiFine_1.12.2_HD_U_E2(3).jar
[22:53:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:53:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:53:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:53:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:53:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:53:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:53:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:53:11] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[22:53:11] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:53:13] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[22:53:13] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[22:53:13] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: java.lang.ExceptionInInitializerError
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.common.ForgeHooks.<clinit>(ForgeHooks.java:324)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName0(Native Method)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName(Class.java:264)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.getTargetClass(ReflectorClass.java:47)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:26)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:17)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:264)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.renderer.vertex.DefaultVertexFormats.<clinit>(DefaultVertexFormats.java:16)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.client.ForgeHooksClient$LightGatheringTransformer.<clinit>(ForgeHooksClient.java:599)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.client.ForgeHooksClient.<clinit>(ForgeHooksClient.java:642)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:335)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:53:15] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[22:53:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.RuntimeException: Accessed Items before Bootstrap!
[22:53:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.init.Items.<clinit>(SourceFile:9)
[22:53:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 26 more
[22:53:15] [main/WARN] [Config]: [OptiFine] (Reflector) More than one method found: net.minecraft.potion.Potion.renderHUDEffect
[22:53:15] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(net.minecraft.potion.PotionEffect,net.minecraft.client.gui.Gui,int,int,float,float)
[22:53:15] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(int,int,net.minecraft.potion.PotionEffect,net.minecraft.client.Minecraft,float)
[22:53:15] [main/INFO] [Config]: [OptiFine] *** Reflector Vanilla ***
[22:53:16] [Client thread/INFO] [minecraft/Minecraft]: Setting user: QuImUfu
[22:53:18] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.init.Items
	at net.minecraft.potion.PotionHelper.func_185207_a(PotionHelper.java:154) ~[akh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:504) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 14 more
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(System.java:971)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:53:18] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[22:53:18] [Client thread/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[22:53:18] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:53:18] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[22:53:18] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:53:18] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:53:18] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[22:53:18] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "Client thread" 
Process exited with code 1.
Clipboard copy at: 03 Dec 2018 22:58:15 +0100
```

**Comment by ZombieHDGaming** [comment]
Update Optifine to 1.12.2-U-E3-pre from the Optifine website. This was fixed in a release earlier today.

**Comment by skmedix** [comment]
Duplicate of #2061

**Comment by QuImUfu** [comment]
sorry.
