### ISSUE TITLE
[1.10.2] Crash when trying to run with FTB unstable

### ISSUE THREAD

**Issue by natandestroyer** [sp614x/optifine#213]
Using the latest optifine version. Here is the crash report: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10-0.4.0.31-alpha.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
  LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  LoadingPlugin (Quark-beta-32.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 17:59 05/07/16
Description: Initializing game

java.lang.NoSuchFieldError: ofAaLevel
	at Config.initDisplay(Config.java:199)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:114)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:431)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at Config.initDisplay(Config.java:199)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:114)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:431)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 558428520 bytes (532 MB) / 797442048 bytes (760 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xms256M -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10-0.4.0.31-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)
  
LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  lumien.custommainmenu.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-beta-32.jar)
  vazkii.quark.base.asm.ClassTransformer
	Launched Version: 1.10
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4331, Intel
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft  64x MC110.zip
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by natandestroyer** [comment]
Nevermind, turns out the pack is 1.10.0 and using that optifine version works fine. closed.
