### ISSUE TITLE
Sometimes when changing some options optifine will update all chunks as display lists instead of VBOs, even if VBOs are enabled, causing the game to hang for a long time on some GPUs

### ISSUE THREAD

**Issue by Barteks2x** [sp614x/optifine#2167]
In OptiFine 1.12.2 E3, sometimes when changing some random options (I had it happen with mipmap type and natural textures) OptiFine will randomly decide to reload all visible chunks as display lists instead of VBOs even if VBOs are enabled. This makes OptiFine completely hang for a very long time with big render distance. The stacktrace when it happens looks like this (running in IDE):
```
  java.lang.Thread.State: RUNNABLE
	  at org.lwjgl.opengl.GL11.nglGenLists(GL11.java:-1)
	  at org.lwjgl.opengl.GL11.glGenLists(GL11.java:1415)
	  at net.minecraft.client.renderer.GlStateManager.glGenLists(GlStateManager.java:922)
	  at net.minecraft.client.renderer.GLAllocation.generateDisplayLists(GLAllocation.java:20)
	  - locked <0x17a8> (a java.lang.Class)
	  at net.minecraft.client.renderer.chunk.ListedRenderChunk.<init>(ListedRenderChunk.java:13)
	  at net.minecraft.client.renderer.chunk.ListChunkFactory.create(ListChunkFactory.java:13)
	  at net.minecraft.client.renderer.ViewFrustum.createRenderChunks(ViewFrustum.java:54)
	  at net.minecraft.client.renderer.ViewFrustum.<init>(ViewFrustum.java:38)
	  at net.minecraft.client.renderer.RenderGlobal.loadRenderers(RenderGlobal.java:663)
	  at net.minecraft.client.settings.GameSettings.setOptionValueOF(GameSettings.java:2052)
	  at net.minecraft.client.settings.GameSettings.setOptionValue(GameSettings.java:508)
	  at net.optifine.gui.GuiQualitySettingsOF.actionPerformed(GuiQualitySettingsOF.java:67)
	  at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:494)
	  at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:611)
	  at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:576)
	  at net.minecraft.client.Minecraft.runTick(Minecraft.java:1869)
	  at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1174)
	  at net.minecraft.client.Minecraft.run(Minecraft.java:436)
	  at net.minecraft.client.main.Main.main(Main.java:118)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	  at GradleStart.main(GradleStart.java:25)
```

**Comment by Barteks2x** [comment]
Antialiasing and Anisotropic Filtering could explain it. But I think ptiFine shouldn't just silently disable VBOs in that case.

And would it at least be feasible to allocate all the display lists in one go instead of requesting 4 at a time to speed it up? With big render distance it can take more than half an hour just to create all the (empty) display lists.
