### ISSUE TITLE
java.lang.IllegalStateException: Already building!

### ISSUE THREAD

**Issue by tomevoll** [sp614x/optifine#22]
`java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.WorldRenderer.func_181668_a(WorldRenderer.java:265)
    at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1817)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1606)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1537)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1322)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Doing custon rendering in ISmartItemModel under getGeneralQuads().

Without optifine a worldrenderer.begin(7, DefaultVertexFormats.ITEM); is called before getGeneralQuads(), witch some use by doing a tessellator.draw(); in getGeneralQuads() then do the rendering they need and call worldrenderer.begin(7, DefaultVertexFormats.ITEM) again before returning a emty list.

Is this something that can easily be changed in optifine to allow this to also work with optifine?

**Comment by tomevoll** [comment]
forgot to mention this error only shows when i open the inventory in creative mode, and did not crash rendering those items in hand or in the inventory (i think it may be the tab icon?). 

In hand an in the inventory, text and other items rendered as an overlay on the block was visible, the cube itself rendered using worldrenderer with vertexUV was not visible. this work as expected  without optifine.

**Comment by sp614x** [comment]
Is this issue still relevant to latest version D2 for 1.10.2?

**Comment by juanmelk** [comment]
I got this bug in D2 and I still get it in D3, here's a paste.ee
I think it might be related to JEI? At least for me. It happens in survival.
http://paste.ee/p/sNPI0

**Comment by sp614x** [comment]
This is probably the problem:

    [18:17:12] [Client thread/WARN]: net.minecraft.client.renderer.RenderItem.func_184391_a:512
    [18:17:12] [Client thread/WARN]: net.minecraft.client.renderer.RenderItem.func_180450_b:467
    [18:17:12] [Client thread/WARN]: mcp.mobius.waila.overlay.DisplayUtil.renderStack:77
    [18:17:12] [Client thread/WARN]: Catched unhandled exception : [renderStack | 1xtile.ExtraUtils2:EnderLilly@7] net.minecraft.util.ReportedException: Rendering item

The EnderLily from ExtraUtilities2 uses an invalid model. One of the BakedQuads has a NULL TextureAtlasSprite: https://github.com/rwtema/extrautilities/issues/1057

This is a known problem which only appears with AA/AF enabled: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-d1-fps-boost-dynamic-lights-shaders?comment=52948

**Comment by sp614x** [comment]
The error can be reproduced with only OptiFine D3 for 1.10.2 and ExtraUtils2-1.10.2-alpha-1.2.2.
Enabling AA or AF and opening the creative inventory on the ExtraUtils tab crashes when rendering the EnderLilly. 
The exception: https://gist.github.com/sp614x/d19b4bddbe22b40e890eb84c5a14829a

**Comment by sp614x** [comment]
Added a workaround in preview D4: http://optifine.net/adloadx?f=preview_OptiFine_1.10.2_HD_U_D4_pre.jar
Now it will try to repair the broken model so that it can be renderer.

**Comment by PineapplExplosive** [comment]
so what do I do to fix this? I don't have AA or AF enabled i have extraUtils1.10.2-1.3.0 and Optifine 1.10.2 HD_U_D6. Can I delete a folder that has JEI/NEI information so it can reset the config but not my inventory?

**Comment by juanmelk** [comment]
Update Optifine.

**Comment by dlk6** [comment]
Culd sombody help me with this?

`The game crashed whilst rendering item
Error: java.lang.IllegalStateException: Not building!
Exit Code: -1`
