### ISSUE TITLE
Already Building! crash

### ISSUE THREAD

**Issue by Dayyer1** [sp614x/optifine#2259]
When scrolling through an Applied Energistics or Refined Storage terminal, I get this crash. I've looked around on here and have seen that the Already Building! part is not the actual issue, so here's the latest log. I'm not sure if it's Optifine, but it was in both reports. I will post on the other mods' githubs.

MC 1.12.2
Forge 2820
Optifine E3

[latest.log](https://github.com/sp614x/optifine/files/2984786/latest.log)

I'm guessing that there's an item rendering issue, but I'm not sure what it is or how to find out what item it is. I'm not good at reading crash logs.
Thanks.

**Comment by realjackasterisk** [comment]
1. OptiFine E3 for 1.12.2 is compatible with Forge 2795. compatibility with newer versions is possible, but not guaranteed.
2. you have over 190 mods, you need to test without them:

- split the mods in two groups
- test one group of the mods
- keep the group that crashes
- repeat until there is only one mod except OptiFine left

**Comment by sp614x** [comment]
The EnderIO recipe plugin crash:
```
[12:42:34] [Client thread/ERROR]: Recipe registry plugin crashed: class crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1
java.lang.NullPointerException: null
	at crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1.getWrappers(DarkSteelUpgradeRecipeCategory.java:127) ~[DarkSteelUpgradeRecipeCategory$1.class:?]
	at crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1.getRecipeWrappers(DarkSteelUpgradeRecipeCategory.java:98) ~[DarkSteelUpgradeRecipeCategory$1.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.lambda$getRecipeWrappers$1(RecipeRegistryPluginSafeWrapper.java:30) ~[RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper$$Lambda$3807/2050366067.get(Unknown Source) ~[?:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.callPluginMethod(RecipeRegistryPluginSafeWrapper.java:42) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.getRecipeWrappers(RecipeRegistryPluginSafeWrapper.java:30) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistry.getRecipeWrappers(RecipeRegistry.java:572) [RecipeRegistry.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.updateRecipes(RecipeGuiLogic.java:169) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setRecipesPerPage(RecipeGuiLogic.java:160) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:461) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:523) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setState(RecipeGuiLogic.java:109) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:64) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:392) [RecipesGui.class:?]
	at mezz.jei.input.InputHandler.handleMouseClickedFocus(InputHandler.java:182) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:130) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:99) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:88) [InputHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2719_InputHandler_onGuiMouseEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
