### ISSUE TITLE
Crash with OpenBlocks Glyph and AF/AA enabled

### ISSUE THREAD

**Issue by Spodi** [sp614x/optifine#2267]
The game crashes every time a glyph (item/block) from OpenBlocks should be rendered and AF (ond/or probalby AA) is enabled in Optifine. In this case its trying to render in JEI.

Crash explained in OpenBlocks bug Tracker: https://github.com/OpenMods/OpenBlocks/issues/948

Maybe related to #1031
```
Description: Rendering ingredient

java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.client.renderer.BufferBuilder.drawMultiTexture(BufferBuilder.java:847)
	[...]

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.drawMultiTexture(BufferBuilder.java:847)
	[...]

-- Ingredient being rendered --
Details:
	Ingredient Mod: OpenBlocks
	Ingredient Info: 1xitem.openblocks.glyph@32 openblocks:glyph
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:250)
	[...]
```
Full Crash report:
https://pastebin.com/rHjhdxmK

**Versions**
Minecraft: 1.12.2
Forge: 14.23.5.2796
Openblocks: 1.8
JEI: 4.13.1.255
OptiFine: HD U E3

**Comment by jedthe3rd** [comment]
I just experienced this bug as well is there any progress on this?

**Comment by jakey1995abc** [comment]
Would be nice if @sp614x took note of this bug. We recently received an update for optifine yet this widespread bug was not fixed.

**Comment by Spodi** [comment]
Please always post at least your version of Minecraft and Optifine where you encountered this or it is assumed youre using the same setup as i was. I only have a MC1.7.10 (jeah, THAT old) setup at the moment, so i can't test things.

**Comment by poisax** [comment]
This bug is still relevant :')

**Comment by Hexcede** [comment]
This bug is still a problem, Forge 1.12.2

Can't type "dirt" into NEI or my game crashes from this item being rendered.

**Comment by Cookiekiste** [comment]
Same

**Comment by realSNES** [comment]
same

**Comment by TheGoldenCloudx** [comment]
Still having this issue

**Comment by IsaacGithub9** [comment]
@sp614x will you try to fix this bug or not?
