### ISSUE TITLE
Mod incompatibility

### ISSUE THREAD

**Issue by Vectron** [sp614x/optifine#227]
there seems to be a problem with mapwriter and optifine for some people.

the game crashes with a buffer error:
org.lwjgl.BufferChecks.throwBufferSizeException(BufferChecks.java:162)
at org.lwjgl.BufferChecks.checkBufferSize(BufferChecks.java:189)
at org.lwjgl.BufferChecks.checkBuffer(BufferChecks.java:244)
at org.lwjgl.opengl.GL11.glGetTexImage(GL11.java:1675)
at mapwriter.util.Texture.getPixelsFromExistingTexture(Texture.java:195)

this only seems to happen if optifine is installed. what i could find in the logs is that after binding the blocks texture the width and height returned from the vga are both 0.

**Comment by sp614x** [comment]
Full crash report?

**Comment by sp614x** [comment]
No response
