### ISSUE TITLE
"/ by 0" crash on startup w/ Dynamic Trees & Apotheosis/Placebo

### ISSUE THREAD

**Issue by XvBUSHvX** [sp614x/optifine#2344]
Dynamic Trees Throws
"/ by 0" crash on startup w/ Dynamic Trees & Apotheosis/Placebo

> [Follow up.
> MC: 1.12.2
> Forge: 2836 (Issue encountered on an earlier version, but suggested by mod involved "Apotheosis"
> 
> Minimal list of mods to reproduce.
> 
> Dynamic Trees 0.9.5
> Apotheosis 1.9.4
> Placebo 1.6.0 (used by Apotheosis)
> Optifine: Encountered w/ "preview_OptiFine_1.12.2_HD_U_E4_pre4"
> Additionally tested against "OptiFine_1.12.2_HD_U_E3"
> 
> This was tested without VanillaFix for the same outcome, then VanillaFix was added for convenience with the hastebin (link) which replicates the above report.](https://github.com/ferreusveritas/DynamicTrees/issues/254#issuecomment-488570733)

**Comment by sp614x** [comment]
The crash is inside DynamicTrees, not related to OptiFine.
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Trees (dynamictrees)
Caused by: java.lang.ArithmeticException: / by zero
    at com.ferreusveritas.dynamictrees.client.TextureUtils.avgColors(TextureUtils.java:191)
    at com.ferreusveritas.dynamictrees.client.TextureUtils$PixelBuffer.averageColor(TextureUtils.java:114)
    at com.ferreusveritas.dynamictrees.proxy.ClientProxy.discoverWoodColors(ClientProxy.java:106)
    at com.ferreusveritas.dynamictrees.proxy.ClientProxy.postInit(ClientProxy.java:85)
    at com.ferreusveritas.dynamictrees.DynamicTrees.postInit(DynamicTrees.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
```
