### ISSUE TITLE
1.14 pre4 Crash cause by animated vanilla paintings.

### ISSUE THREAD

**Issue by JimStoneCraft** [sp614x/optifine#2393]
Crash with my resource pack (John Smith Legacy 1.14.1 v2).

https://www.johnsmithlegacy.co.uk/

One of my users tracked it down to the two animated paintings I have in the pack, they work fine in vanilla and give no error.

textures/painting/plant.png
textures/painting/plant.png.mcmeta
textures/painting/stage.png
textures/painting/stage.png.mcmeta

Here's the crash report using preview_OptiFine_1.14_HD_U_F1_pre4.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 23/05/19 17:59
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.get(BitSet.java:623)
	at net.optifine.SmartAnimations.isSpriteRendered(SmartAnimations.java:55)
	at dug.n(TextureAtlasSprite.java:447)
	at duf.a(TextureMap.java:645)
	at duf.e(TextureMap.java:754)
	at duh.e(TextureManager.java:174)
	at cvi.n(SourceFile:1381)
	at cvi.d(SourceFile:925)
	at cvi.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.BitSet.get(BitSet.java:623)
	at net.optifine.SmartAnimations.isSpriteRendered(SmartAnimations.java:55)
	at dug.n(TextureAtlasSprite.java:447)
	at duf.a(TextureMap.java:645)
	at duf.e(TextureMap.java:754)
	at duh.e(TextureManager.java:174)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [djv['sodamnfake'/1746884, l='MpServer', x=-59.94, y=70.00, z=-99.59]]
	Chunk stats: MultiplayerChunkCache: 729, 5
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dhl.a(WorldClient.java:545)
	at cvi.b(SourceFile:1920)
	at cvi.b(SourceFile:431)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 565476752 bytes (539 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14-OptiFine_HD_U_F1_pre4
	LWJGL: 3.2.1 build 12
	OpenGL: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/John Smith Legacy 1.14.1 v2.zip
	Current Language: English (United Kingdom)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by sp614x** [comment]
Fixed, coming in preview 6
