### ISSUE TITLE
Crash on load with IE, Enchiridion and OptiFine

### ISSUE THREAD

**Issue by bondgb** [sp614x/optifine#244]
This crash only occurs when all three mods are enabled, using stable and preview OptiFine builds. When I disable Enchiridion everything works.

Log: http://pastebin.com/FBTDiPbE
@PenguinSquad

**Comment by sp614x** [comment]
The error:
[11:57:15] [Client thread/ERROR] [FML/]: Caught exception from immersiveengineering
java.lang.StackOverflowError
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]

It looks like IE is patching the FontRenderer to call IEItemFontRender.getCharWidthFloat(), which calls back the original method, which causes an endless loop.

Because IE and OptiFine seem to work, then most probably Enchiridion is also patching FontRenderer and causing the IE patch to generate a wrong code.

Summary:
- OptiFine changes FontRenderer (required)
- Enchiridion probably patches FontRenderer (no idea why)
- IE tries to patch the patched FontRenderer and generates invalid code causing the endless loop

Because of problems like that, the class patching should be avoided and all base class changes should be delegated to Forge. OptiFine takes care to reflect all base class changes which Forge does and to be compatible with it.

**Comment by sp614x** [comment]
Fixed in Enchiridion: https://github.com/PenguinSquad/Enchiridion/issues/85#issuecomment-248170389
