### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by frqnny** [sp614x/optifine#2456]
https://pastebin.com/8cQMDFW6

I crash in 1.12.2 with forge. Crash points to you but I'm not too sure. Help?

**Comment by WeirdDude96** [comment]
using E3

**Comment by sp614x** [comment]
```
java.lang.IllegalArgumentException
    at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
    at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
    at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:382)
    at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
```

**Comment by SoulofSectonia** [comment]
I'm getting that too, but Mine says what I posted below.  I've tried E3 through D1 and it keeps happening. I'm using forge 2772.

java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18) ~[rs.class:?]
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37) ~[rs.class:?]
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:246) ~[oo.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:194) ~[anb.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203) ~[oo.class:?]
	at WorldServerOF.func_72835_b(WorldServerOF.java:37) ~[WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
