### ISSUE TITLE
[1.14.3] "URISyntaxException: Illegal character in path"

### ISSUE THREAD

**Issue by ElectricDuskXX** [sp614x/optifine#2544]
When I launch OptiFine 1.14.3 F1 pre 15 I get an error:
"Exception in thread "main" java.IllegalArgumentException: Illegal character in path at index 50:" then a file path to "class_cache.zip" in my directory. I am using a custom game directory.

**Comment by DaimeneX** [comment]
Mind posting a full crash log? This isn't very informative.

**Comment by ElectricDuskXX** [comment]
The launcher is not saving crash reports to the .minecraft directory anymore, and pressing "view crash report" after it crashes does nothing. However, I can post the error from the output log:
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in path at index 50: file:/C:/Users/Quinn/Documents/Minecraft/Profiles/[1]%20Normal/[1]%20Latest%20Release/.minecraft/class_cache.zip
 at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:87)
 at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
 at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
 at net.minecraft.launchwrapper.LaunchClassLoader.initializeClassCacheSystem(LaunchClassLoader.java:102)
 at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:70)
 at net.minecraft.launchwrapper.Launch.<init>(Launch.java:31)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:23)
 Caused by: java.net.URISyntaxException: Illegal character in path at index 50: file:/C:/Users/Quinn/Documents/Minecraft/Profiles/[1]%20Normal/[1]%20Latest%20Release/.minecraft/class_cache.zip
 at java.net.URI$Parser.fail(URI.java:2848)
 at java.net.URI$Parser.checkChars(URI.java:3021)
 at java.net.URI$Parser.parseHierarchical(URI.java:3105)
 at java.net.URI$Parser.parse(URI.java:3053)
 at java.net.URI.<init>(URI.java:588)
 at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
 ... 6 more

**Comment by ElectricDuskXX** [comment]
Edited title as the problem still occurs in full release

**Comment by sp614x** [comment]
This would need a launchwrapper update
https://stackoverflow.com/questions/4992317/illegal-character-in-path-at-index-16

**Comment by sp614x** [comment]
Ninja updated 1.14.3_HD_U_F1 with a bugfix.
Please redownload it and test again.

**Comment by Ketoyu** [comment]
Fixed it for me! Thank-yoouuuu! <3

**Comment by ElectricDuskXX** [comment]
Works after the reupload thanks
