### ISSUE TITLE
Optifine version 1.14.3 HD U F1 openGL error

### ISSUE THREAD

**Issue by FoxcatgamingZ** [sp614x/optifine#2548]
I keep getting the error report of 1282 and it fills my screen.
![2019-06-27_09 30 55](https://user-images.githubusercontent.com/52290347/60279447-4cba5980-98be-11e9-9247-fdea1748fb5f.png)

**Comment by sp614x** [comment]
Can you post a F3 screenshot?

**Comment by Lord-Vlad** [comment]
I got this in my log:

> OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL14C.nglMultiDrawArrays(Native Method)
	at org.lwjgl.opengl.GL14C.glMultiDrawArrays(GL14C.java:153)
	at org.lwjgl.opengl.GL14.glMultiDrawArrays(GL14.java:352)
	at com.mojang.blaze3d.platform.GlStateManager.glMultiDrawArrays(GlStateManager.java:1221)
	at net.optifine.render.VboRegion.finishDraw(VboRegion.java:325)
	at dnp.drawRegion(VboRenderList.java:110)
	at dnp.a(VboRenderList.java:40)
	at dng.a(WorldRenderer.java:1555)
	at dng.a(WorldRenderer.java:1531)
	at dnc.b(GameRenderer.java:1307)
	at dnc.a(GameRenderer.java:1032)
	at dnc.a(GameRenderer.java:792)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

**Comment by sp614x** [comment]
```
OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.)
java.lang.Exception: Stack trace
at org.lwjgl.opengl.GL14C.nglMultiDrawArrays(Native Method)
at org.lwjgl.opengl.GL14C.glMultiDrawArrays(GL14C.java:153)
at org.lwjgl.opengl.GL14.glMultiDrawArrays(GL14.java:352)
at com.mojang.blaze3d.platform.GlStateManager.glMultiDrawArrays(GlStateManager.java:1221)
at net.optifine.render.VboRegion.finishDraw(VboRegion....
```

**Comment by sp614x** [comment]
![](https://cdn.discordapp.com/attachments/423430686880301060/606084872385200130/2019-07-31_13.23.22.png)
