### ISSUE TITLE
Optifine crash upon launching. 1.14.3 release.

### ISSUE THREAD

**Issue by GW12505** [sp614x/optifine#2550]
Hello, I've been waiting for Optifine 1.14.3 to release for a while to see if I get the same error that I've encountered in the preview versions upon launching the game.

I still get this crash in Optifine release 1.14.3 HD U F1:

[13:34:40] [main/INFO]: Initialized cache system in 121828731 ns
[13:34:40] [main/ERROR]: Unable to launch
java.lang.NullPointerException: null
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:152) [launchwrapper-2.0.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23) [launchwrapper-2.0.jar:?]
[L] Minecraft closed with exit code: 1 (0x1)

**Comment by GW12505** [comment]
Here's the full log
Also yeah I'm using TLauncher

[L] Minecraft Launcher [21;8] has initialized
[L] Running under TLauncher 1.98.13+master for Mc-launcher.com
[L] Current machine: Mac OS X (10.13.6) x64, Java 1.8.0_211, 8192 MB RAM, 4x CPU
[L] Collecting info...
[L] Force update: false
[L] Selected version: 1.14.3-OptiFine_HD_U_F1
[L] Selected account: PlainUser[username=GW12505,displayName=GW12505,type=plain]
[L] Version sync info: VersionSyncInfo{id='1.14.3-OptiFine_HD_U_F1',
local=CompleteVersionCompleteVersion[id=1.14.3-OptiFine_HD_U_F1,jar=<null>,inheritsFrom=<null>,url=<null>,time=Thu Jun 27 13:26:53 EDT 2019,releaseTime=Mon Jun 24 08:52:52 EDT 2019,downloads={CLIENT=net.minecraft.launcher.updater.DownloadInfo@9be7ffc, SERVER=net.minecraft.launcher.updater.DownloadInfo@4ee4da91},assetIndex=AssetIndexInfo[id=1.14,url=https://launchermeta.mojang.com/v1/packages/abff559a3c834dbb6c9664d49293efbf625b3de2/1.14.json,sha1=abff559a3c834dbb6c9664d49293efbf625b3de2,size=226556,totalSize=207748826,known=true],source=LOCAL_VERSION_REPO,list=net.minecraft.launcher.updater.LocalVersionList@109ff6db,libraries=(46 items)],
remote=null, isInstalled=true, hasRemote=false, isUpToDate=true}
[L] Looking up libraries for plain
[L] Command: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
[L] Root directory: /Users/Wagon725/Library/Application Support/minecraft/
[L] Game directory: /Users/Wagon725/Library/Application Support/minecraft/
[L] Options: OptionsFile[file=/Users/Wagon725/Library/Application Support/minecraft/options.txt,fileExist=true,options={version=1631, invertYMouse=false, mouseSensitivity=0.5, fov=0.25, gamma=0.5070422291755676, saturation=0.0, renderDistance=9, guiScale=2, particles=0, bobView=true, maxFps=260, fboEnable=true, difficulty=2, fancyGraphics=false, ao=1, biomeBlendRadius=2, renderClouds=fast, resourcePacks=["vanilla","file/1.14-r3"], incompatibleResourcePacks=[], lastServer=68.51.9.102:50390, lang=en_us, chatVisibility=0, chatColors=true, chatLinks=true, chatLinksPrompt=true, chatOpacity=1.0, snooperEnabled=false, fullscreen=true, enableVsync=true, useVbo=true, hideServerAddress=false, advancedItemTooltips=false, pauseOnLostFocus=false, touchscreen=false, overrideWidth=0, overrideHeight=0, heldItemTooltips=true, chatHeightFocused=1.0, chatHeightUnfocused=0.44366195797920227, chatScale=1.0, chatWidth=1.0, mipmapLevels=3, forceUnicodeFont=false, reducedDebugInfo=false, useNativeTransport=true, entityShadows=false, mainHand=right, attackIndicator=1, showSubtitles=false, realmsNotifications=true, enableWeakAttacks=false, autoJump=false, narrator=0, tutorialStep=none, autoSuggestions=true, mouseWheelSensitivity=1.0, glDebugVerbosity=1, key_key.attack=key.mouse.left, key_key.use=key.mouse.right, key_key.forward=key.keyboard.w, key_key.left=key.keyboard.a, key_key.back=key.keyboard.s, key_key.right=key.keyboard.d, key_key.jump=key.keyboard.space, key_key.sneak=key.keyboard.left.shift, key_key.sprint=key.keyboard.left.control, key_key.drop=key.keyboard.q, key_key.inventory=key.keyboard.e, key_key.chat=key.keyboard.t, key_key.playerlist=key.keyboard.tab, key_key.pickItem=key.keyboard.left.bracket, key_key.command=key.keyboard.slash, key_key.screenshot=key.keyboard.f2, key_key.togglePerspective=key.keyboard.backslash, key_key.smoothCamera=key.keyboard.unknown, key_key.fullscreen=key.keyboard.right.bracket, key_key.spectatorOutlines=key.keyboard.unknown, key_key.swapHands=key.keyboard.f, key_key.saveToolbarActivator=key.keyboard.unknown, key_key.loadToolbarActivator=key.keyboard.x, key_key.advancements=key.keyboard.l, key_key.hotbar.1=key.keyboard.1, key_key.hotbar.2=key.keyboard.2, key_key.hotbar.3=key.keyboard.3, key_key.hotbar.4=key.keyboard.4, key_key.hotbar.5=key.keyboard.5, key_key.hotbar.6=key.keyboard.6, key_key.hotbar.7=key.keyboard.7, key_key.hotbar.8=key.keyboard.8, key_key.hotbar.9=key.keyboard.9, key_of.key.zoom=key.keyboard.c, soundCategory_master=0.15768574, soundCategory_music=0.0, soundCategory_record=1.0, soundCategory_weather=1.0, soundCategory_block=1.0, soundCategory_hostile=1.0, soundCategory_neutral=1.0, soundCategory_player=1.0, soundCategory_ambient=1.0, soundCategory_voice=1.0, modelPart_cape=false, modelPart_jacket=true, modelPart_left_sleeve=true, modelPart_right_sleeve=true, modelPart_left_pants_leg=true, modelPart_right_pants_leg=true, modelPart_hat=false}]
[L] Checking conditions...
[L] Comparing assets...
[L] Instant state on: AssetIndex.AssetObject[compressed=false,hash=e7133a7d4822e40f0abd716faa3a8f340362b8d7,size=13332,reconstruct=false]
[L] Compared assets in 90 ms
[L] Unpacking natives...
[L] Constructing process...
[L] Constructing classpath...
[L] Half command (characters are not escaped):
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -XX:+UseG1GC -XX:ConcGCThreads=4 -Xmx5120M -Dfile.encoding=UTF-8 -XstartOnFirstThread -Xss1M -Djava.library.path=/Users/Wagon725/Library/Application Support/minecraft/versions/1.14.3-OptiFine_HD_U_F1/natives -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=1.6.84-j -cp /Users/Wagon725/Library/Application Support/minecraft/libraries/optifine/OptiFine/1.14.3_HD_U_F1/OptiFine-1.14.3_HD_U_F1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/optifine/launchwrapper/2.0/launchwrapper-2.0.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/optifine/OptiFine/1.14.3_HD_U_F1/OptiFine-1.14.3_HD_U_F1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/optifine/launchwrapper/2.0/launchwrapper-2.0.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/mojang/realms/1.14.17/realms-1.14.17.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/Users/Wagon725/Library/Application Support/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar:/Users/Wagon725/Library/Application Support/minecraft/versions/1.14.3-OptiFine_HD_U_F1/1.14.3-OptiFine_HD_U_F1.jar net.minecraft.launchwrapper.Launch --username GW12505 --version 1.14.3-OptiFine_HD_U_F1 --gameDir /Users/Wagon725/Library/Application Support/minecraft --assetsDir /Users/Wagon725/Library/Application Support/minecraft/assets --assetIndex 1.14 --uuid 00000000000000000000000000000000 --accessToken [vk.cc/7iPiB9] --userType legacy --versionType release --width 925 --height 530
[L] Launching Minecraft...
[L] Starting Minecraft 1.14.3-OptiFine_HD_U_F1
[L] Launching in: /Users/Wagon725/Library/Application Support/minecraft
[L] Processing post-launch actions. Assist launch: false
===============================================================================================
[13:49:35] [main/INFO]: Initialized cache system in 110949862 ns
[13:49:35] [main/ERROR]: Unable to launch
java.lang.NullPointerException: null
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:152) [launchwrapper-2.0.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23) [launchwrapper-2.0.jar:?]
[L] Minecraft closed with exit code: 1 (0x1)

**Comment by sp614x** [comment]
Most probably TLauncher is using the standard `launchwrapper-2.0.jar`.
OptiFine needs an updated launchwrapper that can patch the `com.mojang.blaze3d` classes.

**Comment by GW12505** [comment]
Any help on getting the proper launch wrapper to work?

In my minecraft libraries folder, optifine has it's own folder. Inside that folder is a launchwrapper folder with the launchwrapper-2.0.jar inside.

**Comment by sp614x** [comment]
The file `versions/1.14.3-OptiFine_HD_U_F1/1.14.3-OptiFine_HD_U_F1.jar` does not exist.
The installer doesn't create it anymore as the OF profile extends the `1.14.3` profile and the launcher takes the JAR from there.

**Comment by notsrijit** [comment]
>I'm facing the same problem, and the 1.14.3-OptiFine_HD_U_F1.jar file is there in the optifine folder inside versions.

**Comment by persaiin** [comment]
How do I get the correct launchwrapper in order to get my optifine to start up? In the optifine folder it has a launchwrapper folder which when opened has a 2.0 folder in it.

**Comment by Quavelen** [comment]
> Also yeah I'm using TLauncher on MacOS

> How do I get the correct launchwrapper in order to get my optifine to start up? In the optifine folder it has a launchwrapper folder which when opened has a 2.0 folder in it.


Um... I've debated replying because I know jack squat about macs, or code in general. However, I'd like to suggest using the current vanilla launcher, as I know quite a few mac users who run the latest OptiFine just fine. One in particular, I introduced to the BSL shader and he's been really enjoying it. So I know it works.

(I've also never heard of "TLauncher" before, but I realise there are many third-party launcher out there.)

**Comment by DaemonUmbra** [comment]
TLauncher is a cracked launcher 😢

**Comment by Quavelen** [comment]
> TLauncher is a cracked launcher 😢

.... ohh. That changes a lot. Yeah, I'd fully expect a cracked launcher to be broken, and or use old code. I also don't think @sp614x supports cracked launchers, which is a good thing.

**Comment by persaiin** [comment]
Im using the vanilla launcher and im trying to start up OptiFine 1.14.3 but the mojang screen loads and once it gets to the game it immediately says "an unexpected issue occured and the game has crashed. were sorry for the inconvenience." and when i try to press view crash report nothing opens.

**Comment by DaemonUmbra** [comment]
> Im using the vanilla launcher and im trying to start up OptiFine 1.14.3 but the mojang screen loads and once it gets to the game it immediately says "an unexpected issue occured and the game has crashed. were sorry for the inconvenience." and when i try to press view crash report nothing opens.

If you go to [.minecraft](https://minecraft.gamepedia.com/.minecraft#Locating_.minecraft)/crash-reports you should be able to find it manually

**Comment by persaiin** [comment]
i cannot find a crash report from todays date in that folder.
