### ISSUE TITLE
OptiFine 1.14.3 Crash

### ISSUE THREAD

**Issue by VENTO-off** [sp614x/optifine#2564]
I try to launch OptiFine 1.14.3 HD U F1 (using launchwrapper 1.12) and I got crash:

```
FATAL ERROR in native method: Thread[Server-Worker-6,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglTexImage2D(Native Method)
	at org.lwjgl.opengl.GL11C.glTexImage2D(GL11C.java:1753)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:7055)
	at com.mojang.blaze3d.platform.GlStateManager.texImage2D(SourceFile:493)
	at net.optifine.util.TextureUtils.detectGLMaximumTextureSize(TextureUtils.java:695)
	at net.optifine.util.TextureUtils.getGLMaximumTextureSize(TextureUtils.java:682)
	at dum.a(AtlasTexture.java:338)
	at djb.lambda$reload$3(ParticleManager.java:186)
	at djb$$Lambda$1674/1239761431.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Process finished with exit code 1
```

**Comment by sp614x** [comment]
Using a custom launcher?
See #2411.

**Comment by VENTO-off** [comment]
Yes, I use my own launcher.
Thank you for your answer. I saw this post but I don't understand how to solve this problem? Where can I get the working launchwrapper?

**Comment by VENTO-off** [comment]
I tried "launchwrapper-2.0" - minecraft still can't start. It throws the same error.

**Comment by VENTO-off** [comment]
I tried this files: https://github.com/MMCInstances/OptifineInstances/releases and it worked.
But the version on your site don't work.

**Comment by matejmraz1** [comment]
I have the same problem but i dont know where is log and i'm lazy to do it :)... minecraft starts with black screen (normal), the logo screen starts too and when it reaches cca 100% then it crashes and my launcher get me metaspace error what i get at all time when minecraft is loading resources and its not responding and i click on close program and dont wait so i dont know why...           Launcher: TLauncher 1.110.4 (it can download and install optifine and forge)        1.14.3 RLS-works

**Comment by VENTO-off** [comment]
> I have the same problem but i dont know where is log and i'm lazy to do it :)... minecraft starts with black screen (normal), the logo screen starts too and when it reaches cca 100% then it crashes and my launcher get me metaspace error what i get at all time when minecraft is loading resources and its not responding and i click on close program and dont wait so i dont know why...
> Launcher: TLauncher 1.110.4 (it can download and install optifine and forge at notime)
> 1.14.3 release-works

I don't use TLauncher. In my opinion R-Launcher is more better and more comfortable in use.

**Comment by matejmraz1** [comment]
i dont know what launcher are on the internet but i like mine and i'm not adversting it... anyway fast respond :)

**Comment by VENTO-off** [comment]
Sorry for advertising... I wanted to say that OptiFine 1.14.3 in R-Launcher starts wihout any problems and errors. And this launcher can install OptiFine and Forge versions too.

**Comment by matejmraz1** [comment]
I have realized that the loading line stops near 3/4
i dont know what at that time is loading... and i just want to fix it crashing and i want my launcher and dont say about launchers and i wont either...

**Comment by GW12505** [comment]
> Sorry for advertising... I wanted to say that OptiFine 1.14.3 in R-Launcher starts wihout any problems and errors. And this launcher can install OptiFine and Forge versions too.

I can't find a version of R-Launcher in English. Please help.

**Comment by VENTO-off** [comment]
> > Sorry for advertising... I wanted to say that OptiFine 1.14.3 in R-Launcher starts wihout any problems and errors. And this launcher can install OptiFine and Forge versions too.
> 
> I can't find a version of R-Launcher in English. Please help.

I'm so sorry. It is still in russian. I hope it will be multilanguage soon.
