### ISSUE TITLE
Crash on Latests Optifine Versions (Majority of 1.14 ones)

### ISSUE THREAD

**Issue by CaioLindao** [sp614x/optifine#2671]
Hello, hope you can help me.
Since 1.12, when i try to open my game on the vanilla version it crashes. My solution to that is to use optifine. But, since 1.13, when i try to open some versions of the game it crashes right when it's starting, even with optifine. I found it is a really strange problem, cause it only happens with some versions of Optifine. I'm currently playing on the only 1.14 one that works (1.14.2 pre 4) and i'd like to play on the most recent ones, but not even one of them works :(.
My pc is indeed very old and trashy, but optifine makes it possible to play and i love it. The crash report is down below. I tried to undestant what to do with base on some other posts, but i couldn't undestand a thing.

-------Crash Report --------

[17:59:47] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[17:59:47] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[17:59:47] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: C:\Users\CAIO\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.14.4_HD_U_F2_pre1\OptiFine-1.14.4_HD_U_F2_pre1.jar
OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[17:59:49] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:59:53] [main/INFO]: [OptiFine] *** Reflector Forge ***
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.Attributes
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.BrandingControl
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.capabilities.ICapabilityProvider
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.capabilities.CapabilityProvider
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.ClientModLoader
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.ChunkEvent$Load
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.ClientHooks
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Post
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$FogColors
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$RenderFogEvent
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.entity.EntityJoinWorldEvent
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.IEventBus
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeBlock
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: dnv.getTexture
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: dpt.getModelData
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.addDestroyEffects
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.addHitEffects
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.canRenderInLayer
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getLightValue
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getStateAtViewpoint
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.isAir
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeFluidState
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: ais.getTags
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Field not present: aix.NAMETAG_DISTANCE
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.ForgeEventFactory
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: clj.getTags
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfig
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfig$Client
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfigSpec$ConfigValue
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeItem
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeItemStack
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.ForgeI18n
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.IModel
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.setKeyConflictContext
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.setKeyModifierAndCode
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.getKeyModifier
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeMod
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Method not present: dof.fromJson
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEffect
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEffectInstance
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.registries.ForgeRegistryEntry
[17:59:53] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeTileEntity
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Method not present: cvd$b.preDraw
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Method not present: cvd$b.postDraw
[17:59:54] [main/WARN]: [OptiFine] Field not found: tileEntitiesToBeRemoved
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeDimension
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.gui.GuiModList
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.IRenderHandler
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ItemModelMesherForge
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.LightUtil
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.MinecraftForge
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.MinecraftForgeClient
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.gui.NotificationModUpdateScreen
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.entity.PlaySoundAtEntityEvent
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderBlockOverlayEvent$OverlayType
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.registry.RenderingRegistry
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderItemInFrameEvent
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Pre
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Post
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Pre
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Post
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.ScreenshotEvent
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.server.ServerLifecycleHooks
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.SplashProgress
[17:59:54] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.WorldEvent$Load
[17:59:54] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
[17:59:55] [main/INFO]: Setting user: JubileuGameP
[18:00:28] [main/INFO]: LWJGL Version: 3.2.2 build 10
[18:00:31] [main/INFO]: [OptiFine] 
[18:00:31] [main/INFO]: [OptiFine] OptiFine_1.14.4_HD_U_F2_pre1
[18:00:31] [main/INFO]: [OptiFine] Build: 20190720-180048
[18:00:31] [main/INFO]: [OptiFine] OS: Windows 7 (amd64) version 6.1
[18:00:31] [main/INFO]: [OptiFine] Java: 1.8.0_211, Oracle Corporation
[18:00:31] [main/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[18:00:31] [main/INFO]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[18:00:31] [main/INFO]: [OptiFine] OpenGL: Intel Pineview Platform, version 1.4.0 - Build 8.14.10.2230, Intel
[18:00:31] [main/INFO]: [OptiFine] OpenGL Version: 1.4.0
[18:00:31] [main/INFO]: [OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
[18:00:31] [main/INFO]: [OptiFine] OpenGL Occlussion culling: Not available (GL_ARB_occlusion_query)
[18:00:31] [main/INFO]: [OptiFine] Maximum texture size: 2048x2048
[18:00:31] [VersionCheck/INFO]: [OptiFine] Checking for new version
[18:00:31] [main/INFO]: [Shaders] OpenGL Version: 1.4.0 - Build 8.14.10.2230
[18:00:31] [main/INFO]: [Shaders] Vendor:  Intel
[18:00:31] [main/INFO]: [Shaders] Renderer: Intel Pineview Platform
[18:00:31] [main/INFO]: [Shaders] Capabilities:  -  -  -  -  - 
[18:00:31] [main/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 7
[18:00:31] [main/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 7
[18:00:31] [main/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[18:00:31] [main/INFO]: [Shaders] Load shaders configuration.
[18:00:31] [main/INFO]: [Shaders] Shaders can not be loaded, Fast Render is enabled.
[18:00:31] [main/INFO]: [Shaders] No shaderpack loaded.
[18:00:31] [main/INFO]: [OptiFine] VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 24/07/19 18:00
Description: Initializing game

java.lang.IllegalStateException: The driver does not appear to support framebuffer objects
	at com.mojang.blaze3d.platform.GLX.init(GLX.java:514)
	at cyc.au(SourceFile:482)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX.init(GLX.java:514)
	at cyc.au(SourceFile:482)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 166510184 bytes (158 MB) / 337829888 bytes (322 MB) up to 2134114304 bytes (2035 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.14.4-OptiFine_HD_U_F2_pre1
	LWJGL: 3.2.2 build 10
	OpenGL: Intel Pineview Platform GL version 1.4.0 - Build 8.14.10.2230, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks_r886906.zip
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\CAIO\AppData\Roaming\.minecraft\crash-reports\crash-2019-07-24_18.00.32-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

Sorry if i didn't provide you with enought information, i apoligize for that. Feel free to ask me for anything you need.

**Comment by sp614x** [comment]
Since 1.13 vanilla requires the graphics driver to support framebuffer objects.
A fallback to Fast Render could be used to make the game run on older hardware.

**Comment by CaioLindao** [comment]
So what could/should i do?

**Comment by ItsmeFawaz** [comment]
I have the same problem(considering you wrote "1.13" instead of "1.14" in the post by mistake) and hopefully in the next update he does something to fix it. enabling Fast Render in optionsof doesn't work for me.

**Comment by CaioLindao** [comment]
> A fallback to Fast Render could be used to make the game run on older hardware.

Uh, hello, i'm back here to ask you if you could maybe work on this little workaround for us who cannot play yhe game right now. I think not only me, but a lot of people would like it and be really pleased. Hope you have time to it, and again, i'm sorry to waste your time.
