### ISSUE TITLE
Can't install Optifine_1.14.4_HD_U_F2.jar         	

### ISSUE THREAD

**Issue by tafboi** [sp614x/optifine#2719]
After clicking "install" in the Optifine Installer it shows this error:

java.io.FileNotFoundException: C:\Users\taf\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.14.4_HD_U_F2\OptiFine-1.14.4_HD_U_F2.jar (Access is denied)
  at java.io.FileOutputStream.open0(Native Method)
  at java.io.FileOutputStream.open(Unknown Source)
  at java.io.FileOutputStream.<init>(Unknown Source)
  at java.io.FileOutputStream.<init>(Unknown Source)
  at optifine.Patcher.process(Patcher.java:69)
  at optifine.Installer.installOptiFineLibrary(Installer.java:372)
  at optifine.Installer.doInstall(Installer.java:96)
  at optifine.InstallerFrame.onInstall(InstallerFrame.java:425)
  at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:490)
  at optifine.InstallerFrame.access$7(InstallerFrame.java:484)
  at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
  at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
  at javax.swing.plaf.basic.BasicButtonListener$Actions.actionPerformed(Unknown Source)
  at javax.swing.SwingUtilities.notifyAction(Unknown Source)
  at javax.swing.JComponent.processKeyBinding(Unknown Source)
  at javax.swing.JComponent.processKeyBindings(Unknown Source)
  at javax.swing.JComponent.processKeyEvent(Unknown Source)
  at java.awt.Component.processEvent(Unknown Source)
  at java.awt.Container.processEvent(Unknown Source)
  at java.awt.Component.dispatchEventImpl(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
  at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
  at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
  at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
  at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
  at java.awt.Component.dispatchEventImpl(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Window.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
  at java.awt.EventQueue.access$500(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue.dispatchEvent(Unknown Source)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.run(Unknown Source)

in the versions folder there is an Optifine_1.14.4_HD_U_F2 folder with both jar and json files, but there is Optifine_1.14.4_HD_U_F2 version available in the launcher.

**Comment by sp614x** [comment]
The installer can't update the OptiFine library: C:\Users\taf\AppData\Roaming.minecraft\libraries\optifine\OptiFine\1.14.4_HD_U_F2\OptiFine-1.14.4_HD_U_F2.jar (Access is denied)

Make sure that Minecraft is not running and the Minecraft launcher is closed.
If still not working, you can try restarting the PC.

**Comment by tafboi** [comment]
Still the same error after closing MC/restarting PC
