### ISSUE TITLE
Installation file can not be launched on OSX

### ISSUE THREAD

**Issue by Pyke501** [sp614x/optifine#2722]
![Screenshot 2019-08-04 at 21 16 15](https://user-images.githubusercontent.com/53709895/62428069-6e98ce80-b6fd-11e9-938c-0449aa8a567a.png)

As the title says, my Mac is unable to even launch the the Optifine JAR file for Minecraft 1.14.4. Is there any way to fix this issue?

**Comment by Regnander** [comment]
_"Check the Console for possible error messages"_

Are there any error messages in the console?

**Comment by Pyke501** [comment]
> _"Check the Console for possible error messages"_
> 
> Are there any error messages in the console?

I am unable to find any error messages caused by the failed installation.

**Comment by sp614x** [comment]
You can also open it from command prompt (shell)
`java -jar OptiFine_1.14.4_HD_U_F3.jar`

**Comment by hardtmedia** [comment]
Running the jar from command line results in NPE:
`
java.lang.NullPointerException
	at java.desktop/java.awt.Window.init(Window.java:499)
	at java.desktop/java.awt.Window.<init>(Window.java:539)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at optifine.InstallerFrame.<init>(InstallerFrame.java:55)
	at optifine.InstallerFrame.main(InstallerFrame.java:115)
Exception in thread "main" java.lang.NullPointerException
	at java.desktop/sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:154)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:275)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1243)
	at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1646)
	at java.desktop/javax.swing.text.PlainView.calculateLongestLine(PlainView.java:783)
	at java.desktop/javax.swing.text.PlainView.updateMetrics(PlainView.java:332)
	at java.desktop/javax.swing.text.PlainView.updateDamage(PlainView.java:670)
	at java.desktop/javax.swing.text.PlainView.insertUpdate(PlainView.java:591)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1709)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1968)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675)
	at java.desktop/javax.swing.text.JTextComponent.setText(JTextComponent.java:1729)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:207)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:145)
	at optifine.InstallerFrame.main(InstallerFrame.java:131)
`

**Comment by zeekoe** [comment]
I get the same issue in a different piece of software. My guess is that for me it's something with the DisplayLink attached display. If I unplug the display, the software runs well.
HTH.
