### ISSUE TITLE
Paper 1.14.4 will not load Optifine

### ISSUE THREAD

**Issue by PhantumOne** [sp614x/optifine#2758]
Optifine will not load in Paper 1.14.4. I get the following error message:

[14:48:39] [Server thread/ERROR]: Could not load 'plugins\OptiFine_1.14.4_HD_U_F3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:169) ~[patched_1.14.4.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:142) ~[patched_1.14.4.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-137]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:218) ~[patched_1.14.4.jar:git-Paper-137]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:871) ~[patched_1.14.4.jar:git-Paper-137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 1, column 15:
    name: OptiFine:
                  ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.14.4.jar:git-Paper-137]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452) ~[patched_1.14.4.jar:git-Paper-137]
	at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:240) ~[patched_1.14.4.jar:git-Paper-137]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:164) ~[patched_1.14.4.jar:git-Paper-137]
	... 5 more

I tried all 1.14.4, 1.14.3 and 1.14.2 version on the download site and they all return the same message. I looked into the JAR file using 7Zip and I could not find the plugin.yml file within the file structure of the JAR.

Thanks

**Comment by realjackasterisk** [comment]
Um... you realize OptiFine is not a server plugin, right?

**Comment by Studio528-real** [comment]
^ it is a client-side mod/profile for the Minecraft launcher, it does nothing to a server.

**Comment by Vencorr** [comment]
Not gonna lie, this gave me a chuckle.
