### ISSUE TITLE
Freezing/crashing in jungle

### ISSUE THREAD

**Issue by realsnowy** [sp614x/optifine#2779]
When I enter a jungle my fps drops from 700 to 500 to 300 fairly quickly. Also sometimes it likes freezing my whole PC, I checked it out once with task manager open and it seems like it jumps from 4GB to 6GB RAM usage, even though I set `-Xmx 4G `

Here's the log of the crash:

> [17:13:06] [main/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid offset and/or size.)
> java.lang.Exception: Stack trace
> 	at org.lwjgl.opengl.GL15C.nglBufferSubData(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
> 	at org.lwjgl.opengl.GL15C.glBufferSubData(GL15C.java:449) ~[lwjgl-opengl-3.2.2.jar:build 10]
> 	at org.lwjgl.opengl.GL15.glBufferSubData(GL15.java:475) ~[lwjgl-opengl-3.2.2.jar:build 10]
> 	at com.mojang.blaze3d.platform.GLX.glBufferSubData(GLX.java:1248) ~[GLX.class:?]
> 	at net.optifine.render.VboRegion.bufferData(VboRegion.java:107) ~[VboRegion.class:?]
> 	at cva.a(VertexBuffer.java:38) ~[cva.class:?]
> 	at cvb.a(VertexBufferUploader.java:24) ~[cvb.class:?]
> 	at dpu.a(ChunkRenderDispatcher.java:347) ~[dpu.class:?]
> 	at dpu.a(ChunkRenderDispatcher.java:312) ~[dpu.class:?]
> 	at dpu.lambda$uploadChunk$2(ChunkRenderDispatcher.java:326) ~[dpu.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
> 	at dpu.a(ChunkRenderDispatcher.java:166) [dpu.class:?]
> 	at dng.a(WorldRenderer.java:2272) [dng.class:?]
> 	at dnc.b(GameRenderer.java:1153) [dnc.class:?]
> 	at dnc.a(GameRenderer.java:1032) [dnc.class:?]
> 	at dnc.a(GameRenderer.java:792) [dnc.class:?]
> 	at cyc.e(SourceFile:954) [cyc.class:?]
> 	at cyc.b(SourceFile:410) [cyc.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:155) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]

Also this message gets spammed in the log quite often:

> [17:07:50] [main/FATAL]: Error executing task on Client
> java.lang.NullPointerException: null
> 	at cti.d(SourceFile:199) ~[cti.class:?]
> 	at dkc.a(SourceFile:2004) ~[dkc.class:?]
> 	at nb.a(SourceFile:122) ~[nb.class:?]
> 	at nb.a(SourceFile:16) ~[nb.class:?]
> 	at ke.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[ke.class:?]
> 	at agq.h(ThreadTaskExecutor.java:170) [agq.class:?]
> 	at agu.h(SourceFile:23) [agu.class:?]
> 	at agq.q(ThreadTaskExecutor.java:135) [agq.class:?]
> 	at agq.bh(ThreadTaskExecutor.java:115) [agq.class:?]
> 	at cyc.e(SourceFile:915) [cyc.class:?]
> 	at cyc.b(SourceFile:410) [cyc.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:155) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]

I have also attached my full log. Hope I can find a solution ._.
P.S.: I'm using version `preview_OptiFine_1.14.4_HD_U_F4_pre2`
[latest.log](https://github.com/sp614x/optifine/files/3506163/latest.log)

**Comment by sp614x** [comment]
Does it happen when Render Regions is disabled?

**Comment by realsnowy** [comment]
I disabled Render Regions and it doesn't happen anymore! Thank you so much!

**Comment by sp614x** [comment]
The crash still has to be fixed.
Render Regions should work everywhere.

**Comment by EternalMC** [comment]
It also seems to happen on 1.16.
 https://pastebin.com/8bcKMLjt
https://pastebin.com/Xxd9SpyD

**Comment by sp614x** [comment]
Does it still happen in pre11 for 1.16.1?

**Comment by EternalMC** [comment]
seems so but it just seems to hang now 
https://pastebin.com/XA776HEu

**Comment by EternalMC** [comment]
Hmm I can get a guaranteed hang if I f3+r right now the first chunk load with lightning spaming(tho I don't know if lightning is the key tho)

**Comment by EternalMC** [comment]
nevermind about the previous stuff
https://pastebin.com/1kmS6Nxw
It still happens.

**Comment by sp614x** [comment]
@EternalMC last one is a different crash not related to Render Regions.
It also doesn't seem to be related to OptiFine.

**Comment by sp614x** [comment]
Previous one: https://github.com/sp614x/optifine/issues/2779#issuecomment-665840593
is a crash in the nvidia drivers when swapping pages.
Doesn't seem related to OptiFine.

**Comment by sp614x** [comment]
The two crashes before: https://github.com/sp614x/optifine/issues/2779#issuecomment-665222184
are the same, one crash in the drivers and one not related to OF.

**Comment by EternalMC** [comment]
lmao
I do get something he gets tho
`
13:02:49.012
OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid offset and/or size.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39)
	at org.lwjgl.opengl.GL15C.nglBufferSubData(Native Method)
	at org.lwjgl.opengl.GL15C.glBufferSubData(GL15C.java:449)
	at org.lwjgl.opengl.GL15.glBufferSubData(GL15.java:475)
	at com.mojang.blaze3d.platform.GLX.glBufferSubData(GLX.java:1248)
	at net.optifine.render.VboRegion.bufferData(VboRegion.java:107)
	at cva.a(VertexBuffer.java:37)
	at cvb.a(VertexBufferUploader.java:23)
	at dpu.a(ChunkRenderDispatcher.java:353)
	at dpu.a(ChunkRenderDispatcher.java:318)
	at dpu.lambda$uploadChunk$2(ChunkRenderDispatcher.java:332)
	at dpu$$Lambda$2961/741601550.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at dpu.a(ChunkRenderDispatcher.java:172)
	at dng.a(WorldRenderer.java:2266)
	at dnc.b(GameRenderer.java:1151)
	at dnc.a(GameRenderer.java:1030)
	at dnc.a(GameRenderer.java:790)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
13:02:49.012
[CHAT] §eOpenGL Error§f: 1281 (Invalid value)
13:02:49.012
[Shaders] OpenGL error: 1281 (Invalid value), program: gbuffers_textured, at: pre-useProgram
`
IDK about the last error tho
