### ISSUE TITLE
Optifine 1.14.4 Crashing on Startup

### ISSUE THREAD

**Issue by starplatzawarudo** [sp614x/optifine#2819]
Like the title says, my Minecraft will always crash when loading up Optifine. When checking the logs, I couldn't find anything that could help me fix the issue.

`[main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[16:02:26] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.VanillaTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:102) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:122) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
`

**NOTE: I am using JRE 8, if its related to this issue.**

**Comment by sp614x** [comment]
Are you using the official launcher or a custom one?

**Comment by KaiAF** [comment]
No reply from the original poster
