### ISSUE TITLE
[1.14.4][CRASH] Incompatibility of HD U F4 pre4 with Xaero's Minimap 1.17.9 on Forge 28.0.100

### ISSUE THREAD

**Issue by Neonit** [sp614x/optifine#2873]
With [Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap) installed, the game crashes after loading the world. An empty hotbar and a gray world background is shown shortly for a few frames, then the game switches to the *Saving map* screen and crashes to the launcher with a crash report like shown below.

I have tested all the other mods listed at the end of the report. If I remove Xaero's Minimap, the crash does not occur.

I don't know, whether this is an issue the author of Xaero's minimap should fix or you. Please be lenient to me, if this is not your responsibility.

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 08.09.19 23:05
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at xaero.common.minimap.MinimapRadar.updateRadar(MinimapRadar.java:63) ~[?:1.0] {}
	at xaero.common.minimap.MinimapProcessor.onClientTick(MinimapProcessor.java:134) ~[?:1.0] {}
	at xaero.common.events.FMLEventHandler.handleClientTickEvent(FMLEventHandler.java:36) ~[?:1.0] {}
	at net.minecraftforge.eventbus.ASMEventHandler_49_FMLEventHandler_handleClientTickEvent_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:104) ~[?:?] {}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1270) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:865) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.100.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$348/1027569178.call(Unknown Source) [forge-1.14.4-28.0.100.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at xaero.common.minimap.MinimapRadar.updateRadar(MinimapRadar.java:63)
	at xaero.common.minimap.MinimapProcessor.onClientTick(MinimapProcessor.java:134)
	at xaero.common.events.FMLEventHandler.handleClientTickEvent(FMLEventHandler.java:36)
	at net.minecraftforge.eventbus.ASMEventHandler_49_FMLEventHandler_handleClientTickEvent_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:104)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Firzen'/248, l='MpServer', x=55.94, y=71.00, z=220.71]]
	Chunk stats: Client Chunk Cache: 1225, 529
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (47,63,225), Chunk: (at 15,3,1 in 2,14; contains blocks 32,0,224 to 47,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1446 game time, 1446 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1746)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$348/1027569178.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 906303664 bytes (864 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.100.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.100
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		creeperconfetti-2.1-fix.jar Creeper Confetti {creeperconfetti@2.1 DONE}
		Hwyla-forge-1.10.5-B66_1.14.4.jar Waila {waila@version DONE}
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 DONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
		Xaeros_Minimap_1.17.9_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.17.9 DONE}
		XaerosWorldMap_1.4.7.1_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.7 DONE}
		forge-1.14.4-28.0.100-universal.jar Forge {forge@28.0.100 DONE}
		forge-1.14.4-28.0.100-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.0.100
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
```

**Comment by Neonit** [comment]
This is apparently a bug unrelated to OptiFine in any way. How embarrassing.
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/77
