### ISSUE TITLE
[1.9.4] NullPointerException when trying to retrieve a TextureAtlasSprite

### ISSUE THREAD

**Issue by MrCrayfish** [sp614x/optifine#293]
I'm currently working on a mod that uses coded baked models. I have dynamic textures being applied to the models. However, retrieving the texture (TextureAtlasSprite) while Optifine is installed causes the game to crash.

The method I am using to retrieve the texture is net.minecraft.client.renderer.texture.TextureMap.getTextureExtry(). This is a method added by Forge. Documentation states that it will simply return a null object if no texture was found. Which works without Optifine installed, but when it is, it crashes.

Relevant Crash Log
```
java.lang.NullPointerException: Tesselating block model
	at net.minecraft.util.ResourceLocation.func_177516_a(SourceFile:30)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:21)
	at net.minecraft.client.renderer.texture.TextureMap.getTextureExtry(TextureMap.java:645)
	at com.mrcrayfish.skateboarding.client.model.block.baked.BakedModelSlope.getTexture(BakedModelSlope.java:170)
	at com.mrcrayfish.skateboarding.client.model.block.baked.BakedModelSlope.func_188616_a(BakedModelSlope.java:99)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:135)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:88)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:89)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:65)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:273)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:118)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:46)
	at java.lang.Thread.run(Thread.java:745)
```

Example Code
```
TextureAtlasSprite main = getTexture(texture);
if(main != null)
{
    //Set current texture
}

...

public TextureAtlasSprite getTexture(String texture)
{
    //Example value texture parameter can be assigned to "minecraft:blocks/stone_andesite_smooth"
    return Minecraft.getMinecraft().getTextureMapBlocks().getTextureExtry(texture); //Crash
}
```

My first obvious look into the issue would be splitObjectName() in ResourceLocation, which is called from one of the constructors. I'm not sure if something is different in Optifine. However that should be a good start.

It should be noted too that this might be affecting more than just 1.9.4

**Comment by sp614x** [comment]
You are calling TextureMap.getTextureExtry() with NULL texture.
Added a fix, coming in next preview.

**Comment by MrCrayfish** [comment]
Ahhh, such an easy mistake. I'm assuming you've changed something with Optifine because get() from Map with a null key should just return null, unless Map contains a null key. Regardless, a crash shouldn't happen but also bad programming on my part for not checking.
