### ISSUE TITLE
Connected textures getNeighbourIcon() doesn't take into consideration of ExtendedBlockStates

### ISSUE THREAD

**Issue by MrCrayfish** [sp614x/optifine#294]
I find myself writing extra code just to support Optifine. It seems getNeighbourIcon() from ConnectedTextures isn't taking into consideration of ExtendedBlockStates. Instead of calling getExtendedState() from Block, it is calling getActualState(). Any custom IUnlistedProperty are not included in the IBlockState parameter of getQuads() method from IBakedModel, and thus results in a crash when trying to access.

Forge seems to have deprecated the method and prefers modders to use getExtendedState. This was tested in 1.9.4, but probably an issue in 1.10 too.

```
java.lang.NullPointerException: Tesselating block model
    at com.mrcrayfish.skateboarding.client.model.block.baked.BakedModelSlope.func_188616_a(BakedModelSlope.java:93)
    at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:944)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:894)
    at ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1214)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:422)
    at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:246)
    at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:194)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:115)
    at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:263)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:130)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:88)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:89)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:65)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:273)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:118)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:46)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by sp614x** [comment]
The Block.getActualState() is deprecated, but it still have to work properly (at least not crash) as it is used at many places: http://i.imgur.com/xRtput8.png

**Comment by MrCrayfish** [comment]
You could call getExtendedState() after you call getActualState().
```
//pseudo code
state = getActualState(state);
state = getExtendedState(state);
```

**Comment by sp614x** [comment]
If Block.getActualState() is crashing, then the getExtendedState() is pointless. First the getActualState() has to be fixed not to crash. 
The connected textures are usually used for vanilla blocks. It is quite unlikely that someone will be using them for modded blocks that have different models depending on the extended block state.

**Comment by MrCrayfish** [comment]
Block.getActualState() is not a crash, but the cause of the crash. The problem is that Forge wants modders to use getExtendedState() to add IUnlistedProperties (they are passed to the getQuads() method of my custom IBakedModel). Calling getActualState() doesn't append them to the blockstate, that's why it results in a null pointer. I'm not trying to make connected textures, its blocks that are (eg glass), are checking adjacent blocks. It's calling my custom IBakedModel getQuads() without the IUnlistedProperties, causing a crash.

Overriding getActualState() and returning getExtendedState() is not a solution either, that seems to cause the models to not render at all (strangely).

**Comment by sp614x** [comment]
Block.getActualState() is used at several places and if it crashes, then there is a problem.
The NullPointerException happens in BakedModelSlope so you should be able to fix it.
