### ISSUE TITLE
SVertexBuilder.endAddVertexData doesn't check for vertex count before trying to calculate normals.

### ISSUE THREAD

**Issue by Ordinastie** [sp614x/optifine#295]
It always expects to have 4 vertexes passed directly in with VertexBuffer.addVertexData when it's not always the case.
(Suggestion : check and store vertex count first, and calculate normal when internal counter reaches 4.)

```
java.lang.IndexOutOfBoundsException
at java.nio.Buffer.checkIndex(Unknown Source)
at java.nio.DirectFloatBufferU.get(Unknown Source)
at shadersmod.client.SVertexBuilder.calcNormal(SVertexBuilder.java:157)
at shadersmod.client.SVertexBuilder.endAddVertexData(SVertexBuilder.java:146)
at net.minecraft.client.renderer.VertexBuffer.func_178981_a(VertexBuffer.java:586)
at net.malisis.core.renderer.MalisisRenderer.drawVertex(MalisisRenderer.java:933)
at net.malisis.core.renderer.MalisisRenderer.drawFace(MalisisRenderer.java:893)
at net.malisis.core.renderer.MalisisRenderer.drawShape(MalisisRenderer.java:845)
at net.malisis.doors.renderer.DoorRenderer.renderTileEntity(DoorRenderer.java:217)
at net.malisis.doors.renderer.DoorRenderer.render(DoorRenderer.java:158)
at net.malisis.core.renderer.MalisisRenderer.func_180535_a(MalisisRenderer.java:431)
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:992)
at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:348)
at shadersmod.client.Shaders.beginRender(Shaders.java:3766)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1535)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by sp614x** [comment]
Vertex count is already checked:
```
  public static void endAddVertexData(VertexBuffer wrr)
  {
    SVertexBuilder svb = wrr.sVertexBuilder;
    if (svb.vertexSize == SVertexFormat.vertexSizeBlock)
    {
      // ShadersMod calculate normal and mid UV
      if (wrr.drawMode == GL11.GL_QUADS && wrr.vertexCount % 4 == 0)
      {
        svb.calcNormal(wrr, wrr.getBufferSize() - 4 * svb.vertexSize);
      }
    }
  }
```

**Comment by sp614x** [comment]
Maybe the problem is adding vertex data with the wrong vertex format?
The method addVertexData() will increment vertexCount based on the vertex format size:
```
    public void addVertexData(int[] vertexData)
    {
        // TODO Shaders
        if(Config.isShaders())
          SVertexBuilder.beginAddVertexData(this, vertexData);
        //
        this.growBuffer(vertexData.length * 4);
        this.rawIntBuffer.position(this.getBufferSize());
        this.rawIntBuffer.put(vertexData);
        this.vertexCount += vertexData.length / this.vertexFormat.getIntegerSize();
        // TODO Shaders
        if(Config.isShaders())
          SVertexBuilder.endAddVertexData(this);
        //
    }
```

**Comment by sp614x** [comment]
The shaders use an extended vertex format (vanilla format size = 27, shaders format size = 54). 
The BakedQuad class can automatically fix the vertex data to be compatible with shaders. The method BakedQuad.getVertexData() does the conversion automatically.

**Comment by Ordinastie** [comment]
Passing groups of 4 vertexes did prevent the crash somehow.
But I don't use BakedQuads when rendering, and for TEs, I use my own VertexFormat : https://github.com/Ordinastie/MalisisCore/blob/1.9.4/src/main/java/net/malisis/core/renderer/MalisisRenderer.java#L108

**Comment by sp614x** [comment]
A custom vertex format is not going to work with Shaders. They need the shader specific extended vertex format. The vanilla formats (DefaultVertexFormats.BLOCK and ITEM) are automatically corrected and can be used.

**Comment by Ordinastie** [comment]
That might explain the darkness of my TEs then.

**Comment by sp614x** [comment]
This is the Shaders BLOCK format:
```
  public static VertexFormat makeDefVertexFormatBlock()
  {
    VertexFormat vf = new VertexFormat();
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.FLOAT, VertexFormatElement.EnumUsage.POSITION, 3));
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.UBYTE, VertexFormatElement.EnumUsage.COLOR, 4));
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.FLOAT, VertexFormatElement.EnumUsage.UV, 2));
    vf.addElement(new VertexFormatElement(1, VertexFormatElement.EnumType.SHORT, VertexFormatElement.EnumUsage.UV, 2));
    // added
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.BYTE, VertexFormatElement.EnumUsage.NORMAL, 3));
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.BYTE, VertexFormatElement.EnumUsage.PADDING, 1));
    // mc_midTexCoord
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.FLOAT, VertexFormatElement.EnumUsage.PADDING, 2));
    // at_tangent
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.SHORT, VertexFormatElement.EnumUsage.PADDING, 4));
    // mc_Entity
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.SHORT, VertexFormatElement.EnumUsage.PADDING, 4));
    return vf;
  }
```

**Comment by sp614x** [comment]
The ITEM format is similar:

```
  public static VertexFormat makeDefVertexFormatItem()
  {
    VertexFormat vf = new VertexFormat();
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.FLOAT, VertexFormatElement.EnumUsage.POSITION, 3));
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.UBYTE, VertexFormatElement.EnumUsage.COLOR, 4));
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.FLOAT, VertexFormatElement.EnumUsage.UV, 2));
    // inserted
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.SHORT, VertexFormatElement.EnumUsage.PADDING, 2));
    // moved
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.BYTE, VertexFormatElement.EnumUsage.NORMAL, 3));
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.BYTE, VertexFormatElement.EnumUsage.PADDING, 1));
    // mc_midTexCoord
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.FLOAT, VertexFormatElement.EnumUsage.PADDING, 2));
    // at_tangent
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.SHORT, VertexFormatElement.EnumUsage.PADDING, 4));
    // mc_Entity
    vf.addElement(new VertexFormatElement(0, VertexFormatElement.EnumType.SHORT, VertexFormatElement.EnumUsage.PADDING, 4));
    return vf;
  }
```

**Comment by Ordinastie** [comment]
Using BLOCK vertex format did fix the lighting issue for my TEs, but there is still another problem : 
if I use the FastTESR VertexBuffer I get this result : http://puu.sh/rM4Qa.jpg (with shaders only).

**Comment by sp614x** [comment]
The FastTESR is using the DefaultVertexFormats.BLOCK so it should work with shaders.

**Comment by Ordinastie** [comment]
I couldn't find a mod that uses FastTESR so I could check if it actually works the way it should, or if I'm doing something wrong.

**Comment by sp614x** [comment]
Can you post a test build so I can take a look at it?

**Comment by Ordinastie** [comment]
http://puu.sh/rMbf4.rar

**Comment by Ordinastie** [comment]
I can confirm that the original crash was caused by the use of a custom VertexFormat.
