### ISSUE TITLE
Crash in Forge splashscreen when using Optifine

### ISSUE THREAD

**Issue by kenzierocks** [sp614x/optifine#297]
OptiFine_1.10.2_HD_U_D1
Forge 12.18.2.2102

No crash occurs with splash disabled in Forge or without Optifine.

https://gist.github.com/kenzierocks/3b3086c4941fabf13412d29566a9e8d8

**Comment by sp614x** [comment]
Can this be reproduced with less mods. Ideally it should be reproducible with only OptiFine and one ore two other mods.
Can you also post the error log?

**Comment by Zettt** [comment]
Yes, I'm able to reproduce the problem. I'm using the Curse app on macOS Sierra. Modpack is FTB Unstable 1.10. 

I'm running:

OptiFine_1.10.2_HD_U_D2_pre
Forge 12.18.2.2107

[crash-2016-10-23_11.26.44-client.txt](https://github.com/sp614x/optifine/files/546259/crash-2016-10-23_11.26.44-client.txt)

**Comment by sp614x** [comment]
Is MC crashing every time or only sometimes? Error log?
Which mods are installed? The crash report shows only Forge, OptiFine and CoreChickenLib.
Tested with Forge #2099, OptiFine D1 and CoreChickenLib 2.4.2.106, no crashes so far.

**Comment by Zettt** [comment]
MC is crashing every time. How do I get the error log? I have attached an crash report in my previous message.

**Comment by sp614x** [comment]
In the vanilla launcher the error log is shown in the tab "Game output". 
To keep the launcher open, edit the Forge profile and set "Launcher visibility" to "Keep the launcher open".
No idea where it is in the Curse launcher.

**Comment by Crash0** [comment]
[crash-2016-10-25_21.46.29-client.txt](https://github.com/sp614x/optifine/files/551645/crash-2016-10-25_21.46.29-client.txt)

Having the same problem.

Maybe osx sierra who is the guilty one ?
tho using a MacBook pro with only integrated graphics, and a bunch of mods.

[crash-2016-10-25_21.57.00-client.txt](https://github.com/sp614x/optifine/files/551655/crash-2016-10-25_21.57.00-client.txt)

^without mods

**Comment by sp614x** [comment]
Error log?

**Comment by Crash0** [comment]
Yes,  thats correct.

<details>
<summary>Game output</summary >
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[15:05:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:05:05] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:05:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:05:05] [main/INFO] [FML]: Forge Mod Loader version 12.18.2.2099 for Minecraft 1.10.2 loading
[15:05:05] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_101, running on Mac OS X:x86_64:10.12, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[15:05:05] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.10.2_HD_U_D1.jar
[15:05:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:05:05] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[15:05:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:05:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:05:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:05:05] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[15:05:05] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[15:05:05] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[15:05:05] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[15:05:05] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/Users/jonasviktorfjeld/Documents/Curse/Minecraft/Instances/FTB%20Presents%20HermitPack%20(1)/mods/OptiFine_1.10.2_HD_U_D1.jar
[15:05:05] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: /Users/jonasviktorfjeld/Documents/Curse/Minecraft/Instances/FTB Presents HermitPack (1)/mods/OptiFine_1.10.2_HD_U_D1.jar
[15:05:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:05:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:05:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:05:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:05:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:05:07] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:05:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:05:07] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[15:05:07] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:05:08] [Client thread/INFO]: Setting user: crash0jx
[OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[15:05:11] [Client thread/INFO]: LWJGL Version: 2.9.2
[OptiFine] 
[OptiFine] OptiFine_1.10.2_HD_U_D1
[OptiFine] Build: 20161017-130833
[OptiFine] OS: Mac OS X (x86_64) version 10.12
[OptiFine] Java: 1.8.0_101, Oracle Corporation
[OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[OptiFine] LWJGL: 2.9.2
[OptiFine] OpenGL: Intel Iris Pro OpenGL Engine, version 2.1 INTEL-10.18.65, Intel Inc.
[OptiFine] OpenGL Version: 2.1
[OptiFine] Maximum texture size: 16384x16384
[OptiFine] Checking for new version
[Shaders] ShadersMod version: 2.4.12
[Shaders] OpenGL Version: 2.1 INTEL-10.18.65
[Shaders] Vendor:  Intel Inc.
[Shaders] Renderer: Intel Iris Pro OpenGL Engine
[Shaders] Capabilities:  2.0  2.1  -  -  - 
[Shaders] GL_MAX_DRAW_BUFFERS: 8
[Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[Shaders] Load ShadersMod configuration.
[Shaders] Save ShadersMod configuration.
[Shaders] No shaderpack loaded.
[15:05:12] [Client thread/INFO] [FML]: Forge Mod Loader has detected optifine OptiFine_1.10.2_HD_U_D1, enabling compatibility features
[15:05:12] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:219]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 10/26/16 3:05 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 233296800 bytes (222 MB) / 778567680 bytes (742 MB) up to 3825205248 bytes (3648 MB)
	JVM Flags: 3 total; -Xmx4104m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.18.65' Renderer: 'Intel Iris Pro OpenGL Engine'
[15:05:12] [Client thread/INFO] [FML]: MinecraftForge v12.18.2.2099 Initialized
[15:05:12] [Client thread/INFO] [FML]: Replaced 232 ore recipes
[15:05:12] [Thread-7/ERROR] [FML]: Splash thread Exception
java.lang.IllegalStateException: Texture creation: Invalid value
	at net.minecraftforge.fml.client.SplashProgress.checkGLError(SplashProgress.java:815) ~[SplashProgress.class:?]
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:682) ~[SplashProgress$Texture.class:?]
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:646) ~[SplashProgress$Texture.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:247) ~[SplashProgress$3.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[15:05:12] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[15:05:12] [Client thread/INFO] [FML]: Searching /Users/jonasviktorfjeld/Documents/Curse/Minecraft/Instances/FTB Presents HermitPack (1)/mods for mods
[OptiFine] Version found: D1
[15:05:13] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load
[15:05:13] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[15:05:13] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[15:05:13] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[15:05:13] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[15:05:13] [Client thread/INFO] [FML]: Found 423 ObjectHolder annotations
[15:05:13] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[15:05:13] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[15:05:13] [Client thread/INFO] [FML]: Applying holder lookups
[15:05:13] [Client thread/INFO] [FML]: Holder lookups applied
[15:05:13] [Client thread/INFO] [FML]: Applying holder lookups
[15:05:13] [Client thread/INFO] [FML]: Holder lookups applied
[15:05:13] [Client thread/INFO] [FML]: Applying holder lookups
[15:05:13] [Client thread/INFO] [FML]: Holder lookups applied
[15:05:13] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[15:05:13] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[15:05:13] [Client thread/INFO] [FML]: Applying holder lookups
[15:05:13] [Client thread/INFO] [FML]: Holder lookups applied
[15:05:13] [Client thread/INFO] [FML]: Injecting itemstacks
[15:05:13] [Client thread/INFO] [FML]: Itemstack injection complete
[OptiFine] *** Reloading textures ***
[OptiFine] Resource packs: Default
[15:05:13] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: UP_TO_DATE Target: null
[15:05:14] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:05:14] [Thread-8/INFO]: Initializing LWJGL OpenAL
[15:05:14] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:05:14] [Thread-8/INFO]: OpenAL initialized.
[15:05:14] [Sound Library Loader/INFO]: Sound engine started
[OptiFine] Multitexture: false
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_pane_white.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_white.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_pane_purple.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_purple.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_blue.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_pane_blue.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_brown.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_pane_brown.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_green.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_pane_green.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_pane_red.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_red.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_black.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_pane_black.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_orange.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_pane_orange.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_magenta.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_pane_magenta.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_light_blue.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_pane_light_blue.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_pane_yellow.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_yellow.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_lime.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_pane_lime.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pane_pink.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pink.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_gray.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_pane_gray.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_pane_silver.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_silver.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_cyan.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_pane_cyan.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/bookshelf.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/glass.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/glasspane.properties
[OptiFine] ConnectedTextures: mcpatcher/ctm/default/sandstone.properties
[OptiFine] Multipass connected textures: false
[OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[15:05:15] [Client thread/INFO]: Created: 8x8 textures-atlas
[15:05:17] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// My bad.

Time: 10/26/16 3:05 PM
Description: Initializing game

java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:489)
	at net.minecraftforge.fml.client.SplashProgress.pause(SplashProgress.java:502)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:508)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Texture creation: Invalid value
	at net.minecraftforge.fml.client.SplashProgress.checkGLError(SplashProgress.java:815)
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:682)
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:646)
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:247)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:489)
	at net.minecraftforge.fml.client.SplashProgress.pause(SplashProgress.java:502)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:508)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 585250136 bytes (558 MB) / 1252524032 bytes (1194 MB) up to 3825205248 bytes (3648 MB)
	JVM Flags: 3 total; -Xmx4104m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 Optifine OptiFine_1.10.2_HD_U_D1 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
	UCH	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.18.65' Renderer: 'Intel Iris Pro OpenGL Engine'
	Launched Version: forge-12.18.2.2099
	LWJGL: 2.9.2
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.18.65, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D1
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.18.65
	OpenGlRenderer: Intel Iris Pro OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 8
[15:05:17] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/jonasviktorfjeld/Documents/Curse/Minecraft/Instances/FTB Presents HermitPack (1)/crash-reports/crash-2016-10-26_15.05.16-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
</details>

**Comment by mindforger** [comment]
okay i am very very sorry for disrupting the topic and going off topic to 100% but
@Crash0 ... good lord how did you do that with the spoiler/summary? i can not find anything in the mark down explanation!

**Comment by Crash0** [comment]
You use 
<"details">
 <"summary  "> title <"/summary " >
 text
<"/details  ">

###### Off topic closed

**Comment by Crash0** [comment]
Eureka !
Found a solution !
I disabled the FML splash screen in the splash.properties config.

and now it works using the D1 !

**Comment by kenzierocks** [comment]
@Crash0 that is the fix I specified in the OP.

@sp614x I've been busy but I'll try to get you the error log and other stuff with just Forge + Optifine within the week.

**Comment by Crash0** [comment]
Ohh, Im blind. (facepalm) But yeah. The error is reproducible at least.

**Comment by kenzierocks** [comment]
Error log with Forge 2114 and Optifine D1: https://gist.github.com/kenzierocks/0fab32837ce33a1f9b9e1db7283defe0

**Comment by sp614x** [comment]
Is the latest preview D2 also crashing?

**Comment by Zettt** [comment]
> I disabled the FML splash screen in the splash.properties config.

I just tried this, and the game doesn't crash anymore. So the bug is indeed in the splash screen. Haven't had a chance to produce a crashlog yet.

**Comment by Zettt** [comment]
@sp614x Here's the game output you wanted me to supply. This time I had re-enabled the mods, since we have narrowed the problem down to the splash screen only. Still using D2-pre.

[gameout.txt](https://github.com/sp614x/optifine/files/555357/gameout.txt)

**Comment by sp614x** [comment]
I can not reproduce the problem. All combinations of Forge, OptiFine and different mods are working properly for me.

**Comment by Crash0** [comment]
Are you using mac os sierra? java v. 1.8.0_111 ?

**Comment by Zettt** [comment]
I just installed 111, been on 101. Sierra 10.12.1.

**Comment by mindforger** [comment]
>Caused by: java.lang.IllegalStateException: Texture creation: Invalid value
	at net.minecraftforge.fml.client.SplashProgress.checkGLError(SplashProgress.java:815)
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:682)
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:646)
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:247)
	at java.lang.Thread.run(Thread.java:745)

I have no insight about this particular class, but that sounds like an problem with how textures are displayed/rendered is there the slightest chance to add in a bit diagnostic code around that line number and give em a more verbose version of optifine to get behind it?

**Comment by sp614x** [comment]
The problem seems to appear only on Mac OS, versions 10.9.5 to 10.12.1. 
The Forge splash screen is rendering on a background thread and the graphics driver may have a problem with it. This will be complex to fix as I don't have a Mac for testing.

**Comment by Zettt** [comment]
That is an interesting problem indeed. Since you're mentioning background threads and graphics drivers, it could also be related to the MacBook, which has two built-in graphic cards. Is the splash screen rendering on the built-in or the dedicated card?

Anyway. Is there something I can do to help fix this problem? 

You could setup a virtual Mac through VirtualBox but that is quite a lot of work, and though I'm familiar with a terminal and the command line I have not been able to create a virtual Mac. It depends on how much you want to get this fixed. I think one community member is willing to give you a VNC remote access to a Mac, so you can debug over the web. 

Until it gets fixed, it probably makes sense to let users know that they can edit the splash screen config.

**Comment by Crash0** [comment]
Think i can confirm that the dedicated card is not the problem, i only have the integrated graphics option in my MacBook.

**Comment by sp614x** [comment]
Can you check which is the last OptiFine versions which is working correctly:
- OptiFine C3 for 1.10.2
- OptiFine C2 for 1.10.2
- OptiFine C1 for 1.10.2
- OptiFine C1 for 1.10
- OptiFine B7 for 1.10
- OptiFine B6 for 1.10
- OptiFine B6 for 1.9.4

**Comment by Crash0** [comment]
As said, the latest version that works is C3 for 1.10.2.

**Comment by Crash0** [comment]
ok, fun-fact, I've setup a dev environment with deobfuscated version of D1 for 1.10.2, and now the splash screen is entirely disabled. 
And the splash screen comes back when i remove the deobfuscated jar.

But then again, it wont show the splash screen with any of the deobfuscated vesons of optifine.

**Comment by sp614x** [comment]
Are these 2 versions working?
http://optifine.net/tmp/OptiFine_1.10.2_HD_U_C4_pre1.jar
http://optifine.net/tmp/OptiFine_1.10.2_HD_U_C4_pre2.jar

**Comment by Crash0** [comment]
Pre1 works.
Pre2 crashes.
[Game output](https://gist.github.com/Crash0/5aafb1dbe383329b0e3c71c69608cb3e)

**Comment by sp614x** [comment]
Can you try "Video Settings -> Quality -> Custom Entity Models -> OFF"?

**Comment by Crash0** [comment]
Still crashes.

**Comment by sp614x** [comment]
Is this one better:
http://optifine.net/tmp/OptiFine_1.10.2_HD_U_C4_pre2B.jar

**Comment by Crash0** [comment]
Yes, that works !

**Comment by sp614x** [comment]
Updated preview D2 with a bugfix, is it working?
http://optifine.net/adloadx?f=preview_OptiFine_1.10.2_HD_U_D2_pre.jar

**Comment by Crash0** [comment]
Yes that worked !
May I ask what the problem was ?

**Comment by sp614x** [comment]
Between C3 and D1 OptiFine added a better way to detect the maximum supported texture size on modern GPUs. It is a modified version of the way vanilla does it. It works by creating bigger and bigger virtual textures until the GPU says "Not possible". 

The problem is that some (older) GPU drivers not only respond with "Not possible", but they also raise the glError flag, which is not correct. This is usually not a problem, the next time glError is checked it is automatically cleared. 

OptiFine calls the function when initializing and on Mac OS the glError is set. A bit later the forge splash screen starts and tries to create the screen texture. It checks the glError and crashes because it thinks that the texture creation has failed. It could have just log the error and go on. It looks like the splash screen is too sensitive to gl errors. 

Vanilla is not calling the function when initializing, so the splash screen can start. Vanilla calls it when loading the texture atlas, the glError is raised, but on the next frame the error is checked, logged and reset, so nothing bad happens. 

The bugfix was to clear the glError after the maximum texture detection has finished.

**Comment by Crash0** [comment]
Ok, sounds like it was a easy problem to fix when we found the source of it :)
and yeah, OS X graphics assent always best friends OpenGL. 

As I understand they use some sort of legacy version, specific to OS X.

**Comment by kenzierocks** [comment]
They're not legacy drivers, they're just Apple's drivers. Different drivers have different bugs.

**Comment by Zettt** [comment]
Confirmed. It works. Thanks for fixing, @sp614x.
