### ISSUE TITLE
Crash with latest 1.14.4 preview while trying to join a spigot server 

### ISSUE THREAD

**Issue by ccar795** [sp614x/optifine#2999]
https://pastebin.com/eZvamunY

**Comment by sp614x** [comment]
Problem with Forge class loading, not related to the server:

```
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.BufferBuilder$State
    at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.0.0.jar:?] {}
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
```

Preview 12 is compatible with Forge 28.1.56.
