### ISSUE TITLE
Optifine 1.12.2 HD U F4 Crashing

### ISSUE THREAD

**Issue by yugi1408** [sp614x/optifine#3012]
So I tried loading Optifine with a few mods (keep in mind that all this worked with E3 Version), so anyway I keep crashing when using it.

Here are my specs:

i9-9900k
MSI RTX 2080 Ti GAMING X TRIO
32GB DDR4 RAM

Here is a link to my log:
https://paste.ee/p/xDa2w

**Comment by sp614x** [comment]
The crash is in BuildCraft RenderUtil.

```
java.lang.Error: Incorrect number of fields! (Expected 2, but got [private boolean net.minecraft.client.renderer.BufferBuilder.field_78939_q, private boolean net.minecraft.client.renderer.BufferBuilder.field_179010_r, private boolean net.minecraft.client.renderer.BufferBuilder.modeTriangles])
	at buildcraft.lib.misc.RenderUtil.createGetter(RenderUtil.java:54)
	at buildcraft.lib.misc.RenderUtil.<clinit>(RenderUtil.java:41)
```
