### ISSUE TITLE
Unknown Crash on Startup Optifine 1.14.4 F4

### ISSUE THREAD

**Issue by NitroxPower** [sp614x/optifine#3025]
Its a very weird situation of this bug i started combining this with forge (28.1.0) and when it was going into the title screen its just cashes and this pops up 
![image](https://user-images.githubusercontent.com/46358553/67637182-7624d980-f8e0-11e9-8ff2-f3341657c09f.png) Before i put optifine to the mods it wasnt crashing but when it did i started crashing and later when i removed it it wasnt crashing anymore. Now the weird part is that i also tried with the latest version of forge (28.1.70) and same things. BUT when i removed optifine from the mods list it was keep having the same crash even i removed ALL mods. Even starting only optifine 1.14.4 F4 without forge it keep crashing same way. So i cant actually understand this situation of crashing and whats the issue here i have also the Log:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 27/10/2019 5:31 μμ
Description: Rendering screen

java.lang.IllegalArgumentException: Out of bounds: start: (0, 0) (size: 20x27); size: 20x27
	at net.minecraft.client.renderer.texture.NativeImage.func_211676_a(NativeImage.java:338) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.fonts.providers.TrueTypeGlyphProvider$GlpyhInfo.func_211573_a(SourceFile:140) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.FontTexture.func_211131_a(SourceFile:48) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.Font.func_211185_a(SourceFile:121) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.Font.func_212458_a(SourceFile:107) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.Font$$Lambda$2620/1307655038.apply(Unknown Source) ~[?:?] {}
	at it.unimi.dsi.fastutil.chars.Char2ObjectOpenHashMap.computeIfAbsent(Char2ObjectOpenHashMap.java:479) ~[fastutil-8.2.1.jar:?] {}
	at net.minecraft.client.gui.fonts.Font.func_211187_a(SourceFile:107) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.FontRenderer.func_211843_b(SourceFile:155) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.FontRenderer.func_180455_b(SourceFile:84) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.FontRenderer.func_175063_a(SourceFile:51) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.AbstractGui.drawCenteredString(SourceFile:98) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.MainMenuScreen.render(MainMenuScreen.java:221) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:345) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.70.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$372/1843743552.call(Unknown Source) [forge-1.14.4-28.1.70.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.NativeImage.func_211676_a(NativeImage.java:338)
	at net.minecraft.client.gui.fonts.providers.TrueTypeGlyphProvider$GlpyhInfo.func_211573_a(SourceFile:140)
	at net.minecraft.client.gui.fonts.FontTexture.func_211131_a(SourceFile:48)
	at net.minecraft.client.gui.fonts.Font.func_211185_a(SourceFile:121)
	at net.minecraft.client.gui.fonts.Font.func_212458_a(SourceFile:107)
	at net.minecraft.client.gui.fonts.Font$$Lambda$2620/1307655038.apply(Unknown Source)
	at it.unimi.dsi.fastutil.chars.Char2ObjectOpenHashMap.computeIfAbsent(Char2ObjectOpenHashMap.java:479)
	at net.minecraft.client.gui.fonts.Font.func_211187_a(SourceFile:107)
	at net.minecraft.client.gui.FontRenderer.func_211843_b(SourceFile:155)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(SourceFile:84)
	at net.minecraft.client.gui.FontRenderer.func_175063_a(SourceFile:51)
	at net.minecraft.client.gui.AbstractGui.drawCenteredString(SourceFile:98)
	at net.minecraft.client.gui.screen.MainMenuScreen.render(MainMenuScreen.java:221)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:345)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.MainMenuScreen
	Mouse location: Scaled: (212, 163). Absolute: (851.000000, 655.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:554)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$372/1843743552.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2698653816 bytes (2573 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.70
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		forge-1.14.4-28.1.70-client.jar Minecraft {minecraft@1.14.4 DONE}
		forge-1.14.4-28.1.70-universal.jar Forge {forge@28.1.70 DONE}
	Launched Version: 1.14.4-forge-28.1.70
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.97, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Stevens Traditional 64x64 [1.14.4].zip
	Current Language: English (United Kingdom)
	CPU: 8x Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz

--------------- Let me know if you want more information i can help you ----------------

**Comment by NitroxPower** [comment]
After further testing its seems its crashing only when i have that specific resource pack when i am 100% sure that thats the false i will close this issue

**Comment by sp614x** [comment]
The bug was fixed shortly after release.
Please redownload OptiFine.

**Comment by NitroxPower** [comment]
I did tried this but dint work cause the developer of the texture pack did release another version and he said "fixed crashing with font in weird situations" and i downloaded  that version and it did fix it thats why i closed this issue
