### ISSUE TITLE
CustomColormap crash (1.10.2_HD_U_D2_pre)

### ISSUE THREAD

**Issue by Brottweiler** [sp614x/optifine#303]
I am running `OptiFine_1.10.2_HD_U_D2_pre` with a resource pack containing custom color for durability. Game crashed when I mined a block with a diamond pickaxe.

```java
---- Minecraft Crash Report ----
// You're mean.

Time: 10/27/16 9:37 PM
XRay version: 39
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 32
	at CustomColormap.getColor(CustomColormap.java:374)
	at CustomColors.getDurabilityColor(CustomColors.java:1172)
	at bsu.a(RenderItem.java:579)
	at bsu.a(RenderItem.java:521)
	at bdm.a(GuiIngame.java:1199)
	at bdm.a(GuiIngame.java:566)
	at bdm.a(GuiIngame.java:188)
	at bnz.a(EntityRenderer.java:1370)
	at bcx.av(SourceFile:991)
	at bcx.a(SourceFile:396)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at CustomColormap.getColor(CustomColormap.java:374)
	at CustomColors.getDurabilityColor(CustomColors.java:1172)
	at bsu.a(RenderItem.java:579)
	at bsu.a(RenderItem.java:521)
	at bdm.a(GuiIngame.java:1199)
	at bdm.a(GuiIngame.java:566)
	at bdm.a(GuiIngame.java:188)

-- Affected level --
Details:
	Level name: MpServer
	All players: 65 total; [bnn['Brottweiler'/6876, l='MpServer', x=-35.74, y=10.00, z=-231.90], bno['th21375'/9763, l='MpServer', x=-83.37, y=9.00, z=-212.78], bno['ELBOU99999'/10004, l='MpServer', x=-86.69, y=10.00, z=-202.98], bno['FonfiMC'/57, l='MpServer', x=-77.22, y=9.28, z=-201.77], bno['MrMaarquez'/141, l='MpServer', x=-75.78, y=11.30, z=-197.63], bno['Ricardoamorim0'/69, l='MpServer', x=-47.79, y=11.21, z=-235.39], bno['Aguuh'/4516, l='MpServer', x=-75.59, y=9.00, z=-204.10], bno['albertoreyees_'/17011, l='MpServer', x=-46.16, y=10.23, z=-225.88], bno['c43-beda228ee1ab'/9088, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['d89-e1a8c69fe5fd'/68, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['714-ca3a4483ee3f'/19172, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e30-ccfe82b9d767'/9768, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['123-98e2ddfd0f17'/4680, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['97c-e7b8e4dd6e72'/1096, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['121-a66e45e21ff1'/4521, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['98e-5cee7d3fdb74'/74, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e2f-1d185a3c7662'/138, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd6-aed63f18f908'/17290, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['8a3-4c9ab0e600ba'/17900, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['720-5d621a64cd37'/205, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['344-41a0434da2d3'/47, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['4b9-1eb2480a39ed'/175, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['4a7-148064553787'/4656, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['b13-21f89adc182d'/146, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['40d-04dcb4848b05'/5331, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd0-c82460fe6de3'/53, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['95c-287a6b93358d'/15222, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['3d9-dfa62c8e12fe'/9270, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e4f-59b04b73222b'/17016, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['55b-b7287f9af9a1'/10009, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['050-68d6faa5a880'/11225, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['1e0-30c887e53d2e'/62, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['_CaptainShadow'/200, l='MpServer', x=-92.98, y=8.34, z=-199.09], bno['720-5d621a64cd37'/205, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['121-a66e45e21ff1'/4521, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e4f-59b04b73222b'/17016, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['55b-b7287f9af9a1'/10009, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['1e0-30c887e53d2e'/62, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['b13-21f89adc182d'/146, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['98e-5cee7d3fdb74'/74, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e30-ccfe82b9d767'/9768, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['8a3-4c9ab0e600ba'/17900, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['714-ca3a4483ee3f'/19172, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['4b9-1eb2480a39ed'/175, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['40d-04dcb4848b05'/5331, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['c43-beda228ee1ab'/9088, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['95c-287a6b93358d'/15222, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['344-41a0434da2d3'/47, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd0-c82460fe6de3'/53, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['d89-e1a8c69fe5fd'/68, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['3d9-dfa62c8e12fe'/9270, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['97c-e7b8e4dd6e72'/1096, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['050-68d6faa5a880'/11225, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd6-aed63f18f908'/17290, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['123-98e2ddfd0f17'/4680, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e2f-1d185a3c7662'/138, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['4a7-148064553787'/4656, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['leahmerri'/48, l='MpServer', x=13.78, y=9.48, z=-117.76], bno['lollo1302'/63, l='MpServer', x=-7.08, y=10.06, z=-93.38], bno['HiddenTactical'/15217, l='MpServer', x=17.19, y=9.31, z=-115.89], bno['GREGORY2005'/9083, l='MpServer', x=6.33, y=9.66, z=-108.98], bno['xXN4F3BR3Xx'/17285, l='MpServer', x=7.16, y=10.11, z=-98.88], bno['TechGeorge'/11220, l='MpServer', x=2.72, y=9.41, z=-105.39], bno['LukeBra'/9265, l='MpServer', x=-0.26, y=9.00, z=-95.97], bno['McRain'/1091, l='MpServer', x=0.48, y=9.45, z=-92.14]]
	Chunk stats: MultiplayerChunkCache: 435, 435
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-13,22,-78), Chunk: (at 3,1,2 in -1,-5; contains blocks -16,0,-80 to -1,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 74291238 game time, 72986026 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 109 total; [bno['ELBOU99999'/10004, l='MpServer', x=-86.69, y=10.00, z=-202.98], bno['lollo1302'/63, l='MpServer', x=-7.08, y=10.06, z=-93.38], bno['th21375'/9763, l='MpServer', x=-83.37, y=9.00, z=-212.78], bno['leahmerri'/48, l='MpServer', x=13.78, y=9.48, z=-117.76], bno['LukeBra'/9265, l='MpServer', x=-0.26, y=9.00, z=-95.97], bno['FonfiMC'/57, l='MpServer', x=-77.22, y=9.28, z=-201.77], bno['lollo1302'/63, l='MpServer', x=-7.08, y=10.06, z=-93.38], bno['McRain'/1091, l='MpServer', x=0.48, y=9.45, z=-92.14], bno['Ricardoamorim0'/69, l='MpServer', x=-47.79, y=11.21, z=-235.39], bno['_CaptainShadow'/200, l='MpServer', x=-92.98, y=8.34, z=-199.09], xz['entity.ItemFrame.name'/19050, l='MpServer', x=-16.50, y=13.50, z=-207.03], xz['entity.ItemFrame.name'/19051, l='MpServer', x=-16.50, y=13.50, z=-203.97], xz['entity.ItemFrame.name'/19052, l='MpServer', x=-62.50, y=13.50, z=-108.97], bno['HiddenTactical'/15217, l='MpServer', x=17.19, y=9.31, z=-115.89], bno['albertoreyees_'/17011, l='MpServer', x=-46.16, y=10.23, z=-225.88], bno['xXN4F3BR3Xx'/17285, l='MpServer', x=7.16, y=10.11, z=-98.88], bno['GREGORY2005'/9083, l='MpServer', x=6.33, y=9.66, z=-108.98], bno['GREGORY2005'/9083, l='MpServer', x=6.33, y=9.66, z=-108.98], bno['TechGeorge'/11220, l='MpServer', x=2.72, y=9.41, z=-105.39], bno['xXN4F3BR3Xx'/17285, l='MpServer', x=7.16, y=10.11, z=-98.88], bno['HiddenTactical'/15217, l='MpServer', x=17.19, y=9.31, z=-115.89], bno['MrMaarquez'/141, l='MpServer', x=-75.78, y=11.30, z=-197.63], bno['leahmerri'/48, l='MpServer', x=13.78, y=9.48, z=-117.76], bno['720-5d621a64cd37'/205, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['121-a66e45e21ff1'/4521, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['Aguuh'/4516, l='MpServer', x=-75.59, y=9.00, z=-204.10], bno['1e0-30c887e53d2e'/62, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['b13-21f89adc182d'/146, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e4f-59b04b73222b'/17016, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['55b-b7287f9af9a1'/10009, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['8a3-4c9ab0e600ba'/17900, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['714-ca3a4483ee3f'/19172, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['98e-5cee7d3fdb74'/74, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e30-ccfe82b9d767'/9768, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['c43-beda228ee1ab'/9088, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['95c-287a6b93358d'/15222, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['4b9-1eb2480a39ed'/175, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['40d-04dcb4848b05'/5331, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['d89-e1a8c69fe5fd'/68, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['3d9-dfa62c8e12fe'/9270, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['344-41a0434da2d3'/47, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd0-c82460fe6de3'/53, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd6-aed63f18f908'/17290, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['123-98e2ddfd0f17'/4680, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['97c-e7b8e4dd6e72'/1096, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['050-68d6faa5a880'/11225, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['e2f-1d185a3c7662'/138, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['4a7-148064553787'/4656, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['McRain'/1091, l='MpServer', x=0.48, y=9.45, z=-92.14], bno['LukeBra'/9265, l='MpServer', x=-0.26, y=9.00, z=-95.97], bno['_CaptainShadow'/200, l='MpServer', x=-92.98, y=8.34, z=-199.09], xz['entity.ItemFrame.name'/19145, l='MpServer', x=26.50, y=10.50, z=-111.03], bno['ELBOU99999'/10004, l='MpServer', x=-86.69, y=10.00, z=-202.98], xz['entity.ItemFrame.name'/19150, l='MpServer', x=32.50, y=10.50, z=-111.03], bno['th21375'/9763, l='MpServer', x=-83.37, y=9.00, z=-212.78], bnn['Brottweiler'/6876, l='MpServer', x=-35.74, y=10.00, z=-231.90], bno['leahmerri'/48, l='MpServer', x=7.70, y=13.00, z=-63.38], xz['entity.ItemFrame.name'/19155, l='MpServer', x=-62.50, y=13.50, z=-112.03], bno['121-a66e45e21ff1'/4521, l='MpServer', x=0.00, y=1073741823.00, z=0.00], xz['entity.ItemFrame.name'/19156, l='MpServer', x=-90.50, y=6.50, z=-176.03], bno['HiddenTactical'/15217, l='MpServer', x=8.31, y=13.00, z=-63.15], bno['TechGeorge'/11220, l='MpServer', x=2.72, y=9.41, z=-105.39], bno['e4f-59b04b73222b'/17016, l='MpServer', x=0.00, y=1073741823.00, z=0.00], xz['entity.ItemFrame.name'/19157, l='MpServer', x=-105.50, y=10.50, z=-204.97], bno['FonfiMC'/57, l='MpServer', x=-77.22, y=9.28, z=-201.77], xz['entity.ItemFrame.name'/19158, l='MpServer', x=-111.50, y=10.50, z=-204.97], bno['720-5d621a64cd37'/205, l='MpServer', x=0.00, y=1073741823.00, z=0.00], xz['entity.ItemFrame.name'/19159, l='MpServer', x=-4.03, y=16.50, z=-228.50], bno['McRain'/1091, l='MpServer', x=8.16, y=13.00, z=-63.80], bno['95c-287a6b93358d'/15222, l='MpServer', x=0.00, y=1073741823.00, z=0.00], xz['entity.ItemFrame.name'/19160, l='MpServer', x=-4.03, y=16.50, z=-230.50], bno['344-41a0434da2d3'/47, l='MpServer', x=0.00, y=1073741823.00, z=0.00], aar['Minecart with Chest'/19161, l='MpServer', x=-27.50, y=5.00, z=-235.50], bno['4a7-148064553787'/4656, l='MpServer', x=0.00, y=1073741823.00, z=0.00], yb['Painting'/19162, l='MpServer', x=-30.50, y=17.50, z=-235.03], bno['jamesbond_39'/42, l='MpServer', x=7.36, y=13.00, z=-63.99], bno['c43-beda228ee1ab'/9088, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['GREGORY2005'/9083, l='MpServer', x=7.45, y=13.00, z=-63.77], aar['Minecart with Chest'/19163, l='MpServer', x=-27.49, y=12.06, z=-235.50], bno['e30-ccfe82b9d767'/9768, l='MpServer', x=0.00, y=1073741823.00, z=0.00], xz['entity.ItemFrame.name'/19164, l='MpServer', x=0.97, y=16.50, z=-243.50], bno['8a3-4c9ab0e600ba'/17900, l='MpServer', x=0.00, y=1073741823.00, z=0.00], xz['entity.ItemFrame.name'/19165, l='MpServer', x=-0.03, y=16.50, z=-247.50], bno['LukeBra'/9265, l='MpServer', x=8.41, y=13.00, z=-63.25], bno['3d9-dfa62c8e12fe'/9270, l='MpServer', x=0.00, y=1073741823.00, z=0.00], xz['entity.ItemFrame.name'/19166, l='MpServer', x=-27.03, y=13.50, z=-243.50], bno['98e-5cee7d3fdb74'/74, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['55b-b7287f9af9a1'/10009, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['MrMaarquez'/141, l='MpServer', x=-75.78, y=11.30, z=-197.63], bno['1e0-30c887e53d2e'/62, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['xXN4F3BR3Xx'/17285, l='MpServer', x=7.37, y=13.00, z=-63.51], bno['4b9-1eb2480a39ed'/175, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['lollo1302'/63, l='MpServer', x=7.29, y=13.00, z=-63.22], bno['123-98e2ddfd0f17'/4680, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['TechGeorge'/11220, l='MpServer', x=8.99, y=13.00, z=-63.17], bno['97c-e7b8e4dd6e72'/1096, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['albertoreyees_'/17011, l='MpServer', x=-46.16, y=10.23, z=-225.88], bno['b13-21f89adc182d'/146, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd0-c82460fe6de3'/53, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['Ricardoamorim0'/69, l='MpServer', x=-47.79, y=11.21, z=-235.39], bno['d89-e1a8c69fe5fd'/68, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['Aguuh'/4516, l='MpServer', x=-75.59, y=9.00, z=-204.10], bno['e2f-1d185a3c7662'/138, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['fd6-aed63f18f908'/17290, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['40d-04dcb4848b05'/5331, l='MpServer', x=0.00, y=1073741823.00, z=0.00], bno['050-68d6faa5a880'/11225, l='MpServer', x=0.00, y=1073741823.00, z=0.00], yb['Painting'/19148, l='MpServer', x=-48.50, y=17.50, z=-80.97], yb['Painting'/19162, l='MpServer', x=-30.50, y=17.50, z=-235.03], bno['714-ca3a4483ee3f'/19172, l='MpServer', x=0.00, y=1073741823.00, z=0.00]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.10-SNAPSHOT:88abfb3:unknown) <- SportBukkit
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bln.a(WorldClient.java:498)
	at bcx.b(SourceFile:2535)
	at bcx.a(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.8.4-1-ARCH
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 279327664 bytes (266 MB) / 653606912 bytes (623 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 370.28, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: Matmos Default, PF, Plast Pack (incompatible)
	Current Language: §eEnglish (§bColor§e)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D2_pre
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 370.28
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by sp614x** [comment]
What size is the durability.png?
Link?

**Comment by Brottweiler** [comment]
Today I made it wider. I think it's either 16 or 32 pixels wide, that explains why it crashed today but not yesterday.

**Comment by sp614x** [comment]
Fixed in latest preview D2.
