### ISSUE TITLE
OptiFine_1.12.2_HD_U_F4 crash on "java.lang.NoSuchFieldError"

### ISSUE THREAD

**Issue by Coloryr** [sp614x/optifine#3044]
When switch shaderpack,it crash....

Description: Updating screen events

java.lang.NoSuchFieldError: field_191308_b
    at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
    at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
    at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
    at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1086)
    at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:948)
    at net.optifine.shaders.Shaders.setShaderPack(Shaders.java:871)
    at net.optifine.shaders.gui.GuiSlotShaders.selectIndex(GuiSlotShaders.java:91)
    at net.optifine.shaders.gui.GuiSlotShaders.elementClicked(GuiSlotShaders.java:81)
    at net.minecraft.client.gui.GuiSlot.handleMouseInput(GuiSlot.java:348)
    at net.optifine.shaders.gui.GuiShaders.handleMouseInput(GuiShaders.java:117)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by sp614x** [comment]
Fixed in F6_pre1 for 1.12.2
@Sildurs-shaders

**Comment by vapecloudbear** [comment]
Where can we download OptiFine 1.12.2 HD U F6_pre1 for 1.12.2? Thanks for the help.

**Comment by vapecloudbear** [comment]
My apologies, I found it. Realized you had to click "Preview Versions"
