### ISSUE TITLE
Optifine 1.14.4 crash when loading chunks, especially after using portals.

### ISSUE THREAD

**Issue by NullCase** [sp614x/optifine#3055]
Version: OptiFine 1.14.4 HD U F4

Context: Default setup for optifine. No mods. Game tends to crash when I move around, loading areas. I thought about just reinstalling MC and optifine, but before that it seemed like a good idea to share the crash log.

Here's the JVM arguments.

```
-Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

Crash log:
```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 08/11/19 21:19
Description: Tesselating block model

java.lang.ArithmeticException: / by zero
	at dnz.makeVertexDataSingle(BakedQuad.java:119)
	at dnz.getVertexDataSingle(BakedQuad.java:107)
	at dny.renderQuadsSmooth(BlockModelRenderer.java:236)
	at dny.renderModelSmooth(BlockModelRenderer.java:141)
	at dny.renderModel(BlockModelRenderer.java:95)
	at dnw.renderBlock(BlockRendererDispatcher.java:89)
	at dpy.b(ChunkRender.java:385)
	at dpv.a(SourceFile:90)
	at dpv.run(SourceFile:39)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dnz.makeVertexDataSingle(BakedQuad.java:119)
	at dnz.getVertexDataSingle(BakedQuad.java:107)
	at dny.renderQuadsSmooth(BlockModelRenderer.java:236)
	at dny.renderModelSmooth(BlockModelRenderer.java:141)

-- Block model being tesselated --
Details:
	Block: Block{minecraft:light_blue_stained_glass}
	Block location: World: (-49,66,32), Chunk: (at 15,4,0 in -4,2; contains blocks -64,0,32 to -49,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at dny.renderModel(BlockModelRenderer.java:95)

-- Block being tesselated --
Details:
	Block: Block{minecraft:light_blue_stained_glass}
	Block location: World: (-49,66,32), Chunk: (at 15,4,0 in -4,2; contains blocks -64,0,32 to -49,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at dnw.renderBlock(BlockRendererDispatcher.java:89)

-- Affected level --
Details:
	All players: 1 total; [dmp['NullCase'/936488, l='MpServer', x=41.41, y=70.00, z=40.96]]
	Chunk stats: Client Chunk Cache: 441, 240
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (1098,65,-503), Chunk: (at 10,4,9 in 68,-32; contains blocks 1088,0,-512 to 1103,255,-497), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Level time: 29917 game time, 734646406 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(ClientWorld.java:574)
	at cyc.b(SourceFile:1923)
	at dpv.run(SourceFile:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2230394240 bytes (2127 MB) / 3489660928 bytes (3328 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-OptiFine_HD_U_F4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 4
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.94
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by NullCase** [comment]
Fix steps:

1) AppData\Roaming\.minecraft\versions
2) remove 1.14.4
3) remove 1.14.4-OptiFine .....
4) launch 1.14.4 (to reinstall)
5) reinstall Optifine 1.14.4 ....

This fixed the problem. Took about 3 minutes.

**Comment by NullCase** [comment]
Nevermined.

Optifine crashed again a few hours after working. Without changing anything and reloading Optifine, now it works (for now?).

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 04/12/19 03:14
Description: Tesselating block model

java.lang.ArithmeticException: / by zero
	at dnz.makeVertexDataSingle(BakedQuad.java:119)
	at dnz.getVertexDataSingle(BakedQuad.java:107)
	at dny.renderQuadsSmooth(BlockModelRenderer.java:236)
	at dny.renderModelSmooth(BlockModelRenderer.java:141)
	at dny.renderModel(BlockModelRenderer.java:95)
	at dnw.renderBlock(BlockRendererDispatcher.java:89)
	at dpy.b(ChunkRender.java:385)
	at dpv.a(SourceFile:90)
	at dpv.run(SourceFile:39)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dnz.makeVertexDataSingle(BakedQuad.java:119)
	at dnz.getVertexDataSingle(BakedQuad.java:107)
	at dny.renderQuadsSmooth(BlockModelRenderer.java:236)
	at dny.renderModelSmooth(BlockModelRenderer.java:141)

-- Block model being tesselated --
Details:
	Block: Block{minecraft:light_blue_stained_glass}
	Block location: World: (-49,66,32), Chunk: (at 15,4,0 in -4,2; contains blocks -64,0,32 to -49,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at dny.renderModel(BlockModelRenderer.java:95)

-- Block being tesselated --
Details:
	Block: Block{minecraft:light_blue_stained_glass}
	Block location: World: (-49,66,32), Chunk: (at 15,4,0 in -4,2; contains blocks -64,0,32 to -49,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at dnw.renderBlock(BlockRendererDispatcher.java:89)

-- Affected level --
Details:
	All players: 1 total; [dmp['NullCase'/119124, l='MpServer', x=-61.31, y=63.00, z=19.09]]
	Chunk stats: Client Chunk Cache: 441, 225
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (39,71,53), Chunk: (at 7,4,5 in 2,3; contains blocks 32,0,48 to 47,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 177656 game time, 779743591 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(ClientWorld.java:574)
	at cyc.b(SourceFile:1923)
	at dpv.run(SourceFile:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3188512112 bytes (3040 MB) / 3791650816 bytes (3616 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-OptiFine_HD_U_F4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 4
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.94
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by sp614x** [comment]
Only happens when anisotropic filtering or antialiasing (AF/AA) is enabled.

**Comment by NullCase** [comment]
Confirmed.

I was using AA x4.
Turned it off and no crashes since.
