### ISSUE TITLE
[1.14.4] OutOfMemoryError: Rendering overlay

### ISSUE THREAD

**Issue by RedMoco** [sp614x/optifine#3079]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2019/11/17 上午 10:36
Description: Rendering overlay

java.lang.OutOfMemoryError: Rendering overlay
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:484)
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:517)
	at com.mojang.blaze3d.platform.TextureUtil.readResource(SourceFile:83)
	at cuj.a(NativeImage.java:103)
	at cuj.a(NativeImage.java:93)
	at dxb.a(TextureAtlasSprite.java:567)
	at dxa.a(AtlasTexture.java:553)
	at dxa.lambda$getStitchedSprites$3(AtlasTexture.java:524)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:484)
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:517)
	at com.mojang.blaze3d.platform.TextureUtil.readResource(SourceFile:83)
	at cuj.a(NativeImage.java:103)

-- Overlay render details --
Details:
	Overlay name: dcb
Stacktrace:
	at dnc.a(GameRenderer.java:880)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 134573864 bytes (128 MB) / 385060864 bytes (367 MB) up to 1037959168 bytes (989 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Launched Version: 1.14.4-OptiFine_HD_U_F4
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 745/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/GUI-審美觀.zip
	Current Language: 繁體中文 (台灣)
	CPU: 8x Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0
	OpenGlRenderer: GeForce GTX 745/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by mindforger** [comment]
分配更多的內存 (more RAM)

i hope that translates well

**Comment by sp614x** [comment]
Out of memory when loading textures. Looks like the resource pack is too big.
You can allocate more memory to MC in the launcher profile.

![image](https://user-images.githubusercontent.com/16635441/69228850-a0d31c80-0b84-11ea-976c-d27591a00568.png)
