### ISSUE TITLE
[Shaders] Integer texture formats not working

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#3109]
The integer texture formats like `GL_RGBA32UI` need a pixel transfer format with `_INTEGER` at the end.

Currently trying to use an integer format results in:
```
[10:35:50] [Client thread/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Texture type and format combination is not valid.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL11C.nglTexImage2D(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11C.glTexImage2D(GL11C.java:1696) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:6998) [lwjgl-opengl-3.2.2.jar:build 10]
	at net.optifine.shaders.Shaders.setupFrameBuffer(Shaders.java:3934) [Git/:?]
	at net.optifine.shaders.Shaders.resize(Shaders.java:3880) [Git/:?]
	at net.optifine.shaders.Shaders.init(Shaders.java:2429) [Git/:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4071) [Git/:?]
	at net.minecraft.client.renderer.GameRenderer.renderWorld(GameRenderer.java:1022) [Git/:?]
	at net.minecraft.client.renderer.GameRenderer.updateCameraAndRender(GameRenderer.java:790) [Git/:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1122) [Git/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:473) [Git/:?]
	at net.minecraft.client.main.Main.main(Main.java:143) [Git/:?]
```

https://stackoverflow.com/questions/11278928/opengl-2-texture-internal-formats-gl-rgb8i-gl-rgb32ui-etc/11771643#11771643
https://community.khronos.org/t/invalid-operation-when-i-try-to-load-a-gl-r8ui-texture/75321
https://www.khronos.org/opengl/wiki/Pixel_Transfer#Pixel_format

**Comment by sp614x** [comment]
Fixed in 1.14.4_F5_pre1
