### ISSUE TITLE
OptiFine in Forge 1.14.4-28.1.109 classpath

### ISSUE THREAD

**Issue by Nik-mmzd** [sp614x/optifine#3185]
I tried to add extracted ("extract" button in OptiFine installer) OptiFine 1.14.4 HD U F5 to classpath of an instance of Minecraft 1.14.4 with Forge 28.1.109, and got [this crash (link to full latest.log)](https://gist.github.com/Nik-mmzd/c526f5c6e396b72010b10ab7dc719b28):
```
[java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
...
[java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.NoSuchMethodError: javax.vecmath.Matrix4f.setIdentity()V
```
After I removed empty class javax/vecmath/Matrix4f (why it is even exists?) from OptiFine jar Minecraft was able to start but on world creation/joining I got [this crash (link to full latest.log)](https://gist.github.com/Nik-mmzd/72e9303326b5c7119043382d851c80be):
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/multiplayer/ClientChunkProvider.func_217250_a(Lnet/minecraft/world/World;IILnet/minecraft/network/PacketBuffer;Lnet/minecraft/nbt/CompoundNBT;IZ)Lnet/minecraft/world/chunk/Chunk; @234: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'net/minecraft/world/chunk/Chunk'
  Current Frame:
    bci: @234
    flags: { }
    locals: { 'net/minecraft/client/multiplayer/ClientChunkProvider', 'net/minecraft/world/World', integer, integer, 'net/minecraft/network/PacketBuffer', 'net/minecraft/nbt/CompoundNBT', integer, integer, integer, 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 2ab4 0043 1c1d b800 639a 0017 b200 9312
    0x0000010: 951c b800 9b1d b800 9bb9 00a1 0400 01b0
    0x0000020: 2ab4 0043 1c1d b800 6736 082a b400 43b8
    0x0000030: 00a5 1508 b600 abc0 004f 3a09 1909 1c1d
    0x0000040: b800 6d9a 0050 1507 9a00 17b2 0093 12ad
    0x0000050: 1cb8 009b 1db8 009b b900 a104 0001 b0bb
    0x0000060: 00af 592b bb00 1f59 1c1d b700 2211 0100
    0x0000070: bd00 b1b7 00b4 3a09 1909 1904 1905 1506
    0x0000080: 1507 b600 b82a b400 4315 0819 09b6 00bc
    0x0000090: a700 5803 360a 1909 c100 af99 0034 1909
    0x00000a0: c000 af3a 0b19 0412 beb6 00c4 3a0c 190c
    0x00000b0: c100 c699 001c 190c c000 c63a 0d19 0b19
    0x00000c0: 0db6 00ca b200 d019 0db6 00d6 0436 0a19
    0x00000d0: 0919 0419 0515 0615 07b6 00b8 150a 9900
    0x00000e0: 0ab2 00d0 01b6 00d6 1909 b600 da3a 0a2a
    0x00000f0: b600 dc3a 0b19 0bbb 001f 591c 1db7 0022
    0x0000100: 04b6 00e0 0336 0c15 0c19 0abe a200 2119
    0x0000110: 0a15 0c32 3a0d 190b 1c15 0c1d b800 e619
    0x0000120: 0db8 00ea b600 ee84 0c01 a7ff dd19 09b0
    0x0000130:                                        
  Stackmap Table:
    same_frame(@32)
    append_frame(@95,Integer,Object[#79])
    same_frame(@147)
    append_frame(@207,Integer)
    full_frame(@232,{Object[#2],Object[#263],Integer,Integer,Object[#192],Object[#265],Integer,Integer,Integer,Object[#132]},{})
    append_frame(@263,Object[#266],Object[#41],Integer)
    same_frame(@301)
 
    at net.minecraft.client.world.ClientWorld.lambda$new$0(ClientWorld.java:99) ~[?:?] {re:classloading,xf:OptiFine:default}
    at net.minecraft.world.World.<init>(World.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.client.world.ClientWorld.<init>(ClientWorld.java:97) ~[?:?] {re:classloading,xf:OptiFine:default}
    at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:347) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SJoinGamePacket.java:71) ~[?:?] {re:classloading}
    at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SJoinGamePacket.java:13) ~[?:?] {re:classloading}
    at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[?:?] {re:classloading,xf:OptiFine:default}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
    at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
    at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.client.main.Main.main(SourceFile:155) ~[ForgeOptiFine%201.14.4.jar:?] {re:classloading}
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232] {}
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232] {}
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232] {}
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232] {}
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.1.109.jar:28.1] {}
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}
```
I tried to disable bytecode verification with `-noverify` JVM argument... and it worked. I got an
```
[Client thread/ERROR] [net.minecraftforge.fml.network.simple.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake
```
errors ([full log](https://gist.github.com/Nik-mmzd/f54c6e30084e21aa7d06c223a6e65eef)) on world joining, **but Minecraft continued working and [I was able to install some mods, shaders, textures](https://cdn.discordapp.com/attachments/384096341699330050/660515542456860673/file_412.jpg)**.

So, is it possible to make OptiFine run with Forge from classpath without these hacks?

**Comment by sp614x** [comment]
OptiFine is not designed to run in classpath with Forge 1.14, the errors are normal.
