### ISSUE TITLE
Game crashes with Optifine L5 1.8.9

### ISSUE THREAD

**Issue by spencerpha** [sp614x/optifine#3192]
I played Forge with and without Optifine, and the game crashes with Optifine. Here's the crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LabyModCoreMod (LabyMod-3.jar)
  Glint Colorizer ([1.8.9] GlintColorizer - 1.0.jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  FMLLoadingPlugin (Frames+ 2.0 BETA Build 16 [1.8.9].jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/30/19 5:24 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.entity.RendererLivingEntity.field_77045_g from class net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom
	at net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom.<init>(LayerMooshroomMushroom.java:36)
	at net.minecraft.client.renderer.entity.RenderMooshroom.<init>(SourceFile:14)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:152)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom.<init>(LayerMooshroomMushroom.java:36)
	at net.minecraft.client.renderer.entity.RenderMooshroom.<init>(SourceFile:14)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:152)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 344499240 bytes (328 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	Glint-Colorizer{1.0} [Glint Colorizer] (minecraft.jar) 
	UCH	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCH	wingsmod{1.2} [Wings Mod] ([1.8.9] Wings Mod-1.2.jar) 
	UCH	framesplus{2.0} [Frames+] (Frames+ 2.0 BETA Build 16 [1.8.9].jar) 
	UCH	labymod{3.5.7} [LabyMod] (LabyMod-3.jar) 
	UCH	skinchanger{2.0.0} [SkinChanger] (SkinChanger-2.0.0-SNAPSHOT.jar) 
	UCH	texfix{4.0} [TextureFix] (TexFix+V-1.8.9-4.0.jar) 
	Loaded coremods (and transformers): 
LabyModCoreMod (LabyMod-3.jar)
  net.labymod.core.asm.LabyModTransformer
Glint Colorizer ([1.8.9] GlintColorizer - 1.0.jar)
  me.powns.glintcolorizer.asm.itemrender.RenderItemTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
FMLLoadingPlugin (Frames+ 2.0 BETA Build 16 [1.8.9].jar)
  io.framesplus.forge.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !Dynamic Duo Rose Gold.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4350 Quad-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by asbyth** [comment]
this is an issue with Frames+ and L5 not being compatible, we (frames+ devs) are already aware of it and plan on fixing it sometime soon

**Comment by asbyth** [comment]
update on this, the issue *isnt* Frames+ but rather the Old Animations mod you're using, which can be fixed if you update to v2.6.3
