### ISSUE TITLE
[1.10.2] Forge with Optifine throw an exception when right click on bed block

### ISSUE THREAD

**Issue by SteveKunG** [sp614x/optifine#324]
Forge : 1.10.2-12.18.2.2124
Optifine : preview_OptiFine_1.10.2_HD_U_D3_pre

`[OptiFine] [WARN] *** Exception outside of method ***
[OptiFine] [WARN] Method deactivated: public boolean net.minecraft.block.Block.isBed(net.minecraft.block.state.IBlockState,net.minecraft.world.IBlockAccess,net.minecraft.util.math.BlockPos,net.minecraft.entity.Entity)

[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: java.lang.NullPointerException
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at Reflector.callBoolean(Reflector.java:352)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.renderer.entity.RenderManager.func_180597_a(RenderManager.java:283)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:703)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:01:43] [Client thread/INFO] [STDERR/]: [Reflector:handleException:939]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by sp614x** [comment]
Fixed, coming in next preview D3.
