### ISSUE TITLE
Error during launch of the game

### ISSUE THREAD

**Issue by ItalianGamer3** [sp614x/optifine#3279]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 13/02/20 18.58
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.renderer.entity.EntityRendererManager.validateRendererExistence()V
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:50) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.postSidedRunnable(ClientModLoader.java:127) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2812/418942327.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:158) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2954/792215510.run(Unknown Source) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$2891/2133560802.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.1.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$401/1517758613.call(Unknown Source) [forge-1.15.2-31.1.1.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3077499088 bytes (2934 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.15.2_HD_U_G1_pre1_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.1.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.1
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotori_scala@2.13.1-build-6
	Mod List: 
		forge-1.15.2-31.1.1-client.jar Minecraft {minecraft@1.15.2 ENQUEUE_IMC}
		tubesreloaded-1.15.2-1.2.0.jar Tubes Reloaded {tubesreloaded@1.15.2-1.2.0 ENQUEUE_IMC}
		forge-1.15.2-31.1.1-universal.jar Forge {forge@31.1.1 ENQUEUE_IMC}
		UndergroundMaterials-1.15.x-1.3.2.jar Underground Materials {undermat@1.3.2 ENQUEUE_IMC}
		u_team_core-1.15.2-2.10.4.153.jar U Team Core {uteamcore@2.10.4.153 ENQUEUE_IMC}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 ENQUEUE_IMC}
		Xaeros_Minimap_20.3.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.3.0 ENQUEUE_IMC}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 ENQUEUE_IMC}
	Launched Version: 1.15.2-forge-31.1.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/[1.15.2]SonicoPack0.1.zip (incompatible)
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre1
	OptiFine Build: 20200213-173014
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.66
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
------
Already tried remove the resourcepack but nothing changed.

**Comment by asbyth** [comment]
1.15.2 isn't compatible with forge yet

**Comment by ItalianGamer3** [comment]
> 
> 
> 1.15.2 isn't compatible with forge yet

Ah,i didn't know,thank you 👍
