### ISSUE TITLE
No renderer registered for mekanism:flame

### ISSUE THREAD

**Issue by wanderingmage** [sp614x/optifine#3411]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/20/20 1:01 AM
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for mekanism:flame
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:228) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2-forge-31.1.0.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.0.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:228)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5263481864 bytes (5019 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 COMMON_SETUP}
		Mekanism-1.15.2-9.9.9.401.jar Mekanism {mekanism@9.9.9 COMMON_SETUP}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 COMMON_SETUP}
		MekanismTools-1.15.2-9.9.9.401.jar Mekanism: Tools {mekanismtools@9.9.9 COMMON_SETUP}
		MekanismAdditions-1.15.2-9.9.9.401.jar Mekanism: Additions {mekanismadditions@9.9.9 COMMON_SETUP}
		Xaeros_Minimap_20.1.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.1.0 COMMON_SETUP}
		XaerosWorldMap_1.5.4_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.4 COMMON_SETUP}
		MekanismGenerators-1.15.2-9.9.9.401.jar Mekanism: Generators {mekanismgenerators@9.9.9 COMMON_SETUP}
		Hwyla-forge-1.10.7-B71_1.15.1.jar Waila {waila@version COMMON_SETUP}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 COMMON_SETUP}
	Launched Version: 1.15.2-forge-31.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre5
	OptiFine Build: 20200219-183028
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.19
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

Turned over crash info to Mekanism as well.

**Comment by YhvrWasTaken** [comment]
I thought the 1.15 previews didn't support Forge yet?

**Comment by wanderingmage** [comment]
Didn't see that in the changelog. I'll just have to be patient.
