### ISSUE TITLE
SmartAnimations (maybe) bug?

### ISSUE THREAD

**Issue by uAliFurkanY** [sp614x/optifine#3412]
I have no idea what this error is but it IS caused by optifine.
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 21.02.2020 22:02
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)
	at dqn.a(GameRenderer.java:684)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)

-- Affected level --
Details:
	All players: 1 total; [dqb['AliFurkanY'/109513, l='MpServer', x=70.10, y=63.35, z=-15.91]]
	Chunk stats: Client Chunk Cache: 729, 484
	Level dimension: minecraft:the_nether
	Level name: MpServer
	Level seed: 5596966700267923211
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (80,65,-128), Chunk: (at 0,4,0 in 5,-8; contains blocks 80,0,-128 to 95,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 86976358 game time, 93971441 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:639)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1027793120 bytes (980 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2-OptiFine_HD_U_G1_pre7
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 520 GL version 4.5.0 - Build 25.20.100.6518, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art, file/VanillaTweaks_r298628.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
	OptiFine Build: 20200221-181745
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6518
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4
```

**Comment by Brottweiler** [comment]
Yeah I just had this crash and went here to report it. 

```
[21:28:31] [main/FATAL]: Unreported exception thrown!
java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.set(BitSet.java:445) ~[?:?]
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38) ~[minecraft.jar:?]
	at drd.a(OverlayRenderer.java:80) ~[minecraft.jar:?]
	at drd.a(OverlayRenderer.java:34) ~[minecraft.jar:?]
	at dqn.renderHand(GameRenderer.java:602) ~[minecraft.jar:?]
	at dqn.a(GameRenderer.java:543) ~[minecraft.jar:?]
	at dqn.a(GameRenderer.java:1002) ~[minecraft.jar:?]
	at dqn.a(GameRenderer.java:684) ~[minecraft.jar:?]
	at dbn.d(SourceFile:989) ~[minecraft.jar:?]
	at dbn.d(SourceFile:619) [minecraft.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [minecraft.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2/21/20, 9:28 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.base/java.util.BitSet.set(BitSet.java:445)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)
	at dqn.a(GameRenderer.java:684)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.BitSet.set(BitSet.java:445)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)

-- Affected level --
Details:
	All players: 85 total; [dqb['Brottweiler'/926084, l='MpServer', x=-2.30, y=105.00, z=20.41], dqc['DespisedLove'/1765846, l='MpServer', x=-13.14, y=50.63, z=-1.34], dqc['Zaellack'/1735884, l='MpServer', x=1.83, y=10.07, z=16.33], dqc['The27thElement'/1865901, l='MpServer', x=4.06, y=64.00, z=-19.31], dqc['Sugarpixie4'/1516718, l='MpServer', x=0.40, y=67.01, z=-5.82], dqc['Peterms'/1678874, l='MpServer', x=10.67, y=29.00, z=-7.45], dqc['Spartanicaurdon'/1850165, l='MpServer', x=-0.89, y=31.00, z=4.52], dqc['GYZ1'/1765905, l='MpServer', x=-5.69, y=136.00, z=-4.17], dqc['Almanii04'/1862750, l='MpServer', x=1.59, y=80.75, z=-7.78], dqc['PettoYT'/1807935, l='MpServer', x=-3.46, y=16.03, z=-15.33], dqc['Dave_King'/1852143, l='MpServer', x=-3.25, y=88.66, z=-21.73], dqc['BukeBeven'/1841645, l='MpServer', x=-3.53, y=113.00, z=6.61], dqc['GargoyleKing'/442700, l='MpServer', x=-8.39, y=65.00, z=-9.32], dqc['Dolphinone'/1768298, l='MpServer', x=3.81, y=36.00, z=13.50], dqc['GalenCreeper'/1024043, l='MpServer', x=-8.72, y=93.00, z=-5.96], dqc['mk7master'/1861827, l='MpServer', x=10.75, y=15.99, z=3.97], dqc['babyhippo1020'/1862741, l='MpServer', x=-2.19, y=50.00, z=-16.59], dqc['MM994'/555375, l='MpServer', x=-8.25, y=72.00, z=5.22], dqc['af5-877480860fe2'/926085, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['6a6-5e420755866d'/1862742, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['6db-e3dcd689cf5b'/1859088, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['0b0-65c062f5a2ce'/1776270, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['5bf-5a3297099360'/1793206, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['685-99bad3599173'/1765847, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['71a-01f8f9caeedf'/740602, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['b86-9b90bf307b5e'/1768299, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['1b1-76fa9363e95d'/1024044, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['ade-915295a13966'/1765906, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['21e-f5a8cd31416a'/1839255, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['c1e-6624add3d5fb'/555376, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['b94-c1a805006dec'/1024562, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['68c-711476b2c43d'/1708570, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['6c8-8fd8073b56f3'/1865879, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['a01-fc283f9e2b21'/1856619, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['aa4-e8c4a8a721b9'/759504, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['a9c-be047a2080f3'/1850166, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['fa6-6a0ef50bf3f2'/1516719, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['9a1-a97078c358f9'/636259, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['dcb-9caa549ad8e8'/1735885, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['3dc-1ac2d4422f0e'/1865985, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['3e3-c6ea67c8b008'/466480, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['fd2-35ea87224a50'/1865667, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['4e8-b47a922a43be'/618235, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['021-163411adbcea'/1332296, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['643-f6be8bc6ca6f'/771149, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['6c0-90821882b89a'/1759089, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['a61-0b7e1f09a280'/1862751, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['ac8-01966114faf5'/862505, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['0ba-45c805c1f86c'/1841646, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['60d-8e80ea34efd8'/1865891, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['c35-cacc4e27a37d'/1852144, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['076-91403ac7a513'/1031712, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['55c-a1721c4b65be'/442701, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['832-7bc097f1b55a'/1419193, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['dc9-423e975f52a5'/1861828, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['ebf-1804e6203509'/1678875, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['140-f102e327a420'/804540, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['5c1-aa70ae363e7f'/1550161, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['53b-9076e954f037'/905590, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['7d7-6f5e191b767f'/711658, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['ed3-ff3ccf0b2d16'/907753, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['7a8-3c92c6b7298d'/1023566, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['9f4-27fa5186d611'/1807936, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['f40-9ec05ae00452'/1377815, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['546-bd94a8cca094'/1865902, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['d00-b53062f2ec81'/635368, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['f5f-dd0a66b1c2e1'/1847482, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['ce2-a9fc9af59a56'/1029693, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['1c0-65dea978fb18'/770024, l='MpServer', x=0.00, y=67108863.97, z=0.00], dqc['YOU_DIED'/636258, l='MpServer', x=6.93, y=29.00, z=13.32], dqc['nigges60'/771148, l='MpServer', x=-8.73, y=65.01, z=-9.90], dqc['OCNs_OMEN'/1759088, l='MpServer', x=8.27, y=64.26, z=-2.80], dqc['bonkerspigeon'/1859087, l='MpServer', x=-6.36, y=120.00, z=9.96], dqc['JakePauler11'/1419192, l='MpServer', x=-6.40, y=58.00, z=-4.70], dqc['Bxldmrr'/1776269, l='MpServer', x=6.97, y=15.00, z=9.22], dqc['andreanovemaggio'/862504, l='MpServer', x=-1.28, y=88.04, z=-16.62], dqc['diego_a_001'/740601, l='MpServer', x=-4.78, y=85.00, z=7.48], dqc['elnitido'/1031711, l='MpServer', x=-2.26, y=7.39, z=3.67], dqc['Dertical'/1793205, l='MpServer', x=-8.50, y=120.00, z=-5.63], dqc['skulltrooper2009'/1377814, l='MpServer', x=9.64, y=71.17, z=2.83], dqc['DaegunDistrbd'/1865890, l='MpServer', x=-4.69, y=106.00, z=20.64], dqc['Javier_L_S'/1839254, l='MpServer', x=-4.01, y=81.01, z=-18.34], dqc['eb1-8458d2ac062c'/1877786, l='MpServer', x=5.50, y=6.27, z=22.50], dqc['Joel_'/1865984, l='MpServer', x=-10.31, y=106.00, z=23.06], dqc['0f7-b54b457bc387'/1878854, l='MpServer', x=9.50, y=27.28, z=8.50]]
	Chunk stats: Client Chunk Cache: 18225, 961
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (49,11,0), Chunk: (at 1,0,0 in 3,0; contains blocks 48,0,0 to 63,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 17612 game time, 16000 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:a86e191:320) <- SportPaper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:639)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.5.4-arch1-1
	Java Version: 13.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 350565656 bytes (334 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 4
	JVM Flags: 4 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.59, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art, file/Developer Art+ [v1.3.3] (1.14 – 1.16).zip, file/Brott Box, file/OLEDcraft.zip, file/Microsoft Windows Cave Sounds
	Current Language: §eEnglish (§bColor§e)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
	OptiFine Build: 20200221-181745
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 440.59
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
#@!@# Game crashed! Crash report saved to: #@!@# /home/brott/.local/share/multimc/instances/Latest/.minecraft/crash-reports/crash-2020-02-21_21.28.32-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by sp614x** [comment]
Fixed, coming in pre8.
