### ISSUE TITLE
When entering a nether portal game crashed (1.15.2 pre7)

### ISSUE THREAD

**Issue by martijnpu** [sp614x/optifine#3429]
When entering a nether portal the game just crash with the following Crash report.
```---- Minecraft Crash Report ----

// Uh... Did I do that?

Time: 22-2-20 14:45
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)
	at dqn.a(GameRenderer.java:684)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)

-- Affected level --
Details:
	All players: 1 total; [dqb['martijnpu'/206, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: Client Chunk Cache: 361, 64
	Level dimension: minecraft:the_nether
	Level name: MpServer
	Level seed: 3882366447369343328
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 28 game time, 28 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:adee7bd:1472) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:639)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1169676416 bytes (1115 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2-OptiFine_HD_U_G1_pre7
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 530 GL version 4.6.0 - Build 26.20.100.7755, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
	OptiFine Build: 20200221-181745
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7755
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 4
```

**Comment by sp614x** [comment]
Fixed, coming in pre8.
