### ISSUE TITLE
[1.15.2 pre-7] game crashes due to smart animations

### ISSUE THREAD

**Issue by burgerguy** [sp614x/optifine#3433]
Running with Java 8 OpenJ9 and Shenandoah GC.

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/22/20 3:38 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)
	at dqn.a(GameRenderer.java:684)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)

-- Affected level --
Details:
	All players: 1 total; [dqb['burgerdud3'/2240675, l='MpServer', x=31583.96, y=104.43, z=24231.86]]
	Chunk stats: Client Chunk Cache: 529, 316
	Level dimension: minecraft:the_nether
	Level name: MpServer
	Level seed: -2236854711765881049
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 32710 game time, 417824710 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:639)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_232, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20191106_498 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc1
JCL      - 3504dff40aa based on jdk8u232-b09), Eclipse OpenJ9
	Memory: 733905208 bytes (699 MB) / 1636433920 bytes (1560 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-openj9\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -Xms1536m -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:+AlwaysPreTouch
	Launched Version: 1.15.2-OptiFine_HD_U_G1_pre7
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art, file/VanillaTweaks_r875756.zip, file/BetterBow.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
	OptiFine Build: 20200221-181745
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GT 1030/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by asbyth** [comment]
this was just fixed as mentioned in the 5 other issues about this, coming in pre8 whenever that releases

**Comment by sp614x** [comment]
Fixed, coming in pre8.
