### ISSUE TITLE
[1.8.9 L5][Random Mobs] ANY .png file inside 'mob' folder causes Horses to implode

### ISSUE THREAD

**Issue by TBlazeWarriorT** [sp614x/optifine#3474]
OptiFine 1.8.9 HD U L5.

Having any .png file with proper naming inside mob folder randomly causes Minecraft to fail to load /render Horse textures. This causes Minecraft to spam the MC logs 20 times per second, very bad.
For example, "\resourcepacks\HorseTest\assets\minecraft\mcpatcher\mob\squid2.png" will trigger the bug, even if squid.properties doesn't exist. This is not the only way to trigger this bug, but the easiest.

Resource Pack for Reproducing it:
[OptifineHorseBug.zip](https://github.com/sp614x/optifine/files/4263910/OptifineHorseBug.zip)
Test resource pack off:
![2020-02-27_16 50 05](https://user-images.githubusercontent.com/25572454/75482743-26384b00-5984-11ea-8924-dcf84c3b7baf.png)
Test resource pack on:
![2020-02-27_16 49 56](https://user-images.githubusercontent.com/25572454/75482704-1a4c8900-5984-11ea-85eb-ce2629e13551.png)
![image](https://user-images.githubusercontent.com/25572454/75482791-423bec80-5984-11ea-9fe3-ec82f614127c.png)
`java.lang.NullPointerException
	at net.optifine.RandomEntities.getTextureLocation(RandomEntities.java:168) ~[RandomEntities.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) ~[bmj.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110776_a(Render.java:116) ~[biv.class:?]
	at net.minecraft.client.renderer.entity.Render.func_180548_c(Render.java:109) ~[biv.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_77036_a(RendererLivingEntity.java:349) ~[bjl.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:236) [bjl.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50) [bjo.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:16) [bjo.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:402) [biu.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:356) [biu.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:323) [biu.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:870) [bfr.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1763) [bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580) [bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1372) [bfk.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

This makes using random entities in any world with horses basically not viable, can cause many megabytes/gigabytes of mc logs, and completely ruins horses. Should be fixed whenever possible. Thanks.

**Comment by Futuremappermydud** [comment]
dont use 1.8.9??? there are way later versions that are the same

**Comment by TBlazeWarriorT** [comment]
> dont use 1.8.9??? there are way later versions that are the same

1.8.9. is still supported, therefore I should still be reporting bugs. You have the right not to use it, I have the right to.
The resource pack I make is compatible with every version from 1.8.9 to 1.14 (soon 1.15), and I'd like to keep it this way.

**Comment by TBlazeWarriorT** [comment]
Small status update,
java.lang.NullPointerException at net.optifine.RandomEntities.getTextureLocation(RandomEntities.java:168)
^ this seems to be caused by getHorsePath() returning null and getTextureLocation not knowing how to handle the null or something
should actually be easy to fix next time 1.8 optifine updates, and hopefully 1.8 does update, L5 is elo hell
For now I'm using a mod to fix this lol

**Comment by Zordlan** [comment]
> dont use 1.8.9??? there are way later versions that are the same

1.8.9 is the main version people use for PVP. (dont yell at me, i know about 1.7.10, but hypixel runs on 1.8.9) People like having their game working on the version they play on.

**Comment by rbrick** [comment]
The issue appears to be due to incorrect variables being set via reflection.

The RandomEntities class has these two lines:
```java
 public static final String[] HORSE_TEXTURES = (String[])((String[])ReflectorRaw.getFieldValue((Object)null, EntityHorse.class, String[].class, 0));
    public static final String[] HORSE_TEXTURES_ABBR = (String[])((String[])ReflectorRaw.getFieldValue((Object)null, EntityHorse.class, String[].class, 1));
```

Which grab the fields from indexes `0` and `1`

However, in 1.8.9 those are the horse armor textures & abbreviations.

EntityHorse.java:
```java
 public static final String[] horseArmorTextures = new String[]{null, "textures/entity/horse/armor/horse_armor_iron.png", "textures/entity/horse/armor/horse_armor_gold.png", "textures/entity/horse/armor/horse_armor_diamond.png"};
    public static final String[] HORSE_ARMOR_TEXTURES_ABBR = new String[]{"", "meo", "goo", "dio"};
```

The first element in `horseArmorTextures` is `null`, and the first element in `HORSE_ARMOR_TEXTURES_ABBR ` is an empty string.

In Java, calling `String#startsWith` with an empty string will `return true`

Since the first element of `horseArmorTextures` is `null`, the horse path will be set to null and there is no null check, winding up with a method call on a null variable, producing the NullPointerException.

**Comment by ThePromisedLAN** [comment]
Still able to replicate this in OptiFine HD U L6 pre1.

**Comment by rbrick** [comment]
> Still able to replicate this in OptiFine HD U L6 pre1.
> 
> https://cdn.discordapp.com/attachments/504411466921672704/766511694573731840/unknown.png

Can confirm the offending code is still present in the latest pre-release. Hopefully, it'll be resolved in an upcoming release

**Comment by asbyth** [comment]
bumping rbrick's comment to put into a much simpler message, `RandomEntities` fields `HORSE_TEXTURES` & `HORSE_TEXTURES_ABBR` need to have the indexes as `2` and `3`, instead of `0` and `1`. example in bytecode can be seen here.
![image](https://user-images.githubusercontent.com/36578995/98271419-ed626400-1f5d-11eb-9539-fb032e1b862e.png)

**Comment by ThePromisedLAN** [comment]
Any update on this in 1.8.9_HD_U_M5_pre1?

**Comment by sp614x** [comment]
Coming in M5_pre2
