### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by YourCompanionCube** [sp614x/optifine#3507]
when launching minecraft after forge does all its loading and then the mojang logo appears, once the progress bar finishes it crashes with this error log:

Time: 3/6/20 1:16 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.renderer.entity.EntityRendererManager.validateRendererExistence()V
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:50) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.postSidedRunnable(ClientModLoader.java:127) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2841/1713876122.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:158) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$3017/930727109.run(Unknown Source) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$2947/1624687345.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.18.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$412/61814127.call(Unknown Source) [forge-1.15.2-31.1.18.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 866542648 bytes (826 MB) / 3074949120 bytes (2932 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre9.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.18-client.jar Minecraft {minecraft@1.15.2 ENQUEUE_IMC}
		ClientTweaks_1.15.2-4.1.0.jar Client Tweaks {clienttweaks@4.1.0 ENQUEUE_IMC}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 ENQUEUE_IMC}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 ENQUEUE_IMC}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 ENQUEUE_IMC}
		mappy-1.15.2-1.0.0.jar Mappy {mappy@1.0.0 ENQUEUE_IMC}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 ENQUEUE_IMC}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 ENQUEUE_IMC}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 ENQUEUE_IMC}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 ENQUEUE_IMC}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 ENQUEUE_IMC}
		BetterSprinting-1.15.2-v3.1.0.jar Better Sprinting {bettersprinting@3.1.0 ENQUEUE_IMC}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 ENQUEUE_IMC}
	Launched Version: forge-31.1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 7900 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/NoPumpkinBlur-rv1.2.zip (incompatible), file/Xray_Ultimate_1.15_v3.3.2.zip
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre9
	OptiFine Build: 20200223-095745
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: AMD Radeon HD 7900 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by asbyth** [comment]
forge and optifine arent compatible yet

**Comment by sp614x** [comment]
Not compatible with Forge 1.15.2 yet.
