### ISSUE TITLE
Crashes at the loading screen. Please help.

### ISSUE THREAD

**Issue by TheKamian** [sp614x/optifine#3542]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 15/03/20 4:37 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.renderer.entity.EntityRendererManager.validateRendererExistence()V
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:50) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.postSidedRunnable(ClientModLoader.java:127) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2903/1099087144.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:158) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$3135/329767518.run(Unknown Source) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$3074/1168953476.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.1.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$410/2082678778.call(Unknown Source) [forge-1.15.2-31.1.1.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1507527080 bytes (1437 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre9.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.1.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.1
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.1-client.jar Minecraft {minecraft@1.15.2 ENQUEUE_IMC}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 ENQUEUE_IMC}
		forge-1.15.2-31.1.1-universal.jar Forge {forge@31.1.1 ENQUEUE_IMC}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 ENQUEUE_IMC}
		AdvancedSkinCustomization-2.8.2.jar Advanced Skin Customization {advskinmod@2.8.2 ENQUEUE_IMC}
		TerraForged-1.15.2-0.0.4.jar TerraForged {terraforged@0.0.4 ENQUEUE_IMC}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 ENQUEUE_IMC}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 ENQUEUE_IMC}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 ENQUEUE_IMC}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version ENQUEUE_IMC}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 ENQUEUE_IMC}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 ENQUEUE_IMC}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 ENQUEUE_IMC}
	Launched Version: 1.15.2-forge-31.1.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre9
	OptiFine Build: 20200223-095745
	Render Distance Chunks: 20
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by ZitroDev** [comment]
Hi! I have the same issue. Could you resolve it sp614x?

**Comment by ZitroDev** [comment]
---- Minecraft Crash Report ----
// Oops.

Time: 3/15/20 3:15 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.renderer.entity.EntityRendererManager.validateRendererExistence()V
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:50) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.postSidedRunnable(ClientModLoader.java:127) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2831/1434864259.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:158) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2985/22950337.run(Unknown Source) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$2938/533356347.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.17.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/1583020257.call(Unknown Source) [forge-1.15.2-31.1.17.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.19.0-kali5-amd64
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5169654424 bytes (4930 MB) / 5771362304 bytes (5504 MB) up to 5771362304 bytes (5504 MB)
	CPUs: 4
	JVM Flags: 9 total; -Xmn128M -Xmx5500M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.17.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.17.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.17.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.17.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre9.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.17.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.17
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.17-client.jar Minecraft {minecraft@1.15.2 ENQUEUE_IMC}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 ENQUEUE_IMC}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 ENQUEUE_IMC}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 ENQUEUE_IMC}
		forge-1.15.2-31.1.17-universal.jar Forge {forge@31.1.17 ENQUEUE_IMC}
		justenoughbeacons-1.2.jar Just Enough Beacons {justenoughbeacons@1.2 ENQUEUE_IMC}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 ENQUEUE_IMC}
		tl_skin_cape_1.15.2-1.8.jar TLSkinCape {tlskincape@1.6 ENQUEUE_IMC}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 ENQUEUE_IMC}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 ENQUEUE_IMC}
		JustEnoughCalculation-1.15.2-3.6.1.jar Just Enough Calculation {jecalculation@3.6.1 ENQUEUE_IMC}
	Launched Version: Forge 1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa DRI Intel(R) Sandybridge Mobile  GL version 3.0 Mesa 19.1.4, Intel Open Source Technology Center
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Faraway.zip (incompatible)
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 4x Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre9
	OptiFine Build: 20200223-095745
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 19.1.4
	OpenGlRenderer: Mesa DRI Intel(R) Sandybridge Mobile 
	OpenGlVendor: Intel Open Source Technology Center
	CpuCount: 4

**Comment by Quavelen** [comment]
@TheKamian, and @ZitroDev -
Both of you need to pay attention to the changelogs next time. None of the 1.15.2 OptiFine previews are compatible with Forge, it clearly states this. You can find it on the website, or in the discord.

![image](https://user-images.githubusercontent.com/19168008/76700618-36089c80-66b1-11ea-8efe-7496225f50a3.png)

![image](https://user-images.githubusercontent.com/19168008/76700626-4b7dc680-66b1-11ea-88b9-bcb1d237501f.png)

**Comment by sp614x** [comment]
Not compatible with Forge yet.
