### ISSUE TITLE
[Bug] game instantly crashes with other mods

### ISSUE THREAD

**Issue by Inonedn** [sp614x/optifine#3663]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/2/20 8:24 PM
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for buzzierbees:honey_slime
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.27.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$423/1172417096.call(Unknown Source) [forge-1.15.2-31.1.27.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$423/1172417096.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2082575632 bytes (1986 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre13.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.27.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.27
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.27-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 COMMON_SETUP}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 COMMON_SETUP}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 COMMON_SETUP}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 COMMON_SETUP}
		buzzierbees-1.3.jar Buzzier Bees {buzzierbees@1.3 COMMON_SETUP}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 COMMON_SETUP}
		lycanitesmobs-1.15.2-2.2.3.0-aberrant16.jar Lycanites Mobs {lycanitesmobs@1.0 COMMON_SETUP}
		Upgrade-Aquatic-1.15.2-v1.5.0-TEST-v2.jar Upgrade Aquatic {upgrade_aquatic@1.5.0 COMMON_SETUP}
		Neat+1.6-20.jar Neat {neat@1.6-20 COMMON_SETUP}
		Xaeros_Minimap_20.5.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.1 COMMON_SETUP}
		TerraForged-1.15.2-0.0.4.jar TerraForged {terraforged@0.0.4 COMMON_SETUP}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 COMMON_SETUP}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 COMMON_SETUP}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 COMMON_SETUP}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 COMMON_SETUP}
		WitherSkeletonTweaks-1.15.1-4.0.0 (1).jar Wither Skeleton Tweaks {wstweaks@4.0.0 COMMON_SETUP}
		The-Endergetic-Expansion-1.15.2-v1.2.5.jar The Endergetic Expansion {endergetic@1.2.1 COMMON_SETUP}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c COMMON_SETUP}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 COMMON_SETUP}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 COMMON_SETUP}
		endercompass-2.0.jar Ender Compass {endercompass@2.0 COMMON_SETUP}
		forge-1.15.2-31.1.27-universal.jar Forge {forge@31.1.27 COMMON_SETUP}
		Quark-r2.1-228.jar Quark {quark@r2.1-228 COMMON_SETUP}
		classicbar-3.0.2.jar Classic Bar {classicbar@3.0.2 COMMON_SETUP}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 COMMON_SETUP}
	Launched Version: 1.15.2-forge-31.1.27
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 530 GL version 4.5.0 - Build 22.20.16.4836, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre13
	OptiFine Build: 20200401-232147
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 22.20.16.4836
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by asbyth** [comment]
read changelogs, forge isnt compatible with optifine yet

**Comment by HiItsDevin** [comment]
OptiFine is not yet forge compatible.

**Comment by DaveyL2013** [comment]
Try using [OptiForge](https://www.curseforge.com/minecraft/mc-mods/optiforge), if it still doesn't work [report the issue to them](https://github.com/ZekerZhayard/OptiForge/issues)

**Comment by sp614x** [comment]
Should be fixed in latest preview.
