### ISSUE TITLE
Optifine 1.13.2 Crashes Instantly

### ISSUE THREAD

**Issue by JollyFunTime** [sp614x/optifine#3754]
Hello, Optifine 1.13.2 F5 has been crashing for the last 2 days or so. I don't know the whats causing this, but I tried on #support on Discord but still there wasnt an answer.
Here is the crash report:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/18/20 11:20 AM
Description: Generating mipmaps for frame

java.lang.RuntimeException: Invalid image size: NativeImage[RGBA 16x16@723336688N], sprite: TextureAtlasSprite{name='minecraft:missingno', frameCount=0, rotated=false, x=0, y=0, height=32, width=32, u0=0.0, u1=0.0, v0=0.0, v1=0.0}
	at ddm.b(TextureAtlasSprite.java:157)
	at ddm.a(TextureAtlasSprite.java:645)
	at ddl.b(TextureMap.java:283)
	at ddl.a(TextureMap.java:121)
	at dfc.a(ModelBakery.java:473)
	at dfd.a(SourceFile:24)
	at vh.a(SourceFile:118)
	at cft.am(SourceFile:507)
	at cft.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ddm.b(TextureAtlasSprite.java:157)

-- Frame being iterated --
Details:
	Frame sizes: 16x16
Stacktrace:
	at ddm.a(TextureAtlasSprite.java:645)
	at ddl.b(TextureMap.java:283)
	at ddl.a(TextureMap.java:121)
	at dfc.a(ModelBakery.java:473)
	at dfd.a(SourceFile:24)
	at vh.a(SourceFile:118)
	at cft.am(SourceFile:507)

-- Initialization --
Details:
Stacktrace:
	at cft.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 453578056 bytes (432 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-OptiFine_HD_U_F5
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Faithful+1.13.2-rv2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.13.2_HD_U_F5
	OptiFine Build: 20191204-141645
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

----------------------------------------------------
Cpu : i5 8300H
Gpu: 1050 ti 4GB
Installed using official optifine launcher
and running using official minecraft launcher

**Comment by JollyFunTime** [comment]
i forgot to mention this but, Normal Minecraft runs normally

**Comment by Naworm** [comment]
I am impacted too

**Comment by Naworm** [comment]
Just do not use latest version, working for me : 
http://optifine.net/adloadx?f=OptiFine_1.13.2_HD_U_E7.jar
