### ISSUE TITLE
[1.15.2 Pre16/17 Forge] Crash on Startup (Fresh Install)

### ISSUE THREAD

**Issue by Bilibox** [sp614x/optifine#3891]
## Description of Issue
Upon loading, when Forge loads Optifine it crashes

## Steps to Reproduce
1. Install Minecraft
2. Install Forge 31.1.63
3. Put optifine in the mods folder
4. Launch Forge Version

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre16
OptiFine 1.15.2 HD U G1 pre17

## Installation Method
Tried putting jar in mods folder
Tried extracting to mods folder via installer

## Fabric/Forge Version
Forge 1.15.2 - 31.1.63
Forge 1.15.2 - 31.1.79

## Log Files/Crash Reports
No Crash Reports Generated
https://pastebin.com/2ADjpzkH - Debug Log (Placing Jar in mods folder)
https://pastebin.com/DydNHvws - Debug Log (Extracting Jar via Installer into mods folder)

## Prior Testing
This issue only happens with Optifine and Forge (with and without mods)
It works using Fabric with Optifabric (With other mods)
It also works via standalone install

## Additional Information
I did the exact same setup on my laptop and that worked flawlessly. I'm unsure why it's not loading via my desktop.
A few people on the discord have had this issue

Windows 10 Version 2004
Running with built in Java
Intel i-5 3570
GTX 970

**Comment by JAD3N** [comment]
I'm having this exact issue. The issue only appears on Windows 10, but if I use the exact same files on Ubuntu it works fine. I've tried a fresh installation of Optifine + Minecraft on Windows 10 and still encounter this as mentioned.

**Comment by sp614x** [comment]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
    	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
    	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
    	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
    	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
    Caused by: java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
    	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/295055909.call(Unknown Source)
    	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
    	... 4 more
    Caused by: java.lang.NoSuchMethodError: net.optifine.CrashReporter.onCrashReport(Lnet/minecraft/crash/CrashReport;Lnet/minecraft/crash/CrashReportCategory;)V
    	at net.minecraft.crash.CrashReport.func_71502_e(CrashReport.java:215)
    	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:414)
    	at net.minecraft.client.main.Main.main(SourceFile:129)
    	... 11 more

**Comment by sp614x** [comment]
The OptiFine patch for CrashReporter is not being applied.

**Comment by ZekerZhayard** [comment]
maybe fixed by this pr: https://github.com/MinecraftForge/MinecraftForge/pull/6600

**Comment by Bilibox** [comment]
Thanks @ZekerZhayard looks like it was pushed in 1.15.2-31.1.86, Tested in 31.2.0 w/ pre18 and seems to be working thanks!

I hadnt even thought that the symlinks were causing the problem but yes my Desktop has AppData symlink'd whereas my laptop doesn't.

Closing this issue out.
