### ISSUE TITLE
[1.15.2 pre16] Intermittent crash on SP world load

### ISSUE THREAD

**Issue by DuelMonster** [sp614x/optifine#3916]
## Description of Issue
Game crashes intermittently when loading a single player world.
Restarting the game and trying again will eventually let me in, but can take several retries.

Issue appears to be related to the Refined Storage mod and works fine without it.

## Steps to Reproduce
1. Load game
2. Enter single player world

## OptiFine Version
1.15.2_HD_U_G1_pre16

## Installation Method
Dropped the JAR into "mods" folder

## Fabric/Forge Version
- Forge: 31.1.77

## Other Installed Mods
<details><summary>Expand for mods list</summary>

```
AmbientSounds_v3.0.19_mc1.15.2.jar
BBOutlineReloaded-1.0.14-1.15.2-forge.jar
Bettersigns-1.0_v1.15.2.jar
caelus-FORGE-1.15.2-2.0-beta2.jar
ChunkNoGoByeBye-1.15.2-1.2.0.jar
ClientTweaks_1.15.2-4.1.2.jar
colytra-FORGE-1.15.2-3.0.jar
config-2-3.0.jar
doubledoors_1.15-2.0.jar
extradisks-1.15.1-1.2.jar
FpsReducer-mc1.15.2-1.15.jar
GameMenuModOption-1.15.2-1.2.jar
inventorysorter-1.15.2-17.0.0.jar
jei-1.15.2-6.0.0.4.jar
jmh_1.15.2-2.2.jar
journeymap-1.15.2-5.7.0b2.jar
KleeSlabs_1.15.2-8.0.0.jar
LightOverlay-4.6.1.jar
mcjtylib-1.15-4.1.0-beta.jar
Mekanism-1.15.2-9.10.5.418.jar
MekanismAdditions-1.15.2-9.10.5.418.jar
MekanismGenerators-1.15.2-9.10.5.418.jar
MekanismTools-1.15.2-9.10.5.418.jar
MinersAdvantage-1.15.2-1.6.6.26.jar
MixinBootstrap-1.0.3.jar
MoreMekanismOres-1.15.2-1.0.5.jar
MouseTweaks-2.13-mc1.15.1.jar
NetherPortalFix_1.15.2-6.0.2.jar
noautojump-1.15.2-1.jar
performant-1.15-2.10m.jar
Placebo-1.15.2-3.0.2.jar
randompatches-1.15.2-1.21.1.2.jar
refinedpipes-0.4.1.jar
 intermittently-1.8.3.jar
refinedstorageaddons-0.6.1.jar
StorageDrawers-1.15.2-7.0.2.jar
swingthroughgrass-1.15.2-1.4.0.jar
theoneprobe-1.15-2.0.2.jar
ToastControl-1.15.2-3.0.1.jar
torchmaster-2.1.1-rc0.jar
TrampleNoMore-1.15.2-1.0.2.jar
tubesreloaded-1.15.2-1.3.0c.jar
WitherSkeletonTweaks-1.15.1-4.0.0.jar
```
</details>

## Log Files/Crash Reports
https://gist.github.com/DuelMonster/91ca0f4be221762c7ac3c8e3ece8eb16

**Comment by naeqirelle2020** [comment]
@DuelMonster does this still occur in the latest preview?

**Comment by sp614x** [comment]
Crash with the DiskDriveBakedModel.

```
Caused by: java.lang.IllegalStateException: not enough data
	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.build(BakedQuadBuilder.java:124) ~[?:?] {re:classloading}
	at com.raoulvdberge.refinedstorage.render.model.TRSRBakedModel.func_200117_a(TRSRBakedModel.java:75) ~[?:1.8.3] {re:classloading}
	at com.raoulvdberge.refinedstorage.render.model.DiskDriveBakedModel$1.load(DiskDriveBakedModel.java:74) ~[?:1.8.3] {re:classloading}
	at com.raoulvdberge.refinedstorage.render.model.DiskDriveBakedModel$1.load(DiskDriveBakedModel.java:68) ~[?:1.8.3] {re:classloading}
```
