### ISSUE TITLE
[1.15.2 forge] occasionally crashes on right click

### ISSUE THREAD

**Issue by emkirsh** [sp614x/optifine#3945]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. play the game 
2. right click on something that does a thing, like a container or button
3. maybe it'll crash, maybe it wont

## OptiFine Version
1.15.2 HD U G1 pre16

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

I extracted it so the jar ends in _MOD and put that in the mods folder

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**
1.15.2-forge-31.1.77

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin.

Xaero's Minimap 20.11.0
Xaero's World Map 1.5.7
at the time, autofish-forge 1.15.2-1.7.jar was in the mods folder, but was inactive. I have since removed it but also zipped the optifine jar to disable it.

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/
[crash-2020-05-14_20.08.56-client.txt](https://github.com/sp614x/optifine/files/4635090/crash-2020-05-14_20.08.56-client.txt)
[crash-2020-05-14_20.34.58-client.txt](https://github.com/sp614x/optifine/files/4635091/crash-2020-05-14_20.34.58-client.txt)
[crash-2020-05-14_20.38.05-client.txt](https://github.com/sp614x/optifine/files/4635092/crash-2020-05-14_20.38.05-client.txt)

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

Because of the nature of this bug, and it being a crash, i can't capture it in action, but here's my F3 screen: 
![2020-05-15_11 04 15](https://user-images.githubusercontent.com/62123997/82065342-fdc70f80-969b-11ea-9a48-b7146ad1f799.png)
![2020-05-15_11 04 28](https://user-images.githubusercontent.com/62123997/82065354-015a9680-969c-11ea-9af5-420e75476e7a.png)
^^^^^^^^^^^^
this second one i tried doing as i pressed a button. it didn't cause a crash, so nothing extra helpful, but hey, at least it didn't crash this time. I'm sure it will next time though..

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
it doesn't happen when only forge is installed with other mods, and i don't think it happens with optifine as standalone wither. it only happens with they are both installed.
   - Only OptiFine, OptiFabric, and Fabric
       - i dont use fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
   - idk
- Does this happen in OptiFine standalone?
   - i dont think so
- Does this happen in Vanilla without OptiFine?
   - nooooooooo. or if it does, it certainly doesn't happen nearly as often.
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
      - no because it only happens when there's optifine with mods. not when the mods are alone.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine
          - no it doesn't. only when optifine is installed.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

I vaguely remember this happening in 1.14.4 when the optiforge support was in beta, as in when there were no release builds for that version.

Also, the error is always something about a number not being within the specified range.
- Examples
   - java.lang.IllegalArgumentException: The value 37914 is not in the specified inclusive range of 0 to 16383
   - java.lang.IllegalArgumentException: The value 26577 is not in the specified inclusive range of 0 to 16383
   - java.lang.IllegalArgumentException: The value 124707 is not in the specified inclusive range of 0 to 16383
   - java.lang.IllegalArgumentException: The value 31432 is not in the specified inclusive range of 0 to 16383

and there is always something about optifine in the crash report.

**Comment by sp614x** [comment]
java.lang.IllegalArgumentException: The value 37914 is not in the specified inclusive range of 0 to 16383
    	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1032) ~[commons-lang3-3.5.jar:3.5] {}
    	at net.minecraft.util.BitArray.func_219789_a(SourceFile:37) ~[?:?] {re:classloading}
    	at net.minecraft.util.palette.PalettedContainer.func_222643_a(PalettedContainer.java:121) ~[?:?] {re:classloading}
    	at net.minecraft.util.palette.PalettedContainer.func_222641_a(PalettedContainer.java:110) ~[?:?] {re:classloading}
    	at net.minecraft.world.chunk.ChunkSection.func_177484_a(ChunkSection.java:87) ~[?:?] {re:classloading,xf:OptiFine:default}
    	at net.minecraft.world.chunk.ChunkSection.func_222629_a(ChunkSection.java:78) ~[?:?] {re:classloading,xf:OptiFine:default}
    	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:250) ~[?:?] {re:classloading,xf:fml:xaerominimap:xaero_chunkclass}
    	at net.minecraft.world.World.func_180501_a(World.java:177) ~[?:?] {re:classloading,pl:accesstransformer:B}
    	at net.minecraft.client.world.ClientWorld.func_180501_a(ClientWorld.java:748) ~[?:?] {re:classloading,xf:OptiFine:default}
    	at net.minecraft.block.AbstractButtonBlock.func_226910_d_(SourceFile:117) ~[?:?] {re:classloading}
    	at net.minecraft.block.AbstractButtonBlock.func_225533_a_(SourceFile:111) ~[?:?] {re:classloading}
    	at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:401) ~[?:?] {re:classloading,xf:OptiFine:default}

**Comment by sp614x** [comment]
The crash doesn't seem to be related to OptiFine.
Can you verify that it only happen when OptiFine is installed?

**Comment by emkirsh** [comment]
I remember disabling optifine fixed it. And in the crash report I saw quite a few "OF"s

--Eli Kirshenbaum

________________________________

**Comment by naeqirelle2020** [comment]
Not able to reproduce this with Forge + Optifine only

**Comment by sp614x** [comment]
If it doesn't happen with Forge + Optifine only then it is a conflict between OptiFine and one of the installed mods.
To find the conflicting mod:
- split your mods into 2 groups (not including OptiFine) 
- remove one group and test in-game with OptiFine
- keep the group that has the problem and repeat until only one mod is left
