### ISSUE TITLE
Rendering overlay

### ISSUE THREAD

**Issue by FaranTahir1** [sp614x/optifine#4082]
Error: java.lang.NullPointerException: Rendering overlay

**Comment by EdgyPotato** [comment]
crash log ?

**Comment by FaranTahir1** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/12/20 10:00 PM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at net.minecraft.client.renderer.FluidBlockRenderer.func_178268_a(FluidBlockRenderer.java:41) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_195410_a(BlockRendererDispatcher.java:154) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:16) ~[?:?] {re:classloading}
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$3728/2100166300.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$4125/893189306.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.13.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$402/910504711.call(Unknown Source) [forge-1.14.4-28.2.13.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.FluidBlockRenderer.func_178268_a(FluidBlockRenderer.java:41)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_195410_a(BlockRendererDispatcher.java:154)
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:16)
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$3728/2100166300.run(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$4125/893189306.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:880)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$402/910504711.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 663925256 bytes (633 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.13.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.13.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.13
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.13-client.jar Minecraft {minecraft@1.14.4 DONE}
		gardentools-1.14.4-1.0.0.jar Garden Tools {gardentools@1.14.4-1.0.0 DONE}
		useful_backpacks-1.14.4-1.7.6.60.jar Useful Backpacks {usefulbackpacks@1.7.6.60 DONE}
		themidnight-0.4.7.jar The Midnight {midnight@0.4.7 DONE}
		tombstone-4.3.6-1.14.4.jar Corail Tombstone {tombstone@4.3.6 DONE}
		u_team_core-1.14.4-2.8.2.150.jar U Team Core {uteamcore@2.8.2.150 DONE}
		secretrooms-6.0.5.jar Secret Rooms 6 {secretroomsmod@6.0.5 DONE}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		item-filters-2.1.0.5.jar Item Filters {itemfilters@2.1.0.5 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		forbidden_arcanus-1.14.4-1.5.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.5 DONE}
		FallingTree-1.14.4-2.0.3+21.jar Falling Tree {falling_tree@2.0.3+21 DONE}
		fishtraps-0.0.4.jar Fish Traps {fishtraps@1.14.4-0.0.4 DONE}
		forge-1.14.4-28.2.13-universal.jar Forge {forge@28.2.13 DONE}
		incubation-1.0.1-1.14.4.jar Incubation {incubation@1.0.1 DONE}
		switchbow-1.5.8.jar Switch-Bow {switchbow@1.5.8 DONE}
		Xaeros_Minimap_20.12.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@20.12.1 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		levelhearts-1.14.4-2.2.0.jar LevelHearts {levelhearts@2.2.0 DONE}
		TrinityWeapons-1.14.4-1.4.0.jar TrinityWeapons {trinity@1.4.0 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
	Launched Version: 1.14.4-forge-28.2.13
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by FaranTahir1** [comment]
hello anyone

**Comment by sp614x** [comment]
[crash-2020-06-12_21.37.11-client.txt](https://github.com/sp614x/optifine/files/4772204/crash-2020-06-12_21.37.11-client.txt)
[crash-2020-06-12_21.49.06-client.txt](https://github.com/sp614x/optifine/files/4772205/crash-2020-06-12_21.49.06-client.txt)
[crash-2020-06-12_22.00.46-client.txt](https://github.com/sp614x/optifine/files/4772206/crash-2020-06-12_22.00.46-client.txt)
[crash-2020-06-12_20.41.53-client.txt](https://github.com/sp614x/optifine/files/4772207/crash-2020-06-12_20.41.53-client.txt)
[crash-2020-06-12_20.48.14-client.txt](https://github.com/sp614x/optifine/files/4772208/crash-2020-06-12_20.48.14-client.txt)
