### ISSUE TITLE
My shadows for leaves and player models wont work in a specific area on my server (it's at my house location)

### ISSUE THREAD

**Issue by Emette** [sp614x/optifine#4159]
I was playing minecraft when it froze, I decided to close the application using the "X" in the tab rather than trying to get it to work and do a save and exit. I was using sildurs shaders. after rejoining the server I found leaves don't have shadows, I didn't have a shadow, with the exception of my shield, and at some point after this started getting the message "OpenGL Error 1281 (invalid value)". I checked my graphics drivers which I have two an intel and a geforce and they are both up to date. My "shadow glitch" seems to only be in a certain area of the server being at my house but if I went to spawn the shadows would work fine. I am using the 1.15.2 optifine pre30 that recently came out which I downloaded from https://optifine.net/downloads . It is a case of the shadows so it does not happen outside of optifine it is however solely related to sildurs, I have used atleast two other shaders without the issue occurring but would like sildurs to work again. 

The log files don't have anything to say since it froze apparently a few people got achievements then i closed it without the save and exit so it just says "Stopping!"

This seems to be the most important information I can gleam from the crash report, everything else seems to just give location details of the world:
Time: 6/21/20 11:26 PM
Description: Batching chunks

java.lang.NullPointerException: Batching chunks
	at dth$c$b.a(ChunkRenderDispatcher.java:859)
	at dth$c$b.a(ChunkRenderDispatcher.java:711)
	at dth.lambda$runTask$1(ChunkRenderDispatcher.java:180)
	at dth$$Lambda$2567/436399861.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

![2020-06-23_12 34 53](https://user-images.githubusercontent.com/67336813/85439357-ea407b80-b55a-11ea-9d4b-a1533e5c46e5.png)

This is an island away from my house where seeing being far away the shadows work

![2020-06-23_12 34 13](https://user-images.githubusercontent.com/67336813/85439365-ed3b6c00-b55a-11ea-8596-cbfa9726579d.png)

this is at my house where the only shadow on my character is the shield and the only shadows made by the trees is the logs, the leaf blocks also dont have shadows on the side opposing the sun

![2020-06-23_12 41 47](https://user-images.githubusercontent.com/67336813/85439371-f0365c80-b55a-11ea-847d-abe6df7cd937.png)

this is the debug screen hope it helps

**Comment by SkyeRise** [comment]
I use Sildurs shaders in pre30 without any issues. In fact, pre30 has fixed all the prior issues I had with shaders (chunk loading issues to be precise being the biggest issue). Maybe the fix is unstable and you randomly got the result?

**Comment by Emette** [comment]
IDK if by fix you mean my download, I have uninstalled and reinstalled, I'd think it unlikely i had the same issue twice in a row

**Comment by Emette** [comment]
I don't think it's an issue with optifine, I have downloaded and used a few different versions and they all have the same issue
I'm thinking it has to to with sildurs itslef but I don't know how, it jsut seems to be the only thing that affects whether the leaves have shadows
