### ISSUE TITLE
(1.16.1) Crash when using optifine and mine colonies

### ISSUE THREAD

**Issue by Wehrmicel** [sp614x/optifine#4389]
Hello,

There seems to be a compatibility problem between Optifine (1.16.1) and "Mine Colonies" mod.

MineColonie's dev team told me that "Optifine seems to be killing our client sided world capability" and that I should open a bug report here because they can't fix that on their side.

The mod works perfectly fine when I remove optifine.

Versions:

- Forge 1.16.1 - 32.0.70
- OptiFine 1.16.1 HD U G2 pre5

Crash logs:

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 19/07/20 23:59
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.common.util.LazyOptional.orElseGet(LazyOptional.java:237) ~[?:?] {re:classloading}
	at com.minecolonies.coremod.util.ChunkDataHelper.canClaimChunksInRange(ChunkDataHelper.java:245) ~[?:0.13.95-PERSONAL] {re:classloading}
	at com.minecolonies.coremod.colony.ColonyManager.isTooCloseToColony(ColonyManager.java:350) ~[?:0.13.95-PERSONAL] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowTownHallColonyManage.<init>(WindowTownHallColonyManage.java:97) ~[?:0.13.95-PERSONAL] {re:classloading}
	at com.minecolonies.coremod.blocks.huts.BlockHutTownHall.func_225533_a_(BlockHutTownHall.java:92) ~[?:0.13.95-PERSONAL] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:633) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:289) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1339) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1596) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1433) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:927) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.70.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/673384643.call(Unknown Source) [forge-1.16.1-32.0.70.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.common.util.LazyOptional.orElseGet(LazyOptional.java:237)
	at com.minecolonies.coremod.util.ChunkDataHelper.canClaimChunksInRange(ChunkDataHelper.java:245)
	at com.minecolonies.coremod.colony.ColonyManager.isTooCloseToColony(ColonyManager.java:350)
	at com.minecolonies.coremod.client.gui.WindowTownHallColonyManage.<init>(WindowTownHallColonyManage.java:97)
	at com.minecolonies.coremod.blocks.huts.BlockHutTownHall.func_225533_a_(BlockHutTownHall.java:92)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:633)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:289)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1339)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1596)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Serana'/319, l='ClientLevel', x=-108.86, y=69.40, z=127.31]]
	Chunk stats: Client Chunk Cache: 841, 552
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,69,112), Chunk: (at 0,4,0 in -7,7; contains blocks -112,0,112 to -97,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 631 game time, 631 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:616)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:602)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/673384643.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6020266416 bytes (5741 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.16.1_HD_U_G2_pre5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.70.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.70
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.70-client.jar Minecraft {minecraft@1.16.1 DONE}
		structurize-0.13.17-ALPHA.jar Structurize {structurize@0.13.17-ALPHA DONE}
		forge-1.16.1-32.0.70-universal.jar Forge {forge@32.0.70 DONE}
		minecolonies-0.13.95-PERSONAL-universal.jar Minecolonies {minecolonies@0.13.95-PERSONAL DONE}
	Launched Version: 1.16.1-forge-32.0.70
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre5
	OptiFine Build: 20200719-015630
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by SteadEXE** [comment]
+1 got the same issue, works fine w/o optifine. I am using the latest version "OptiFine 1.16.1_HD_U_G2_pre5"

**Comment by Raycoms** [comment]
This is due to uninitialized client world capabilities that were added by forge here: https://github.com/MinecraftForge/MinecraftForge/commit/201349f8def534c5a2351528429430aab8ef329b#diff-44078f97b593e59656ec065d900a48afL7
