### ISSUE TITLE
OpenGL 1281 Error (Invalid Value) (Invalid Texture format)

### ISSUE THREAD

**Issue by PiporGames** [sp614x/optifine#4480]
Generated on Minecraft Optifine (last version) 1.16.1

Details:
[00:41:02] [Thread-11/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid texture format.)
java.lang.Exception: Stack trace
	at dgk.a(GlDebugTextUtils.java:153) ~[OptiFine-1.16.1_HD_U_G2_pre4.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
[00:41:02] [Thread-11/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid texture format.)
java.lang.Exception: Stack trace
	at dgk.a(GlDebugTextUtils.java:153) ~[OptiFine-1.16.1_HD_U_G2_pre4.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
[00:41:02] [Thread-11/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid texture format.)
java.lang.Exception: Stack trace
	at dgk.a(GlDebugTextUtils.java:153) ~[OptiFine-1.16.1_HD_U_G2_pre4.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
[00:41:02] [Thread-11/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid texture format.)
java.lang.Exception: Stack trace
	at dgk.a(GlDebugTextUtils.java:153) ~[OptiFine-1.16.1_HD_U_G2_pre4.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
[00:41:02] [Thread-11/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid texture format.)
java.lang.Exception: Stack trace
	at dgk.a(GlDebugTextUtils.java:153) ~[OptiFine-1.16.1_HD_U_G2_pre4.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]

**Comment by sp614x** [comment]
Please test latest pre11.
