### ISSUE TITLE
Tesselating block model

### ISSUE THREAD

**Issue by CreepyLord** [sp614x/optifine#450]
When I tp to players or just wonder around in spectator mode with 1.11.2_Optifine_HD_U_B5, I'd sometimes get the Tesselating block model error and cuases my game to crash. Here is the crash report

---- Minecraft Crash Report ----
// Sorry :(

Time: 1/28/17 3:46 PM
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: -1
	at akb.a(SourceFile:194)
	at akb.b(SourceFile:82)
	at ChunkCacheOF.b(ChunkCacheOF.java:73)
	at alu.d(SourceFile:347)
	at atm$a.a(BlockStateContainer.java:367)
	at brc$b.a(BlockModelRenderer.java:580)
	at brc.renderQuadsSmooth(BlockModelRenderer.java:183)
	at brc.b(BlockModelRenderer.java:110)
	at brc.a(BlockModelRenderer.java:74)
	at brc.a(BlockModelRenderer.java:54)
	at bra.a(SourceFile:65)
	at bte.b(RenderChunk.java:293)
	at bta.a(ChunkRenderWorker.java:119)
	at bta.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at akb.a(SourceFile:194)
	at akb.b(SourceFile:82)
	at ChunkCacheOF.b(ChunkCacheOF.java:73)
	at alu.d(SourceFile:347)
	at atm$a.a(BlockStateContainer.java:367)
	at brc$b.a(BlockModelRenderer.java:580)
	at brc.renderQuadsSmooth(BlockModelRenderer.java:183)
	at brc.b(BlockModelRenderer.java:110)

-- Block model being tesselated --
Details:
	Block: minecraft:stone[variant=stone]
	Block location: World: (160,48,80), Chunk: (at 0,3,0 in 10,5; contains blocks 160,0,80 to 175,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at brc.a(BlockModelRenderer.java:74)
	at brc.a(BlockModelRenderer.java:54)

-- Block being tesselated --
Details:
	Block type: ID #1 (tile.stone // arc)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (160,48,80), Chunk: (at 0,3,0 in 10,5; contains blocks 160,0,80 to 175,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at bra.a(SourceFile:65)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bps['CreeperLord170'/652403, l='MpServer', x=79.32, y=80.00, z=-2174.87]]
	Chunk stats: MultiplayerChunkCache: 117, 117
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,21,0), Chunk: (at 0,1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 75990524 game time, 75923751 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: ~~ERROR~~ ConcurrentModificationException: null
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bnq.a(WorldClient.java:524)
	at bes.b(SourceFile:2539)
	at bta.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 66135528 bytes (63 MB) / 287309824 bytes (274 MB) up to 1213726720 bytes (1157 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1200M -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.11.2-OptiFine_HD_U_B5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU M 380 @ 2.53GHz

**Comment by sp614x** [comment]
This is a known problem, but so far I am not able to find what is the cause.
Does it happen more often when teleporting around?
Is there a way to reproduce it reliably or more often)?

**Comment by CreepyLord** [comment]
Yeah it happens much more often when tping to people in spectator mode and going through dimensions in survival.

**Comment by CreepyLord** [comment]
I don't know how to cause it as other players I know with the same version of optifine and mine craft aren't having issues with it, probably something with my gpu and optifine.

**Comment by CreepyLord** [comment]
Actually I do have more than 30 crash reports of the same reason. Would that help?

**Comment by sp614x** [comment]
Does it crash more often when teleporting near (inside the visible chunks) or far (outside of the visible chunks)?

**Comment by CreepyLord** [comment]
far (outside of the visible chunks)
Or moving very fast in spectator(loading a lot of new chunks in a short period of time),

**Comment by Kellytyrant** [comment]
this crash report happened whenever im in combat then crashed report appeared, then 2nd time i get crashed whenever im in spectator mode going too fast with loading chucks? not understand how does it causing it.

**Comment by CreepyLord** [comment]
Well, for me it *mostly* occurs when loading a lot of new chunks. I have no idea what is causing it too

**Comment by Kellytyrant** [comment]
3rd time crashed again whenever im in spectator each time i died and not moving ( i was AFK for 2min) then crash report appeared.

**Comment by sp614x** [comment]
So far I can not reproduce the crash.
Tried flying in creative, teleporting around, loading a lot of new chunks, etc. also single-player and multiplayer.

**Comment by Kellytyrant** [comment]
flying in creative is also causing this, whenever im not in spectator such as hypixel warlord whenever i play minigames and pressed "C" as im running then combat begin the crash report appeared, either i have to walk to not cause this crash report, only crash report whenever i go too fast and huge chucks appear then crashed.

**Comment by CreepyLord** [comment]
@sp614x try tping to players with the spectator mode thingy and going through end portals both sides

**Comment by CreepyLord** [comment]
Hello it's the problem fixable?

**Comment by PunKeel** [comment]
[cro.txt](https://github.com/sp614x/optifine/files/1078873/cro.txt)
Additional crash-report log in case it helps. Can't tell you how it happened, ~that's a sssssecret~ I don't know :(

**Comment by dustinduse** [comment]
I found a way to reproduce this nearly every 10-20 minutes. https://hastebin.com/qiqosijije.pas

**Comment by dustinduse** [comment]
If anyone cares. I have a plugin I built that allows a player to tour the Minecraft network. Traveling from server to server. (built for Twitch). This bug literally breaks the whole idea. Because Minecraft will crash about every 10-20 minutes with this error. Ive tested and tested. It seems no computer is immune.  I would be glad to rig up a system for a dev to play with that could recreate the error much faster.

**Comment by BluPenDragon** [comment]
i get a similar error (seems to be happening more and more) i crash with 
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: 3

as soon as i hit my macro to log in, (started happening about a month ago sporadically but now it happens at least once a day)

**Comment by sp614x** [comment]
@BluPenDragon Have you tried with latest version C7?
It has some bugfixes that should fix it.

**Comment by BluPenDragon** [comment]
im running 1.10.2 and using E3 its the latest available so idk what to do... downgrade?

**Comment by sp614x** [comment]
I mean E7 for 1.10.2, it is based on C7 for 1.12.2.

**Comment by BluPenDragon** [comment]
oh... ok ill give it a try

**Comment by AxoCode** [comment]
Any Update? And also I think this issue is because of connected texture, [source](https://hypixel.net/threads/how-to-fix-tesselating-block-model-crash.3560198/)
