### ISSUE TITLE
[1.16.1] Mod Interaction crash

### ISSUE THREAD

**Issue by oleg333l** [sp614x/optifine#4610]
## Description of Issue
Minecraft crashes trying to render "Mana Pylon" from Botania

## Steps to Reproduce
1. Open creative inventory
2. Find a mana pylon

## OptiFine Version
OptiFine_1.16.1_HD_U_G2

## Installation Method
Mods folder

## Fabric/Forge Version
Minecraft 1.16.1 Forge 32.0.108

## Other Installed Mods
Tested with Botania-1.16-401 and its dependencies Patchouli-1.16-39 and curios-FORGE-1.16.1-3.0.0.2

## Log Files/Crash Reports
[crash-2020-08-14_16.49.58-client.txt](https://github.com/sp614x/optifine/files/5074933/crash-2020-08-14_16.49.58-client.txt)

[latest.log](https://github.com/sp614x/optifine/files/5074932/latest.log)

## F3 Debug Screenshot
![2020-08-14_16 56 22](https://user-images.githubusercontent.com/8050905/90256994-3a4b0880-de4f-11ea-9614-9ae19c5c1367.png)

**Comment by lyghters** [comment]
I have the same problem with Botania. Also, some items completely missing textures (from different mods AND some vanilla minecraft items, like fireworks or enchanted books).
Both problems happen **only** with Optifine enabled.

Here's a Botania crash log:
<details>
<summary>spoiler</summary>

```
Time: 8/15/20 6:35 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at vazkii.botania.client.render.tile.RenderTilePylon.access$200(RenderTilePylon.java:41) ~[?:1.16-402] {re:classloading}
	at vazkii.botania.client.render.tile.RenderTilePylon$TEISR.func_239207_a_(RenderTilePylon.java:144) ~[?:1.16-402] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:252) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:407) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:447) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:436) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:40) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:26) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.render.IngredientListElementRenderer.renderSlow(IngredientListElementRenderer.java:81) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:204) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:107) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:114) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:179) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:85) ~[?:7.0.1.10] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_779_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraft.client.gui.screen.Screen.func_238651_a_(Screen.java:344) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230446_a_(Screen.java:338) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230430_a_(SourceFile:83) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:725) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.108-launcher.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at vazkii.botania.client.render.tile.RenderTilePylon.access$200(RenderTilePylon.java:41)
	at vazkii.botania.client.render.tile.RenderTilePylon$TEISR.func_239207_a_(RenderTilePylon.java:144)
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:252)
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:407)

-- Item being rendered --
Details:
	Item Type: mana_pylon
	Registry Name: botania:mana_pylon
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:447)
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:436)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:40)

-- Ingredient being rendered --
Details:
	Mod Name: Botania
	Registry Name: botania:mana_pylon
	Display Name: Mana Pylon
	String Name: 1 mana_pylon
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:270)
	at mezz.jei.render.IngredientListElementRenderer.renderSlow(IngredientListElementRenderer.java:83)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:204)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:107)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:114)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:179)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:85)
	at net.minecraftforge.eventbus.ASMEventHandler_779_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraft.client.gui.screen.Screen.func_238651_a_(Screen.java:344)
	at net.minecraft.client.gui.screen.Screen.func_230446_a_(Screen.java:338)
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230430_a_(SourceFile:83)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:725)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- JEI render details --
Details:
	Unique Id (for Blacklist): botania:mana_pylon
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1 mana_pylon botania:mana_pylon
	Filter Text: ch
	Edit Mode Enabled: false
	Debug Mode Enabled: false

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.InventoryScreen
	Mouse location: Scaled: (676, 514). Absolute: (1352.000000, 1028.000000)
	Screen size: Scaled: (960, 528). Absolute: (1920, 1055). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['lyghters'/107, l='ClientLevel', x=-1436.77, y=63.94, z=179.87]]
	Chunk stats: Client Chunk Cache: 625, 400
	Level dimension: minecraft:overworld
	Level spawn location: World: (-127,65,92), Chunk: (at 1,4,12 in -8,5; contains blocks -128,0,80 to -113,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 186246 game time, 313896 day time
	Server brand: forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.7.12-artix1-1
	Java Version: 1.8.0_262, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1539918456 bytes (1468 MB) / 4462739456 bytes (4256 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.1_HD_U_G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		torchslabmod-1.16.1_v1.6.16.jar Torch Slab Mod {torchslabmod@1.6.16 DONE}
		NetherPortalFix_1.16.1-7.0.1.jar NetherPortalFix {netherportalfix@7.0.1 DONE}
		jei-1.16.1-7.0.1.10.jar Just Enough Items {jei@7.0.1.10 DONE}
		Mekanism-1.16.1-10.0.9.432.jar Mekanism {mekanism@10.0.9 DONE}
		Waystones_1.16.1-7.1.0.jar Waystones {waystones@7.1.0 DONE}
		ForgeEndertech-1.16.1-7.0.0.0-build.0006.jar Forge Endertech {forgeendertech@7.0.0.0 DONE}
		XaerosWorldMap_1.10.0_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.10.0 DONE}
		Placebo-1.16.1-4.1.3.jar Placebo {placebo@4.1.3 DONE}
		appliedenergistics2-8.0.0-alpha.3.jar Applied Energistics 2 {appliedenergistics2@8.0.0-alpha.3 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		pneumaticcraft-repressurized-1.16.1-2.1.0-11.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.1-2.1.0-11 DONE}
		Apotheosis-1.16.1-4.1.0.jar Apotheosis {apotheosis@4.1.0 DONE}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Morpheus-1.16.1-4.2.55.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.16.1-10.0.9.432.jar Mekanism: Generators {mekanismgenerators@10.0.9 DONE}
		Hwyla-forge-1.10.10-B77_1.16.1.jar Waila {waila@1.10.10-B77_1.16.1 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		CraftingTweaks_1.16.2-12.1.0.jar Crafting Tweaks {craftingtweaks@12.1.0 DONE}
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		mcw-bridges-1.0.4-mc1.16.1.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.16.1-3.0.4-eeeb31e.jar Industrial Foregoing {industrialforegoing@3.0.4 DONE}
		titanium-1.16.1-3.0.4.jar Titanium {titanium@3.0.4 DONE}
		ImmersiveEngineering-1.16.1-3.1-112.jar Immersive Engineering {immersiveengineering@1.16.1-3.1-112 DONE}
		BiomesOPlenty-1.16.1-11.0.0.393-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.393 DONE}
		valhelsia_structures-16.0.1.jar Valhelsia Structures {valhelsia_structures@16.0.1 DONE}
		jeiintegration_1.16.1-4.0.0.4.jar JEI Integration {jeiintegration@4.0.0.4 DONE}
		curios-FORGE-1.16.1-3.0.0.2.jar Curios API {curios@FORGE-1.16.1-3.0.0.2 DONE}
		Botania-1.16-402.jar Botania {botania@1.16-402 DONE}
		Patchouli-1.16-39.jar Patchouli {patchouli@1.16-39 DONE}
		Mantle-1.16.1-1.6.27.jar Mantle {mantle@1.6.27 DONE}
		Inspirations-1.16.1-1.2.0.jar Inspirations {inspirations@1.16.1-1.2.0 DONE}
		Xaeros_Minimap_20.20.0_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.20.0 DONE}
		extlights-3.0.jar Extended Lights {extlights@3.0 DONE}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 DONE}
		Quark-r2.2-260.jar Quark {quark@r2.2-260 DONE}
		[1.16.1]+SecurityCraft+v1.8.19.1-beta2.jar SecurityCraft {securitycraft@v1.8.19.1-beta2 DONE}
		sit-1.16.1-v1.3.jar Sit {sit@v1.3 DONE}
		MekanismTools-1.16.1-10.0.9.432.jar Mekanism: Tools {mekanismtools@10.0.9 DONE}
		mcws-roofs-1.16.1-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		furniture-7.0.0-pre18-1.16.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre18 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.16.1-1.1.1-b6.jar Engineer's Decor {engineersdecor@1.1.1-b6 DONE}
		cc-tweaked-1.16.1-1.90.3.jar CC: Tweaked {computercraft@1.90.3 DONE}
		modular-routers-1.16.1-7.0.1-29.jar Modular Routers {modularrouters@1.16.1-7.0.1-29 DONE}
		Aquaculture-1.16.1-2.0.18.jar Aquaculture 2 {aquaculture@1.16.1-2.0.18 DONE}
		AdChimneys-1.16.1-6.0.0.0-build.0006.jar Advanced Chimneys {adchimneys@6.0.0.0 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		CosmeticArmorReworked-1.16.1-v1b.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1b DONE}
		SoundFilters-0.14_for_1.16.jar Sound Filters {soundfilters@0.14_for_1.16 DONE}
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 450.57, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor
	OptiFine Version: OptiFine_1.16.1_HD_U_G2
	OptiFine Build: 20200802-005745
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Complementary
	OpenGlVersion: 4.6.0 NVIDIA 450.57
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```
</details>
