### ISSUE TITLE
[1.16.2] Unable to install

### ISSUE THREAD

**Issue by Vulcan-02** [sp614x/optifine#4645]
I get this error when attempting to install

java.lang.IllegalArgumentException: URI has an authority component
  at java.base/java.io.File.<init>(File.java:423)
  at optifine.Installer.getOptiFineZipFile(Installer.java:424)
  at optifine.Installer.installOptiFineLibrary(Installer.java:328)
  at optifine.Installer.doInstall(Installer.java:96)
  at optifine.InstallerFrame.onInstall(InstallerFrame.java:425)
  at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:490)
  at optifine.InstallerFrame.access$7(InstallerFrame.java:484)
  at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
  at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
  at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
  at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
  at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
  at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
  at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
  at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
  at java.desktop/java.awt.Component.processEvent(Component.java:6401)
  at java.desktop/java.awt.Container.processEvent(Container.java:2263)
  at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
  at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
  at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
  at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
  at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
  at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
  at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
  at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
  at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by sp614x** [comment]
The installation folder or the JAR folder should not be a "\\\\" UNC path.
https://stackoverflow.com/a/2371874

**Comment by Vulcan-02** [comment]
Ok so how do I change this?
