### ISSUE TITLE
crashed when attempting to load Minecraft with Forge + optifine

### ISSUE THREAD

**Issue by gofirst2220** [sp614x/optifine#465]
```
2017-02-03 08:45:17,147 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-02-03 08:45:17,151 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[08:45:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:45:17] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:45:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[08:45:17] [main/INFO] [FML]: Forge Mod Loader version 13.19.1.2189 for Minecraft 1.11 loading
[08:45:17] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_121
[08:45:17] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.11.2_HD_U_B6_MOD.jar
[08:45:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:45:17] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[08:45:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[08:45:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:45:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:45:17] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[08:45:17] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[08:45:17] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[08:45:17] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[08:45:17] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/C:/Users/Luke/AppData/Roaming/.minecraft/mods/OptiFine_1.11.2_HD_U_B6_MOD.jar
[08:45:17] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: C:\Users\Luke\AppData\Roaming\.minecraft\mods\OptiFine_1.11.2_HD_U_B6_MOD.jar
[08:45:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:45:20] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[08:45:21] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[08:45:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:45:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[08:45:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[08:45:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[08:45:22] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[08:45:22] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[08:45:22] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Exception in thread "main" [08:45:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[08:45:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[08:45:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[08:45:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[08:45:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[08:45:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[08:45:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```
See the crash log. it works fine by itself without Forge

**Comment by sp614x** [comment]
[FML]: Forge Mod Loader version 13.19.1.2189 for **Minecraft 1.11** loading
[FML]: Loading tweaker optifine.OptiFineForgeTweaker from **OptiFine_1.11.2**_HD_U_B6_MOD.jar
...
Versions do not match, you should use OptiFine for 1.11.

**Comment by gofirst2220** [comment]
Really? Where's 1.11.2 Forge?

**Comment by sp614x** [comment]
Forge for 1.11.2: http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.11.2.html

**Comment by Senzatetthow** [comment]
2018-01-13 21:44:46,869 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-01-13 21:44:46,872 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[21:44:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:44:46] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:44:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:44:47] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2185 for Minecraft 1.10.2 loading
[21:44:47] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_144
[21:44:47] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.10.2_HD_U_E7.jar
[21:44:47] [main/WARN] [FML]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:44:47] [main/INFO] [FML]: Loading tweaker shadersmod.launch.SMCTweaker from ShadersMod-v2.5.3mc1.10.2.jar
[21:44:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:44:47] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[21:44:47] [main/INFO] [LaunchWrapper]: Loading tweak class name shadersmod.launch.SMCTweaker
[21:44:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:44:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:44:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:44:47] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[21:44:47] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[21:44:47] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[21:44:47] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[21:44:47] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\Francesca\AppData\Roaming\.minecraft\mods\OptiFine_1.10.2_HD_U_E7.jar
[21:44:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:44:49] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:44:49] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:44:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:44:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:44:49] [main/INFO] [LaunchWrapper]: Calling tweak class shadersmod.launch.SMCTweaker
2018-01-13 21:44:49,153 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-01-13 21:44:49,173 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-01-13 21:44:49,176 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[21:44:49] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] ShadersMod 2.5.3
[21:44:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:44:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:44:49] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class $wrapper.net.gegy1000.wearables.server.patcher.WearablesRuntimePatcher
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.gegy1000.wearables.server.patcher.WearablesRuntimePatcher
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:241) ~[ASMTransformerWrapper$TransformerWrapper.class:?]
	at $wrapper.net.gegy1000.wearables.server.patcher.WearablesRuntimePatcher.<init>(Unknown Source) ~[WearablesRuntimePatcher.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_144]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:131) [forge-1.10.2-12.18.3.2185.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.gegy1000.wearables.server.patcher.WearablesRuntimePatcher
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:237) ~[ASMTransformerWrapper$TransformerWrapper.class:?]
	... 10 more
Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:237) ~[ASMTransformerWrapper$TransformerWrapper.class:?]
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:237) ~[ASMTransformerWrapper$TransformerWrapper.class:?]
	... 10 more
[21:44:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:44:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:44:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:44:49] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[21:44:49] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:44:50] [main/INFO] [STDOUT]: [brad16840.core.ClassTransformer:patchGuiContainer:221]: Backpacks! has patched GuiContainer to allow its backpacks to be opened from vanilla guis
[21:44:51] [Client thread/INFO]: Setting user: TFUP_ZephirFace
[21:44:55] [Client thread/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/vertex/VertexFormat
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraftforge.client.model.Attributes.<clinit>(Attributes.java:38)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at java.lang.Class.forName0(Native Method)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at java.lang.Class.forName(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at ReflectorClass.getTargetClass(ReflectorClass.java:45)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at ReflectorClass.<init>(ReflectorClass.java:24)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at ReflectorClass.<init>(ReflectorClass.java:15)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at Reflector.<clinit>(Reflector.java:114)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.settings.GameSettings.setForgeKeybindProperties(GameSettings.java:3192)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:294)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:44:55] [Client thread/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.vertex.VertexFormat
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 18 more
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: shadersmod.common.SMCLog.finer(Ljava/lang/String;[Ljava/lang/Object;)V
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at shadersmod.transform.STVertexFormat$CVTransform.visitMethod(STVertexFormat.java:72)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.objectweb.asm.ClassReader.b(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at shadersmod.transform.STVertexFormat.transform(STVertexFormat.java:24)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at shadersmod.transform.SMCClassTransformer.transform(SMCClassTransformer.java:116)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 20 more
[21:44:55] [Client thread/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[21:44:55] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class Reflector
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:136) ~[b.class:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:52) ~[b.class:?]
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:423) ~[b.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:355) ~[bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [21:44:55] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[21:44:55] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)




I have a modpack installed with 43 mods and I tried almost everything for making it work
