### ISSUE TITLE
[Forge] Some dual high blocks crash the game if broken at the top.

### ISSUE THREAD

**Issue by GradiusLover2000** [sp614x/optifine#4764]
## Description of Issue
Only some mods seem to return this issue, namely Ultimate Car mod.  This issue happens whenever cars mod is alone, or with others, and happens only with optifine installed.

## Steps to Reproduce
1. Install forge, optifine and ultimate car mod.
2. launch a world and place down a Gas Station
3. break the top of the gas station (breaking the bottom works correctly, only breaking it from the top does not.)

## OptiFine Version
Optifine 1.16.2 G3

## Installation Method
installed via mods folder for normal forge, or via Vivecraft's LIB loader for vivecraft forge (both tested)

## Fabric/Forge Version
33.0.22+

## Other Installed Mods
Ultimate Car Mod (debug file has other mods, however the issue persists even if the mod is by itself with optifine and forge.

## Log Files/Crash Reports
https://drive.google.com/file/d/1-pMPvmA_B2r5anz9V37X7V5MzwP8IsKC/view?usp=sharing

## Prior Testing
The mod will not crash and will break the block correctly if optifine is not installed.

##Additional Information
The Ultimate Car mod developer is convinced this is an optifine issue and not his own.  it is very frustrating to be in this situation where other mods are completely fine with two block tall blocks whilst the car mod is not.  Consultation with the Ultimate Car mod developer might be required and I will be happy to pass messages along.

**Comment by sp614x** [comment]
```
// You're mean.

Time: 02/09/2020, 14:44
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:97) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1801) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:1218) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:Vivecraft:default}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:723) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:Vivecraft:default}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.2.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.2-33.0.32.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:97)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1801)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['MarksmanFoxy'/157, l='ClientLevel', x=-827.72, y=69.00, z=505.81]]
	Chunk stats: Client Chunk Cache: 841, 576
	Level dimension: minecraft:overworld
	Level spawn location: World: (-880,63,512), Chunk: (at 0,3,0 in -55,32; contains blocks -880,0,512 to -865,255,527), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 7943 game time, 7943 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2749)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:751)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2384461824 bytes (2274 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -Xms2G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.2_HD_U_G3_LIB.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.32.jar fml TRANSFORMATIONSERVICE 
		/minecrift-1.16.2-jrbudda-NONVR-4-r1.jar Vivecraft TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.32
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		doubledoors_1.16.2-2.1.jar Double Doors {doubledoors@2.1 DONE}
		Ma-Enchants-1.16.2-3.3.0.jar Ma Enchants {ma-enchants@1.16.2-3.3.0 DONE}
		NetherPortalFix_1.16.2-7.1.0.jar NetherPortalFix {netherportalfix@7.1.0 DONE}
		inventoryprofiles-forge-1.16.2-0.4.2.jar Inventory Profiles {inventoryprofiles@0.4.2 DONE}
		endportalrecipe_1.16.2-2.1.jar End Portal Recipe {endportalrecipe@2.1 DONE}
		mining-helmet-1.16.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		vanillaexcavators-1.16.2-2.1.3.jar Vanilla Excavators {vanillaexcavators@2.1.3 DONE}
		jei-1.16.2-7.3.2.25.jar Just Enough Items {jei@7.3.2.25 DONE}
		FallingTree-Forge-1.16.2-2.2.2.jar Falling Tree {falling_tree@2.2.2 DONE}
		EditSign-Forge-1.16.2-2.1.2.jar Edit Sign {edit_sign@2.1.2 DONE}
		mcw-windows-1.0.2-mc1.16.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		torohealth-1.16.2-forge-2.jar ToroHealth {torohealth@NONE DONE}
		KleeSlabs_1.16.2-9.1.0.jar KleeSlabs {kleeslabs@9.1.0 DONE}
		rsgauges-1.16.2-1.2.4-b6.jar Gauges and Switches {rsgauges@1.2.4-b6 DONE}
		BowInfinityFix-1.16.x-rv9.jar Bow Infinity Fix {bowinfinityfix@rv9 DONE}
		essentials-1.16.2-2.9.1.jar Essentials {essentials@1.16.2-2.9.1 DONE}
		BetterCaves-1.16.2-1.0.jar YUNG's Better Caves {bettercaves@1.16.2-1.0 DONE}
		ForgeEndertech-1.16.2-7.0.2.0-build.0012.jar Forge Endertech {forgeendertech@7.0.2.0 DONE}
		AdFinders-1.16.2-5.0.2.0-build.0012.jar Advanced Finders {adfinders@5.0.2.0 DONE}
		Clumps-6.0.0.9.jar Clumps {clumps@6.0.0.9 DONE}
		JRFTL+[1.16.2]-1.1.jar JRFTL {jrftl@1.1 DONE}
		CookingForBlockheads_1.16.2-9.1.1.jar Cooking for Blockheads {cookingforblockheads@9.1.1 DONE}
		Placebo-1.16.2-4.2.0.jar Placebo {placebo@4.2.0 DONE}
		comforts-forge-1.16.2-4.0.0.0.jar Comforts {comforts@1.16.2-4.0.0.0 DONE}
		gardentools-1.16.2-1.0.0.jar Garden Tools {gardentools@1.16.2-1.0.0 DONE}
		decorative_blocks-1.16.2-1.0.jar Decorative Blocks {decorative_blocks@1.4 DONE}
		SkinnedCarts-1.16.2-1.1.1.jar Skinned Carts {skinnedcarts@1.1.1 DONE}
		WitherSkeletonTweaks-1.16.2-5.1.0.jar Wither Skeleton Tweaks {wstweaks@5.1.0 DONE}
		u_team_core-1.16.2-3.1.6.177.jar U Team Core {uteamcore@3.1.6.177 DONE}
		simpleplanes-1.16.2-2.0.5.4.jar Simple Planes {simpleplanes@1.16.2-2.0.5.3 DONE}
		cryingghasts_1.16.2-1.1.jar Crying Ghasts {cryingghasts@1.1 DONE}
		grapple_hooks-1.2.2-32.jar Grapple Hooks {grapple_hooks@1.2.2-32 DONE}
		additional_lights-1.16.2-2.1.1.jar Additional Lights {additional_lights@2.1.1 DONE}
		StoneChest-1.16.2-1.0.0.jar Stone Chest {stonechest@1.0.0 DONE}
		extradisks-1.16.2-1.3.1.jar Extra Disks {extradisks@1.3.1 DONE}
		forge-1.16.2-33.0.32-universal.jar Forge {forge@33.0.32 DONE}
		absentbydesign-1.16.2-1.1.0.jar Absent By Design Mod {absentbydesign@1.16.2-1.1.0 DONE}
		scuba-gear-1.16.2-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		xercamusic-1.16.2-1.0.jar Xerca's Music Maker Mod {xercamusic@1.16.2-1.0 DONE}
		refinedstorage-1.9.4.jar Refined Storage {refinedstorage@1.9.4 DONE}
		ironchest-1.16.2-11.1.5.jar Iron Chests {ironchest@1.16.2-11.1.5 DONE}
		corpse-1.16.2-1.0.8.jar Corpse {corpse@1.16.2-1.0.8 DONE}
		forge-1.16.2-33.0.32-client.jar Minecraft {minecraft@1.16.2 DONE}
		extraanvils-4.0.jar Extra Anvils {extraanvils@4.0 DONE}
		repurposed_structures-1.16.2-2.1.1.jar Repurposed Structures {repurposed_structures@1.16.2-2.1.1 DONE}
		netherportalspread_1.16.2-3.5.jar Nether Portal Spread {netherportalspread@3.5 DONE}
		useful_railroads-1.16.2-1.4.3.28.jar Useful Railroads {usefulrailroads@1.4.3.28 DONE}
		morevanillalib-1.16.2-1.2.12.jar MoreVanillaLib {morevanillalib@1.2.12 DONE}
		ironfurnaces-1.16.2-2.2.0.jar Iron Furnaces {ironfurnaces@2.2.0 DONE}
		CreativeCore_v2.0.7_mc1.16.2.jar CreativeCore {creativecore@2.0.0 DONE}
		mcw-trapdors-1.0.0fix-mc1.16.2.jar Macaw's Trapdoors {mcwtrpdoors@1.0.0 DONE}
		ceramicbucket-2.0.2-1.16.2+.jar Ceramic Bucket {ceramicbucket@2.0.2-1.16.2+ DONE}
		movingelevators-1.2.20-mc1.16.2.jar Moving Elevators {movingelevators@1.2.20 DONE}
		simplylight-1.16.2-1.0.2.jar Simply Light {simplylight@1.16.2-1.0.2 DONE}
		ceramicshears-1.3.1-1.16.1+.jar Ceramic Shears {ceramicshears@1.3.1-1.16.1+ DONE}
		villagespawnpoint_1.16.2-1.3.jar Village Spawn Point {villagespawnpoint@1.3 DONE}
		simplybackpacks-1.16.2-1.4.12.jar Simply Backpacks {simplybackpacks@1.16.2-1.4.12 DONE}
		car-1.16.2-1.0.3.jar Ultimate Car Mod {car@1.16.2-1.0.3 DONE}
		collective-1.16.2-1.39.jar Collective {collective@1.39 DONE}
		camera-1.16.2-1.0.4.jar Camera Mod {camera@1.16.2-1.0.4 DONE}
		lava-monster-1.16.2-1.0.8.jar Lava Monster {lava_monster@1.0.8 DONE}
		xercapaint-1.16.2-1.1.jar Joy of Painting {xercapaint@1.16.2-1.1 DONE}
		vanillahammers-1.16.2-2.1.3.jar Vanilla Hammers {vanillahammers@2.1.3 DONE}
		Regrowth-1.16.2-33.0.22.jar Regrowth Mod {regrowth@33.0.22 DONE}
		structurize-0.13.59-ALPHA.jar Structurize {structurize@0.13.59-ALPHA DONE}
		Infinite-Music-1.2.0.jar Infinite Music {infinitemusic@1.2.0 DONE}
		minecolonies-0.13.203-ALPHA-universal.jar Minecolonies {minecolonies@0.13.203-ALPHA DONE}
		mcws-roofs-1.16.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		cc-tweaked-1.16.2-1.91.0.jar CC: Tweaked {computercraft@1.91.0 DONE}
		kotlin_libraries-1.0-5.jar Kotlin Libraries {kotlin_libraries@1.0-5 DONE}
		ItemPhysic_v1.4.6_mc1.16.2.jar ItemPhysic {itemphysic@1.6.0 DONE}
		easyelytrato_1.16.2-1.5.jar Easy Elytra Takeoff {easyelytrato@1.5 DONE}
		trashcans-1.0.3-mc1.16.2.jar Trash Cans {trashcans@1.0.3 DONE}
		smallernp_1.16.2-1.4.jar Smaller Nether Portals {smallernp@1.4 DONE}
		byg-1.0.4.jar Oh The Biomes You'll Go {byg@1.0.4 DONE}
		snowbfrmobs_1.16.2-1.1.jar Snowballs Freeze Mobs {snowbfrmobs@1.1 DONE}
		SoundFilters-0.14_for_1.16.2.jar Sound Filters {soundfilters@0.14_for_1.16.2 DONE}
		DangerousStoneCutter-1.16.2-1.4.jar Dangerous Stone Cutter {dangerousstonecutter@1.4 DONE}
		Cyclic-1.16.2-0.6.2.jar Cyclic {cyclic@1.16.2-0.6.2 DONE}
	Launched Version: vivecraft-1.16.2-jrbudda-NONVR-4-r1-forge
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla
	Current Language: English (United Kingdom)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
	OptiFine Version: OptiFine_1.16.2_HD_U_G3
	OptiFine Build: 20200829-104659
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce RTX 2080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**Comment by GradiusLover2000** [comment]
Extra info: this happens if Ultimate Cars mod is used alone with Optifine G3 and Forge 1.16.2 33.0.22+.  All mods found in the debug log (including Vivecraft's reflectors) are entirely irrelevant.  The bug can be replicated by placing down a Gas Station block in Ultimate Cars mod, then destroying the block from the top side (breaking from the bottom works)

**Comment by NightScale5755** [comment]
[crash-2021-03-19_22.48.32-client.txt](https://github.com/sp614x/optifine/files/6174844/crash-2021-03-19_22.48.32-client.txt)
Can Confirm this bug is STILL relevent.

**Comment by sp614x** [comment]
The shaders block aliases crash:
```
java.lang.NullPointerException: Unexpected error
	at net.optifine.shaders.BlockAliases.getAliasBlockId(BlockAliases.java:64) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.getBlockEntityId(Shaders.java:6072) ~[?:?] {re:classloading}
```

**Comment by NightScale5755** [comment]
hm? Is the bugfix on your end, or mine?

**Comment by amandexspeed** [comment]
It happens with me too...I talked to Optifine guys and they said me that...
![2021-03-27-_1_](https://user-images.githubusercontent.com/60000299/112725076-11b2e300-8ef5-11eb-8c4e-c2c2eea9d8af.jpg)

**Comment by NightScale5755** [comment]
> This is a different crash, the bugfix is easy:
> 
> ```
> java.lang.NullPointerException: Unexpected error
> 	at net.optifine.shaders.BlockAliases.getAliasBlockId(BlockAliases.java:64) ~[?:?] {re:classloading}
> 	at net.optifine.shaders.Shaders.getBlockEntityId(Shaders.java:6072) ~[?:?] {re:classloading}
> ```

Hey uhh, are you gonna tell me this magical bugfix? I've really been desperate for a fix for this...

**Comment by ink717** [comment]
regarding the ultimate car mod gas pump issue, it's still not fixed as of today. 
I'm having lots of trouble trying to reach that developer and convince him of what should be done or improved but looks like he just doesn't care at all.
not a very positive attitude to develop a mod and release it to the public, then leave in a buggy state.

**Comment by henkelmax** [comment]
> regarding the ultimate car mod gas pump issue, it's still not fixed as of today. I'm having lots of trouble trying to reach that developer and convince him of what should be done or improved but looks like he just doesn't care at all. not a very positive attitude to develop a mod and release it to the public, then leave in a buggy state.

This only happens with optifine installed. As optifine is not open source, I can't look into the code to find a fix.

**Comment by ink717** [comment]
after 2+ years of running the server, I'm already tired of trying to fix crashes like this due to not being open source. 
all I can do is ask players to build a protection case around the gas pump and other blocks like that from other mods. 
So I don't mind if it'll still happen or might get fixed. At least all our gas stations looks like a big box with pumps locked in a trapdoor
