### ISSUE TITLE
[Bug Report] CEM Red Mushrooms on Mooshrooms doesn't load randomly

### ISSUE THREAD

**Issue by Zefferis** [sp614x/optifine#4770]
## Description of Issue
Occationally the Red Mushroom texture that allows for a custom red mushroom to be applied to a mooshroom

## Steps to Reproduce
1. Refresh Texture Pack
2. Check to see if issue arose.

## OptiFine Version
1.16.2 HD_U_G3

## Installation Method
Standalone Installer

## Log Files/Crash Reports
```
20:10:15.155
ejv
main
Failed to load texture: minecraft:textures/entity/cow/red_mushroom.png
java.io.FileNotFoundException: minecraft:textures/entity/cow/red_mushroom.png
	at abz.a(SourceFile:67)
	at ack.a(SourceFile:64)
	at ejq$a.a(SimpleTexture.java:113)
	at ejq.b(SimpleTexture.java:85)
	at ejq.a(SimpleTexture.java:38)
	at ejv.c(TextureManager.java:135)
	at ejv.a(TextureManager.java:96)
	at eji.a(Texture.java:122)
	at ejv.lambda$reload$4(TextureManager.java:287)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:116)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:103)
	at dew.e(MainWindow.java:384)
	at djw.e(SourceFile:1043)
	at djw.e(SourceFile:656)
	at net.minecraft.client.main.Main.main(SourceFile:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
```

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/15270437/92197108-b1a80280-ee25-11ea-8687-cd8e4e042677.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

--- This is an optifine only feature, cannot be tested outside of Optifine

## Additional Information

Red Mooshroom's Custom Red Mushroom texture seems to load upon first entering the world, but randomly when refreshing the texture packs it can suddenly throw the error above and display a missing texture.

**Comment by WeegeeTheDoggo** [comment]
having the exact same problem. It's only the original red mushroom too. my pack has red_mushroom2 and red_mushroom3, both of which work fine

**Comment by MushirMickeyJoe** [comment]
seems to still hapen in 1.19.2. 
![image](https://user-images.githubusercontent.com/31923214/205523451-9f0a5a2b-5efe-4259-b2d9-6929b79df934.png)
new mooshroom mode, same problems

**Comment by Maisbohne** [comment]
still happens on 1.20.1 even after refreshing still there
