### ISSUE TITLE
Crash on 1.8.9 Startup

### ISSUE THREAD

**Issue by 1234fireball** [sp614x/optifine#48]
I have been attempting to install Optifine on minecraft 1.8.9 with journeymap and  seem to have this reoccurring problem

[15:08:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:08:05] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:08:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:08:05] [main/INFO] [FML]: Forge Mod Loader version 11.14.4.1577 for Minecraft 1.8 loading
[15:08:05] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_66
[15:08:05] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.9_HD_U_H3 (1).jar
[15:08:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:08:05] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[15:08:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:08:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:08:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:08:05] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[15:08:05] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[15:08:05] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[15:08:06] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[15:08:06] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Declan/AppData/Roaming/.minecraft/mods/OptiFine_1.8.9_HD_U_H3%20(1).jar
[15:08:06] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@2a742aa2
[15:08:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:08:07] [main/WARN] [FML]: Patcher expecting empty class data file for net.minecraft.server.dedicated.DedicatedServer$4, but received non-empty
[15:08:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:08:07] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[15:08:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:08:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:08:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:08:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:08:08] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[15:08:08] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:08:10] [Client thread/INFO]: Setting user: 1234fireball
[15:08:10] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/state/BlockState$StateImplementation
	at net.minecraft.block.state.BlockState.createState(BlockState.java:55) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:83) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:50) ~[bed.class:?]
	at net.minecraft.block.Block.func_180661_e(Block.java:968) ~[atr.class:?]
	at net.minecraft.block.Block.<init>(Block.java:248) ~[atr.class:?]
	at net.minecraft.block.BlockAir.<init>(BlockAir.java:15) ~[asy.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2021) ~[atr.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.state.BlockState$StateImplementation
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.block.state.BlockState.createState(BlockState.java:55) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:83) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:50) ~[bed.class:?]
	at net.minecraft.block.Block.func_180661_e(Block.java:968) ~[atr.class:?]
	at net.minecraft.block.Block.<init>(Block.java:248) ~[atr.class:?]
	at net.minecraft.block.BlockAir.<init>(BlockAir.java:15) ~[asy.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2021) ~[atr.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/state/BlockStateBase
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.block.state.BlockState.createState(BlockState.java:55) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:83) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:50) ~[bed.class:?]
	at net.minecraft.block.Block.func_180661_e(Block.java:968) ~[atr.class:?]
	at net.minecraft.block.Block.<init>(Block.java:248) ~[atr.class:?]
	at net.minecraft.block.BlockAir.<init>(BlockAir.java:15) ~[asy.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2021) ~[atr.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.state.BlockStateBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.block.state.BlockState.createState(BlockState.java:55) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:83) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:50) ~[bed.class:?]
	at net.minecraft.block.Block.func_180661_e(Block.java:968) ~[atr.class:?]
	at net.minecraft.block.Block.<init>(Block.java:248) ~[atr.class:?]
	at net.minecraft.block.BlockAir.<init>(BlockAir.java:15) ~[asy.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2021) ~[atr.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.block.state.BlockState.createState(BlockState.java:55) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:83) ~[bed.class:?]
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:50) ~[bed.class:?]
	at net.minecraft.block.Block.func_180661_e(Block.java:968) ~[atr.class:?]
	at net.minecraft.block.Block.<init>(Block.java:248) ~[atr.class:?]
	at net.minecraft.block.BlockAir.<init>(BlockAir.java:15) ~[asy.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2021) ~[atr.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [15:08:10] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:08:10] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[15:08:10] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[15:08:10] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[15:08:10] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[15:08:10] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:08:10] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by sp614x** [comment]
...
Forge Mod Loader version 11.14.4.1577 for Minecraft **1.8** loading
...
Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_**1.8.9**_HD_U_H3 (1).jar

OptiFine for 1.8.9 does not work with Forge for 1.8.

**Comment by 1234fireball** [comment]
2016-03-27 14:18:57,085 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-03-27 14:18:57,086 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[14:18:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:18:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:18:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:18:57] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.1808 for Minecraft 1.8.9 loading
[14:18:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_66
[14:18:57] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_D1.jar
[14:18:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:18:57] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[14:18:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:18:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:18:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:18:57] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[14:18:57] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[14:18:57] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[14:18:57] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[14:18:57] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Declan/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_D1.jar
[14:18:57] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@63440df3
[14:18:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:18:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:18:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:18:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:18:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:19:00] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:19:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:19:00] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[14:19:00] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:19:01] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Catch type is not a subclass of Throwable in exception handler 115
Exception Details:
  Location:
    net/minecraft/client/Minecraft.func_99999_d()V @115: astore_1
  Reason:
    Type 'net/minecraft/util/ReportedException' (constant pool 578) is not assignable to 'java/lang/Throwable'
  Bytecode:
    0x0000000: 2a04 b501 662a b702 45a7 001e 4c2b 1302
    0x0000010: 47b8 024d 4d2c 1302 4fb6 0253 572a 2a2c
    0x0000020: b602 57b6 025b b12a b401 6699 0039 2ab4
    0x0000030: 025d 9900 0a2a b402 5fc7 0020 2ab7 0262
    0x0000040: a7ff e74c 2ab6 0265 2abb 0267 59b7 0268
    0x0000050: b602 6cb8 026f a7ff d12a 2ab4 025f b602
    0x0000060: 5ba7 ffc6 2ab6 0272 a700 684c 2ab6 0272
    0x0000070: a700 614c 2a2b b602 76b6 0257 572a b602
    0x0000080: 65b2 01df 1302 782b b902 7c03 002a 2bb6
    0x0000090: 0276 b602 5b2a b602 72a7 0038 4c2a bb02
    0x00000a0: 4959 1302 7e2b b702 80b6 0257 4d2a b602
    0x00000b0: 65b2 01df 1302 822b b902 7c03 002a 2cb6
    0x00000c0: 025b 2ab6 0272 a700 0b4e 2ab6 0272 2dbf
    0x00000d0: b1b1                                   
  Exception Handler Table:
    bci [5, 9] => handler: 12
    bci [60, 64] => handler: 67
    bci [39, 100] => handler: 107
    bci [39, 100] => handler: 115
    bci [39, 100] => handler: 156
    bci [39, 100] => handler: 201
    bci [107, 108] => handler: 201
    bci [115, 149] => handler: 201
    bci [156, 194] => handler: 201
    bci [201, 202] => handler: 201
  Stackmap Table:
    same_locals_1_stack_item_frame(@12,Object[#572])
    same_frame(@39)
    same_frame(@60)
    same_locals_1_stack_item_frame(@67,Object[#574])
    same_frame(@89)
    same_frame(@100)
    same_locals_1_stack_item_frame(@107,Object[#576])
    same_locals_1_stack_item_frame(@115,Object[#578])
    same_locals_1_stack_item_frame(@156,Object[#572])
    same_locals_1_stack_item_frame(@201,Object[#572])
    same_frame(@208)
    same_frame(@209)

	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Exception in thread "main" [14:19:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:19:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[14:19:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[14:19:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[14:19:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[14:19:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:19:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Still doesnt like working... @sp614x

**Comment by sp614x** [comment]
...
Forge Mod Loader version 11.15.1.1808 for Minecraft **1.8.9** loading
...
OptiFine URL: file:/C:/Users/Declan/AppData/Roaming/.minecraft/mods/OptiFine_**1.7.10**_HD_D1.jar

Mixing versions does not work.
