### ISSUE TITLE
[Crash on startup] 1.16.3pre2 ERROR Game Crashed an unexpected issue occurred and the game has crashed. Exit Code: 0

### ISSUE THREAD

**Issue by NKSHV** [sp614x/optifine#4802]
## Description of Issue
When I launch 1.16.3-OptiFine_HD_U_G3_pre2 from minecraft launcher, it says: ERROR Game Crashed an unexpected issue occurred and the game has crashed. Exit Code: 0
When I launch 1.16.3 without optifine it works
## Steps to Reproduce
When I launch 1.16.3-OptiFine_HD_U_G3_pre2 from minecraft launcher, it says: ERROR Game Crashed an unexpected issue occurred and the game has crashed. Exit Code: 0
When I launch 1.16.3 without optifine it works

## OptiFine Version
 1.16.3-OptiFine_HD_U_G3_pre2 

## Installation Method
use the included standalone installer

## Log Files/Crash Reports
[22:14:12] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[22:14:12] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[22:14:12] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[22:14:13] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:14:13] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[22:14:13] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[22:14:13] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[22:14:13] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[22:14:13] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[22:14:14] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError
	at hk.<clinit>(SourceFile:50) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148) ~[?:1.8.0_252]
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137) ~[?:1.8.0_252]
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_252]
	at java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:869) ~[?:1.8.0_252]
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:948) ~[?:1.8.0_252]
	at hk.<clinit>(SourceFile:50) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at hk.a(SourceFile:88) ~[hk.class:?]
	at kk.a(SourceFile:20) ~[kk.class:?]
	at kk.<clinit>(SourceFile:13) ~[kk.class:?]
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_252]
	at java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:869) ~[?:1.8.0_252]
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:948) ~[?:1.8.0_252]
	at hk.<clinit>(SourceFile:50) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more

## Prior Testing
does not happened on vanilla, don't have forge or fabrick

## Additional Information
When I launch 1.16.3-OptiFine_HD_U_G3_pre2 from minecraft launcher, it says: ERROR Game Crashed an unexpected issue occurred and the game has crashed. Exit Code: 0
When I launch 1.16.3 without optifine it works

**Comment by LuckyOwl1105** [comment]
I have exactly the same problem!!!

**Comment by Feath3rblade** [comment]
I'm also having this issue in 1.16.2 G3

**Comment by amelialutz9** [comment]
I'm having the same issue, did you fix yours?

**Comment by NKSHV** [comment]
> I'm having the same issue, did you fix yours?

I think i changed the java runtime from openjvm to vanilla
