### ISSUE TITLE
[Bug 1.16.3] Optifine with shaders breaks biome mods

### ISSUE THREAD

**Issue by maxanier** [sp614x/optifine#4880]
## Description of Issue
When using Optifine with Shaders enabled, somehow modded biomes will be cleared from the WorlGenRegistry leading to crashes, log spam and missing biomes. 
My mod Vampirism crashes on world creation because the biome registered during startup is not present anymore. (I can avoid that crash, but it still leads to that biome missing in the world (and in the registry) as well as log spam from the biome layer.
I am very confident that this affects any mod that adds biomes (for overworld generation at least).
There have been multiple reports of this and I was able to reproduce it using these shaders: https://www.planetminecraft.com/mod/makeup-ultra-fast-shader/ (Didn't test any others)

## Steps to Reproduce
1. Fresh 1.16.3 install with Forge 
2. Install Optifine and Vampirism and shaders
3. Start game and click SinglePlayer (if you are not redirected to the create new world menu click "Create New world"). Notice that everything is fine
4. Go to the options and enable the shader pack
5. (Optional) Go to the new world menu again and see how everything is still fine.
6. Restart the game and go to the new world menu and it should crash because the biome is not registered

## OptiFine Version
1.16.3_HD_U_G3

## Installation Method
Dropped in mods folder

## Fabric/Forge Version
 1.16.3 - 34.1.0+

## Other Installed Mods
Vampirism: 1.16.3-1.6.0-alpha+20200927-1208 https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/3066684
Example issue: https://github.com/TeamLapen/Vampirism/issues/780

## Log Files/Crash Reports
https://paste.ee/p/bznKt
The crash occurs because (a previously registered) biome is not present in the dynamic biome registry on `OverworldBiomeProvider` creation

**Comment by maxanier** [comment]
Further investigation shows that biomes registered in Forge's `Registry.Register<Biome>` event either never make it to the vanilla dynamic registry or are removed before the Forge CommonSetup event.
`DynamicRegistries.func_239770_b_().func_230521_a_(Registry.BIOME_KEY).get().getValueForKey(ModBiomes.VAMPIRE_FOREST_KEY)` returns null during `CommonSetup` when Optifine + Shaders are installed.
`ForgeRegistries.Biome` seems fine, but the vanilla one is used for world generation

**Comment by superninjakiwi** [comment]
This also affects ore generation negatively from what I've seen. In conjunction with several biome mods, certain modded ores started showing up in 2x2 columns composed randomly of those ores, and vanilla ores such as iron and coal were not visible at all. Ore generation and biome generation are both handled similarly in 1.16.3, I believe, so fixing one _should_ fix the other.

**Comment by CindyBlendy** [comment]
I was also able to reproduce this with Optifine + Shaders + Biomes O Plenty (same steps to reproduce as above except replace Vampirism with BOP)

Also, getting a log spamming issue (the line below repeats):

[m[33m[03:31:05] [Worker-Main-22/WARN] [minecraft/Layer]: Unknown biome id:

**Comment by maxanier** [comment]
Thx to @TelepathicGrunt 's Blame mod I would pinpoint the cause of this issue to here:
```
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: java.lang.Exception: Stack trace
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.util.registry.DynamicRegistries.handler$zzb000$onInit(SourceFile:574)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.util.registry.DynamicRegistries.<clinit>(SourceFile:150)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.util.BiomeUtils.getBiomeRegistry(BiomeUtils.java:52)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.util.BiomeUtils.<clinit>(BiomeUtils.java:30)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:60)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:30)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:901)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:865)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1154)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:967)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.loadConfig(Shaders.java:739)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.startup(Shaders.java:2077)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.Config.initDisplay(Config.java:220)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at com.mojang.blaze3d.platform.GlStateManager.func_227666_a_(GlStateManager.java:403)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at com.mojang.blaze3d.platform.GLX._init(GLX.java:151)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(SourceFile:1043)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.client.main.Main.main(Main.java:149)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[m[32m[13:22:40] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Forstride** [comment]
Sure would love for this to be fixed so I can stop getting multiple reports about it every single day...

**Comment by Siuolthepic** [comment]
Could this be tried with a custom biome datapack? (Both on forge and vanilla.) Might be able to get more info about this. I have a feeling this relates to 4769 but Im not 100% sure.

**Comment by TelepathicGrunt** [comment]
@Siuolthepic This one? https://github.com/sp614x/optifine/issues/4769

Datapacks register directly into the DynamicRegistry so they aren't affected by the class being classloaded too early. I even tested with making my mod classload it at initialization and the worldgen datapacks still worked. But if the said datapack's JSON references modded stuff that need to be registered, then it will explode with optifine on. I feel like that #4769 issue report is a similar but different issue caused by how optifine handles worldgen registries.

**Comment by Siuolthepic** [comment]
I see. Well still, it allows me to understand the issue a lil better.

**Comment by revoltinsurgence** [comment]
issue still persists with OptiFine 1.16.3_HD_U_G4_pre2 and Sildur's Shaders

**Comment by Oct0bass** [comment]
Please can we get an update on this?

**Comment by Forstride** [comment]
Yeah, I second an update on this.  I'm getting really tired of dealing with constant issue reports to *us* and having to redirect people here.

**Comment by Jazzinghen** [comment]
I am having the same issue and I just wanted to drop some extra log files.
I had to remove a ton of duplicated lines that made the files 50MB+.
Hope this is useful

[latest_snip.log](https://github.com/sp614x/optifine/files/5470155/latest_snip.log)
[debug_snip.log](https://github.com/sp614x/optifine/files/5470157/debug_snip.log)

**Comment by AaronLMorgan** [comment]
Encountering a similar issue that I believe is in the same vein. While using Optifine 1.16.3 HD U G3, Yung's Better Mineshafts, and BSL or Complementary (A BSL Edit). The Stronghold will not generate. You cannot throw an Eye of Ender and the 'locate' command doesn't work. Attached the latest log from my game. Hope this helps!

[latest.log](https://github.com/sp614x/optifine/files/5472527/latest.log)

**Comment by lulabyte** [comment]
Any fixes yet?

**Comment by revoltinsurgence** [comment]
not in 1.16.3_HD_U_G5_MOD, no. still crashes when used with BOP & Slidur's Shaders :/

**Comment by lulabyte** [comment]
Poop

**Comment by Edern76** [comment]
It seems to break more than just the custom biomes not spawning in, since when generating a world with Optifine + Shaders and a biome mod loaded, the world will be entirely composed of extremely small single-biome islands, regardless of whether you use the default world-gen preset or a preset added by a mod (e.g Quark Realistic).

Ocean biomes however seem to generate fine.

**Comment by superninjakiwi** [comment]
It's less consistent than that. My world was actually generated with normal landmasses, but without any vanilla ores, and modded ores were generating in strange clumps, at least back on 1.16.1.

**Comment by Forstride** [comment]
I just did a small test on 1.16.4, and it seems to be fixed?  Needs more testing, but just trying it with BOP and a shader pack, it seems to be fine upon restarting the game and reloading a world.

**Comment by lulabyte** [comment]
We just got everything upgraded to 1.16.3 from 1.16.1 T_T I was hoping we could stick to 1.16.3 my people are sick of upgrading and worlds getting corrupted but I guess them's the breaks. Minecraft seems to update every few days and it kind of drives me nuts.

**Comment by lulabyte** [comment]
Hey tho:

I just installed the latest 1.16.3 Optifine and it seems to be working with my BOP worlds now! 8D

Need to test a bit further but it looks like it's been updated since I was last messing with it?

**Comment by lulabyte** [comment]
Can confirm OptiFine HD U G5 is working with the latest BOP 1.16.3 version, single player and server. No crashes. MY BEAUTIFUL SHADERS ARE BACK. I can't tell you how much more enjoyable this makes Minecraft for me. In fact, it wasn't until I discovered shaders and texture packs 6 months ago that I even considered playing Minecraft cause the game was too ugly for me!

Thank you for your work and enduring my whining.

**Comment by Edern76** [comment]
> I just did a small test on 1.16.4, and it seems to be fixed? Needs more testing, but just trying it with BOP and a shader pack, it seems to be fine upon restarting the game and reloading a world.

Can confirm world gen doesn't crash anymore when shader packs are with the BOP preset on 1.16.4, and the surface landmasses seem to generate correctly on all presets now.

However now it's the ore spawning that is broken : no vanilla ores will spawn when shader packs are used with biome mods. I suspect this is related to these lines in the log :

`[12Nov2020 10:30:20.738] [Render thread/ERROR] [net.minecraft.world.biome.BiomeGenerationSettings/]: Feature: Not a JSON object: "minecraft:ore_debris_small"; Not a JSON object: "minecraft:ore_debris_large"; Not a JSON object: "minecraft:ore_quartz_nether"; Not a JSON object: "minecraft:ore_gold_nether"; Not a JSON object: "minecraft:ore_blackstone"; Not a JSON object: "minecraft:ore_gravel_nether"; Not a JSON object: "minecraft:ore_magma"; Not a JSON object: "minecraft:red_mushroom_nether"; Not a JSON object: "minecraft:brown_mushroom_nether"; Not a JSON object: "minecraft:glowstone"; Not a JSON object: "minecraft:glowstone_extra"; Not a JSON object: "minecraft:patch_fire"; Not a JSON object: "minecraft:spring_lava"; Not a JSON object: "minecraft:spring_closed"
[12Nov2020 10:30:20.746] [Render thread/ERROR] [net.minecraft.world.biome.BiomeGenerationSettings/]: Feature: Not a JSON object: "minecraft:disk_gravel"; Not a JSON object: "minecraft:disk_clay"; Not a JSON object: "minecraft:disk_sand"; Not a JSON object: "minecraft:ore_lapis"; Not a JSON object: "minecraft:ore_diamond"; Not a JSON object: "minecraft:ore_redstone"; Not a JSON object: "minecraft:ore_gold"; Not a JSON object: "minecraft:ore_iron"; Not a JSON object: "minecraft:ore_coal"; Not a JSON object: "minecraft:ore_andesite"; Not a JSON object: "minecraft:ore_diorite"; Not a JSON object: "minecraft:ore_granite"; Not a JSON object: "minecraft:ore_gravel"; Not a JSON object: "minecraft:ore_dirt"`

**Comment by edenprojectde** [comment]
Confirming once more the same kind of logs are in my game using G5 1.16.3

**Comment by maxanier** [comment]
With G5 and latest Forge it seeems like biome registry somehow works again.
HOWEVER, the original issue is still present, and it still breaks a lot of things related to DynamicRegistries.
This includes many parts of custom world gen.

It's been 1.5 months and 2 Optifine releases, and the devs still haven't event acknowledged this severe issue. Great job.
Sure, they probably do this in their free time (although Optifine ads probably generate a lot of revenue). But I also have to deal with a lot of users reporting issues caused by optifine to me in my free time.

Still the same issue apparently.

```
****************** Blame Report 1.5.0 ******************

 Oh no! Oh god! Someone classloaded DynamicRegistries class way too early!
 Most registry entries for other mods is broken now! Please read the following stacktrace
 and see if you can find which mod broke the game badly and please show them this log file.
 (If you can't tell which mod, let Blame creator, TelepathicGrunt, know!)

 If you are the modder notified, you may be registering/accessing the dynamic
 registries before the world is loaded/made. Please use the registries in
 WorldGenRegistries as that is what DynamicRegistries will copy from when 
 vanilla creates/loads the world (and is why loading DynamicRegistries early breaks all mods)

[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: java.lang.Exception: Stack trace
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at com.telepathicgrunt.blame.main.DynamicRegistriesBlame.classloadedCheck(DynamicRegistriesBlame.java:76)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.util.registry.DynamicRegistries.handler$zzc001$onInit(DynamicRegistries.java:526)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.util.registry.DynamicRegistries.<clinit>(DynamicRegistries.java:46)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.util.BiomeUtils.getBiomeRegistry(BiomeUtils.java:52)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.util.BiomeUtils.<clinit>(BiomeUtils.java:30)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:60)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:30)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:901)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:865)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1154)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:967)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.loadConfig(Shaders.java:739)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.shaders.Shaders.startup(Shaders.java:2077)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.optifine.Config.initDisplay(Config.java:220)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at com.mojang.blaze3d.platform.GlStateManager.func_227666_a_(GlStateManager.java:422)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at com.mojang.blaze3d.platform.GLX._init(GLX.java:151)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(SourceFile:1065)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:433)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.client.main.Main.main(Main.java:149)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:08:54] [Render thread/INFO] [STDERR/]: [java.lang.Thread:dumpStack:1336]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by SatDog92** [comment]
This happens to me on 1.16.4, with OptiFine HD U G5 and Forge 35.0.1/35.0.17, but only when Minecraft with Forge is loaded with shaders on. (therefore, when OFF or Internal are selected as shaders).

For example, a handful of Oh the Biomes You'll Go's biomes generate without any type of structure, while the same happens to Biomes o'Plenty's Nether biomes, but only if, as said before, Minecraft is loaded with an active shader. If you open Minecraft without a shader selected and select it later, biomes seem to generate correctly. It's a start-up issue, i think.

I'll put it in a stupid way: it's as if Byg or BoP say "well, i want to add biomes here", shaders with Optifine reply "no, i don't think you will", and the former replies "well, i will do it when you're sleeping, then".

**Comment by HelveticaToast** [comment]
> It's been 1.5 months and 2 Optifine releases, and the devs still haven't event acknowledged this severe issue. Great job.


Dev*, singular, Optifine is developed by only one person, that's why it takes a while for stuff like this to be fixed, be patient.

**Comment by truhard** [comment]
This issue seems to still be present on OptiFine G5 and the latest forge version 35.0.10. Still no acknowledgment of a 2 month old issue...

**Comment by Cr4fTJuNkiE** [comment]
I know no ETA's, but can we get some kind of conformation this is actually being worked on? This a pretty severe bug here mang. :(

**Comment by jeremie22** [comment]
Does this happen to affect a world generation wherein a huge horizontal (just a 4 blocks high and plain straight wide area both ceiling and floor) cave generates? It's also generating weird floating masses of land and ugly looking cuts, some are even wide, I mean enormous fissures from above sea level all the way through bedrock.

**Comment by sp614x** [comment]
Should be fixed in next preview.

**Comment by maxanier** [comment]
I can confirm, that all my issues have been solved with the latest preview

**Comment by Jazzinghen** [comment]
Thank you for this patch!
