### ISSUE TITLE
Cant install optifine

### ISSUE THREAD

**Issue by Wolfies1011** [sp614x/optifine#4938]
an error message pops up with this message:
java.io.FileNotFoundException: C:\Users\Myname\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.16.3_HD_U_G3\OptiFine-1.16.3_HD_U_G3.jar (Access is denied)
  at java.io.FileOutputStream.open0(Native Method)
  at java.io.FileOutputStream.open(Unknown Source)
  at java.io.FileOutputStream.<init>(Unknown Source)
  at java.io.FileOutputStream.<init>(Unknown Source)
  at optifine.Patcher.process(Patcher.java:72)
  at optifine.Installer.installOptiFineLibrary(Installer.java:374)
  at optifine.Installer.doInstall(Installer.java:96)
  at optifine.InstallerFrame.onInstall(InstallerFrame.java:425)
  at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:490)
  at optifine.InstallerFrame.access$7(InstallerFrame.java:484)
  at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
  at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
  at java.awt.Component.processMouseEvent(Unknown Source)
  at javax.swing.JComponent.processMouseEvent(Unknown Source)
  at java.awt.Component.processEvent(Unknown Source)
  at java.awt.Container.processEvent(Unknown Source)
  at java.awt.Component.dispatchEventImpl(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Window.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
  at java.awt.EventQueue.access$500(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue.dispatchEvent(Unknown Source)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.run(Unknown Source)

I have no idea what happened, it was working fine last night but I let my mum onto my laptop and now its doing this

**Comment by Jorkles** [comment]
Go to this file location `C:\Users\<user>\AppData\Roaming.minecraft\libraries\optifine\OptiFine\` delete the folder named "1.16.2_HD_U_G3" and then go back to optifine.net and re-download optifine
