### ISSUE TITLE
[Crash] Optifine crashes when the swamp biome isn't registered.

### ISSUE THREAD

**Issue by LeoDog896** [sp614x/optifine#5088]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
Join a Minestom server (https://github.com/Minestom/Minestom) with optifine. Since it doesn't register any biomes by default, it causes optifine to crash because the swamp biome isn't there.

## OptiFine Version
06.11.2020 1.16.4

## Installation Method
Standalone

## Log Files/Crash Reports
https://pastebin.com/Hae4UEPz

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Nope, if Optifine is installed regardless of the installation process it crashes.

**Comment by sp614x** [comment]
The crash doesn't seem to be related to the biome handling.
Can you post a list of Minestom servers for testing?

**Comment by TheMode** [comment]
Here is how we are able to support players with Optifine https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/extras/optifine/OptifineSupport.java#L28
The PLAINS biome is the only one registered by default, adding those two makes everything work.

I will edit my message once I have a server to share or remember the exact location of the problematic code

**Comment by sp614x** [comment]
OptiFine expects all of the vanilla biomes to be existing by default.

**Comment by TheMode** [comment]
Is it a design choice? I believe that Optifine should be able to comply with the game protocol

**Comment by sp614x** [comment]
Can you post a Minestom server IP for testing?
I don't know exactly what crashes when vanilla biomes are missing.

**Comment by TheMode** [comment]
I currently do not have any hosted server, here is a JAR that can be used for testing: https://cdn.discordapp.com/attachments/786079397110874135/792767299153166366/MinestomTest-1.0-SNAPSHOT-all.jar
Works with a vanilla client, crash using Optifine (tested with the latest version: https://pastebin.com/WQ5PAeR1)

The server binds to 0.0.0.0:25565 (first run will generate 2 folders in the current directory) in 1.16.4

The only registered biome is "minecraft:plains" and is the biome used for the whole world (I do not know if it is possible to do not specify a biome in the chunk packet)

**Comment by sp614x** [comment]
The crash:
```
java.lang.IllegalStateException: Missing: ResourceKey[minecraft:worldgen/biome / minecraft:swamp]
	at net.minecraft.util.registry.Registry.func_243576_d(Registry.java:495)
	at net.optifine.util.BiomeUtils.onWorldChanged(BiomeUtils.java:43)
	at net.minecraft.client.renderer.WorldRenderer.setWorldAndLoadRenderers(WorldRenderer.java:869)
	at net.minecraft.client.Minecraft.updateWorldRenderer(Minecraft.java:2467)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2384)
	at net.minecraft.client.network.play.ClientPlayNetHandler.handleJoinGame(ClientPlayNetHandler.java:421)
	at net.minecraft.network.play.server.SJoinGamePacket.processPacket(SJoinGamePacket.java:126)
	at net.minecraft.network.play.server.SJoinGamePacket.processPacket(SJoinGamePacket.java:1)
	at net.minecraft.network.PacketThreadUtil.lambda$0(PacketThreadUtil.java:34)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:172)
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:28)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:134)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.drainTasks(ThreadTaskExecutor.java:115)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1193)
	at net.minecraft.client.Minecraft.run(Minecraft.java:726)
	at net.minecraft.client.main.Main.main(Main.java:214)
```

**Comment by TheMode** [comment]
Great, do you plan on fixing it? Or should we keep our dirty fix?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
