### ISSUE TITLE
hi when i try to install optifine this message pops up 

### ISSUE THREAD

**Issue by xSpace00x** [sp614x/optifine#5135]
Hi when i try to install optifine for 1.16.4 this message pops up

**Comment by xSpace00x** [comment]
java.io.FileNotFoundException: C:\Users\Alper\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.16.4_HD_U_G5\OptiFine-1.16.4_HD_U_G5.jar (Access Denied)
  at java.io.FileOutputStream.open0(Native Method)
  at java.io.FileOutputStream.open(Unknown Source)
  at java.io.FileOutputStream.<init>(Unknown Source)
  at java.io.FileOutputStream.<init>(Unknown Source)
  at optifine.Patcher.process(Patcher.java:72)
  at optifine.Installer.installOptiFineLibrary(Installer.java:374)
  at optifine.Installer.doInstall(Installer.java:96)
  at optifine.InstallerFrame.onInstall(InstallerFrame.java:425)
  at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:490)
  at optifine.InstallerFrame.access$7(InstallerFrame.java:484)
  at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
  at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
  at java.awt.Component.processMouseEvent(Unknown Source)
  at javax.swing.JComponent.processMouseEvent(Unknown Source)
  at java.awt.Component.processEvent(Unknown Source)
  at java.awt.Container.processEvent(Unknown Source)
  at java.awt.Component.dispatchEventImpl(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Window.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
  at java.awt.EventQueue.access$500(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue.dispatchEvent(Unknown Source)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by xSpace00x** [comment]
pls help me

**Comment by Aurumaker72** [comment]
This isn't a proper github issue... Read the first fucking line and you will see it couldn't find a file

**Comment by schrodingerspsycho** [comment]
Aurumaker72? don't be rude

as for an issue, there is the solution

Q: I can't install OptiFine/I get an error when trying to install OptiFine.
A: If you get the error "java.io.FileNotFoundException: C:\Users\<user>\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\<optifine_version>\<optifine_file_name>.jar (Access Denied)"
Here is the fix:
Go to the file location C:\Users\<your username here>\AppData\Roaming\.minecraft\libraries\optifine\OptiFine And delete the folder named the version you are trying to install, then restart your pc.
