### ISSUE TITLE
[Crash] Instant crash after forge early-loading

### ISSUE THREAD

**Issue by JWTHDYTWA** [sp614x/optifine#5250]
## Description of Issue
The game instantly crashes after forge early loading.

## Steps to Reproduce
1. Install preview_OptiFine_1.16.5_HD_U_G7_pre4
2. Install immersive-portals-0.14-mc1.16.4-forge
3. Press "PLAY"

## OptiFine Version
preview_OptiFine_1.16.5_HD_U_G7_pre4

## Installation Method
.jar

## Fabric/Forge Version
Forge 35.1.37

## Other Installed Mods
https://pastebin.com/WUZjiVRi

## Log Files/Crash Reports
https://pastebin.com/TxYb9RCK

Binary search showed that `immersive-portals-0.14-mc1.16.4-forge` is causing the issue.

**Comment by JWTHDYTWA** [comment]
I have to add: older OF version worked fine. Likely, G6 pre.

**Comment by Moleculor** [comment]
I get something somewhat similar with Forge 36.0.1, Minecraft 1.16.5, and just Optifine and Immersive Portals. 

https://gist.github.com/Moleculor/59c509ceb6d41a66a5ed18eb454bfa7c

**Comment by sp614x** [comment]
Immersive Portals is not compatible with the latest shaders changes.
More specifically the field `Shaders.activeDrawBuffers` have been changed.
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_mixins_optifine.json:MixinShaders_Swap] from phase [DEFAULT] in config [imm_ptl_mixins_optifine.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 26 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field activeDrawBuffers was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:616)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more
```
