### ISSUE TITLE
1.7.10 Crashed game at startup

### ISSUE THREAD

**Issue by KiraLinux** [sp614x/optifine#527]
[crash-2017-03-14_21.18.12-client.zip](https://github.com/sp614x/optifine/files/842311/crash-2017-03-14_21.18.12-client.zip)
Updated optifine with the penultimate to the latest version
And the game now crashes

**Comment by KiraLinux** [comment]
[crash-2017-03-14_21.50.18-client.zip](https://github.com/sp614x/optifine/files/842382/crash-2017-03-14_21.50.18-client.zip)
Attempt to load the game again but with all settings reset

**Comment by sp614x** [comment]
Relevant part of the crash:
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/RenderGlobal.func_72714_a(F)V @1176: getfield
  Reason:
    Type integer (current frame, stack[0]) is not assignable to 'net/minecraft/client/renderer/RenderGlobal'
  Current Frame:
    bci: @1176
    flags: { }
    locals: { 'net/minecraft/client/renderer/RenderGlobal', float, 'net/minecraft/util/Vec3', float, float, float, 'net/minecraft/client/renderer/Tessellator', '[F', float, float, float, float, float }
    stack: { integer }
```

**Comment by sp614x** [comment]
Some other mod is incorrectly patching the class RenderGlobal.
Possible conflicting mod is BetterFoliage. 
There are too many core mods installed which can cause this problem.

**Comment by KiraLinux** [comment]
Indicate problematic mods please

**Comment by KiraLinux** [comment]
And on the last version of the optifine everything works

**Comment by SetantaLP** [comment]
That's right, but the last version of optifine has no shader-support, this version has. So there are more classes/code parts that are modified by optifine, which means that it's possible that you now have a crash even if the problematic code-modification is much older.

**Comment by Neuromantix** [comment]
Delete Fastcraft from modpack. Without it working well.

**Comment by KiraLinux** [comment]
I have not Fastcraft

**Comment by sp614x** [comment]
Loaded core plugins, one of them is conflicting with OptiFine:

    Enqueued coremod AppEngCore 
    Enqueued coremod BetterFoliageLoader 
    Enqueued coremod CodeChickenCorePlugin 
    Enqueued coremod CraftingTweaks 
    Enqueued coremod dsurroundcore 
    Enqueued coremod EnderCorePlugin 
    Enqueued coremod IC2core 
    Enqueued coremod ItemPatchingLoader 
    Enqueued coremod MalisisCorePlugin 
    Enqueued coremod MicdoodlePlugin 
    Enqueued coremod NEICorePlugin 
    Enqueued coremod OpenBlocksCorePlugin 
    Enqueued coremod OpenModsCorePlugin 
    Enqueued coremod B3M_CorePlugin

**Comment by platinumphoenix2** [comment]
I get crashes with fastcraft using OptiFine 1.7.10 HD U D7.
My world loads a lot slower without fastcraft, although its the mod causing the crash.

`Description: Registering texture

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureMap
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.k(F:68)
	at net.minecraft.client.renderer.texture.AbstractTexture.func_147631_c(AbstractTexture.java)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:30)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:52)
	at net.minecraft.client.gui.FontRenderer.bindTexture(FontRenderer.java:1075)
	at net.minecraft.client.gui.FontRenderer.<init>(FontRenderer.java:128)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:488)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more`

**Comment by HaggardCar7790** [comment]
[crash-2017-03-23_00.41.56-client.txt](https://github.com/sp614x/optifine/files/863758/crash-2017-03-23_00.41.56-client.txt
I had the same issue as well and removing fastcraft solved it

**Comment by DrAAA-X** [comment]
Fixxx

**Comment by sp614x** [comment]
This can only be fixed in FastCraft as it patches the OptiFine classes.
