### ISSUE TITLE
Screenshot with Antialiasing get divided by zero error

### ISSUE THREAD

**Issue by EchoEndr** [sp614x/optifine#5286]
When taking a screenshot with F2, the chat logs get the error "Cannot take screenshot : / by zero"
The chat logs from when this happens:
`[13:11:20] [IO-Worker-219/WARN]: Couldn't save screenshot
java.lang.ArithmeticException: / by zero
    at det.a(NativeImage.java:478) ~[det.class:?]
    at det.a(NativeImage.java:443) ~[det.class:?]
    at det.a(NativeImage.java:405) ~[det.class:?]
    at dkh.lambda$saveScreenshotRaw$2(ScreenShotHelper.java:140) [dkh.class:?]
    at dkh$$Lambda$5605/1255066787.run(Unknown Source) [dkh.class:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[13:11:20] [main/INFO]: [CHAT] Couldn't save screenshot: / by zero`
This only happens when antialiasing is turned on, and when shaders are on without enabling the antialiasing option from the Quality menu.

**Comment by Regnander** [comment]
Which version of OptiFine do you have? This was reported in #5228 and then fixed in a future release.

**Comment by EchoEndr** [comment]
Sorry about that! I'm using the newest officially released version of OptiFine, the one detailed in that post. Thanks for clearing this up.
