### ISSUE TITLE
[BUG] Game crashes on preparing/launch

### ISSUE THREAD

**Issue by gamersi** [sp614x/optifine#5375]
## Description of Issue
I start the game and nothing even opens. There's just a Error message, when I turn on the Log window
I also tried reinstalling it several times

## Steps to Reproduce
1. I start the game

## OptiFine Version
1.16.1 HD U G2

## Installation Method
with the installer from the official website

## Log Files/Crash Reports
In the gam log theres the following Error: 
`Exception in thread "main" java.lang.SecurityException: class "v"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(SourceFile:64)`

## F3 Debug Screenshot
Its not starting

## Prior Testing
- Does this happen in Vanilla without OptiFine? **No**

## Additional Information
I first got something with Javaw usage and now there was this error

**Comment by gamersi** [comment]
When I launch another version of OptiFine I get this error(Its in german bc my computer is in german): 
`
Verwendung: javaw [-options] class [args...]
(zur Ausführung einer Klasse)
oder  javaw [-options] -jar jarfile [args...]
(zur Ausführung einer JAR-Datei)
wobei options Folgendes umfasst:
-d32	  Verwendet ein 32-Bit-Datenmodell, sofern verfügbar
-d64	  Verwendet ein 64-Bit-Datenmodell, sofern verfügbar
-server	  zur Auswahl der "server" VM`

**Comment by gamersi** [comment]
I found out that it is caused by THe MC Beta. It now works fine for me
