### ISSUE TITLE
[Minecraft Crash] I use the minecraft Shiginima Launcher and I'm making a modpack, but when you add this crash

### ISSUE THREAD

**Issue by NathanGamer1290** [sp614x/optifine#5414]
Os detalhes do Crash:

Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[23:20:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:20:49] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:20:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:20:49] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[23:20:49] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_261, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_261
[23:20:49] [main/INFO] [FML]: Searching C:\Users\HP\AppData\Roaming\.minecraft\mods for mods
[23:20:49] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from .OptiFine_1.12.2_HD_U_F5.jar
[23:20:49] [main/WARN] [FML]: The coremod Backpacked (com.mrcrayfish.backpacked.asm.BackpackedPlugin) is not signed!
[23:20:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in cxlibrary-1.12.1-1.6.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:20:49] [main/WARN] [FML]: The coremod cubex2.cxlibrary.CoreModLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:20:49] [main/WARN] [FML]: The coremod CXLibraryCore (cubex2.cxlibrary.CoreModLoader) is not signed!
[23:20:49] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from MalisisCore-1.12.2.jar
[23:20:49] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:20:49] [main/WARN] [FML]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[23:20:49] [main/WARN] [FML]: The coremod ObfuscatePlugin (com.mrcrayfish.obfuscate.asm.ObfuscatePlugin) is not signed!
[23:20:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:20:49] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:20:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in RandomThings-MC1.12.2-4.2.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:20:49] [main/WARN] [FML]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:20:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in redstonepaste-mc1.12-1.7.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:20:49] [main/WARN] [FML]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:20:49] [main/WARN] [FML]: The coremod NWRTweak (net.fybertech.nwr.NWRTweak) is not signed!
[23:20:49] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from wolfarmor-1.12.2-3.7.5-universal-signed.jar
[23:20:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Xaeros_Minimap_21.4.1_Forge_1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:20:49] [main/WARN] [FML]: The coremod XaeroMinimapPlugin (xaero.common.core.XaeroMinimapPlugin) is not signed!
[23:20:49] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50.jar
[23:20:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:20:49] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[23:20:49] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
Exception in thread "main" [23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.fail(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.access$100(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$1.next(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.checkCerts(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.preDefineClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[23:20:49] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 19 more

**Comment by ZenithRogue** [comment]
We do not support hacked clients

**Comment by NathanGamer1290** [comment]
> Não daremos suporte para clientes ilegais de pirataria

Isso não faz sentido, deviam ajudar todos os jogadores, só por eu não poder comprar o cliente original não dão ajuda? Deviam mudar essas regras!
