### ISSUE TITLE
[1.16] [Compat Issuse] Crash with Mekanism

### ISSUE THREAD

**Issue by KhanhPham05** [sp614x/optifine#5464]
## Description of Issue
`NullPointerExeption` when open energy cube gui in nether
I submitted this issue to mekanism but with out optifine, it works ok 

## Steps to Reproduce
1. Place Ultimate Energy Cube
2. open GUI
## OptiFine Version
OF : G8 pre8

## Installation Method
on optifine.net

## Fabric/Forge Version
36.1.0
java : 14

## Other Installed Mods
OptiForge

## Log Files/Crash Reports
[Crash](https://pastebin.com/hy81SzY6)

- Does this happen without other mods installed? 
   - Only OptiFine and Forge
- Does this happen without any mods at all?
   - Forge + Mekanism

**Comment by sp614x** [comment]
The crash is in the Mekanism GUI classes:
```
java.lang.NullPointerException: Rendering screen
	at mekanism.client.gui.GuiMekanismTile.renderTitleText(GuiMekanismTile.java:57) ~[mekanism:10.0.21] {re:classloading}
	at mekanism.client.gui.machine.GuiElectricPump.drawForegroundText(GuiElectricPump.java:59) ~[mekanism:10.0.21] {re:classloading}
	at mekanism.client.gui.GuiMekanism.func_230451_b_(GuiMekanism.java:163) ~[mekanism:10.0.21] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:122) ~[?:?] 
```

**Comment by sp614x** [comment]
The GUI tile is null:
https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/client/gui/GuiMekanismTile.java#L57

**Comment by BentoGambin** [comment]
I wasn't able to replicate. with latest Mekanism at least.

**Comment by KhanhPham05** [comment]
But i tried w/o OF in nether but it works fine, with optifine, it crash, mekanism team tell me that some thing corrupted the screen initialisation in OF

**Comment by KhanhPham05** [comment]
I will close this issue due to no reply for a long time
