### ISSUE TITLE
[Shaders] Broken shaders.

### ISSUE THREAD

**Issue by TerminalHash** [sp614x/optifine#5613]
## Description of Issue
How does the render generally work for someone now, if the game actively writes the following to the log:

```
[01:31:41] [main/ERROR]: OpenGL API ERROR: 1 (GL_INVALID_ENUM in glCreateShaderObjectARB(GL_GEOMETRY_SHADER))
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.ARBShaderObjects.glCreateShaderObjectARB(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at net.optifine.shaders.Shaders.createGeomShader(Shaders.java:2813) [Shaders.class:?]
	at net.optifine.shaders.Shaders.setupProgram(Shaders.java:2613) [Shaders.class:?]
	at net.optifine.shaders.Shaders.init(Shaders.java:2359) [Shaders.class:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4108) [Shaders.class:?]
	at dzz.a(GameRenderer.java:949) [dzz.class:?]
	at dzz.a(GameRenderer.java:693) [dzz.class:?]
	at djz.e(SourceFile:1048) [djz.class:?]
	at djz.e(SourceFile:681) [djz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
[01:31:41] [main/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: create
```

The error, depending on the shader, can be repeated as many times as you like. It produces the following result:

![image](https://user-images.githubusercontent.com/64691722/116830109-92c65f80-abb0-11eb-8759-b733a1ec5964.png)
![image](https://user-images.githubusercontent.com/64691722/116830112-9d80f480-abb0-11eb-8bc6-72151aa5cdd0.png)

The version for a certain number worked perfectly, now NOTHING works. (Although, if the very many lags is considered ideal ...)

The bug is confirmed on AMD (on Linux) and NVIDIA (on Windows 10) video cards.

**Comment by TerminalHash** [comment]
And even though you switch to different shaders, it is not repaired at all, because there is an obvious error in the code of the mod itself.

**Comment by ShadowGoat128134** [comment]
I don't have any help, but did this happen to work in 1.16.3 before breaking in the latest version? Just wondering if this is similar to the bug I reported

**Comment by TerminalHash** [comment]
> I don't have any help, but did this happen to work in 1.16.3 before breaking in the latest version? Just wondering if this is similar to the bug I reported

It seems that the developer, without notice, is stupidly bumping support to the newest video cards and unscrewing the old ones. Or he simply simply does not know how to write renderings, since all this happens and all the tickets hang here for YEARS.

**Comment by mindforger** [comment]
what a great way to apriciate a single persons work for attempting to improve gameplay quality without forcing you to pay anything ... maybe you should take over the development yourself since your wording makes you look so much better :D 

you should apply for a full time job in ticket managing for him, so no tickets get forgotten, without any pay naturally, only donations

**Comment by ShadowGoat128134** [comment]
Do you have any actual evidence that this issue is caused by support being dropped for older cards or is that just a random assumption you're making?

**Comment by TerminalHash** [comment]
> Do you have any actual evidence that this issue is caused by support being dropped for older cards or is that just a random assumption you're making?

Assumption, don't worry.

**Comment by ShadowGoat128134** [comment]
Why would you say don't worry when you're saying the wrong option?

**Comment by KaiAF** [comment]
Could you send a f3 debug menu screenshot? And the full crash log?
