### ISSUE TITLE
[Crash] Short description 

### ISSUE THREAD

**Issue by SPEEDYMAN56** [sp614x/optifine#5622]
## Description of Issue 
 Optifine in the 1.16 versions of MineCraft have a nullpointerexception error and i don't know whats causing it.

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
 1.16.1- 1.16.2-1.16.3-1.16.4-1.16.5

## Installation Method
 Yes 

## Fabric/Forge Version
 Forge 

## Other Installed Mods
 it happens when i have optifine installed

## Log Files/Crash Reports
 ---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 5/5/21 6:12 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.GlDebugTextUtils.func_209244_a(GlDebugTextUtils.java:207) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GlDebugTextUtils$$Lambda$2870/1931723660.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokePV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwSwapBuffers(GLFW.java:4572) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:108) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraftforge.fml.client.EarlyLoaderGUI.renderTick(EarlyLoaderGUI.java:79) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2999/633103787.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader$SpacedRunnable.run(ClientModLoader.java:89) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:41) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2911/420215012.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2912/2055962129.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$450/557386040.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GlDebugTextUtils.func_209244_a(GlDebugTextUtils.java:207) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GlDebugTextUtils$$Lambda$2870/1931723660.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokePV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwSwapBuffers(GLFW.java:4572) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:108) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraftforge.fml.client.EarlyLoaderGUI.renderTick(EarlyLoaderGUI.java:79) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2999/633103787.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader$SpacedRunnable.run(ClientModLoader.java:89) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:41) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2911/420215012.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2912/2055962129.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$450/557386040.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 794703400 bytes (757 MB) / 1962409984 bytes (1871 MB) up to 6323437568 bytes (6030 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6784m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.16.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.16
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		Cucumber-1.16.4-4.1.9.jar                         |Cucumber Library              |cucumber                      |4.1.9               |CREATE_REG|NOSIGNATURE
		Hats-1.16.5-10.1.0.jar                            |Hats                          |hats                          |10.1.0              |CREATE_REG|NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |CREATE_REG|NOSIGNATURE
		flatbedrock-1.16.4-1.1.6.jar                      |Flat Bedrock                  |flatbedrock                   |1.16.4-1.1.6        |CREATE_REG|NOSIGNATURE
		Bountiful Baubles FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |CREATE_REG|NOSIGNATURE
		jei-1.16.5-7.6.4.90.jar                           |Just Enough Items             |jei                           |7.6.4.90            |CREATE_REG|NOSIGNATURE
		Uppers-0.3.2.jar                                  |Uppers                        |uppers                        |0.3.2               |CREATE_REG|NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |CREATE_REG|NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |CREATE_REG|NOSIGNATURE
		IronJetpacks-1.16.4-4.2.0.jar                     |Iron Jetpacks                 |ironjetpacks                  |4.2.0               |CREATE_REG|NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |CREATE_REG|NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |CREATE_REG|NOSIGNATURE
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar      |Forge Endertech               |forgeendertech                |7.1.0.0             |CREATE_REG|NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |CREATE_REG|NOSIGNATURE
		Controlling-7.0.0.15.jar                          |Controlling                   |controlling                   |7.0.0.15            |CREATE_REG|NOSIGNATURE
		Placebo-1.16.4-4.4.2.jar                          |Placebo                       |placebo                       |4.4.2               |CREATE_REG|NOSIGNATURE
		dankstorage-3.16.jar                              |Dank Storage                  |dankstorage                   |3.16                |CREATE_REG|NOSIGNATURE
		citadel-1.6.3.jar                                 |Citadel                       |citadel                       |1.6.3               |CREATE_REG|NOSIGNATURE
		alexsmobs-1.10.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.0              |CREATE_REG|NOSIGNATURE
		appliedenergistics2-8.3.0-beta.2.jar              |Applied Energistics 2         |appliedenergistics2           |8.3.0-beta.2        |CREATE_REG|95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        |CREATE_REG|NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |CREATE_REG|NOSIGNATURE
		Powah-1.16.5-2.3.16.jar                           |Powah                         |powah                         |2.3.16              |CREATE_REG|NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |CREATE_REG|NOSIGNATURE
		Bookshelf-1.16.5-10.0.7.jar                       |Bookshelf                     |bookshelf                     |10.0.7              |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		u_team_core-1.16.5-3.2.1.195.jar                  |U Team Core                   |uteamcore                     |3.2.1.195           |CREATE_REG|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		DarkUtilities-1.16.5-8.0.9.jar                    |Dark Utilities                |darkutils                     |8.0.9               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Apotheosis-1.16.4-4.5.2.jar                       |Apotheosis                    |apotheosis                    |4.5.2               |CREATE_REG|NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |CREATE_REG|NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.15.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.15            |CREATE_REG|NOSIGNATURE
		iChunUtil-1.16.5-10.2.0.jar                       |iChunUtil                     |ichunutil                     |10.2.0              |CREATE_REG|NOSIGNATURE
		mininggadgets-1.7.5.jar                           |Mining Gadgets                |mininggadgets                 |1.7.5               |CREATE_REG|NOSIGNATURE
		JustEnoughResources-1.16.4-0.12.0.109.jar         |Just Enough Resources         |jeresources                   |0.12.0.109          |CREATE_REG|NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.261.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.261           |CREATE_REG|NOSIGNATURE
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |CREATE_REG|NOSIGNATURE
		BotanyPots-1.16.5-7.0.17.jar                      |BotanyPots                    |botanypots                    |7.0.17              |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		forge-1.16.5-36.1.16-universal.jar                |Forge                         |forge                         |36.1.16             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |CREATE_REG|NOSIGNATURE
		twilightforest-1.16.5-4.0.435-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |CREATE_REG|NOSIGNATURE
		mob_grinding_utils-1.16.5-0.4.21.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.16.5-0.4.21       |CREATE_REG|NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |CREATE_REG|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.16-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |CREATE_REG|NOSIGNATURE
		thermal_foundation-1.16.4-1.2.0.jar               |Thermal Series                |thermal                       |1.2.0               |CREATE_REG|NOSIGNATURE
		TConstruct-1.16.5-3.0.3.136.jar                   |Tinkers' Construct            |tconstruct                    |3.0.3.136           |CREATE_REG|NOSIGNATURE
		useful_backpacks-1.16.5-1.12.0.89.jar             |Useful Backpacks              |usefulbackpacks               |1.12.0.89           |CREATE_REG|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |CREATE_REG|NOSIGNATURE
		thermal_innovation-1.16.4-1.2.0.jar               |Thermal Innovation            |thermal_innovation            |1.2.0               |CREATE_REG|NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.459-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.439   |CREATE_REG|NOSIGNATURE
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |CREATE_REG|NOSIGNATURE
		valkyrielib-1.16.5-3.0.8.0.jar                    |ValkyrieLib                   |valkyrielib                   |1.16.5-3.0.8.0      |CREATE_REG|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |CREATE_REG|NOSIGNATURE
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               |CREATE_REG|NOSIGNATURE
		ironfurnaces-1.16.5-2.6.7.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.7               |CREATE_REG|NOSIGNATURE
		AdLods-1.16.4-4.1.5.1-build.0118.jar              |Large Ore Deposits            |adlods                        |4.1.5.1             |CREATE_REG|NOSIGNATURE
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |CREATE_REG|NOSIGNATURE
		SolarFluxReborn-1.16.3-16.2.5.jar                 |Solar Flux Reborn             |solarflux                     |16.2.5              |CREATE_REG|NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |CREATE_REG|NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |CREATE_REG|NOSIGNATURE
		Mantle-1.16.5-1.6.92.jar                          |Mantle                        |mantle                        |1.6.92              |CREATE_REG|NOSIGNATURE
		thermal_cultivation-1.16.4-1.2.0.jar              |Thermal Cultivation           |thermal_cultivation           |1.2.0               |CREATE_REG|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |CREATE_REG|NOSIGNATURE
		FluxNetworks-1.16.5-6.1.7.12.jar                  |Flux Networks                 |fluxnetworks                  |6.1.7.12            |CREATE_REG|NOSIGNATURE
		blockcarpentry-1.16-0.3.5b.jar                    |BlockCarpentry                |blockcarpentry                |1.16-0.3.5b         |CREATE_REG|NOSIGNATURE
		thermal_expansion-1.16.4-1.2.0.jar                |Thermal Expansion             |thermal_expansion             |1.2.0               |CREATE_REG|NOSIGNATURE
		simplegens-1.16.5-3.0.8.0.jar                     |Simple Generators             |simplegens                    |1.16.5-3.0.8.0      |CREATE_REG|NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |CREATE_REG|NOSIGNATURE
		ftb-ultimine-1605.2.0-build.26-forge.jar          |FTB Ultimine                  |ftbultimine                   |1605.2.0-build.26   |CREATE_REG|NOSIGNATURE
		tombstone-1.16-6.3.5.jar                          |Corail Tombstone              |tombstone                     |6.3.5               |CREATE_REG|NOSIGNATURE
		obfuscate-0.6.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.1               |CREATE_REG|e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		BetterStrongholds-1.16.4-1.0.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.0.1        |CREATE_REG|NOSIGNATURE
		expandedstorage-3.0.5+1.16.3.jar                  |Expanded Storage              |expandedstorage               |3.0.5               |CREATE_REG|NOSIGNATURE
		Runelic-1.16.5-7.0.1.jar                          |Runelic                       |runelic                       |7.0.1               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		thermal_locomotion-1.16.4-1.2.0.jar               |Thermal Locomotion            |thermal_locomotion            |1.2.0               |CREATE_REG|NOSIGNATURE
		constructionwand-1.16.5-2.2.jar                   |Construction Wand             |constructionwand              |1.16.5-2.2          |CREATE_REG|NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |CREATE_REG|NOSIGNATURE
		architectury-1.12.148-forge.jar                   |Architectury                  |architectury                  |1.12.148            |CREATE_REG|NOSIGNATURE
		cloth-config-4.11.19-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.19             |CREATE_REG|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |CREATE_REG|NOSIGNATURE
		CodeChickenLib-1.16.4-3.5.1.408-universal.jar     |CodeChicken Lib               |codechickenlib                |3.5.1.408           |CREATE_REG|31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.16.4-2.7.1.166-universal.jar       |EnderStorage                  |enderstorage                  |2.7.1.166           |CREATE_REG|31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |CREATE_REG|NOSIGNATURE
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |CREATE_REG|NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |CREATE_REG|NOSIGNATURE
	Crash Report UUID: cc8fbf6a-19c8-4474-8ff9-5de392dc5d18
	Launched Version: forge-36.1.16
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

## Prior Testing
 yes its optifine thats causing the issue

## Additional Information
 nothing sorry i don't know whats happening or where it came from i just would like it fixed if possible

**Comment by KaiAF** [comment]
Can you try splitting the mods up so you can find which mod that is causing OptiFine to crash?
