### ISSUE TITLE
Doesn't Start

### ISSUE THREAD

**Issue by Hanbaikii** [sp614x/optifine#5722]
It doesn't start, it just give me an ''glfw error 65543 wgl failed to create opengl context'' window after it crash
I tested the normal 1.17 and it does runs fine
There's the log

18:11:16.398
net.optifine.Log
Render thread
[OptiFine] (Reflector) Method not present: net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.handOffWindow
18:11:21.641
net.minecraft.client.main.Main
Render thread
Failed to create window: 
dpq$a: GLFW error 65543: WGL: Failed to create OpenGL context
	at dpq.b(Window.java:334)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at dpq.<init>(Window.java:132)
	at enw.a(SourceFile:21)
	at dvo.<init>(SourceFile:483)
	at net.minecraft.client.main.Main.main(SourceFile:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
18:11:21.928
launcher
main

18:11:21.929
monitor
Process Monitor
Process ended with exit code 0

**Comment by RaphaSapo** [comment]
I have this error too

**Comment by 0-x-2-2** [comment]
Related to #5739 maybe but on windows with some AMD driver? What OS and what GPU and CPU?

**Comment by Hanbaikii** [comment]
I'm using an old Integrated Intel Graphics Card, It's called ''Intel Family Graphics 4 Series'', and I have Windows 8.1
The Vanilla Minecraft runs fairly well, and Optifine for 1.16 does too, I had problems before updating drivers and OpenGL to run the game because Intel does not keep updating this card anymore

**Comment by Hanbaikii** [comment]
The CPU it's an Core 2 Duo P8700 2.54 GHz

**Comment by Rapozito2000** [comment]
My minecraft just dont open, and exit with a code 1

**Comment by 0-x-2-2** [comment]
> The CPU it's an Core 2 Duo P8700 2.54 GHz

i don't think this gpu is supported by the game at all anymore in 1.17

**Comment by Hanbaikii** [comment]
I can play vanilla without any problems

**Comment by Jiingy** [comment]
CLosing for no follow up provided in the past 2 years.
