### ISSUE TITLE
Not compatible with other sound systems

### ISSUE THREAD

**Issue by IzzelAliz** [sp614x/optifine#581]
Like DynamicSurround, SoundPhysics, AmbientSound
`[18:18:39] [Client thread/INFO] [dsurround/]: Muting sounds
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalStateException: Only one OpenAL context may be instantiated at any one time.
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.AL.create(AL.java:113)
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.AL.create(AL.java:102)
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.AL.create(AL.java:206)
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
[18:18:40] [Thread-11/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.CommandThread.run(CommandThread.java:121)`

**Comment by Ristovski** [comment]
How is this an OptiFine issues? I run 1.11.2 with OptiFine and DynamicSurroundings and it works fine.

**Comment by IzzelAliz** [comment]
I use 1.10.2 Optifine D7, and the Minecraft doesn't have sound output.

**Comment by IzzelAliz** [comment]
I am sorry but, do you still maintenance old-version optifine?

**Comment by Ristovski** [comment]
OptiFine does nothing with sound, this is a mod problem. You most likely have installed 2 conflicting mods (DynamicSurroundings + something else) that register 2 OpenAL contexts.

**Comment by IzzelAliz** [comment]
No, I use 4 sound mod. When no Optifine, they work well, and when I add optifine, they don't wanna work anymore.

**Comment by IzzelAliz** [comment]
Ok, this thread can close now.
It is maybe my computer's problem, I reboot it, the all the matters go away. xD
