### ISSUE TITLE
Minecraft 1.17.1 with OptiFine HD U G9 pre33 wont launch anymore. (Linux)

### ISSUE THREAD

**Issue by SwissGameing2351** [sp614x/optifine#6143]
Minecraft on Ubuntu 18.04 refuses to launch with OptiFine. It can launch without it. Worked fine yesterday until now.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 8/8/21, 8:54 PM
Description: Initializing game

java.lang.NoSuchMethodError: 'boolean com.mojang.blaze3d.platform.GLX.isUsingFBOs()'
	at doy.c(RenderTarget.java:290)
	at doy.a(RenderTarget.java:283)
	at doy.b(RenderTarget.java:406)
	at dvp.<init>(SourceFile:502)
	at net.minecraft.client.main.Main.main(SourceFile:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:188)
	at crystallauncher.MineClient.main(MineClient.java:33)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Render thread
Stacktrace:
	at doy.c(RenderTarget.java:290)
	at doy.a(RenderTarget.java:283)
	at doy.b(RenderTarget.java:406)
	at dvp.<init>(SourceFile:502)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:188)
	at crystallauncher.MineClient.main(MineClient.java:33)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-80-generic
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2542600880 bytes (2424 MiB) / 3221225472 bytes (3072 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
	Identifier: Intel64 Family 6 Model 37 Stepping 5
	Microarchitecture: Westmere (Client)
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Pinewood [Mobility Radeon HD 5570/6550A]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x68c7
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 14052.21
	Virtual memory used (MB): 4811.90
	Swap memory total (MB): 10140.00
	Swap memory used (MB): 0.76
	JVM Flags: 9 total; -Xmx4096M -Xms3072M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-OptiFine_HD_U_G9_pre33
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD REDWOOD (DRM 2.50.0 / 5.4.0-80-generic, LLVM 10.0.0) GL version 4.5 (Compatibility Profile) Mesa 20.0.8, X.Org
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5 CPU 650 @ 3.20GHz
	OptiFine Version: OptiFine_1.17.1_HD_U_G9_pre33
	OptiFine Build: 20210807-213934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 4

**Comment by fayer3** [comment]
does pre32 work? might be related to the fix for #5852

**Comment by Peca21** [comment]
Does it work with the official MC launcher?

**Comment by SwissGameing2351** [comment]
> does pre32 work? might be related to the fix for #5852

I'll try it tommorow.

**Comment by SwissGameing2351** [comment]
> Does it work with the official MC launcher?

I'm assuming it will be the same result.

**Comment by SlimeDog** [comment]
pre32 works fine. The issue was introduced in pre33.

**Comment by SwissGameing2351** [comment]
It does work on vanilla MC launcher and pre32. I prefer crystal launcher, but I'm fine with it either way. Thank you for your suggestions.

**Comment by SlimeDog** [comment]
Why closed? It still needs to be fixed.

**Comment by SwissGameing2351** [comment]
True, but I think it's a problem with the launcher. I'll still reopen.

**Comment by sp614x** [comment]
The OptiFine patch for the GLX class is missing.
Either OptiFine is not installed correctly or another mod is conflicting with it.
The relevant code (RenderTarget and GLX) hasn't been changed in pre33.
May also be caused by the custom launcher.
```
java.lang.NoSuchMethodError: 'boolean com.mojang.blaze3d.platform.GLX.isUsingFBOs()'
at doy.c(RenderTarget.java:290)
```
