### ISSUE TITLE
Let's talk about: the compatibility with forge 1.17.1

### ISSUE THREAD

**Issue by ZekerZhayard** [sp614x/optifine#6216]
The current file structure of OptiFine is not suitable for being loaded by modlauncher, but it only needs to be adjusted slightly, and it will not break the compatibility with the old version of modlauncher/launchwrapper. 

1. Move all `net/minecraftforge/*`, `net/optifine/*` from the root directory to the `notch` directory;
1. Move all the notch-obfuscated class patches from the `patch` directory to the `patch/notch` directory;

After this, the directory structure should look like this: 
```
├───notch (all notch-obfuscated minecraft classes should be extracted here)
│   └───net
│       ├───minecraftforge
│       └───optifine (the notch-obfuscated optifine class)
├───patch
│   ├───assets
│   ├───notch (all notch-obfuscated minecraft class pacthes)
│   └───srg (all srg-obfuscated minecraft class pacthes)
├───srg (all srg-obfuscated minecraft classes should be extracted here)
└ (other file locations remain unchanged)
```

Next are the changes to the configuration file: 

1. `META-INF/MANIFEST.MF` (See [JarMetadata](https://github.com/MinecraftForge/securejarhandler/blob/388d0321a2d3ab5ee8281233324e50b6f4bbdb9c/src/main/java/cpw/mods/jarhandling/JarMetadata.java#L45))
   ```diff
   @@ -1,4 +1,5 @@
    Manifest-Version: 1.0
   +Automatic-Module-Name: optifine
    Main-Class: optifine.InstallerFrame
    TweakClass: optifine.OptiFineForgeTweaker
    TweakOrder: -1000
   ```
1. `patch.cfg`
   https://gist.github.com/ZekerZhayard/6346bb2794796744a0c0ca34aec246e6
1. Use the correct srg mapping to reobfuscate optifine 

Finally, there are changes to the code (The basic code is decompiled by [CFR 0.151](https://www.benf.org/other/cfr/)):
https://gist.github.com/ZekerZhayard/af26a82922bf01fd975fcf0eac40adce

This is the finished product after the above steps: (*Of course, putting it in Forge may not work correctly, because OptiFine is not fully compatible with Forge internally.*)
[OptiFine_1.17.1_HD_U_G9_REPACK.jar.zip](https://github.com/sp614x/optifine/files/7109743/OptiFine_1.17.1_HD_U_G9_REPACK.jar.zip)

**Comment by ejm554** [comment]
Indeed, my game crashed today when I tried to put _OptiFine_1.17.1_HD_U_G9_MOD.jar_ in my mods folder (for a _Forge 37.0.53_ game). Is the REPACK file linked above safe for me, a regular end user, to try? Or is it like recommended for the contributors on this project/repository?

**Comment by ZekerZhayard** [comment]
@ejm554 the REPACK is just to demonstrate how to make optifine be loaded correctly by forge, I did not modify any code other than the parts mentioned above, so it is not fully compatible with the internal forge, just adapted to modlauncher and fml

**Comment by sp614x** [comment]
@ZekerZhayard why should the notch obfuscated classes be moved to a subfolder? 
Is this the problem with the java module loading?

**Comment by ZekerZhayard** [comment]
> Is this the problem with the java module loading?
yes, module jar is not allowed to have default package classes.

**Comment by sp614x** [comment]
@ZekerZhayard The fix for package private access is not needed as `accessClean` already has the access bits (public/protected/private) set to 0 and if no flags are set in `access/access2` then the `accessClean` will be returned.

**Comment by ZekerZhayard** [comment]
@sp614x Because after Java 11, when outer classes access private members of inner classes, no additional synthetic package-private methods are generated, but [nesthost](https://openjdk.java.net/jeps/181) is used to control access. Therefore, when the original members of minecraft are private, and the members after patching are package-private , The current implementation will return private instead of package-private. Because optifine is compiled with java 8, there is no nesthost, that is not correct.
And I got this error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.17.1-37.0.60/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 7 more
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class net.minecraft.core.Direction$Axis tried to access private method 'void net.minecraft.core.Direction$Axis$1.<init>(java.lang.String, int, java.lang.String)' (net.minecraft.core.Direction$Axis and net.minecraft.core.Direction$Axis$1 are in module minecraft@1.17.1 of loader 'TRANSFORMER' @360bc645)
        at MC-BOOTSTRAP/fmlloader@1.17.1-37.0.60/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.client.main.Main.main(Main.java:125)
        ... 13 more
Caused by: java.lang.IllegalAccessError: class net.minecraft.core.Direction$Axis tried to access private method 'void net.minecraft.core.Direction$Axis$1.<init>(java.lang.String, int, java.lang.String)' (net.minecraft.core.Direction$Axis and net.minecraft.core.Direction$Axis$1 are in module minecraft@1.17.1 of loader 'TRANSFORMER' @360bc645)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.core.Direction$Axis.<clinit>(Direction.java:547)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.core.Direction.<clinit>(Direction.java:28)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.world.level.block.state.BlockBehaviour.<clinit>(BlockBehaviour.java:69)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:40)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.world.level.levelgen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.data.worldgen.SurfaceBuilders.<clinit>(SourceFile:11)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.data.BuiltinRegistries.m_123904_(BuiltinRegistries.java:36)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.data.BuiltinRegistries.m_123896_(BuiltinRegistries.java:92)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:91)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.core.Registry.<clinit>(Registry.java:510)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:39)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.client.main.Main.lambda$main$0(Main.java:125)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sp614x** [comment]
This is correct, package private is above private, fixing it.

**Comment by sp614x** [comment]
The change in `ITransformationService.beginScanning()` is incompatible. 

ModLauncher 8.1:
    `void beginScanning(IEnvironment environment)`
ModLauncher 9:
    `default List<Resource> beginScanning(IEnvironment environment)`

It isn't possible to compile a class that is compatible with both interfaces. 
It either fails on compilation with: 
`"The return type is incompatible with ITransformationService.beginScanning(IEnvironment)"` 
or fails at runtime with: 
`"java.lang.AbstractMethodError: Method optifine/OptiFineTransformationService.beginScanning(Lcpw/mods/modlauncher/api/IEnvironment;)V is abstract"`

I will have to use different implementations for ModLauncher 8 and 9.

**Comment by ZekerZhayard** [comment]
yeah, I also encountered the same issue when I contributed to [Mixinbootstrap](https://github.com/LXGaming/MixinBootstrap). At that time, I used a tricky method:
- write the [implementation](https://github.com/LXGaming/MixinBootstrap/pull/47/files#diff-774009f7af86946c71e1388ea50437da21864afec9f3bd3a0cec8a4ed33637e1R1) of `ITransfomationService` of the old modulauncher in `META-INF/services/cpw.mods.modlauncher.api.ITransformationService`, 
- write the [implementation](https://github.com/LXGaming/MixinBootstrap/pull/47/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R158) of `ITransfomationService` of the new modlauncher in `module-info.class` .

**Comment by ZekerZhayard** [comment]
or, when writing the code involved in this issue, I used Gradle to dependent on modlauncher 8 in Maven, and then used Gradle to dependent on modlauncher 9 downloaded locally.

**Comment by sp614x** [comment]
Fixed the SRG mapping to match Forge and the mod loading generally started to work.
Currently crashes when loading a local world with:
```
[Netty Local Client IO #1/ERROR]: Received class net.minecraft.network.protocol.game.ClientboundDisconnectPacket that couldn't be processed
java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl cannot be cast to class net.minecraft.network.protocol.game.ClientGamePacketListener (net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl and net.minecraft.network.protocol.game.ClientGamePacketListener are in module minecraft@1.17.1 of loader 'TRANSFORMER' @59bbe88a)
at net.minecraft.network.protocol.game.ClientboundDisconnectPacket.m_5797_(SourceFile:7) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?]
at net.minecraft.network.Connection.m_129517_(Connection.java:156) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?]
```
The integrtated server is probably crashing on initialization and responding with disconnect packet, but it doesn't log the real exception.

**Comment by ZekerZhayard** [comment]
@sp614x make sure the full name of forge classes are correct:
https://github.com/ZekerZhayard/OptiForge/blob/412a92a5b23e50d8418c249ced094ee9140be5b8/src/main/java/io/github/zekerzhayard/optiforge/asm/transformers/net/optifine/reflect/ReflectorTransformer.java#L27-L36
I can reproduce it if this transformer is disabled.

**Comment by sp614x** [comment]
Fixed Forge class names and the rest of Forge internal compatibility. The patcher is updated to support regex groups.
However Forge only loads the JAR if it is named `OF.jar`. When I rename it to full name 'OptiFine_1.17.1_HD_U_H1_pre2.jar' it crashes with: `java.lang.IllegalArgumentException: OptiFine.1.17.1.HD.U.H1.pre2: Invalid module name: '1' is not a Java identifier`
Looks like it is ignoring the `Automatic-Module-Name` in `MANIFEST.MF`.
Latest version: [OptiFine_1.17.1_HD_U_H1_pre2.jar.zip](https://github.com/sp614x/optifine/files/7205380/OptiFine_1.17.1_HD_U_H1_pre2.jar.zip)

**Comment by sp614x** [comment]
Looks like a JAR file packing problem: https://stackoverflow.com/questions/4727637/how-do-i-verify-the-order-of-manifest-mf-within-jar

**Comment by sp614x** [comment]
H1_pre2 is out and it should run with Forge 37.0.65.

**Comment by ZekerZhayard** [comment]
I think I made a mistake, `optifine.OptiFineTransformationService#toFile` would cause:
![image](https://user-images.githubusercontent.com/41327811/134283794-4f1c17f1-2bd4-4186-a86a-4eef4edd3618.png)

Originally, I thought because `optifine.*` is full of references to `java.util.zip.ZipFile`, changing them to `java.nio.Path` will cause too many changes. but I forgot some characters are invalid in URL/URI, so here is my solution:
```java
    public static File toFile(URI uri) {
        if (!"union".equals(uri.getScheme())) {
            return new File(uri);
        }
        try {
            String path = uri.getPath();
            File file = new File(path.substring(0, path.lastIndexOf("#")));
            ofZipFileUrl = file.toURI().toURL();
            HashMap<String, String> map = new HashMap<String, String>();
            map.put("create", "true");
            FileSystems.newFileSystem(URI.create("jar:" + ofZipFileUrl + "!/"), map);
            return file;
        }
        catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
```

**Comment by sp614x** [comment]
Updated `toFile()`

**Comment by funjon** [comment]
Not just if the file has a space in it, if the file path anywhere has a space in it - a big issue on macOS, where Minecraft by default goes in ~/Library/Application Support/minecraft.

```
Preparing to launch minecraft client for 1.17.1-forge-37.0.65
Checking installations.
Minecraft client 1.17.1-forge-37.0.65 is ready to start.
Starting!
Version does not support log configuration, will assume one plaintext entry per line
2021-09-22 03:45:38,994 main WARN Advanced terminal features are not available in this environment
[03:45:39] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, funjon, --version, 1.17.1-forge-37.0.65, --gameDir, /Users/funjon/Library/Application Support/minecraft, --assetsDir, /Users/funjon/Library/Application Support/minecraft/assets, --assetIndex, 1.17, --uuid, 2886be3df8af403b805c7cf8c40cd1c1, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --width, 1920, --height, 1080, --launchTarget, forgeclient, --fml.forgeVersion, 37.0.65, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]
[03:45:39] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.1 by Microsoft
[03:45:39] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[03:45:39] [main/ERROR] [op.OptiFineTransformationService/]: Error loading OptiFine ZIP file: union:/Users/funjon/Library/Application%20Support/minecraft/mods/OptiFine_1.17.1_HD_U_H1_pre2.jar%2353!
java.lang.NullPointerException: Cannot invoke "java.io.File.getPath()" because "file" is null
at java.util.zip.ZipFile.<init>(ZipFile.java:227) ~[?:?] {}
at java.util.zip.ZipFile.<init>(ZipFile.java:171) ~[?:?] {}
at java.util.zip.ZipFile.<init>(ZipFile.java:185) ~[?:?] {}
at optifine.OptiFineTransformationService.onLoad(OptiFineTransformationService.java:103) ~[?:?] {}
at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:117) ~[modlauncher-9.0.7.jar%235!:?] {}
at java.util.HashMap$Values.forEach(HashMap.java:1067) [?:?] {}
at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:117) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:49) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:87) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
[03:45:39] [main/ERROR] [cp.mo.mo.TransformationServiceDecorator/MODLAUNCHER]: Service failed to load OptiFine
cpw.mods.modlauncher.api.IncompatibleEnvironmentException: Error loading OptiFine ZIP file: union:/Users/funjon/Library/Application%20Support/minecraft/mods/OptiFine_1.17.1_HD_U_H1_pre2.jar%2353!
```

**Comment by ZekerZhayard** [comment]
@sp614x yeah, the stacktrace @funjon posted and the stack you posted are two different issues. We both ignored the power of spaces, haha. Currently, it is not just the problem of `toFile` having escape characters. 
```java
    public List<Resource> completeScan(IModuleLayerManager layerManager) {
        ArrayList<Resource> list = new ArrayList<Resource>();
        ArrayList<SecureJar> jarList = new ArrayList<>();
        // yeah, I ignored that url.getPath and uri.getPath are not the same, the url one cannot restore escape characters 
        // so here need to manually escape with URLDecoder 
        jarList.add(new OptiFineJar(Paths.get(Utils.removePrefix(URLDecoder.decode(ofZipFileUrl.getPath()), "/")))); 
        list.add(new Resource(IModuleLayerManager.Layer.GAME, jarList));
        return list;
    }
```

**Comment by sp614x** [comment]
Fixed it by getting the path in `onLoad()` and then reusing in `completeScan()`.
```
      URI uri = ofZipFileUrl.toURI();
      File file = toFile(uri);
      ofZipFile = new ZipFile(file);
      LOGGER.info("OptiFine ZIP file: " + file);
      // Keep the path
      ofZipFilePath = file.toPath();
```
```
      // Reuse the path
      jarList.add(new OptiFineJar(ofZipFilePath));

```
