### ISSUE TITLE
The game crashed whilst batching chunks 255

### ISSUE THREAD

**Issue by Lo0is** [sp614x/optifine#6487]
## Description of Issue
It happens whenever it loads chunk quickly.

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
Optifine_HD_U_H4

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 18/12/21, 13:07
Description: Batching chunks

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:202)
	at com.google.common.collect.Iterables.toArray(Iterables.java:300)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:635)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:620)
	at esb.<init>(RenderChunk.java:33)
	at esd$a.b(RenderRegionCache.java:106)
	at esd.createRegion(RenderRegionCache.java:55)
	at esa$c.makeChunkCacheOF(ChunkRenderDispatcher.java:1410)
	at esa$c$b.a(ChunkRenderDispatcher.java:970)
	at esa$c$b.a(ChunkRenderDispatcher.java:914)
	at esa.lambda$runTask$0(ChunkRenderDispatcher.java:194)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:202)
	at com.google.common.collect.Iterables.toArray(Iterables.java:300)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:635)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:620)
	at esb.<init>(RenderChunk.java:33)
	at esd$a.b(RenderRegionCache.java:106)
	at esd.createRegion(RenderRegionCache.java:55)

-- Affected level --
Details:
	All players: 2 total; [eop['Loois_'/2473453, l='ClientLevel', x=77.54, y=198.06, z=4742.55], eoq['Erosschs'/2618647, l='ClientLevel', x=89.02, y=193.00, z=4730.20]]
	Chunk stats: 529, 314
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,127,0), Section: (at 0,15,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 44547732 game time, 3057090 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at ell.a(ClientLevel.java:517)
	at dxo.b(SourceFile:2402)
	at esa.lambda$runTask$2(ChunkRenderDispatcher.java:205)
	at dxo.e(SourceFile:722)
	at net.minecraft.client.main.Main.main(SourceFile:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Loois - Redstone 1.18

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.4.0-91-generic
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 794010064 bytes (757 MiB) / 1744830464 bytes (1664 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz
	Identifier: Intel64 Family 6 Model 23 Stepping 10
	Microarchitecture: Penryn (Client) / Penryn (Server)
	Frequency (GHz): 2,60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: GM107 [GeForce GTX 750 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288,00
	Graphics card #0 deviceId: 0x1380
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4015,67
	Virtual memory used (MB): 3835,45
	Swap memory total (MB): 2048,00
	Swap memory used (MB): 459,00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.1-OptiFine_HD_U_H4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 470.86, NVIDIA Corporation
	Window size: 1920x1029
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/Loois - Redstone 1.18 (incompatible)
	Current Language: Italiano (Italia)
	CPU: 2x Pentium(R) Dual-Core CPU E5300 @ 2.60GHz
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 470.86
	OpenGlRenderer: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2`

**Comment by Samsonyte** [comment]
I believe I had this same issue

**Comment by Zminer99** [comment]
I just started having this same issue when using OptiFine_1.18.1_HD_U_H4 today.  I've been using it fairly regularly since its release about a month ago and this is the first day I've had the issue.  I tried 3 times but crashed about 10 or so minutes into being on the server I was on.  The default 1.18.1 didn't give me any issues when I switched back to it.

Attached is one of the crash logs.

[crash-2022-01-17_14.01.17-client.txt](https://github.com/sp614x/optifine/files/7885256/crash-2022-01-17_14.01.17-client.txt)

**Comment by Lo0is** [comment]
> I just started having this same issue when using OptiFine_1.18.1_HD_U_H4 today. I've been using it fairly regularly since its release about a month ago and this is the first day I've had the issue. I tried 3 times but crashed about 10 or so minutes into being on the server I was on. The default 1.18.1 didn't give me any issues when I switched back to it.
> 
> Attached is one of the crash logs.
> 
> [crash-2022-01-17_14.01.17-client.txt](https://github.com/sp614x/optifine/files/7885256/crash-2022-01-17_14.01.17-client.txt)

Were you able to find a solution?

**Comment by Zminer99** [comment]
No, I just started using the normal release of Minecraft again.

**Comment by dfeneck** [comment]
I've started getting this bug now myself as of latest update to 1.18.2-OptiFine_HD_U_H6.

**Comment by anirban0104** [comment]
yep same for me, crashes while running ianxo4's stacking raid farm

**Comment by sp614x** [comment]
Fixed in 1.20.4 preview, to be backported.
