### ISSUE TITLE
Minecraft crashes with optifine and shaders

### ISSUE THREAD

**Issue by philrolfe** [sp614x/optifine#6599]
## Description of Issue
Minecraft crashes repeatedly when playing multiplayer with shaders and Optifine turned on.  Have noticed the following:  it doesn't seem to happen with single player, only multiplayer.  If I allocate less than about 3GB of RAM, I get out of memory errors.  If I allocate 4 GB or more, I get "Exit code 0" errors, which is what I'm pasting into this bug report.  I'm mostly looking for help examining my dump file and I'm hoping that someone will spot a configuration error I have made and help me correct it.

## Steps to Reproduce
Start Launcher
Select Optifine profile
add shaders
start multiplayer
watch it crash.  often.

## OptiFine Version
1.18.1-Optifine_HD_U_H4

## Installation Method
Included standalone installer

## Fabric/Forge Version
No Fabric or Forge

## OptiFabric Version
No OptiFabric as far as I know

## Other Installed Mods
No mods installed

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/7975278/latest.log)
[crash-2022-01-31_20.15.06-client.txt](https://github.com/sp614x/optifine/files/7975281/crash-2022-01-31_20.15.06-client.txt)

## Prior Testing
 Does this happen in Vanilla without OptiFine? 
No.  In fact, it does not happen in OptiFine per se but while using shader packs.

## Additional Information
Thank you to anyone who may be able to help me narrow down my issue.  I have updated my video drivers and have tried to Java that comes bundled with the launcher, but the behavior is the same.  If it better for me to post this somewhere else, please do not flame me, just point me in the right direction.

**Comment by sp614x** [comment]
The graphics card is out of memory where it stores textures, compiled chunks, etc.
You can try the following:
- disable Render Regions
- disable Anisotropic Filtering
- reduce render distance
- use another resource pack
- use another shader pack

```
[20:19:10] [Render thread/ERROR]: OpenGL API ERROR: 0 (Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=34628 java.exe 64bit))
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL15C.nglBufferData(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL15C.glBufferData(GL15C.java:235) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:259) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at com.mojang.blaze3d.platform.GlStateManager._glBufferData(GlStateManager.java:574) ~[GlStateManager.class:?]
	at net.optifine.render.VboRegion.expandVbo(VboRegion.java:274) ~[?:?]
	at net.optifine.render.VboRegion.checkVboSize(VboRegion.java:235) ~[?:?]
	at net.optifine.render.VboRegion.bufferData(VboRegion.java:110) ~[?:?]
```
