### ISSUE TITLE
Crash when turning shaders off

### ISSUE THREAD

**Issue by SolImmortalis** [sp614x/optifine#672]
This issue seems to occur when the biomes o' plenty mod is active with shaders. I did not see any reference to the biomes o' plenty mod in the crash report, but I have also posted this on their page. Other mods appear to work fine, but even using biomes o' plenty in isolation causes this. Turning on a shader works perfectly, but when I set it back to off the screen completely glitches out and the game crashes shortly after. 

Crash Report:
[crash-2017-05-27_13.34.58-client.txt](https://github.com/sp614x/optifine/files/1033846/crash-2017-05-27_13.34.58-client.txt)

Normal Shader Selection:

![2017-05-27_18 29 12](https://cloud.githubusercontent.com/assets/29007011/26524746/7498ff48-430b-11e7-85a3-bbffc3926796.png)

Shader Selection Screen after turning off shaders:

![2017-05-27_18 29 56](https://cloud.githubusercontent.com/assets/29007011/26524750/933966d6-430b-11e7-832d-14edfb5bab8d.png)

Glitched out Screen before crash:

![2017-05-27_18 30 03](https://cloud.githubusercontent.com/assets/29007011/26524751/9c733f88-430b-11e7-9eb6-b11622d642a7.png)

**Comment by SolImmortalis** [comment]
In case the link does not work, here is the crash report again

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 5/27/17 6:30 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1971)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1661)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1361)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1971)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1661)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheUltrocity'/2082, l='MpServer', x=81.29, y=65.00, z=223.39]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (72,64,256), Chunk: (at 8,4,0 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 932 game time, 932 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntityZombie['Zombie'/6144, l='MpServer', x=66.50, y=18.00, z=168.50], EntityZombie['Zombie'/6167, l='MpServer', x=121.50, y=32.00, z=171.50], EntityEnderman['Enderman'/6203, l='MpServer', x=107.50, y=53.00, z=237.29], EntityCreeper['Creeper'/6204, l='MpServer', x=106.35, y=52.00, z=235.02], EntitySkeleton['Skeleton'/6205, l='MpServer', x=106.50, y=50.00, z=266.50], EntityZombie['Zombie'/6220, l='MpServer', x=118.50, y=47.00, z=243.50], EntityZombie['Zombie'/6221, l='MpServer', x=118.50, y=47.00, z=245.50], EntityZombie['Zombie'/6222, l='MpServer', x=116.50, y=47.00, z=242.50], EntityEnderman['Enderman'/6319, l='MpServer', x=122.50, y=47.00, z=254.50], EntityCreeper['Creeper'/6402, l='MpServer', x=20.50, y=28.00, z=200.50], EntityZombie['Zombie'/6487, l='MpServer', x=17.50, y=46.00, z=298.50], EntitySkeleton['Skeleton'/6504, l='MpServer', x=38.50, y=37.00, z=289.50], EntitySkeleton['Skeleton'/6505, l='MpServer', x=36.41, y=35.00, z=299.29], EntitySkeleton['Skeleton'/6506, l='MpServer', x=37.50, y=37.00, z=288.50], EntitySpider['Spider'/6508, l='MpServer', x=38.50, y=37.00, z=285.50], EntityCreeper['Creeper'/6526, l='MpServer', x=18.50, y=61.00, z=258.50], EntityCreeper['Creeper'/6527, l='MpServer', x=20.33, y=61.00, z=258.14], EntitySkeleton['Skeleton'/6540, l='MpServer', x=31.50, y=15.00, z=165.50], EntitySkeleton['Skeleton'/6541, l='MpServer', x=30.50, y=15.00, z=165.50], EntityBat['Bat'/6555, l='MpServer', x=151.34, y=14.05, z=291.61], EntitySkeleton['Skeleton'/6579, l='MpServer', x=126.50, y=25.00, z=205.50], EntityZombie['Zombie'/6583, l='MpServer', x=27.50, y=46.00, z=178.50], EntityPlayerSP['TheUltrocity'/2082, l='MpServer', x=81.29, y=65.00, z=223.39], EntitySkeleton['Skeleton'/4801, l='MpServer', x=118.29, y=18.00, z=288.50], EntityCreeper['Creeper'/4902, l='MpServer', x=24.30, y=24.36, z=164.61], EntityCreeper['Creeper'/4903, l='MpServer', x=22.50, y=26.00, z=158.50], EntityBat['Bat'/5093, l='MpServer', x=55.12, y=21.22, z=252.96], EntitySpider['Spider'/5172, l='MpServer', x=95.50, y=27.00, z=219.50], EntitySpider['Spider'/5176, l='MpServer', x=52.50, y=36.00, z=209.50], EntityCreeper['Creeper'/5177, l='MpServer', x=52.50, y=36.00, z=207.50], EntityCreeper['Creeper'/5243, l='MpServer', x=19.48, y=48.00, z=286.19], EntityBat['Bat'/5282, l='MpServer', x=120.88, y=48.00, z=250.25], EntityBat['Bat'/5314, l='MpServer', x=128.65, y=47.71, z=232.48], EntityBat['Bat'/5319, l='MpServer', x=87.54, y=26.50, z=296.46], EntitySpider['Spider'/5360, l='MpServer', x=16.50, y=30.00, z=158.50], EntityBat['Bat'/5375, l='MpServer', x=73.75, y=30.11, z=247.25], EntityZombieVillager['Zombie Villager'/5388, l='MpServer', x=2.50, y=19.00, z=234.50], EntityZombieVillager['Zombie Villager'/5389, l='MpServer', x=1.50, y=19.00, z=233.50], EntitySkeleton['Skeleton'/5390, l='MpServer', x=2.50, y=19.00, z=228.50], EntityBat['Bat'/5394, l='MpServer', x=32.89, y=34.91, z=227.13], EntityBat['Bat'/5470, l='MpServer', x=2.78, y=25.96, z=264.49], EntityBat['Bat'/5495, l='MpServer', x=95.25, y=26.10, z=207.43], EntityBat['Bat'/5496, l='MpServer', x=98.75, y=26.10, z=216.75], EntityBat['Bat'/3470, l='MpServer', x=24.75, y=24.10, z=250.75], EntityBat['Bat'/3476, l='MpServer', x=66.51, y=25.00, z=232.25], EntityZombie['Zombie'/5525, l='MpServer', x=109.50, y=49.00, z=268.50], EntitySpider['Spider'/5527, l='MpServer', x=110.50, y=49.00, z=268.50], EntitySkeleton['Skeleton'/5542, l='MpServer', x=107.50, y=32.00, z=171.50], EntitySkeleton['Skeleton'/5543, l='MpServer', x=109.50, y=32.00, z=173.50], EntityChicken['Chicken'/1498, l='MpServer', x=2.50, y=73.00, z=255.50], EntityChicken['Chicken'/1500, l='MpServer', x=2.50, y=73.00, z=255.50], EntityChicken['Chicken'/1501, l='MpServer', x=2.50, y=73.00, z=255.50], EntityCreeper['Creeper'/5607, l='MpServer', x=111.50, y=37.00, z=158.50], EntityCreeper['Creeper'/5608, l='MpServer', x=109.50, y=37.00, z=161.50], EntityZombie['Zombie'/5610, l='MpServer', x=106.50, y=49.00, z=249.50], EntityChicken['Chicken'/1518, l='MpServer', x=25.39, y=76.00, z=246.89], EntityChicken['Chicken'/1519, l='MpServer', x=10.07, y=73.00, z=259.50], EntityChicken['Chicken'/1520, l='MpServer', x=15.50, y=77.00, z=256.50], EntityChicken['Chicken'/1521, l='MpServer', x=16.50, y=78.00, z=256.50], EntityChicken['Chicken'/1524, l='MpServer', x=38.50, y=65.00, z=143.50], EntityChicken['Chicken'/1525, l='MpServer', x=33.54, y=65.00, z=144.22], EntityChicken['Chicken'/1526, l='MpServer', x=33.50, y=64.00, z=289.50], EntityChicken['Chicken'/1527, l='MpServer', x=43.11, y=68.00, z=290.52], EntityChicken['Chicken'/1528, l='MpServer', x=37.50, y=68.00, z=284.50], EntityChicken['Chicken'/1533, l='MpServer', x=47.50, y=63.00, z=166.50], EntityChicken['Chicken'/1534, l='MpServer', x=48.50, y=63.00, z=167.50], EntityChicken['Chicken'/1535, l='MpServer', x=44.50, y=63.00, z=165.50], EntityChicken['Chicken'/1536, l='MpServer', x=59.19, y=72.00, z=258.49], EntityChicken['Chicken'/1537, l='MpServer', x=61.13, y=72.00, z=258.50], EntityChicken['Chicken'/1538, l='MpServer', x=56.13, y=72.00, z=257.39], EntityChicken['Chicken'/1539, l='MpServer', x=53.50, y=73.00, z=261.19], EntityChicken['Chicken'/1556, l='MpServer', x=78.52, y=65.00, z=188.89], EntityChicken['Chicken'/1557, l='MpServer', x=73.48, y=64.00, z=193.55], EntitySheep['Sheep'/1558, l='MpServer', x=86.57, y=63.00, z=200.34], EntitySheep['Sheep'/1559, l='MpServer', x=91.49, y=67.00, z=189.76], EntityChicken['Chicken'/1600, l='MpServer', x=128.84, y=63.00, z=154.45], EntityChicken['Chicken'/1601, l='MpServer', x=138.49, y=63.00, z=153.20], EntityChicken['Chicken'/1602, l='MpServer', x=136.50, y=63.00, z=156.50], EntityChicken['Chicken'/1603, l='MpServer', x=136.71, y=63.00, z=153.58], EntitySheep['Sheep'/1604, l='MpServer', x=138.29, y=63.00, z=153.86], EntitySheep['Sheep'/1605, l='MpServer', x=140.58, y=63.00, z=159.83], EntitySheep['Sheep'/1606, l='MpServer', x=145.50, y=64.00, z=157.50], EntitySheep['Sheep'/1607, l='MpServer', x=148.50, y=65.00, z=153.50], EntityChicken['Chicken'/1608, l='MpServer', x=143.86, y=69.00, z=244.43], EntityChicken['Chicken'/1609, l='MpServer', x=146.50, y=70.00, z=234.50], EntityChicken['Chicken'/1610, l='MpServer', x=145.50, y=70.00, z=235.50], EntityChicken['Chicken'/1611, l='MpServer', x=142.50, y=71.00, z=232.50], EntitySpider['Spider'/5784, l='MpServer', x=35.50, y=40.00, z=193.50], EntitySkeleton['Skeleton'/5807, l='MpServer', x=104.50, y=47.00, z=263.50], EntityCreeper['Creeper'/3816, l='MpServer', x=34.50, y=62.00, z=254.50], EntityZombie['Zombie'/5871, l='MpServer', x=46.50, y=35.00, z=202.50], EntityCreeper['Creeper'/5892, l='MpServer', x=105.50, y=53.00, z=238.50], EntityZombieVillager['Zombie Villager'/6016, l='MpServer', x=17.50, y=49.00, z=289.50], EntityZombie['Zombie'/6021, l='MpServer', x=15.51, y=44.00, z=175.78], EntityZombie['Zombie'/6022, l='MpServer', x=18.50, y=43.00, z=176.50], EntityCreeper['Creeper'/6110, l='MpServer', x=94.50, y=22.00, z=206.50], EntitySkeleton['Skeleton'/6117, l='MpServer', x=126.50, y=30.00, z=185.50], EntitySpider['Spider'/6141, l='MpServer', x=48.30, y=43.00, z=209.05], EntityZombie['Zombie'/6142, l='MpServer', x=68.50, y=18.00, z=170.50], EntityZombie['Zombie'/6143, l='MpServer', x=68.50, y=18.00, z=168.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 586344424 bytes (559 MB) / 1391001600 bytes (1326 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.38 Powered by Forge 13.20.0.2304 Optifine OptiFine_1.11.2_HD_U_B9 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2304.jar) 
	UCHIJAAAAAAAAA	forge{13.20.0.2304} [Minecraft Forge] (forge-1.11.2-13.20.0.2304.jar) 
	UCHIJAAAAAAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAAAAAAA	betterfoliage{2.1.5} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.5.jar) 
	UCHIJAAAAAAAAA	biomesoplenty{6.1.0.2222} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2222-universal.jar) 
	UCHIJAAAAAAAAA	dsurround{3.3.3.1} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.3.3.1.jar) 
	UCHIJAAAAAAAAA	jei{4.3.3.270} [Just Enough Items] (jei_1.11.2-4.3.3.270.jar) 
	UCHIJAAAAAAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAAAAAAA	jeresources{0.6.4.6} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.4.6.jar) 
	UCHIJAAAAAAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2.jar) 
	UCHIJAAAAAAAAA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2304
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B9
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
