### ISSUE TITLE
[Bug] Chunk batching in 1.18.2

### ISSUE THREAD

**Issue by Mr-Quasi** [sp614x/optifine#6723]
## Description of Issue
When in a chunk with a redstone contraption that overlaps a chunkborder or looking at a point that reduces game-tick the game crashes. Tried the same without using Optifine and no problems at all.

## Steps to Reproduce
Use Optifine HD U H6 in 1.18.2 near redstone contraptions such as a flying machine or moss-farm (ilmango)

## OptiFine Version
OptiFine HD U H6
OptiFine HD U H7 (also in the latest version)

## Installation Method
I used the stand alone installer.

## Log Files/Crash Reports

Time: 28-03-2022 23:09
Description: Batching chunks

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:202)
	at com.google.common.collect.Iterables.toArray(Iterables.java:300)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:635)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:620)
	at eti.<init>(RenderChunk.java:33)
	at etk$a.b(RenderRegionCache.java:106)
	at etk.createRegion(RenderRegionCache.java:55)
	at eth$c.makeChunkCacheOF(ChunkRenderDispatcher.java:1421)
	at eth$c$b.a(ChunkRenderDispatcher.java:981)
	at eth$c$b.a(ChunkRenderDispatcher.java:924)
	at eth.lambda$runTask$0(ChunkRenderDispatcher.java:195)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:202)
	at com.google.common.collect.Iterables.toArray(Iterables.java:300)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:635)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:620)
	at eti.<init>(RenderChunk.java:33)
	at etk$a.b(RenderRegionCache.java:106)
	at etk.createRegion(RenderRegionCache.java:55)

## F3 Debug Screenshot
Game is crashing, back to launcher with additional error message

**Comment by sp614x** [comment]
Fixed in 1.20.4 preview, to be backported.
