### ISSUE TITLE
FTB Beyond 1.8 Optifine and Shaders

### ISSUE THREAD

**Issue by ReportBot9009** [sp614x/optifine#675]
Hello sp614x,

I seem to be getting a ton of crashes after installing Optifine to FTB Beyond 1.8 for 1.10.2. 

I'm on Optifine D8 for 1.10.2

I'm getting these two crashes:
https://paste.ee/p/H0Qwy

https://paste.ee/p/ENT2z

The first one I'm not sure if it is Optifine, but the second one I was shuffling through JEI looking at recipes in Railcraft when it crashed.

Anyway, thanks for all the hard work all these years. I'm sure millions of people, including myself are very grateful for you and your work.

**Comment by sp614x** [comment]
The first crsh is the codechicken library crashing:

```
Caused by: java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291) ~[bnt.class:?]
	at codechicken.lib.render.buffer.BakingVertexBuffer.func_181668_a(BakingVertexBuffer.java:55) ~[BakingVertexBuffer.class:?]
	at codechicken.lib.render.CCRenderState.startDrawing(CCRenderState.java:259) ~[CCRenderState.class:?]
	at codechicken.lib.model.blockbakery.SimpleBlockRenderer.bakeItemQuads(SimpleBlockRenderer.java:79) ~[SimpleBlockRenderer.class:?]
	at codechicken.lib.model.blockbakery.sub.SubBlockBakery.bakeItemQuads(SubBlockBakery.java:109) ~[SubBlockBakery.class:?]
```

the second one is infinityraider crashing:
```
java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.startDrawing(TessellatorBakedQuad.java:103)
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.onStartDrawingQuadsCall(TessellatorBakedQuad.java:91)
	at com.infinityraider.infinitylib.render.tessellation.TessellatorAbstractBase.startDrawingQuads(TessellatorAbstractBase.java:90)
	at com.infinityraider.infinitylib.render.item.BakedInfItemModel.func_188616_a(BakedInfItemModel.java:54)```

**Comment by sp614x** [comment]
Both do not seem to be related to OptiFine.

**Comment by ReportBot9009** [comment]
I see. Sorry to bother then.

**Comment by ReportBot9009** [comment]
What is strange though is I removed Optifine and I have non of these crashes occurring anymore. With Optifine installed these would happen within a couple minutes of loading into the world. I've gone hours now with no crashes and replicating the same problems with no crash. So, is it the interaction between Optifine and these mods? Is Optifine causing the other mods to throw these errors?

I hope you understand.

**Comment by justinpierson** [comment]
I found the issue... it is the Project Red mods specifically the MRTJPCore once I removed that it stopped crashing:

-- Item being rendered --
Details:
	Item Type: mrtjp.core.block.ItemBlockCore@573cb8ee
	Item Aux: 10
	Item NBT: null
	Item Foil: false

Hope this helps.
