### ISSUE TITLE
[Category] Entites getting invisible after rejoin

### ISSUE THREAD

**Issue by Javanosa** [sp614x/optifine#6764]
## Description of Issue
Entities that already exists are invisible after rejoin but can hit you and you can hear them.

## Steps to Reproduce
1. Install craftbukkit 1.12.2 server
2. Join with optifine
3. went outside of the spawnarea, spawn some zombies, in front of you, then rejoin

## OptiFine Version
`Optifine 1.12.2 HD U G5`

## Installation Method
.jar installer
normal mc launcher

## Fabric/Forge Version
no

## OptiFabric Version
no

## Other Installed Mods
no

## Log Files/Crash Reports
```
[14:04:39] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at h.a(Util.java:48) [h.class:?]
	at bib.az(SourceFile:991) [bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.NullPointerException
	at brz.a(SourceFile:458) ~[brz.class:?]
	at kf.a(SourceFile:66) ~[kf.class:?]
	at kf.a(SourceFile:9) ~[kf.class:?]
	at hv$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at h.a(Util.java:47) ~[h.class:?]
	... 9 more
[14:04:40] [main/INFO]: Connecting to localhost, 25565
[14:04:41] [main/INFO]: [CHAT] Jonosa joined the game
[14:04:43] [main/INFO]: Loaded 48 advancements
```

## F3 Debug Screenshot
idk how to add the image here

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- = no it does not happen on vanilla

## Additional Information
does not happen to baby zombies, vilagers, animals, elder guardians, does happen to squids, does happen to vex, does not happen to shulker

**Comment by Ari-RERA-43** [comment]
For the log file, please send the entire log by putting it in a pastebin. To upload the F3 screenshot, just drag it over the area you want to insert it at.

**Comment by Javanosa** [comment]
https://pastebin.com/Gfj1Eu79
![2022-04-26_14 49 00](https://user-images.githubusercontent.com/77454714/165308247-ab1396bf-c3db-4f2e-8989-0168dbc86fbf.png)

**Comment by Javanosa** [comment]
Edit: you need to stop the server again after that and try some times to get the issue

**Comment by Ari-RERA-43** [comment]
Ignore that last comment I'm blind ^
