### ISSUE TITLE
[Bug] `Error executing task on Client` (World Stuck At 100%)

### ISSUE THREAD

**Issue by ErrorBot1122** [sp614x/optifine#6815]
## Description of Issue

I try loading into a world, but it's stuck at 100% when trying. 
When I look at the logs, I see that it gets to 100% then infinitely repeated this error:

```
...
[13:11:50] [Render thread/INFO]: Loaded 7 recipes
[13:11:51] [Render thread/INFO]: Loaded 1141 advancements
[13:11:54] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:11:54] [Render thread/INFO]: Applied 0 biome modifications to 0 of 61 new biomes in 1.457 ms
[13:11:54] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[13:11:54] [Server thread/INFO]: Generating keypair
[13:12:23] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:12:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:36] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:36] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:37] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:37] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:37] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:37] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:38] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:38] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:39] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:39] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:40] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:40] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:41] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:41] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:42] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:42] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:43] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:43] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:44] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:44] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:45] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:45] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:46] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:46] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:47] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:47] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:48] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:48] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:49] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:49] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:50] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:50] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:51] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:51] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:52] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:52] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:53] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:53] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:54] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:54] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:55] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:55] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:56] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:56] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:57] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:57] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:58] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:58] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:59] [Render thread/INFO]: Preparing spawn area: 0%
[13:12:59] [Render thread/INFO]: Preparing spawn area: 0%
[13:13:00] [Render thread/INFO]: Preparing spawn area: 0%
[13:13:00] [Render thread/INFO]: Preparing spawn area: 0%
[13:13:01] [Render thread/INFO]: Preparing spawn area: 0%
[13:13:01] [Render thread/INFO]: Preparing spawn area: 0%
[13:13:02] [Render thread/INFO]: Preparing spawn area: 1%
[13:13:02] [Render thread/INFO]: Preparing spawn area: 1%
[13:13:03] [Render thread/INFO]: Preparing spawn area: 4%
[13:13:03] [Render thread/INFO]: Preparing spawn area: 4%
[13:13:04] [Render thread/INFO]: Preparing spawn area: 4%
[13:13:04] [Render thread/INFO]: Preparing spawn area: 4%
[13:13:05] [Render thread/INFO]: Preparing spawn area: 4%
[13:13:05] [Render thread/INFO]: Preparing spawn area: 4%
[13:13:06] [Render thread/INFO]: Preparing spawn area: 4%
[13:13:06] [Render thread/INFO]: Preparing spawn area: 5%
[13:13:07] [Render thread/INFO]: Preparing spawn area: 6%
[13:13:07] [Render thread/INFO]: Preparing spawn area: 6%
[13:13:08] [Render thread/INFO]: Preparing spawn area: 11%
[13:13:08] [Render thread/INFO]: Preparing spawn area: 11%
[13:13:09] [Render thread/INFO]: Preparing spawn area: 14%
[13:13:09] [Render thread/INFO]: Preparing spawn area: 14%
[13:13:10] [Render thread/INFO]: Preparing spawn area: 19%
[13:13:10] [Render thread/INFO]: Preparing spawn area: 19%
[13:13:11] [Render thread/INFO]: Preparing spawn area: 32%
[13:13:11] [Render thread/INFO]: Preparing spawn area: 32%
[13:13:12] [Render thread/INFO]: Preparing spawn area: 49%
[13:13:12] [Render thread/INFO]: Preparing spawn area: 49%
[13:13:13] [Render thread/INFO]: Preparing spawn area: 50%
[13:13:14] [Render thread/INFO]: Preparing spawn area: 52%
[13:13:14] [Render thread/INFO]: Preparing spawn area: 59%
[13:13:14] [Render thread/INFO]: Preparing spawn area: 59%
[13:13:15] [Render thread/INFO]: Preparing spawn area: 78%
[13:13:15] [Render thread/INFO]: Preparing spawn area: 78%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 85%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 85%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 86%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 86%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 86%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 86%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 86%
[13:13:20] [Render thread/INFO]: Preparing spawn area: 86%
[13:13:22] [Server thread/INFO]: Changing view distance to 4, from 10
[13:13:22] [Server thread/INFO]: Changing simulation distance to 5, from 0
[13:13:26] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2186ms or 43 ticks behind
[13:13:28] [Render thread/INFO]: Time elapsed: 63833 ms
[13:13:28] [Server thread/INFO]: Errorbot1122[local:E:33487bbf] logged in with entity id 406 at (-711.5, 80.0, -35.5)
[13:13:28] [Server thread/INFO]: Errorbot1122 joined the game
[13:13:43] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2665ms or 53 ticks behind
[13:13:45] [Render thread/ERROR]: Error executing task on Client
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_631 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_634.method_11120(class_634.java:364) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.6.jar:?]
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onChunkUnload(IILnet/minecraft/class_2540;Lnet/minecraft/class_2487;Ljava/util/function/Consumer;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ILnet/minecraft/class_2818;Lnet/minecraft/class_1923;)V in fabric-lifecycle-events-v1.mixins.json:client.ClientChunkManagerMixin from mod fabric-lifecycle-events-v1 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-lifecycle-events-v1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.6.jar:?]
	... 19 more
[13:13:45] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_3146(String)" because "this.field_3690.field_1724" is null
	at net.minecraft.class_634.method_11152(class_634.java:1753) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
[13:13:45] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_31549()" because "$$1" is null
	at net.minecraft.class_634.method_11154(class_634.java:1558) ~[client-intermediary.jar:?]
	at net.minecraft.class_2696.method_11697(class_2696.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_2696.method_11054(class_2696.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
[13:13:45] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3690.field_1724" is null
	at net.minecraft.class_634.method_11135(class_634.java:509) ~[client-intermediary.jar:?]
	at net.minecraft.class_2735.method_11802(class_2735.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2735.method_11054(class_2735.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
...
```

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
```
Download Fabric 0.14.6
Add Fabric API 0.54.0
Add Optifabric 1.13.0
Add Optifine 1.18
(If you need to, add download cusfurage pack and do this as a modpack as that is how im doing it.)
Play the game
Create a world
Ether it kicks you saying you disconnected or it just frezzes at 100%
```
## OptiFine Version

`OptiFine_1.18.2_HD_U_H7.jar`

## Installation Method

**Drop in onto mods folder** as you cant install it using cursforge app

## Fabric/Forge Version

`fabric-loader-0.14.6-1.18.2`
`fabric-api-0.54.0+1.18.2`

## OptiFabric Version

`optifabric-1.13.0`

## Other Installed Mods

- `modmenu-3.2.2`

## Log Files/Crash Reports

[latest.txt](https://github.com/sp614x/optifine/files/8838697/latest.txt)

## F3 Debug Screenshot

Non

### If you've installed using Forge/Fabric:
- Does this happen without other mods installed? **YES**
   - Only OptiFine and Forge **???**
   - Only OptiFine, OptiFabric, and Fabric **Yes**
- Does this happen without any mods at all? **No**
   - Only Forge/Fabric by itself. **I Forgot, but i beleve yes**
- Does this happen in OptiFine standalone? **Dont Remember**
- Does this happen in Vanilla without OptiFine? **No**
- Have you tried using a binary search to find which mods cause this issue? **WAT**
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing. **Yes**
   - Does the issue still happen with only the remaining mods installed? **No**
      - Forge/Fabric and remaining mods, without OptiFine **No**

## Additional Information

Im using a custom curseforge mod pack i made, which has a small amount of mods currentlly. (Cursforage seys 8 but all but `Mod Menu` is enabled and that APP dose not regester Optifine and OptiFabric as i added them externally.)

**Comment by fayer3** [comment]
this sounds more like an optifabric issue
see here https://github.com/Chocohead/OptiFabric/issues/726
apparently these version work together
```
fabric-api-0.53.3+1.18.2
optifabric-1.13.0
OptiFine_1.18.2_HD_U_H7
```

**Comment by ErrorBot1122** [comment]
I just tested it and it works! THANK YOU SO MUCH!!!!!!!! I have been trying to fix it for the past week and now I can finally play Minecraft! Thx so much 😀
