### ISSUE TITLE
[Question] How to disable MD5 checks?

### ISSUE THREAD

**Issue by iocmet** [sp614x/optifine#6851]
[00:19:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.IOException: MD5 not matching, name: bjf.class, saved: 035fa591a1968b8a6483431802cb0480, patched: f0f0825f06922c3c9085305e70174a48
[00:19:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:184)
[00:19:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:108)
[00:19:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:72)

I need modify minecraft.jar for some reasons

**Comment by vinc3nz** [comment]
Delete the META-INF Folder in the jar file. It should work then. If not, delete files starting with Mojang in the meta inf folder instead of the whole folder and modify the Manifest

**Comment by vinc3nz** [comment]
Just checked, you need to delete files staring with Mojang in meta-inf and you need to delete everything except for the first 2 lines in Manifest.MF. Make sure the Manifest ends with a new line.
