### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by Nitrolysis** [sp614x/optifine#690]
Hiya, I have just installed 32 mods (to know the maximum amount of mods my PC can run on) and it comes up with this error.. I figured that it has something to do with MalisisDoors as it is the only mod to fail on load up but I reinstalled it, and nothing worked. It isn't the sort of error where minecraft forge tells you it requires another mod for it to work or a different version, minecraft actually crashed and gave me a crash report. Here it is.

**---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (Not-Enough-Items-1.10.2-Recommended.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  FMLPlugin (Inventory-Tweaks-Mod-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 06/06/17 19:11
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MalisisDoors (malisisdoors)
Caused by: java.lang.ExceptionInInitializerError
	at net.malisis.doors.MalisisDoors.postInit(MalisisDoors.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassCastException: [F cannot be cast to [I
	at net.malisis.core.renderer.font.MinecraftFont.setFields(MinecraftFont.java:94)
	at net.malisis.core.renderer.font.MinecraftFont.<init>(MinecraftFont.java:68)
	at net.malisis.core.renderer.font.MalisisFont.<clinit>(MalisisFont.java:73)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 338783736 bytes (323 MB) / 827658240 bytes (789 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D6 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJ	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJ	NotEnoughItems{2.1.3.207} [Not Enough Items] (Not-Enough-Items-1.10.2-Recommended.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.4.218-universal.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJ	BiblioCraft{2.2.3} [BiblioCraft] (BiblioCraft-Mod-1.10.2.jar) 
	UCHIJ	CodeChickenLib{2.5.4.218} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.4.218-universal.jar) 
	UCHIJ	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHIJ	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJ	excore{1.6.2} [EXCore] (Excore-1.10.2.jar) 
	UCHIJ	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-Mod-1.10.2.jar) 
	UCHIJ	fenceoverhaul{1.2.1} [Fence Overhaul] (Fence-Overhaul-Mod-1.10.2.jar) 
	UCHIJ	JEI{3.14.7.416} [Just Enough Items] (Just-Enough-Items-Mod-1.10.2.jar) 
	UCHIJ	FEI{1.0.17.2} [Forever Enough Items] (Forever-Enough-Items-Mod-1.10.2.jar) 
	UCHIJ	friendlyfire{1.3.0} [Friendly Fire] (Friendly-Fire-Mod-1.10.2.jar) 
	UCHIJ	headcrumbs{2.0.2} [Headcrumbs] (Headcrumbs-Mod-1.10.2.jar) 
	UCHIJ	Waila{1.8.0} [Waila] (Hwyla-Mod-1.10.2.jar) 
	UCHIJ	inventoryspam{0.0.5} [Inventory Spam] (Inventory-Spam-Mod-1.10.2.jar) 
	UCHIJ	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.10.2.jar) 
	UCHIJ	journeymap{1.10.2-5.4.6} [JourneyMap] (JourneyMap-Mod-1.10.2-Unlimited.jar) 
	UCHIJ	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	UCHIE	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UCHIJ	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJ	mobends{0.22.5} [Mo'Bends] (Mo-Bends-Mod-1.10.2.jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.10.2.jar) 
	UCHIJ	natura{1.10.2-4.1.0.64} [Natura] (Natura-Mod-1.10.2.jar) 
	UCHIJ	skeleton{1.0.3} [Skeleton] (skeleton-1.10.2-1.0.3.jar) 
	UCHIJ	simplyjuices{1.0.4} [Simply Juices] (Simply-Juices-Mod-1.10.2.jar) 
	UCHIJ	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-Mod-1.10.2.jar) 
	UCHIJ	tinker_io{release 2.4.4} [Tinker I/O] (tinker_io-1.10.2-release 2.4.4.jar) 
	UCHIJ	wailaplugins{MC1.10.2-0.3.0-26} [WAILA Plugins] (WAILA-Plugins-1.10.2.jar) 
	UCHIJ	icse{1.1.0.0} [I Can See Everything] (Wawla-Mod-1.10.2.jar) 
	UCHIJ	wawla{2.3.2.215} [What Are We Looking At] (Wawla-Mod-1.10.2.jar) 
	UCHIJ	WizardSellingMachines{1.0.0} [WizardSellingMachines] (Wizards-Vending-Machine-Mod-1.10.2.jar) 
	UCHIJ	zeiyocraft{0.6.4} [ZeiyoCraft] (ZeiyoCraft-Mod-1.10.2.jar) 
	Loaded coremods (and transformers): 
NEICorePlugin (Not-Enough-Items-1.10.2-Recommended.jar)
  codechicken.nei.asm.NEITransformer
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (Inventory-Tweaks-Mod-1.10.2.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4242' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4242
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 8**

It would be great if someone could tell me why it crashes and a solution to this problem.
Many thanks,
Tommy

**Comment by sp614x** [comment]
This is a conflict with MalisisDoors.
You can try with the latest OptiFine 1.10.2_HD_U_D8.

**Comment by liach** [comment]
Still happens as of E7.
https://gist.github.com/liach/835cc3ae43749cdef089a2c5b039b0f5

**Comment by MRS-OBAMA** [comment]
might have to do something with anisotropic filtering/anti aliasing, happened to me after i turned it on with E7 on mc 1.10.2

**Comment by sp614x** [comment]
This was fixed at one point.
You could try with the latest available version (preview).
```
Caused by: java.lang.ClassCastException: [F cannot be cast to [I
at net.malisis.core.renderer.font.MinecraftFont.setFields(MinecraftFont.java:94)
at net.malisis.core.renderer.font.MinecraftFont.(MinecraftFont.java:68)
at net.malisis.core.renderer.font.MalisisFont.(MalisisFont.java:73)
... 37 more
```

**Comment by pyscho974** [comment]
to leave a note here.. OptiFine_1.10.2_HD_U_E3 works  i tried a few newer versions of optifine none work...  so if u want to use optifine u will need this verion to work with malisis doors. for anyone else seeking this information.
