### ISSUE TITLE
Game crashed while using Optifine prerelease

### ISSUE THREAD

**Issue by rcharizard1013** [sp614x/optifine#6909]
## Description of Issue
 I was flying with an elytra when it randomly crashed. It had worked for about thirty minutes, with the elytra usage totally fine. 

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## Log Files/Crash Reports
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/2/22, 5:07 PM
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at amg.a(SourceFile:84)
	at czv.c(SourceFile:49)
	at czj.g(SourceFile:43)
	at fkd.a(SourceFile:31)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1556)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1518)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1498)
	at net.optifine.ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1894)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:549)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:387)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:321)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:128)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:114)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:68)
	at eyn.renderModelSmooth(ModelBlockRenderer.java:159)
	at eyn.renderModel(ModelBlockRenderer.java:110)
	at eyl.renderBatched(BlockRenderDispatcher.java:91)
	at faj$c$b.a(ChunkRenderDispatcher.java:1095)
	at faj$c$b.a(ChunkRenderDispatcher.java:912)
	at faj.lambda$runTask$0(ChunkRenderDispatcher.java:198)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at amg.a(SourceFile:84)
	at czv.c(SourceFile:49)
	at czj.g(SourceFile:43)
	at fkd.a(SourceFile:31)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1556)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1518)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1498)
	at net.optifine.ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1894)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:549)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:387)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:321)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:128)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:114)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:68)
	at eyn.renderModelSmooth(ModelBlockRenderer.java:159)
	at eyn.renderModel(ModelBlockRenderer.java:110)

-- Thread dumps --
Details:
	Thread dumps: Worker-Main-12: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at amg.a(SourceFile:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at amg.a(SourceFile:82)
	at czv.c(SourceFile:49)
	at czj.g(SourceFile:43)
	at fkd.a(SourceFile:31)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1556)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1518)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1498)
	at net.optifine.ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1894)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:549)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:387)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:321)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:128)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:114)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:68)
	at eyn.renderModelSmooth(ModelBlockRenderer.java:159)
	at eyn.renderModel(ModelBlockRenderer.java:110)
	at eyl.renderBatched(BlockRenderDispatcher.java:91)
	at faj$c$b.a(ChunkRenderDispatcher.java:1095)
	at faj$c$b.a(ChunkRenderDispatcher.java:912)
	at faj.lambda$runTask$0(ChunkRenderDispatcher.java:198)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Stacktrace:
	at amg.a(SourceFile:84)
	at czv.c(SourceFile:49)
	at czj.g(SourceFile:43)
	at fkd.a(SourceFile:31)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1556)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1518)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1498)
	at net.optifine.ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1894)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:549)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:387)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:321)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:128)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:114)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:68)
	at eyn.renderModelSmooth(ModelBlockRenderer.java:159)
	at eyn.renderModel(ModelBlockRenderer.java:110)
	at eyl.renderBatched(BlockRenderDispatcher.java:91)
	at faj$c$b.a(ChunkRenderDispatcher.java:1095)
	at faj$c$b.a(ChunkRenderDispatcher.java:912)
	at faj.lambda$runTask$0(ChunkRenderDispatcher.java:198)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Block model being tesselated --
Details:
	Block: Block{minecraft:sandstone}
	Block location: World: (-3523,61,-760), Section: (at 13,13,8 in -221,3,-48; chunk contains blocks -3536,-64,-768 to -3521,319,-753), Region: (-7,-2; contains chunks -224,-64 to -193,-33, blocks -3584,-64,-1024 to -3073,319,-513)
	Using AO: true
Stacktrace:
	at eyn.renderModel(ModelBlockRenderer.java:110)
	at eyl.renderBatched(BlockRenderDispatcher.java:91)
	at faj$c$b.a(ChunkRenderDispatcher.java:1095)
	at faj$c$b.a(ChunkRenderDispatcher.java:912)
	at faj.lambda$runTask$0(ChunkRenderDispatcher.java:198)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Block being tesselated --
Details:
	Block: Block{minecraft:sandstone}
	Block location: World: (-3523,61,-760), Section: (at 13,13,8 in -221,3,-48; chunk contains blocks -3536,-64,-768 to -3521,319,-753), Region: (-7,-2; contains chunks -224,-64 to -193,-33, blocks -3584,-64,-1024 to -3073,319,-513)
Stacktrace:
	at eyl.renderBatched(BlockRenderDispatcher.java:91)
	at faj$c$b.a(ChunkRenderDispatcher.java:1095)
	at faj$c$b.a(ChunkRenderDispatcher.java:912)
	at faj.lambda$runTask$0(ChunkRenderDispatcher.java:198)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [ewy['lordshade101'/103083, l='ClientLevel', x=-3466.63, y=84.82, z=-898.12]]
	Chunk stats: 841, 460
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,264,0), Section: (at 0,8,0 in 0,16,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 105081 game time, 28553 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:ff5727c:1644) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at etm.a(ClientLevel.java:569)
	at eev.d(SourceFile:2288)
	at eev.f(SourceFile:822)
	at eev.e(SourceFile:723)
	at net.minecraft.client.main.Main.main(SourceFile:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 600888384 bytes (573 MiB) / 1778384896 bytes (1696 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11375H @ 3.30GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2520
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a49
	Graphics card #1 versionInfo: DriverVersion=30.0.100.9864
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37333.81
	Virtual memory used (MB): 19236.08
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 120.21
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19-OptiFine_HD_U_H8_pre2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-11375H @ 3.30GHz
	OptiFine Version: OptiFine_1.19_HD_U_H8_pre2
	OptiFine Build: 20220701-001425
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.1.01.zip
	OpenGlVersion: 3.2.0 NVIDIA 516.59
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Ari-RERA-43** [comment]
This issue has already been reported. Close this issue. 

For a temporary workaround, disable connected textures in quality video settings.

**Comment by KaiAF** [comment]
Reported #6858
