### ISSUE TITLE
[bug] NoSuchMethodError when call tesselateWithAO(...)

### ISSUE THREAD

**Issue by USS-Shenzhou** [sp614x/optifine#6976]
## Description of Issue
NoSuchMethodError ocured when I use `net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO()` in my mod.

## Steps to Reproduce
as the description

## OptiFine Version
HD_U_H7

## Installation Method
HMCL installed Optifine for me.

## Fabric/Forge Version
1.18.2-forge-40.1.25

## Other Installed Mods
You can check my mods at 
[https://github.com/USS-Shenzhou/extinguish/blob/master/src/main/java/cn/ussshenzhou/extinguish/blockentities/ExtinguisherBracketBuiltinEntityRenderer.java#L106](url)

## Log Files/Crash Reports
```
[18:50:13] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:161) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:77) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1929) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1542) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1158) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.client.resources.model.BakedModel, net.minecraft.world.level.block.state.BlockState, net.minecraft.core.BlockPos, com.mojang.blaze3d.vertex.PoseStack, com.mojang.blaze3d.vertex.VertexConsumer, boolean, java.util.Random, long, int, net.minecraftforge.client.model.data.IModelData)'
	at cn.ussshenzhou.extinguish.blockentities.ExtinguisherBracketBuiltinEntityRenderer.renderDisguise(ExtinguisherBracketBuiltinEntityRenderer.java:110) ~[extinguish-0.1.0.tc.jar%2354!/:0.1.0.tc]
	at cn.ussshenzhou.extinguish.blockentities.ExtinguisherBracketBuiltinEntityRenderer.render(ExtinguisherBracketBuiltinEntityRenderer.java:103) ~[extinguish-0.1.0.tc.jar%2354!/:0.1.0.tc]
	at cn.ussshenzhou.extinguish.blockentities.ExtinguisherBracketBuiltinEntityRenderer.m_6922_(ExtinguisherBracketBuiltinEntityRenderer.java:40) ~[extinguish-0.1.0.tc.jar%2354!/:0.1.0.tc]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:107) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.lambda$renderTileEntity$0(BlockEntityRenderDispatcher.java:79) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:154) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?]
	... 20 more
```

## Additional Information
My mod mentioned above works well in a forge-only environment.
Can you fix this problem? Or should I use an other method instead, if I should, what is it?

**Comment by ZekerZhayard** [comment]
In `net.minecraft.client.renderer.block.ModelBlockRenderer`, before 1.16.5, forge added three new overloaded methods `renderModel` `renderModelSmooth` `renderModelFlat`, after 1.17.1, forge in order to unify with mojang name, and the three methods are renamed `tesselateBlock` `tesselateWithAO` `tesselateWithoutAO` but optifine1.18.2 still uses the old names before 1.16.5.

**Comment by USS-Shenzhou** [comment]
for others met this problem: use `tesselateWithAO(BlockAndTintGetter, BakedModel, BlockState, BlockPos, PoseStack, VertexConsumer, boolean, Random, long, int)` instead of `tesselateWithAO(BlockAndTintGetter, BakedModel, BlockState, BlockPos, PoseStack, VertexConsumer, boolean, Random, long, int, IModelData)`
