### ISSUE TITLE
Batching Chunks error.

### ISSUE THREAD

**Issue by Aculoss** [sp614x/optifine#7120]
The game crashed whilst batching chunks
Error: java.util.ConcurrentModificationException

Fabric 1.19.2, fabric loader 0.14.9

**Comment by Aculoss** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-09-24 10:18:08
Description: Batching chunks

java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:202)
	at com.google.common.collect.Iterables.toArray(Iterables.java:300)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:635)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:620)
	at net.minecraft.class_6849.<init>(class_6849.java:33)
	at net.minecraft.class_6850$class_6851.method_39972(class_6850.java:106)
	at net.minecraft.class_6850.createRegion(class_6850.java:55)
	at net.minecraft.class_846$class_851.makeChunkCacheOF(class_846.java:1384)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:970)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:908)
	at net.minecraft.class_846.method_22757(class_846.java:195)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:202)
	at com.google.common.collect.Iterables.toArray(Iterables.java:300)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:635)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:620)
	at net.minecraft.class_6849.<init>(class_6849.java:33)
	at net.minecraft.class_6850$class_6851.method_39972(class_6850.java:106)
	at net.minecraft.class_6850.createRegion(class_6850.java:55)
	at net.minecraft.class_846$class_851.makeChunkCacheOF(class_846.java:1384)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:970)

-- Affected level --
Details:
	All players: 1 total; [class_746['Aculoss'/88, l='ClientLevel', x=136.50, y=222.00, z=-7.50]]
	Chunk stats: 1521, 401
	Level dimension: minecraft:the_nether
	Level spawn location: World: (2,106,3), Section: (at 2,10,3 in 0,6,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 52519471 game time, 54168200 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:581)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_43589(class_310.java:856)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks.zip, Minecarts+with+Wheels.zip

**Comment by sp614x** [comment]
Fixed in 1.20.4 preview, to be backported.
