### ISSUE TITLE
[1.14.4] Crash when running without OptiFine

### ISSUE THREAD

**Issue by Just-rare** [sp614x/optifine#7269]
## Description of Issue
Crash after switching from forge to fabric and removing optifine from modlist

## Steps to Reproduce
1. use optifine and forge
2. switch from forge to fabric
3. delete optifine
4. run minecraft
## OptiFine Version
1.14.4

## Installation Method
dropping optifine into modlist

## Fabric/Forge Version
latest, 1.14.4

## Other Installed Mods
Bad neighbor
fabric api
Voxel map
Immortal coral
Worldedit 
Pick block pro

## Log Files/Crash Reports
Description: Rendering overlay

net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:block/optifine/road_sign/one way traffic
	at net.minecraft.class_2960.<init>(class_2960.java:38)
	at net.minecraft.class_2960.<init>(class_2960.java:43)
	at net.minecraft.class_793.method_4754(class_793.java:181)
	at net.minecraft.class_807.method_3498(class_807.java:63)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.minecraft.class_807.method_4754(class_807.java:63)
	at net.minecraft.class_1088.method_4732(class_1088.java:195)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.minecraft.class_1088.<init>(class_1088.java:195)
	at net.minecraft.class_1092.method_18178(class_1092.java:45)
	at net.minecraft.class_1092.method_18789(class_1092.java:16)
	at net.minecraft.class_4080.method_18791(class_4080.java:11)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

## Prior Testing
 If you've installed standalone:
- Does this happen in Vanilla without OptiFine? yes

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? yes
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all? yes
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone? yes
- Does this happen in Vanilla without OptiFine? yes
- Have you tried using a binary search to find which mods cause this issue? no mods cause this issue
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? yes
      - Forge/Fabric and remaining mods, without OptiFine

**Comment by sp614x** [comment]
Most probably your resource pack uses OptiFine features which are not supported in vanilla.
