### ISSUE TITLE
Unable to launch on MC1.11.2 Forge, no mods

### ISSUE THREAD

**Issue by EzerArch** [sp614x/optifine#727]
Optifine is crashing right at starting up the client window, before the loading screen.

```
[16:34:44] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 13
```

**Log:** https://gist.github.com/EzerArch/4f04796846fb8270773a221b0cde16ea#file-gistfile1-txt-L422

**Specs:**
- Minecraft 1.11.2
- Forge 1.11.2 Forge 2345 (edit: and 2356)
- OptiFine 1.11 HD U B8
- No mods or resource packs.

**Comment by SetantaLP** [comment]
You are using Optifine for 1.11 but Minecraft 1.11.2 which is not compatible with 1.11 (different obfuscation mapping) due to some additions in 1.11.2. So optifine is unable to patch the classes, which results in the errors you got.

**Comment by EzerArch** [comment]
Hey, thank you. :)

**Comment by SetantaLP** [comment]
No problem.
