### ISSUE TITLE
1.11.2 - Crash when enabling anisotropic filtering with dense ores mod

### ISSUE THREAD

**Issue by Barteks2x** [sp614x/optifine#736]
It happens even when changing the "anisotropic filtering" slider when not ingame.

Crash report: [crash-2017-06-29_20.12.06-client.txt](https://github.com/sp614x/optifine/files/1113123/crash-2017-06-29_20.12.06-client.txt)

**Comment by sp614x** [comment]
The crash is in DenseOres, it can not find some texture:
```
java.lang.RuntimeException: java.io.FileNotFoundException: denseores:textures/minecraft/blocks/redstone_ore_dense.png
	at com.rwtema.denseores.client.TextureOre.load(TextureOre.java:307)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:212)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:155)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:764)
```

**Comment by Barteks2x** [comment]
Everything works fine as long as I don't change anisotropic filtering.  Everything else works.
