### ISSUE TITLE
1.12 Optifine C2,C3,C4_pre. Error world loading in fullscreen mode

### ISSUE THREAD

**Issue by JoHarker** [sp614x/optifine#737]
I have tried to load different worlds with versions
1.12_HD_U_**C2** and 1.12_HD_U_**C3** of Optifine and Forge - 1.12-14.21.0.**2331**
and with 1.12_HD_U_**C4_pre** - Forge 1.12-14.21.1.**2387**. 
This forge versions marked as compatible in changelog. But in all cases I have got the same error on loading world. [Log for C4](https://paste.ee/p/ueJtw) and [log for C3](https://paste.ee/p/mi3bl).
After random starting I have realized that error occur with fullscreen mode enabled and without it this work fine. After correct world loading I can enable fullcreen back.

**Comment by sp614x** [comment]
This looks lika a Forge login problem (packet mismatch), does not seem to be related to OptiFine.
```
[03:27:37] [Netty Local Client IO #0/ERROR] [FML]: ChannelRegistrationHandler exception
java.lang.ClassCastException: Cannot cast net.minecraft.client.network.NetHandlerLoginClient to net.minecraft.client.network.NetHandlerPlayClient
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_131]
	at net.minecraftforge.fml.common.network.FMLNetworkEvent$CustomPacketRegistrationEvent.<init>(FMLNetworkEvent.java:147) ~[FMLNetworkEvent$CustomPacketRegistrationEvent.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.fireNetRegistrationEvent(FMLClientHandler.java:924) ~[FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.fireNetRegistrationEvent(FMLCommonHandler.java:612) ~[FMLCommonHandler.class:?]
	at net.minecraftforge.fml.common.network.handshake.ChannelRegistrationHandler.channelRead0(ChannelRegistrationHandler.java:51) ~[ChannelRegistrationHandler.class:?]
	at net.minecraftforge.fml.common.network.handshake.ChannelRegistrationHandler.channelRead0(ChannelRegistrationHandler.java:38) ~[ChannelRegistrationHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[SimpleChannelInboundHandler.class:4.1.9.Final]
```

**Comment by JoHarker** [comment]
Without Optifine forge works fine [log](https://paste.ee/p/oU9ST).
Without forge (executed with standard minecraft launcher) Optifine works fine [log](https://paste.ee/p/fFYpA).
But with both error occur.

**Comment by drb48** [comment]
"Without Optifine forge works fine log.
Without forge (executed with standard minecraft launcher) Optifine works fine log.
But with both error occur."

Both Forge and Optifine are pointing to the other guy as the problem.  Latest Optifine - 1.12_HD_U_C3 - works with Forge up through vers 14.21.0.2362.  Crashes game with any Forge version after that.  Forge changelog for 14.21.0.236 says:

Build 2363:
	fry:
		Cleanup of model system, taking advantage of java 8; replaced guava
		Optional and Function with java 8 versions.

Since that's the version where things break, I suggest the Optifine folks look into that.

**Comment by sp614x** [comment]
There is a preview C4 which works with latest Forge #2387.

This bug is something else, the crash is about invalid login packets in the network communication to server and it happens only in fullscreen mode. OptiFine is definitely not changing the login protocol or anything related to network packets.

Looks like it may be a side effect of something else.

**Comment by sp614x** [comment]
The crash only happens when using custom fullscreen resolution. The default resolution works fine.

**Comment by JoHarker** [comment]
Now I managed to reproduce the crash without fullscreen. I think that it depends on system loading. I start minecraft in same time with worked IDE and browser and get this error without fullscreen. Forgive me, it seems like I just wast your time.
