### ISSUE TITLE
Optifine Doesn't Work With Forge 2389

### ISSUE THREAD

**Issue by kenijey** [sp614x/optifine#742]
here are the logs. preview-OptiFine_1.12_HD_U_C4_pre.jar used with forge 2389. game started, but no optifine. i also checked video settings to approve it.

[fml-client-latest.log.txt](https://github.com/sp614x/optifine/files/1119198/fml-client-latest.log.txt)
[fml-junk-earlystartup.log.txt](https://github.com/sp614x/optifine/files/1119199/fml-junk-earlystartup.log.txt)
[latest.log.txt](https://github.com/sp614x/optifine/files/1119200/latest.log.txt)

**Comment by sp614x** [comment]
Forge can not open the OptiFine ZIP file. It may be damaged, you can try to redownload it.
```
Unable to read the jar file preview-OptiFine_1.12_HD_U_C4_pre.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_25]
	at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_25]
	at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_25]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_25]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_25]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:343) [forge-1.12-14.21.1.2389.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) [forge-1.12-14.21.1.2389.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:100) [forge-1.12-14.21.1.2389.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.12-14.21.1.2389.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12-14.21.1.2389.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) [forge-1.12-14.21.1.2389.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
