### ISSUE TITLE
[1.20/Forge] A strange error appears in the log file...

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7433]
## OptiFine Version
OptiFine_1.20.1_HD_U_I5_pre5_MOD.jar

## Installation Method
Forge

## Fabric/Forge Version
47.0.3

## Error:

```
[OptiFine] 
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "retVal" is null
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:745) ~[OptiFine_1.20.1_HD_U_I5_pre5_MOD.jar%23152!/:?] {re:classloading}
	at net.minecraft.client.KeyboardHandler.lambda$onCharEvent$6(KeyboardHandler.java:697) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_90889_(KeyboardHandler.java:682) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$10(KeyboardHandler.java:741) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$11(KeyboardHandler.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,xf:OptiFine:default}
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46) ~[lwjgl-glfw-3.3.1.jar%2373!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2385!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2373!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:210) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:221) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:369) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23146!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:28) ~[fmlloader-1.20.1-47.0.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at ...(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?] {}
```

**Comment by sp614x** [comment]
Fixed, coming in next preview
