### ISSUE TITLE
[FORGE] Forge 47.0.43 causes errors with Optifine

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7460]
```
[mojang/GlDebug]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL11C.glBindTexture(Native Method) ~[lwjgl-opengl-3.3.1.jar%2381!/:build 7] {}
	at net.minecraftforge.fml.earlydisplay.RenderElement.lambda$mojang$2(RenderElement.java:103) ~[fmlearlydisplay-1.20.1-47.0.43.jar%23145!/:1.0] {}
	at net.minecraftforge.fml.earlydisplay.RenderElement.render(RenderElement.java:62) ~[fmlearlydisplay-1.20.1-47.0.43.jar%23145!/:1.0] {}
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.lambda$paintFramebuffer$6(DisplayWindow.java:252) ~[fmlearlydisplay-1.20.1-47.0.43.jar%23145!/:1.0] {}
	at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?] {}
	at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?] {}
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.paintFramebuffer(DisplayWindow.java:252) ~[fmlearlydisplay-1.20.1-47.0.43.jar%23145!/:1.0] {}
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.render(DisplayWindow.java:268) ~[fmlearlydisplay-1.20.1-47.0.43.jar%23145!/:1.0] {}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:86) ~[forge-1.20.1-47.0.43-universal.jar%23153!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1380) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.0.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.0.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.0.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?] {}
```
`[OptiFine] OpenGL error: 1282 (Invalid operation), at: Expand VBO`

**Comment by sp614x** [comment]
`glBindTexture` can return `GL_INVALID_OPERATION` when the texture was previously created with a different target or when used between glBegin/glEnd.
https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glBindTexture.xml
