### ISSUE TITLE
[Category] Cannot start game

### ISSUE THREAD

**Issue by Yamijeusz** [sp614x/optifine#7518]
## Description of Issue
I cannot start game on forge 1.20.1
It seems that optifine is not compatible with mod create
Produces error code: -1

## Steps to Reproduce
1.I nstal Forge
2. Start game on Forge
3. Add Optifine to mods
4. Start game on Forge with Optifine
5. Add the rest of the mods
6. Start game on Forge with Optifine and the rest of the mods
7. Crash Closing Error: -1

## OptiFine Version
OptiFine_1.20.1_HD_U_I5

## Installation Method
It is in my mods folder

## Fabric/Forge Version
forge-1.20.1-47.1.0-installer
forge-1.20.1-47.1.43-installer

## Other Installed Mods
architectury-9.1.12-forge
awesomedungeonend-forge-1.20.1-3.1.1
awesomedungeon-forge-1.20.1-3.2.0
awesomedungeonnether-forge-1.20.1-3.1.1
awesomedungeonocean-forge-1.20.1-3.3.0
caelus-forge-3.1.0+1.20
cloth-config-11.1.106-forge
create-1.20.1-0.5.1.d
curios-forge-5.2.0-beta.3+1.20.1
elytraslot-forge-6.3.0+1.20.1
journeymap-1.20.1-5.9.12-forge
libraryferret-forge-1.20.1-4.0.0
light-overlay-8.0.0-forge
RoughlyEnoughItems-12.0.634
RoughlyEnoughProfessions-forge-1.20.1-2.0.1
sophisticatedbackpacks-1.20.1-3.18.56.890
sophisticatedcore-1.20.1-0.5.83.395

## Log Files/Crash Reports

[crash-2023-08-07_06.55.35-client.txt](https://github.com/sp614x/optifine/files/12272288/crash-2023-08-07_06.55.35-client.txt)

## Prior Testing
Ive been trying to use diferent forge versions, diferent oftifine fersions and diferent create versions
Descriptions says that one of the mods could nod be loaded but only when i deleted either optifine or create it could load to menu

**Comment by saturnux** [comment]
remove optifine, and mod, the game crash too
it's more forge bue than optifine

altenative solution : change your launcher,for me with  multimc it work

**Comment by 3it-jan-cernin** [comment]
> for me with multimc it work

Are you saying you are able to run forge + optifine + create 1.20.1 in multimc?

**Comment by Yamijeusz** [comment]
If this is what he was saying than i tried and it did not worked

**Comment by SilentWhisperer** [comment]
you are using the wrong version of Optifine
use I6 pre6

**Comment by Yamijeusz** [comment]
Tested already. ain't working
Like i said i tested a couple of diferent optifine versions
It is not forge problem it looks like compatybility problem of optifine and create

**Comment by SilentWhisperer** [comment]
try getting rid of Create
if it starts working it means they aren't compatible

**Comment by Yamijeusz** [comment]
![image](https://github.com/sp614x/optifine/assets/94564459/57a16628-627a-416e-96e6-710a649ea224)

**Comment by saturnux** [comment]
if your are on win11, test OptiFine HD U I6 pre5 on forge Forge 47.1.42

**Comment by Fingernailsss** [comment]
same issue: here is the crash report

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-08-11 12:56:41
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraftforge.client.gui.overlay.ForgeGui.renderSelectedItemName(net.minecraft.client.gui.GuiGraphics, int)'
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$15(VanillaGuiOverlay.java:147) ~[forge-1.20.1-47.1.43-universal.jar%23187!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.1.43-universal.jar%23187!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {re:mixin}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.1.43-universal.jar%23187!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1343) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.43.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$15(VanillaGuiOverlay.java:147) ~[forge-1.20.1-47.1.43-universal.jar%23187!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.1.43-universal.jar%23187!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {re:mixin}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.1.43-universal.jar%23187!/:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Fingernailss'/44, l='ClientLevel', x=-273.73, y=65.08, z=-372.86]]
	Chunk stats: 529, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,82,0), Section: (at 0,2,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 16202 game time, 16202 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:590) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.43.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, file/Better+Sniffer+Eggs.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 924132544 bytes (881 MiB) / 2346713088 bytes (2238 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.00
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.00
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37518.21
	Virtual memory used (MB): 26538.94
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 315.90
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Launched Version: forge-47.1.43
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/Better+Sniffer+Eggs.zip (incompatible)
	Current Language: en_us
	CPU: 20x Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Fingernailss'/44, l='ServerLevel[New World]', x=-273.73, y=65.08, z=-372.86]]
	Data Packs: vanilla, mod:forge, mod:notenoughcrashes (incompatible), mod:moonlight (incompatible), mod:torchflower_arrows, mod:moresnifferflowers (incompatible), mod:jei, mod:snifferplus (incompatible), mod:jeresources, mod:appleskin (incompatible), mod:iceberg (incompatible), mod:advancementframes (incompatible), mod:advancementplaques (incompatible), mod:nyfsspiders (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.20.1_HD_U_I6_pre4
	OptiFine Build: 20230726-185704
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 531.79
	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		notenoughcrashes-4.4.6+1.20.1-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.4.6+1.20.1        |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.7.2-forge.jar                    |Moonlight Library             |moonlight                     |1.20-2.7.2          |DONE      |Manifest: NOSIGNATURE
		torchflower_arrows-1.20.1-1.0.jar                 |Torchflower Arrows            |torchflower_arrows            |1.0                 |DONE      |Manifest: NOSIGNATURE
		moresnifferflowers-1.0.1.jar                      |More Sniffer Flowers          |moresnifferflowers            |1.0.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.25.jar                    |Just Enough Items             |jei                           |15.2.0.25           |DONE      |Manifest: NOSIGNATURE
		Sniffer+-forge-1.20.1-0.2.0.jar                   |Hellion's Sniffer+            |snifferplus                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.238.jar          |Just Enough Resources         |jeresources                   |1.4.0.238           |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.43-universal.jar                |Forge                         |forge                         |47.1.43             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.20.1-2.5.0.jar                |AppleSkin                     |appleskin                     |2.5.0+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.20.1-forge-1.1.13.jar                   |Iceberg                       |iceberg                       |1.1.13              |DONE      |Manifest: NOSIGNATURE
