### ISSUE TITLE
Tesselating Tile Entity

### ISSUE THREAD

**Issue by janagyjr** [sp614x/optifine#757]
I had to disable Optifine (first issue I've ever had with it) to log in to my VIP server.

https://gist.github.com/janagyjr/916e2bd4393845a623c293a89ef7f6d2

I was investigating an issue with my quarry and accidentally placed water up against it. Immediately crashed my client.

Dell Precision T3500
Xeon W3550
12GB RAM
Win 7 x64
FirePro V5900

**Comment by janagyjr** [comment]
Addendum: Optifine causes the Buildcraft quarry to cease functioning.

**Comment by janagyjr** [comment]
Another crash from optifine, this time I was placing down a framed drawer. 

https://gist.github.com/janagyjr/2ebe4e1b39f55022816e5553c21e42c7

**Comment by sp614x** [comment]
Can you post the game output (error log), the real error is shown there.

**Comment by janagyjr** [comment]
You mean the fml logs? As there is nothing specifically noted as an 'error log' aside from the crash report.

**Comment by janagyjr** [comment]
Here are all the logs from the day in question, have fun:

**Comment by janagyjr** [comment]
Just crashed again.

Crash report:
https://gist.github.com/janagyjr/c95357e918fe43f6d2f479743bf06c7a

Game output logs updated for most recent incident in the folder on Dropbox already linked to.

**Comment by sp614x** [comment]
This is the problem:
```
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalArgumentException: Incompatible vertex states
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.shader.TesselatorVertexState.addTessellatorVertexState(TesselatorVertexState.java:67)
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererSmooth.postRenderBlocksSmooth(WorldRendererSmooth.java:424)
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererSmooth.updateRenderer(WorldRendererSmooth.java:331)
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdaterSmooth.updateRenderer(WrUpdaterSmooth.java:252)
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdaterSmooth.updateRenderersImpl(WrUpdaterSmooth.java:98)
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdaterSmooth.updateRenderers(WrUpdaterSmooth.java:57)
[20:07:39] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdates.updateRenderers(WrUpdates.java:71)
```

**Comment by sp614x** [comment]
You could try to:
- set Chunk Loading to Default
- disable shaders if active

**Comment by janagyjr** [comment]
I don't use shaders.

I will see if changing the chunk loading to default will help. I have it set where I do on all the packs I use it in to help improve performance.
