### ISSUE TITLE
[1.20.1] Game Crash on Placing Basic Energizer (Create: New Age mod)

### ISSUE THREAD

**Issue by Flexico** [sp614x/optifine#7610]
## Description of Issue
Create: New Age -- https://www.curseforge.com/minecraft/mc-mods/create-new-age
My game crashes immediately when I try to place the "Basic Energizer" item in the world. This does not happen if I uninstall Optifine.

## Steps to Reproduce
-- Install Create: New Age v1.1.1 and Optifine v1.20.1 HD U I6
-- Craft Basic Energizer
-- On right-clicking  to place it in the world the game crashes immediately.
-- On reloading the world, the item is still in my hand.

## Installation Method
Install Forge v47.2.20 to vanilla launcher, and place Optifine v1.20.1 HD U I6.jar into "mods" folder

## Other Installed Mods
I uninstalled everything except Create, Create: New Age, and Optifine and got the same crash

## Log Files/Crash Reports
[crash-2024-01-27_14.39.54-client.txt](https://github.com/sp614x/optifine/files/14073608/crash-2024-01-27_14.39.54-client.txt)
[latest.log](https://github.com/sp614x/optifine/files/14073610/latest.log)

## F3 Debug Screenshot
![2024-01-27_14 43 31](https://github.com/sp614x/optifine/assets/5751770/550e1d2a-cde6-4d0e-911c-695705b2a79e)

**Comment by Jiingy** [comment]
A prerelease of 1.20.4 has recently been released. Can you verify that the issue also occurs for that version as well?

**Comment by Flexico** [comment]
The Create and Create: New Age mods don't exist for that version yet.

**Comment by VulkoOnDrugs** [comment]
i am currently making a modpack and running into the same issue is optifine the problem

**Comment by LordRomzessV** [comment]
I checked it on my personal build 1.19.2 - the problem is relevant for all existing versions of New Age. OptiFine 1.19.2 HD U I2.

It’s very annoying, because replacing OptiFine is not so easy, I have 8 modifications in a separate folder to replace one of it - and when I use them, FPS is still on average 40% lower than with OptiFine, and Oculus is almost not updated year, which is why it has almost more incompatibilities than OptiFine, which is why I can't use shaders.

Unfortunately, the New Age author does not know how to fix the problem. However, the error is the same in all versions:

```
[01июн.2024 10:37:22.029] [Render thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader cpw.mods.modlauncher.TransformingClassLoader@d66502
[01июн.2024 10:37:22.068] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "org.antarcticgardens.newage.energy.InsertOnlyResizableEnergyContainer.setMaxCapacity(long)" because "this.energy" is null
	at org.antarcticgardens.newage.content.energiser.EnergiserBlockEntity.<init>(EnergiserBlockEntity.java:34) ~[create-new-age-forge-1.19.2-1.0.1.jar%23340!/:1]
	at org.antarcticgardens.newage.content.energiser.EnergiserBlockEntity.newTier1(EnergiserBlockEntity.java:43) ~[create-new-age-forge-1.19.2-1.0.1.jar%23340!/:1]
```

All hope lies with the authors of OptiFine.

**Comment by ryderlol214** [comment]
Having this same issue... Im still confused
