### ISSUE TITLE
Optifine and dev environment

### ISSUE THREAD

**Issue by Barteks2x** [sp614x/optifine#766]
I know there already is https://github.com/sp614x/optifine/issues/196. But the way to make it work outlined there doesn't work (anymore?). Optifine loads, but there are no new video settings options, and I doubt it actually does anything (but I'm not sure).

I want to eventually make optifine compatible with my mod, but without being able to run optifine in dev environment it's not going to be possible (and there is nothing optifine can reasonably do about compatibility, it's just conflicting code patches).

**Comment by SetantaLP** [comment]
I didn't tested it, but I think (the guide)[https://github.com/octarine-noise/simpledeobf/blob/master/README.md#optifine-h5-and-beyond] in the section below the section mentioned in #196 should work (if you ajust the version-numbers), because as far as I know there are no changes to the way optifine works since then. If not, it might help to post the error-log here so that everyone that wants to help, can see what exactly went wrong.

**Comment by Barteks2x** [comment]
There is now error log. It starts just fine, and optifine appears to be there in F3 debug screen, but there are no new options in video settings.

**Comment by Barteks2x** [comment]
I tried with the exact version of forge mentioned in optifine changelog, still the same result. The log: 
[fml-client-latest.log.txt](https://github.com/sp614x/optifine/files/1144637/fml-client-latest.log.txt)

**Comment by SetantaLP** [comment]
That's strange. Did you replaced the tweak-class as mentioned in the guide? Based on the log, it seams that optifine loads it's normal tweak-class and class-transformer, so it can't inject the classes into the class loader (and I'm quite sure it doesn't inject classes, because there are no log-outputs about the Reflector-Class and about ConnectedTextures, which should appear as far as I know).

**Comment by Barteks2x** [comment]
Wait, does the tweaker replacement from the previous section still apply? I didn't know that.

**Comment by Barteks2x** [comment]
So that was a proble on my side, I misunderstood the instructions.

**Comment by SetantaLP** [comment]
Not really misunderstood, you only skipped the important part: "Again, you'll need to create a class transformer that is able to load it [like this](https://github.com/octarine-noise/BetterFoliage/blob/abf037d8a9640594a76b9f2524885da6f440bd41/src/main/kotlin/optifine/OptifineTweakerDevWrapper.kt)."

**Comment by Barteks2x** [comment]
I jumped straight to the "OptiFine H5 and beyond" part, ignoring what was before, thinking this is all I need to do for these newer versions.

**Comment by SetantaLP** [comment]
Yea, and this section describes all you need to do, including the text I quoted in my previous post (which is the last sentence of the second paragraph of the section "OptiFine H5 and beyond".) The only thing not mentioned in this section is the fact that you need to edit the the transformer-entry in the manifest-file, if you use a class that is named differently.

**Comment by Barteks2x** [comment]
I got optifine running in dev environment, but all blocks and items have missing textures. Any idea why?

**Comment by Barteks2x** [comment]
Also, it tends to crash when rendering forge fancy missing model:
```
java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:651)
	at net.minecraft.client.renderer.GlStateManager.bindTexture(GlStateManager.java:508)
	at net.minecraft.client.renderer.texture.TextureUtil.bindTexture(TextureUtil.java:328)
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:57)
	at net.minecraft.client.gui.FontRenderer.bindTexture(FontRenderer.java:1122)
	at net.minecraft.client.gui.FontRenderer.renderDefaultChar(FontRenderer.java:313)
	at net.minecraft.client.gui.FontRenderer.renderChar(FontRenderer.java:300)
	at net.minecraft.client.gui.FontRenderer.renderStringAtPos(FontRenderer.java:570)
	at net.minecraft.client.gui.FontRenderer.renderString(FontRenderer.java:693)
	at net.minecraft.client.gui.FontRenderer.drawString(FontRenderer.java:428)
	at net.minecraft.client.gui.FontRenderer.drawString(FontRenderer.java:407)
	at net.minecraftforge.client.model.FancyMissingModel$BakedModel.getQuads(FancyMissingModel.java:150)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:115)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:54)
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sp614x** [comment]
This issue belongs in the SimpleDeobf issues: https://github.com/octarine-noise/simpledeobf/issues

**Comment by Barteks2x** [comment]
Is it even maintained anymore?

**Comment by sp614x** [comment]
Continued in SimpleDeobf: https://github.com/octarine-noise/simpledeobf/issues/3
