### ISSUE TITLE
[TexturePacks] BetterVanillaBuilding texture pack makes Minecraft crashed

### ISSUE THREAD

**Issue by AliolyMader** [sp614x/optifine#7722]
## Description of Issue
When I use the BetterVanillaBuilding Datapack, the game crashes, but on vanilla Minecraft doesn't 

## Steps to Reproduce

1. What do you do...
2. ...to find this bug?

Launch de Minecraft with and without the texture pack "BetterVanillaBuilding"
## OptiFine Version
1.21 prerelease 2

## Installation Method

With the installer

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-08-27 13:41:09
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.optifine.config.ParserEnchantmentId.parse(ParserEnchantmentId.java:17)
	at net.optifine.CustomItemProperties.parseInts(CustomItemProperties.java:513)
	at net.optifine.CustomItemProperties.<init>(CustomItemProperties.java:154)
	at net.optifine.CustomItems.update(CustomItems.java:210)
	at net.optifine.CustomItems.update(CustomItems.java:122)
	at net.optifine.util.TextureUtils.resourcesPreReload(TextureUtils.java:310)
	at aub.a(ReloadableResourceManager.java:54)
	at fgo.<init>(SourceFile:691)
	at net.minecraft.client.main.Main.main(SourceFile:239)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: java.lang.NegativeArraySizeException: -1
	at java.base/java.lang.reflect.Array.newArray(Native Method)
	at java.base/java.lang.reflect.Array.newInstance(Array.java:78)
	at net.optifine.reflect.ReflectorFields.getFieldValues(ReflectorFields.java:141)
	at net.optifine.util.EnchantmentUtils.makeEnchantmentKeys(EnchantmentUtils.java:53)
	at net.optifine.util.EnchantmentUtils.<clinit>(EnchantmentUtils.java:26)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.config.ParserEnchantmentId.parse(ParserEnchantmentId.java:17)
	at net.optifine.CustomItemProperties.parseInts(CustomItemProperties.java:513)
	at net.optifine.CustomItemProperties.<init>(CustomItemProperties.java:154)
	at net.optifine.CustomItems.update(CustomItems.java:210)
	at net.optifine.CustomItems.update(CustomItems.java:122)
	at net.optifine.util.TextureUtils.resourcesPreReload(TextureUtils.java:310)
	at aub.a(ReloadableResourceManager.java:54)
	at fgo.<init>(SourceFile:691)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:239)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Mac OS X (aarch64) version 14.6.1
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 410955112 bytes (391 MiB) / 671088640 bytes (640 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 10
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1 Pro
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.23
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 10
	Graphics card #0 name: Apple M1 Pro
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MiB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MiB): 16384.00
	Virtual memory used (MiB): 10523.44
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 486425.19, total: 948584.19
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 486425.19, total: 948584.19
	Space in storage for io.netty.native.workdir (MiB): available: 486425.19, total: 948584.19
	Space in storage for java.io.tmpdir (MiB): available: 486425.19, total: 948584.19
	Space in storage for workdir (MiB): available: 486425.19, total: 948584.19
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.21-OptiFine_HD_U_J1_pre2
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3+5
	Backend API: Apple M1 Pro GL version 4.1 Metal - 88.1, Apple
	Window size: <not initialized>
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'optifine'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: es_ES
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 10x Apple M1 Pro
	OptiFine Version: OptiFine_1.21_HD_U_J1_pre2
	OptiFine Build: 20240825-210005
	Render Distance Chunks: 22
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.1 Metal - 88.1
	OpenGlRenderer: Apple M1 Pro
	OpenGlVendor: Apple
	CpuCount: 10

**Comment by SeaOfPixels** [comment]
Same issue as https://github.com/sp614x/optifine/issues/7709.

**Comment by sp614x** [comment]
Fixed in one of the previews.
