### ISSUE TITLE
[1.21.3] XorDevs Default causes many OpenGL errors, and is broken

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7783]
## Description of Issue

XorDevs Default causes many OpenGL errors, and is broken

## Steps to Reproduce

1. Try to apply XorDevs Default

## OptiFine Version

J2_pre1

## Log file

https://mclo.gs/OvfJnem
[latest.log](https://github.com/user-attachments/files/17547159/latest.log)

## Video

https://github.com/user-attachments/assets/eb3b0f56-fe14-43b7-9b44-913076a1abc4

```
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_entities (gbuffers_textured), at: pre-useProgram
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_entities (gbuffers_textured), at: pre-useProgram
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_entities (gbuffers_textured), at: pre-useProgram
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[19:15:25] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_entities (gbuffers_textured), at: pre-useProgram
[19:15:25] [Thread-14/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at ffk.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
```

**Comment by AstromanGaming** [comment]
Same here!

But with Optifine J2_pre5 on Ubuntu 24.10 (with Wayland) and a Nvidia GPU.

But the error no show on Windows 11 in the same pc.

**Comment by Lolothepro** [comment]
not fixed in Preview OptiFine 1.21.3_HD_U_J2_pre7

**Comment by sp614x** [comment]
No errors on Windows with NVidia and Intel graphics.
This may be something specific to Linux drivers.

**Comment by Lolothepro** [comment]
> No errors on Windows with NVidia and Intel graphics. This may be something specific to Linux drivers.

possibly

**Comment by Lolothepro** [comment]
```
[16:55:12] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_block, at: pre-useProgram
[16:55:12] [Thread-16/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at fen.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[16:55:12] [Thread-16/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at fen.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[16:55:12] [Thread-16/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at fen.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[16:55:12] [Thread-16/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at fen.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[16:55:12] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_block, at: pre-useProgram
[16:55:12] [Thread-16/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at fen.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[16:55:12] [Thread-16/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at fen.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
[16:55:12] [Thread-16/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.)
java.lang.Exception: Stack trace
	at fen.a(GlDebug.java:179) ~[minecraft.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.3.jar:build 5]
```
