### ISSUE TITLE
java.lang.NullPointerException: Stitching texture atlas

### ISSUE THREAD

**Issue by JMLG1999** [sp614x/optifine#787]
For some reason, I can't open my modpack with optifine installed.
https://pastebin.com/dpi1izJZ
Fresh install (just did the modpack in the curse/twitch launcher with some mods i would like to try)

**Comment by JMLG1999** [comment]
Did some testing (a very delayed one) and found out optifine E3 is not compatible with the lastest version of BetterFPS.

**Comment by mezz** [comment]
This is an incompatibility between Optifine and OpenBlocks, also reported to OpenBlocks here: https://github.com/OpenMods/OpenBlocks/issues/831
This requires a fix from Optifine.

**Comment by JMLG1999** [comment]
But it got fixed when i disabled BetterFPS, do you think it has something related with the 3 mods?

**Comment by sp614x** [comment]
Can you reproduce the crash with ONLY Forge+OptiFine+BetterFPS or Forge+OptiFine+OpenBlocks?

**Comment by JMLG1999** [comment]
Results:
Forge + Optifine + OpenBlocks = **CRASHED**
Forge + Optifine + BetterFPS = **DIDN'T CRASH**
Report for the crash: https://pastebin.com/zxWNRgiu

**Comment by boq** [comment]
For reference, [here's code for that 'stencil-primer' sprite](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/client/renderer/item/stencil/StencilTextureManager.java#L29). Maybe it's problem with overridden `generateMipmaps` method?

**Comment by FlaggedBrad** [comment]
[Crash Report created with Optifine, OpenBlocks, OpenModsLib, and OpenEye on forge version 12.18.3.2316 on minecraft 1.10.2](https://pastebin.com/raw/SkJs4BTM)

**Comment by Herobone** [comment]
So will ther e be a fix for this? It's annoying if you have so many mods installed and it'
s lagging because optifine is not installed!!! Please fit it! Thanks!

**Comment by boq** [comment]
I figured sane workaround on my side - latest release seems to work.

**Comment by Herobone** [comment]
I don't know what u are doing but Optifine + OpenBlocks crashes every time!

**Comment by Matakor** [comment]
I was also having this crash with latest 1.10.2 forge/optifine with openblocks.

However, I just tested with the latest release of openblocks (1.10.2-1.7.2 and openmodslib 0.11.2) and the issue appears to have been resolved. I no longer crash on start. (I'd test in world, but the server I play on hasn't updated yet). 

Recommend anyone else with this crash to test with the newest openblocks version for 1.10.2.

**Comment by JMLG1999** [comment]
Tested with Forge 12.18.3.2422, optifine HD_U_E3 and OpenBlocks 1.7.2
Results: Does not crash
Guess the problem has been fixed.

**Comment by Herobone** [comment]
No, has not been fixed. It crashes every time. BUT: If you delete optionsof.txt it starts. Some settings are not compatible

**Comment by JMLG1999** [comment]
maybe a rendering setting. I didn't notice that because i made a fresh install.
At least a part of the problem was fixed since it used to crash even on a fresh installation

**Comment by Stephenator0316** [comment]
Getting this in 1.12.2 with OF HD_U_E3 and Openblocks 1.12.2-1.8

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 3/3/19 9:34 PM
Description: Stitching texture atlas

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkBounds(Buffer.java:567)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:327)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:182)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:365)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:155)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.checkBounds(Buffer.java:567)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:327)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:182)

-- Texture being stitched together --
Details:
	Atlas path: textures
	Sprite: TextureAtlasSprite{name='openblocks:canvas-0', frameCount=1, rotated=false, x=1600, y=2272, height=32, width=32, u0=0.39062744, u1=0.39843506, v0=0.55468994, v1=0.56249756}
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:365)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:155)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_192, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 854470336 bytes (814 MB) / 1794113536 bytes (1711 MB) up to 7397179392 bytes (7054 MB)
	JVM Flags: 4 total; -Xmx7936m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version         | Source                                     | Signature                                |
	|:----- |:------------------- |:--------------- |:------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2          | minecraft.jar                              | None                                     |
	| UCH   | mcp                 | 9.42            | minecraft.jar                              | None                                     |
	| UCH   | FML                 | 8.0.99.99       | forge-1.12.2-14.23.5.2768.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.5.2768    | forge-1.12.2-14.23.5.2768.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore        | 0.12.1          | minecraft.jar                              | None                                     |
	| UCH   | bookshelf           | 2.3.574         | Bookshelf-1.12.2-2.3.574.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | eplus               | 5.0.176         | EnchantingPlus-1.12.2-5.0.176.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | waila               | 1.8.26          | Hwyla-1.8.26-B41_1.12.2.jar                | None                                     |
	| UCH   | ironbackpacks       | 1.12.2-3.0.8-12 | IronBackpacks-1.12.2-3.0.8-12.jar          | None                                     |
	| UCH   | jei                 | 4.13.1.225      | jei_1.12.2-4.13.1.225.jar                  | None                                     |
	| UCH   | journeymap          | 1.12.2-5.5.3    | journeymap-1.12.2-5.5.3.jar                | None                                     |
	| UCH   | openmods            | 0.12.1          | OpenModsLib-1.12.2-0.12.1.jar              | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks          | 1.8             | OpenBlocks-1.12.2-1.8.jar                  | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | pixelmon            | 7.0.2           | Pixelmon-1.12.2-7.0.3-universal.jar        | None                                     |
	| UCH   | pixelmoninformation | 0.3.0           | PixelmonInformation-1.12.2-7.0.0-0.3.0.jar | None                                     |

	Loaded coremods (and transformers): 
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.16' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Launched Version: forge-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.16, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.12.2-rv4.zip, Pixelmon's_faithful_x32.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 1700 Eight-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.16
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16`
