### ISSUE TITLE
[1.8.9] Crash when rendering Botania:pylon with shaders enabled

### ISSUE THREAD

**Issue by Drakonas** [sp614x/optifine#81]
I simply enabled the latest KUDA Shader beta with the built-in shadermod in Optifine HD U5, and Minecraft crashed when it attempted to render a Botania pylon nearby.

[Minecraft Crash Report](http://pastebin.com/wLwhFZww)

[FML latest.log](http://pastebin.com/pb4NJJXf)
[FML Full Log (Trimmed)](https://gist.github.com/Drakonas/d4c859e8b5df5d8331a76932b6ca1dcb)

**Comment by Drakonas** [comment]
Is this the right place to fill a bug report for this?

**Comment by sp614x** [comment]
java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:306)
	at net.minecraft.client.renderer.WorldRenderer.func_178972_a(WorldRenderer.java:466)
	at net.minecraftforge.client.ForgeHooksClient.putQuadColor(ForgeHooksClient.java:521)
	at net.minecraftforge.client.model.pipeline.**LightUtil.renderQuadColor**(LightUtil.java:285)
	at vazkii.botania.client.model.ModelPylon.renderQuads(ModelPylon.java:146)

The ModelPylon is calling LightUtil.renderQuadColor() which is not compatible with shaders. It uses a fixed vertex size of 7 instead of "vertexData.length / 4" or from the VertexFormat. This was fixed to work properly in Forge 1.9.

**Comment by Drakonas** [comment]
I'll let the devs of Botania know about this. Thanks.
