### ISSUE TITLE
[1.12.1] Can't load a world

### ISSUE THREAD

**Issue by Blatts12** [sp614x/optifine#893]
So i created a world and i can't load it. Something with FuturePack shows(https://pastebin.com/x6FRDwd7) but when i deleted the OF everything load.

**Comment by Blatts12** [comment]
Update!
Okay I tried out with OF again(I loaded world without OF then with OF) and this time it don't freeze minecraft but back to minecraft's multiplayer menu and next time(without restart) world loaded.

I gonna make more tests later

**Comment by Blatts12** [comment]
Update!
I deleted FP and this log comes out
`[16:42:16] [Server thread/FATAL] [FML]: The ForgeModLoader state engine has become corrupted. Probably, a state was missed by and invalid modification to a base classForgeModLoader depends on. This is a critical error and not recoverable. Investigate any modifications to base classes outside ofForgeModLoader, especially Optifine, to see if there are fixes available.
[16:42:16] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
java.lang.RuntimeException: The ForgeModLoader state engine is invalid
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:192) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:903) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:290) [FMLCommonHandler.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at Reflector.callBoolean(Reflector.java:737) [Reflector.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:193) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by sp614x** [comment]
First crash looks like FuturePack sending a packet too early before the world is initialized.
The second crash is Forge complaining the initialization sequence.
I don't see how this can be related to OptiFine.
You could try with the Forge version OptiFine is compatible with (see the changleog).
