### ISSUE TITLE
Placing a MalisisDoors Trapdoor next to another (maybe in a special circumstance?) causes the Client to crash.

### ISSUE THREAD

**Issue by D3nnis3n** [sp614x/optifine#945]
See this issue: https://github.com/Ordinastie/MalisisCore/issues/128

**Comment by sp614x** [comment]
The crash is in the MalisisDoors classes when rendering a block entity.
```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=null, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
    at net.malisis.doors.tileentity.TrapDoorTileEntity.getDirection(TrapDoorTileEntity.java:55)
    at net.malisis.doors.renderer.TrapDoorRenderer.setup(TrapDoorRenderer.java:172)
    at net.malisis.doors.renderer.TrapDoorRenderer.render(TrapDoorRenderer.java:158)
    at net.malisis.core.renderer.MalisisRenderer.func_192841_a(MalisisRenderer.java:441)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:180)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:148)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1001)
```

Does not seem to be related to OptiFine.
