### ISSUE TITLE
Error with BetterWithMods

### ISSUE THREAD

**Issue by coreymills26** [sp614x/optifine#948]
trying to load a world an the crash keeps happening, i was told to report the bug here.
https://pastebin.com/qg62CWdE

**Comment by sp614x** [comment]
One of the installed mods is overwriting the OptiFine classes:
```
java.lang.NoSuchMethodError: net.minecraft.client.multiplayer.WorldClient.isPlayerUpdate()Z
    at net.minecraft.client.renderer.chunk.RenderChunk.isWorldPlayerUpdate(RenderChunk.java:570)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178575_a(RenderChunk.java:532)
```
can't be fixed by OptiFine.
